# Generated by scripts/gen_api_v4_contract.py; DO NOT EDIT.
"""Dependency-free API v4 bootstrap DTOs for Python/desktop clients."""

from __future__ import annotations

from typing import Any, Literal, TypedDict, cast


API_V4_MAJOR = 4
MIN_DESKTOP_BUILD = '0.16.0'
MIN_ANDROID_BUILD = 17
API_META_PATH = '/api/v4/meta'


class ApiMeta(TypedDict):
    apiMajor: Literal[4]
    schemaVersion: int
    serverBuild: str
    minDesktopBuild: str
    minAndroidBuild: int


class ResponseMeta(TypedDict):
    requestId: str
    serverTimeMs: int


class ApiMetaResponse(TypedDict):
    data: ApiMeta
    meta: ResponseMeta


def _require_int(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f'{field} must be an integer')
    return value


def _require_string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f'{field} must be a non-empty string')
    return value


def _numeric_build(build: str) -> tuple[int, ...]:
    components = build.split('.')
    if not components or any(
        not component or not component.isdigit()
        for component in components
    ):
        raise ValueError('build must contain only dotted numeric components')
    return tuple(int(component) for component in components)


def parse_api_meta_response(value: Any) -> ApiMetaResponse:
    """Fail closed when a server does not speak the generated v4 contract."""
    if not isinstance(value, dict) or set(value) != {'data', 'meta'}:
        raise ValueError('API v4 meta response must contain exactly data and meta')
    data = value.get('data')
    meta = value.get('meta')
    expected_data = {
        'apiMajor', 'schemaVersion', 'serverBuild',
        'minDesktopBuild', 'minAndroidBuild',
    }
    if not isinstance(data, dict) or set(data) != expected_data:
        raise ValueError('API v4 data has an invalid shape')
    if not isinstance(meta, dict) or set(meta) != {'requestId', 'serverTimeMs'}:
        raise ValueError('API v4 response meta has an invalid shape')
    if _require_int(data.get('apiMajor'), 'apiMajor') != API_V4_MAJOR:
        raise ValueError('server API major is not compatible with this client')
    if _require_int(data.get('schemaVersion'), 'schemaVersion') < 1:
        raise ValueError('schemaVersion must be positive')
    _require_string(data.get('serverBuild'), 'serverBuild')
    _numeric_build(_require_string(
        data.get('minDesktopBuild'), 'minDesktopBuild'))
    if _require_int(data.get('minAndroidBuild'), 'minAndroidBuild') < 1:
        raise ValueError('minAndroidBuild must be positive')
    _require_string(meta.get('requestId'), 'requestId')
    if _require_int(meta.get('serverTimeMs'), 'serverTimeMs') < 0:
        raise ValueError('serverTimeMs must be non-negative')
    return cast(ApiMetaResponse, value)


def desktop_build_is_compatible(
    current_build: str,
    minimum_build: str = MIN_DESKTOP_BUILD,
) -> bool:
    current = _numeric_build(current_build)
    minimum = _numeric_build(minimum_build)
    width = max(len(current), len(minimum))
    return current + (0,) * (width - len(current)) >= (
        minimum + (0,) * (width - len(minimum)))


def require_desktop_api_compatibility(
    value: Any,
    current_build: str,
) -> ApiMetaResponse:
    """Validate live metadata and reject a desktop build below its minimum."""
    parsed = parse_api_meta_response(value)
    minimum_build = parsed['data']['minDesktopBuild']
    if not desktop_build_is_compatible(current_build, minimum_build):
        raise ValueError(
            f'desktop build {current_build!r} is below server minimum '
            f'{minimum_build!r}')
    return parsed


def android_build_is_compatible(
    current_version_code: int,
    minimum_version_code: int = MIN_ANDROID_BUILD,
) -> bool:
    return current_version_code >= minimum_version_code
