// Generated by scripts/gen_api_v4_contract.py; DO NOT EDIT.
// Canonical API v4 bootstrap DTOs and compatibility probe.

export const API_V4_MAJOR = 4 as const;
export const MIN_DESKTOP_BUILD = "0.16.0";
export const MIN_ANDROID_BUILD = 17;
export const API_META_PATH = '/api/v4/meta';

export interface ApiMeta {
  apiMajor: typeof API_V4_MAJOR;
  schemaVersion: number;
  serverBuild: string;
  minDesktopBuild: string;
  minAndroidBuild: number;
}

export interface ResponseMeta {
  requestId: string;
  serverTimeMs: number;
}

export interface ApiMetaResponse {
  data: ApiMeta;
  meta: ResponseMeta;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function hasExactKeys(value: Record<string, unknown>, keys: readonly string[]): boolean {
  const actual = Object.keys(value).sort();
  const expected = [...keys].sort();
  return actual.length === expected.length && actual.every((key, index) => key === expected[index]);
}

export function parseApiMetaResponse(value: unknown): ApiMetaResponse {
  if (!isRecord(value) || !hasExactKeys(value, ['data', 'meta'])) {
    throw new Error('API v4 meta response must contain exactly data and meta');
  }
  const data = value.data;
  const meta = value.meta;
  if (!isRecord(data) || !hasExactKeys(data, [
    'apiMajor', 'schemaVersion', 'serverBuild', 'minDesktopBuild', 'minAndroidBuild',
  ])) {
    throw new Error('API v4 data has an invalid shape');
  }
  if (!isRecord(meta) || !hasExactKeys(meta, ['requestId', 'serverTimeMs'])) {
    throw new Error('API v4 response meta has an invalid shape');
  }
  if (data.apiMajor !== API_V4_MAJOR || !Number.isInteger(data.schemaVersion)
      || (data.schemaVersion as number) < 1
      || typeof data.serverBuild !== 'string' || data.serverBuild.length === 0
      || typeof data.minDesktopBuild !== 'string' || data.minDesktopBuild.length === 0
      || !Number.isInteger(data.minAndroidBuild) || (data.minAndroidBuild as number) < 1
      || typeof meta.requestId !== 'string' || meta.requestId.length === 0
      || !Number.isInteger(meta.serverTimeMs) || (meta.serverTimeMs as number) < 0) {
    throw new Error('API v4 meta response contains invalid field values');
  }
  numericBuild(data.minDesktopBuild as string);
  return value as unknown as ApiMetaResponse;
}

function numericBuild(build: string): number[] {
  const components = build.split('.');
  if (components.length === 0 || components.some((component) => !/^\d+$/.test(component))) {
    throw new Error('build must contain only dotted numeric components');
  }
  const values = components.map((component) => Number.parseInt(component, 10));
  if (values.some((component) => !Number.isSafeInteger(component))) {
    throw new Error('build contains an unsafe numeric component');
  }
  return values;
}

export function desktopBuildIsCompatible(
  currentBuild: string,
  minimumBuild = MIN_DESKTOP_BUILD,
): boolean {
  const current = numericBuild(currentBuild);
  const minimum = numericBuild(minimumBuild);
  const length = Math.max(current.length, minimum.length);
  for (let index = 0; index < length; index += 1) {
    const difference = (current[index] ?? 0) - (minimum[index] ?? 0);
    if (difference !== 0) return difference > 0;
  }
  return true;
}

export function requireDesktopApiCompatibility(
  value: unknown,
  currentBuild: string,
): ApiMetaResponse {
  const parsed = parseApiMetaResponse(value);
  if (!desktopBuildIsCompatible(currentBuild, parsed.data.minDesktopBuild)) {
    throw new Error(
      `desktop build ${currentBuild} is below server minimum ${parsed.data.minDesktopBuild}`,
    );
  }
  return parsed;
}

export function androidBuildIsCompatible(
  currentVersionCode: number,
  minimumVersionCode = MIN_ANDROID_BUILD,
): boolean {
  return Number.isInteger(currentVersionCode) && currentVersionCode >= minimumVersionCode;
}

export async function fetchApiMeta(
  baseUrl: string,
  init: RequestInit = {},
): Promise<ApiMetaResponse> {
  const response = await fetch(`${baseUrl.replace(/\/+$/, '')}${API_META_PATH}`, {
    ...init,
    method: 'GET',
    headers: { Accept: 'application/json', ...(init.headers ?? {}) },
  });
  if (!response.ok) throw new Error(`API v4 meta request failed with ${response.status}`);
  return parseApiMetaResponse(await response.json());
}

export async function fetchCompatibleApiMeta(
  baseUrl: string,
  currentBuild: string,
  init: RequestInit = {},
): Promise<ApiMetaResponse> {
  return requireDesktopApiCompatibility(
    await fetchApiMeta(baseUrl, init),
    currentBuild,
  );
}
