"""tests/test_wire_fixtures.py — Golden-wire fixture corpus conformance.

``contracts/fixtures/`` is the checked-in golden corpus for both wire
boundaries (SSE events, push frames) and the persisted-data read boundary
(conversation sync v3). Every fixture is generated by
``scripts/gen_wire_fixtures.py`` from the same schemas the runtime gates
enforce — never hand-edit a fixture.

  A. **Corpus freshness** — ``render_fixtures()`` must byte-match the
     committed corpus (the pytest half of ``make contracts-check``).
  B. **Wire conformance** — every event fixture passes ``validate_event``
     and rebuilds byte-identically through ``build_event``; every push
     fixture passes ``validate_push_frame`` and rebuilds through
     ``build_push_frame``. The corpus covers every schema'd type exactly
     once.
  C. **Persisted boundary** — modern sync fixtures pass the real
     ``decode()``; the legacy pre-``attemptId`` observation fixtures (the
     clone-500 incident class) fail closed raw and decode after the
     ``TURN_READ_ADAPTERS`` registry lifts them.

If this fails
-------------
You changed a declared wire or persisted shape. Update the schema
authority (``EventSpec.schema`` in ``lib/agent_core/events.py`` or
``contracts/conversation_sync_v3.yaml``), regenerate the derived artifacts
AND the corpus (``python3 scripts/gen_wire_fixtures.py``), and on a
breaking change bump the contract version.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from lib.agent_core.events import (
    all_event_specs,
    all_push_frame_specs,
    build_event,
    build_push_frame,
    validate_event,
    validate_push_frame,
)
from lib.conversation_sync.service import (
    TURN_READ_ADAPTERS,
    _backfill_legacy_observation_attempt_ids,
    adapt_turn_read,
)
from lib.conversation_sync.validation import ContractViolation, decode
from scripts.gen_wire_fixtures import (
    LEGACY_OBSERVATION_SUFFIX,
    SYNC_DECODE_BOUNDARIES,
    SYNC_LEGACY_BOUNDARIES,
    render_fixtures,
)

pytestmark = pytest.mark.unit

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "contracts" / "fixtures"


def _fixture_paths(subdir: str) -> list[Path]:
    return sorted((FIXTURES / subdir).glob("*.json"))


def _load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


# ═══════════════════════════════════════════════════════════════════
#  A. Corpus freshness
# ═══════════════════════════════════════════════════════════════════


def test_corpus_matches_generator_output_byte_for_byte():
    rendered = render_fixtures()
    committed = {
        str(path.relative_to(FIXTURES)): path.read_text(encoding="utf-8")
        for path in sorted(FIXTURES.rglob("*.json"))
    }
    missing = sorted(set(rendered) - set(committed))
    orphaned = sorted(set(committed) - set(rendered))
    stale = sorted(
        path
        for path in rendered
        if path in committed and committed[path] != rendered[path]
    )
    assert committed == rendered, (
        "fixture corpus drift — run python3 scripts/gen_wire_fixtures.py; "
        f"missing: {missing}, orphaned: {orphaned}, stale: {stale}"
    )


# ═══════════════════════════════════════════════════════════════════
#  B. Wire conformance
# ═══════════════════════════════════════════════════════════════════


def test_event_fixtures_validate_and_rebuild_through_the_gate():
    declared = {spec.type for spec in all_event_specs() if spec.schema is not None}
    paths = _fixture_paths("events")
    assert {path.stem for path in paths} == declared
    for path in paths:
        payload = _load(path)
        assert payload["type"] == path.stem
        assert validate_event(payload) == (), path.name
        fields = {key: value for key, value in payload.items() if key != "type"}
        assert build_event(path.stem, **fields) == payload, path.name


def test_push_fixtures_validate_and_rebuild_through_the_gate():
    declared = {spec.type for spec in all_push_frame_specs() if spec.schema is not None}
    paths = _fixture_paths("push")
    assert {path.stem for path in paths} == declared
    for path in paths:
        payload = _load(path)
        assert payload["type"] == path.stem
        assert validate_push_frame(payload) == (), path.name
        fields = {key: value for key, value in payload.items() if key != "type"}
        assert build_push_frame(path.stem, **fields) == payload, path.name


# ═══════════════════════════════════════════════════════════════════
#  C. Persisted-data boundary
# ═══════════════════════════════════════════════════════════════════


def test_decode_boundaries_match_the_service_call_sites():
    source = (ROOT / "lib/conversation_sync/service.py").read_text(encoding="utf-8")
    served = {
        name
        for name in (
            "ConversationSyncSnapshot",
            "ConversationTurnPage",
            "SyncHeartbeat",
            "ConversationChange",
            "SyncResetRequired",
        )
        if f'decode("{name}"' in source
    }
    assert served == set(SYNC_DECODE_BOUNDARIES), (
        "gen_wire_fixtures.SYNC_DECODE_BOUNDARIES drifts from the service "
        "decode call sites"
    )


def test_modern_sync_fixtures_decode_through_the_real_boundary():
    for schema_name in SYNC_DECODE_BOUNDARIES:
        payload = _load(FIXTURES / "sync_v3" / f"{schema_name}.json")
        assert decode(schema_name, payload) is payload, schema_name


def test_legacy_observation_fixtures_fail_closed_then_adapt():
    assert _backfill_legacy_observation_attempt_ids in TURN_READ_ADAPTERS
    for schema_name in SYNC_LEGACY_BOUNDARIES:
        legacy = _load(
            FIXTURES / "sync_v3" / f"{schema_name}{LEGACY_OBSERVATION_SUFFIX}.json"
        )
        with pytest.raises(ContractViolation):
            decode(schema_name, legacy)
        adapted = {
            **legacy,
            "turns": [adapt_turn_read(turn) for turn in legacy["turns"]],
        }
        assert decode(schema_name, adapted) is adapted, schema_name
        observations = adapted["turns"][0]["projection"]["timingTrace"][
            "clientObservations"
        ]
        assert observations
        assert all("attemptId" in item for item in observations)


def test_read_adapters_are_copy_on_write():
    legacy = _load(
        FIXTURES
        / "sync_v3"
        / f"ConversationSyncSnapshot{LEGACY_OBSERVATION_SUFFIX}.json"
    )
    before = json.dumps(legacy, sort_keys=True)
    for turn in legacy["turns"]:
        adapt_turn_read(turn)
    assert json.dumps(legacy, sort_keys=True) == before
