/* AUTO-GENERATED by scripts/gen_api_v1_model_routing_contract.py.
 * Canonical sources: contracts/api_v1_model_routing.yaml and
 * contracts/model_routing_v2.schema.json.
 * DO NOT EDIT BY HAND.
 *
 * Type-level mirror only; the server-side generated module is the
 * runtime validation authority. Conditional keywords (allOf/if/then/
 * else/not) and uniqueness bounds are enforced there, not here.
 */

export const API_V1_MODEL_ROUTING_CONTRACT_ID = "tofu.api-v1-model-routing/v1" as const;

export type ModelRoutingIdentifier = string;

export type ModelRoutingIdentifierList = ReadonlyArray<ModelRoutingIdentifier>;

export type ModelRoutingCapabilities = ReadonlyArray<ModelRoutingIdentifier>;

export type ModelRoutingPricing = {
  "input": number;
  "output": number;
  "currency": "USD" | "CNY";
  "unit": "per_million_tokens";
  "cache_read"?: number;
  "cache_write"?: number;
};

export type ModelRoutingCreator = {
  "creator_id": ModelRoutingIdentifier;
  "name": string;
  "website"?: string;
};

export type ModelRoutingModel = {
  "creator_id": ModelRoutingIdentifier;
  "model_id": ModelRoutingIdentifier;
  "display_name": string;
  "capabilities": ModelRoutingCapabilities;
  "context_window": number;
  "quality_rank": number;
  "list_pricing"?: ModelRoutingPricing;
  "release_date"?: string;
  "lifecycle"?: "stable" | "preview" | "dated_snapshot" | "retired";
};

export type ModelRoutingProvider = {
  "provider_id": ModelRoutingIdentifier;
  "name": string;
  "scope": "public" | "owner";
  "brand"?: string;
  "website"?: string;
};

export type ModelRoutingQuotaPolicy = {
  "rpm"?: number;
  "tpm"?: number;
  "daily_tokens"?: number;
  "balance"?: number;
  "currency"?: "USD" | "CNY";
};

export type ModelRoutingProviderAccess = {
  "provider_access_id": ModelRoutingIdentifier;
  "provider_id": ModelRoutingIdentifier;
  "enabled": boolean;
  "quota_policy": ModelRoutingQuotaPolicy;
  "display_name"?: string;
};

export type ModelRoutingConnection = {
  "connection_id": ModelRoutingIdentifier;
  "provider_access_id": ModelRoutingIdentifier;
  "base_url": string;
  "protocol": "openai" | "openai_responses" | "anthropic" | "local" | "custom";
  "enabled": boolean;
  "priority": number;
  "region"?: string;
  "gateway_namespace"?: string;
  "adapter"?: ModelRoutingDesktopAdapter;
  "extra_headers": {
  [key: string]: string;
};
};

export type ModelRoutingDesktopAdapter = {
  "agent_id": ModelRoutingIdentifier;
  "port": number;
};

export type ModelRoutingCredentialAuthorization = {
  "connection_ids": ModelRoutingIdentifierList;
  "models": ReadonlyArray<ModelRoutingModelRef>;
};

export type ModelRoutingCredentialMetadata = {
  "credential_id": ModelRoutingIdentifier;
  "provider_access_id": ModelRoutingIdentifier;
  "kind": "api_key" | "oauth" | "local_identity" | "subscription";
  "secret_reference": string;
  "key_hint": string;
  "enabled": boolean;
  "authorization": ModelRoutingCredentialAuthorization;
  "quota_policy": ModelRoutingQuotaPolicy;
};

export type ModelRoutingModelRef = {
  "creator_id": ModelRoutingIdentifier;
  "model_id": ModelRoutingIdentifier;
};

export type ModelRoutingOffering = {
  "offering_id": ModelRoutingIdentifier;
  "provider_access_id": ModelRoutingIdentifier;
  "identity_state": "confirmed" | "pending_identity";
  "model"?: ModelRoutingModelRef;
  "pending_model_id"?: string;
  "enabled": boolean;
  "stale"?: boolean;
  "capabilities": ModelRoutingCapabilities;
  "context_window": number;
  "actual_pricing"?: ModelRoutingPricing;
  "priority": number;
};

export type ModelRoutingDeployment = {
  "deployment_id": ModelRoutingIdentifier;
  "offering_id": ModelRoutingIdentifier;
  "connection_id": ModelRoutingIdentifier;
  "wire_model_id": ModelRoutingIdentifier;
  "max_output_tokens"?: number;
  "enabled": boolean;
  "identity_confidence": "high" | "medium" | "low" | "pending";
  "probe_status": "passed" | "failed" | "unprobed" | "stale";
  "priority": number;
};

export type ModelRoutingMigrationMetadata = {
  "source": string;
  "migrated_at": number;
  "receipt_id": ModelRoutingIdentifier;
};

export type ModelRoutingDocument = {
  "contract_version": "tofu.model-routing/v2";
  "revision": number;
  "creators": ReadonlyArray<ModelRoutingCreator>;
  "models": ReadonlyArray<ModelRoutingModel>;
  "providers": ReadonlyArray<ModelRoutingProvider>;
  "provider_accesses": ReadonlyArray<ModelRoutingProviderAccess>;
  "connections": ReadonlyArray<ModelRoutingConnection>;
  "credentials": ReadonlyArray<ModelRoutingCredentialMetadata>;
  "offerings": ReadonlyArray<ModelRoutingOffering>;
  "deployments": ReadonlyArray<ModelRoutingDeployment>;
  "migration"?: ModelRoutingMigrationMetadata;
};

export type Revision = number;

export type ModelRoutingAuthorityResponse = {
  "model_routing": ModelRoutingDocument;
  "revision": Revision;
};

export type ModelRoutingPutRequest = {
  "model_routing": ModelRoutingDocument;
  "expected_revision": Revision;
};

export type ProviderBundle = {
  "provider": ModelRoutingProvider;
  "provider_access": (ModelRoutingProviderAccess) | (null);
  "connections": ReadonlyArray<ModelRoutingConnection>;
  "credentials": ReadonlyArray<ModelRoutingCredentialMetadata>;
  "offerings": ReadonlyArray<ModelRoutingOffering>;
  "deployments": ReadonlyArray<ModelRoutingDeployment>;
};

export type ProviderListResponse = {
  "providers": ReadonlyArray<ProviderBundle>;
  "revision": Revision;
};

export type ProviderResponse = {
  "provider": ProviderBundle;
  "revision": Revision;
};

export type ProviderWriteRequest = {
  "provider": ModelRoutingProvider;
  "provider_access": ModelRoutingProviderAccess;
  "connections": ReadonlyArray<ModelRoutingConnection>;
  "credentials": ReadonlyArray<ModelRoutingCredentialMetadata>;
  "offerings": ReadonlyArray<ModelRoutingOffering>;
  "deployments": ReadonlyArray<ModelRoutingDeployment>;
  "creators"?: ReadonlyArray<ModelRoutingCreator>;
  "models"?: ReadonlyArray<ModelRoutingModel>;
  "credential_secrets"?: {
  [key: string]: string;
};
  "expected_revision": Revision;
};

export type ProviderDeleteRequest = {
  "expected_revision": Revision;
};

export type ProviderDeleteResponse = {
  "deleted": string;
  "revision": Revision;
};

export type CredentialSecretPutRequest = {
  "secret": string;
  "expected_revision": Revision;
};

export type CredentialSecretPutResponse = {
  "credential_id": string;
  "key_hint": string;
  "revision": Revision;
};

export type CredentialSecretRevealResponse = {
  "credential_id": string;
  "secret": string;
};

export type ProviderTemplate = {
  "key": string;
  "name"?: string;
  "category"?: string;
  "brand"?: string;
  "base_url"?: string;
  [key: string]: unknown;
};

export type ProviderTemplateListResponse = {
  "items": ReadonlyArray<ProviderTemplate>;
};

export type ProviderTemplateCompileRequest = {
  "template_key": string;
  "selected_model_ids"?: ReadonlyArray<string>;
};

export type CompiledProviderBundle = {
  "provider": ModelRoutingProvider;
  "provider_access": ModelRoutingProviderAccess;
  "connections": ReadonlyArray<ModelRoutingConnection>;
  "credentials": ReadonlyArray<ModelRoutingCredentialMetadata>;
  "offerings": ReadonlyArray<ModelRoutingOffering>;
  "deployments": ReadonlyArray<ModelRoutingDeployment>;
  "creators": ReadonlyArray<ModelRoutingCreator>;
  "models": ReadonlyArray<ModelRoutingModel>;
  "credential_extra_headers": {
  [key: string]: string;
};
};

export type ProviderTemplateCompileResponse = {
  "provider_bundle": CompiledProviderBundle;
};

export type ProviderProbeRequest = {
  "base_url": string;
  "api_key"?: string;
  "models_path"?: string;
};

export type ProviderProbeResponse = {
  "ok"?: boolean;
  "error"?: string;
  "base_url"?: string;
  "name"?: string;
  "brand"?: string;
  "provider_bundle"?: CompiledProviderBundle;
  "credential_id"?: string;
  "model_count"?: number;
  [key: string]: unknown;
};

export type ProbeCellsStartRequest = {
  "timeout"?: number;
  "attempts"?: number;
  "force"?: boolean;
  "only"?: {
  "key_idxs"?: ReadonlyArray<number>;
  "model_ids"?: ReadonlyArray<string>;
};
};

export type ProbeCellsSnapshot = {
  "status": string;
  "probe_schema_version"?: number;
  "provider_id"?: string;
  "started_at"?: number;
  "finished_at"?: (number) | (null);
  "total"?: number;
  "done_count"?: number;
  "attempts"?: number;
  "cells"?: {
  [key: string]: unknown;
};
  "summary"?: {
  "ok"?: number;
  "disable"?: number;
  "skipped"?: number;
  "neutral"?: number;
  "failed"?: number;
  [key: string]: unknown;
};
  "error"?: (string) | (null);
  [key: string]: unknown;
};

export type MigrationPlan = {
  "contract_version": "tofu.model-routing/v2";
  "source_digest": string;
  "entity_counts": {
  "creators": number;
  "models": number;
  "providers": number;
  "provider_accesses": number;
  "connections": number;
  "credentials": number;
  "offerings": number;
  "deployments": number;
};
  "secrets": ReadonlyArray<{
  "credential_id": string;
  "secret_reference": string;
  "key_hint": string;
}>;
  "issues": ReadonlyArray<{
  "severity": string;
  "code": string;
  "message": string;
  "path"?: string;
  "candidates"?: ReadonlyArray<{
  [key: string]: string;
}>;
}>;
  "ready": boolean;
};

export type MigrationPlanResponse = {
  "migration_plan": MigrationPlan;
};

export type MigrationCommitResponse = {
  "model_routing": (ModelRoutingDocument) | (null);
  "revision": Revision;
  "migration_receipt": {
  [key: string]: unknown;
};
};
