/* AUTO-GENERATED by scripts/gen_conversation_sync_contract.py.
 * Canonical source: contracts/conversation_sync_v3.yaml.
 * DO NOT EDIT BY HAND.
 */
import { request, resolvePath, type RequestOptions } from './transport';

export const CONVERSATION_SYNC_CONTRACT_ID = "tofu.conversation-sync/v3" as const;
export const CONVERSATION_SYNC_STREAM_POLICY = {
  "cursor": "opaque",
  "ordering": "conversation-scoped-monotonic",
  "heartbeatIntervalMs": 15000,
  "reconnectGraceMs": 37500,
  "replayRetentionMs": 604800000,
  "eventSource": "/api/v3/conversations/{conversationId}/events",
  "gapEvent": "sync.reset_required",
  "streamClientIdQuery": "streamClientId",
  "streamGenerationQuery": "streamGeneration",
  "capacityStopStatus": 204
} as const;
export const CONVERSATION_SYNC_COMMAND_RETRY_POLICY = {
  "maxAttempts": 3,
  "baseDelayMs": 250,
  "minDelayMs": 50,
  "maxDelayMs": 2000,
  "jitterRatio": 0.2,
  "httpStatuses": [
    502,
    503,
    504
  ],
  "storageCodes": [
    "database_busy",
    "database_unavailable",
    "database_timeout"
  ],
  "transportCodes": [
    "network"
  ]
} as const;
export const CONVERSATION_SYNC_SCHEMAS = {
  "AbortAttemptResponse": {
    "additionalProperties": true,
    "properties": {
      "ok": {
        "const": true
      }
    },
    "required": [
      "ok"
    ],
    "type": "object"
  },
  "AppendSettledTurnRequest": {
    "additionalProperties": false,
    "properties": {
      "actor": {
        "$ref": "#/components/schemas/TurnActor"
      },
      "commandId": {
        "maxLength": 256,
        "minLength": 1,
        "type": "string"
      },
      "conversation": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "createdAt": {
        "minimum": 0,
        "type": "integer"
      },
      "kind": {
        "type": "string"
      },
      "laneId": {
        "type": "string"
      },
      "projection": {
        "$ref": "#/components/schemas/TurnProjection"
      },
      "runId": {
        "type": "string"
      },
      "settlement": {
        "$ref": "#/components/schemas/TurnSettlement"
      },
      "status": {
        "enum": [
          "completed",
          "interrupted",
          "truncated",
          "failed"
        ],
        "type": "string"
      }
    },
    "required": [
      "commandId",
      "actor",
      "projection"
    ],
    "type": "object"
  },
  "AttemptEvent": {
    "additionalProperties": false,
    "properties": {
      "attemptId": {
        "type": "string"
      },
      "conversationId": {
        "type": "string"
      },
      "payload": {
        "additionalProperties": true,
        "properties": {
          "attempts": {
            "items": {
              "$ref": "#/components/schemas/AttemptRecord"
            },
            "type": "array"
          },
          "phase": {},
          "projection": {
            "$ref": "#/components/schemas/TurnProjection"
          },
          "projectionPatch": {
            "$ref": "#/components/schemas/ProjectionPatch"
          },
          "request": {},
          "settlement": {
            "$ref": "#/components/schemas/TurnSettlement"
          },
          "status": {
            "$ref": "#/components/schemas/TurnStatus"
          },
          "turnState": {
            "$ref": "#/components/schemas/TurnRuntimeStateChange"
          },
          "turns": {
            "items": {
              "$ref": "#/components/schemas/TurnRecord"
            },
            "type": "array"
          }
        },
        "type": "object"
      },
      "projectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "seq": {
        "minimum": 1,
        "type": "integer"
      },
      "turnId": {
        "type": "string"
      },
      "type": {
        "enum": [
          "projection_updated",
          "interaction_request",
          "status_changed",
          "terminal_settlement"
        ],
        "type": "string"
      }
    },
    "required": [
      "conversationId",
      "turnId",
      "attemptId",
      "seq",
      "projectionRevision",
      "type",
      "payload"
    ],
    "type": "object"
  },
  "AttemptOperation": {
    "enum": [
      "generate",
      "continue",
      "checkpoint_resume",
      "regenerate",
      "ingest"
    ],
    "type": "string"
  },
  "AttemptRecord": {
    "additionalProperties": false,
    "properties": {
      "attemptId": {
        "type": "string"
      },
      "baseProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "commandId": {
        "type": "string"
      },
      "conversationId": {
        "type": "string"
      },
      "createdAt": {
        "minimum": 0,
        "type": "integer"
      },
      "operation": {
        "$ref": "#/components/schemas/AttemptOperation"
      },
      "resumeAnchor": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "settledAt": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "startedAt": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "status": {
        "$ref": "#/components/schemas/AttemptStatus"
      },
      "taskId": {
        "type": "string"
      },
      "turnId": {
        "type": "string"
      }
    },
    "required": [
      "attemptId",
      "conversationId",
      "turnId",
      "commandId",
      "taskId",
      "operation",
      "status",
      "baseProjectionRevision",
      "resumeAnchor",
      "createdAt"
    ],
    "type": "object"
  },
  "AttemptStatus": {
    "enum": [
      "pending",
      "running",
      "completed",
      "interrupted",
      "truncated",
      "failed",
      "superseded"
    ],
    "type": "string"
  },
  "BranchLaneDescriptor": {
    "additionalProperties": true,
    "properties": {
      "anchorText": {
        "type": "string"
      },
      "icon": {
        "type": "string"
      },
      "kind": {
        "type": "string"
      },
      "label": {
        "type": "string"
      },
      "laneId": {
        "type": "string"
      },
      "parentSelection": {
        "type": "string"
      },
      "title": {
        "type": "string"
      }
    },
    "required": [
      "laneId"
    ],
    "type": "object"
  },
  "ConnectionHealth": {
    "additionalProperties": false,
    "properties": {
      "generation": {
        "minimum": 0,
        "type": "integer"
      },
      "lastFrameAt": {
        "minimum": 0,
        "type": "number"
      },
      "observedAt": {
        "minimum": 0,
        "type": "number"
      },
      "reason": {
        "type": "string"
      },
      "retryCount": {
        "minimum": 0,
        "type": "integer"
      },
      "state": {
        "$ref": "#/components/schemas/ConnectionHealthState"
      },
      "transport": {
        "enum": [
          "conversation-sse",
          "task-sse",
          "push-websocket"
        ],
        "type": "string"
      }
    },
    "required": [
      "state",
      "transport",
      "observedAt",
      "generation"
    ],
    "type": "object"
  },
  "ConnectionHealthState": {
    "enum": [
      "idle",
      "connecting",
      "live",
      "recovering",
      "degraded",
      "offline",
      "closed"
    ],
    "type": "string"
  },
  "ConversationChange": {
    "additionalProperties": false,
    "properties": {
      "attemptId": {
        "type": "string"
      },
      "contract": {
        "const": "tofu.conversation-sync.event/v1"
      },
      "conversationId": {
        "type": "string"
      },
      "occurredAt": {
        "minimum": 0,
        "type": "integer"
      },
      "payload": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "syncSeq": {
        "minimum": 1,
        "type": "integer"
      },
      "turnId": {
        "type": "string"
      },
      "type": {
        "$ref": "#/components/schemas/ConversationChangeType"
      }
    },
    "required": [
      "contract",
      "type",
      "conversationId",
      "syncSeq",
      "occurredAt",
      "payload"
    ],
    "type": "object"
  },
  "ConversationChangeType": {
    "enum": [
      "turn.upsert",
      "turn.patch",
      "turn.deleted",
      "attempt.event",
      "conversation.activity"
    ],
    "type": "string"
  },
  "ConversationInvalidation": {
    "additionalProperties": false,
    "properties": {
      "channel": {
        "const": "notify"
      },
      "contract": {
        "const": "tofu.conversation-sync.invalidation/v1"
      },
      "conversationId": {
        "type": "string"
      },
      "cursorHint": {
        "type": "string"
      },
      "taskId": {
        "type": "string"
      },
      "type": {
        "const": "conversation.invalidated"
      },
      "userId": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "integer"
          }
        ]
      }
    },
    "required": [
      "channel",
      "taskId",
      "contract",
      "type",
      "conversationId",
      "cursorHint",
      "userId"
    ],
    "type": "object"
  },
  "ConversationQueueItem": {
    "additionalProperties": false,
    "properties": {
      "fromConv": {
        "type": "string"
      },
      "hasImages": {
        "type": "boolean"
      },
      "hasPdfs": {
        "type": "boolean"
      },
      "hasQuotes": {
        "type": "boolean"
      },
      "hasRefs": {
        "type": "boolean"
      },
      "isPeerHuman": {
        "type": "boolean"
      },
      "isPeerMessage": {
        "type": "boolean"
      },
      "kind": {
        "type": "string"
      },
      "position": {
        "minimum": 1,
        "type": "integer"
      },
      "priority": {
        "minimum": 0,
        "type": "integer"
      },
      "queueId": {
        "type": "string"
      },
      "sourceMessageId": {
        "type": "string"
      },
      "text": {
        "type": "string"
      },
      "timestamp": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "queueId",
      "position",
      "kind",
      "priority",
      "timestamp",
      "text"
    ],
    "type": "object"
  },
  "ConversationSyncEvent": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/ConversationChange"
      },
      {
        "$ref": "#/components/schemas/SyncHeartbeat"
      },
      {
        "$ref": "#/components/schemas/SyncResetRequired"
      }
    ]
  },
  "ConversationSyncSnapshot": {
    "additionalProperties": false,
    "properties": {
      "attempts": {
        "items": {
          "$ref": "#/components/schemas/AttemptRecord"
        },
        "type": "array"
      },
      "contract": {
        "const": "tofu.conversation-sync.snapshot/v1"
      },
      "conversationId": {
        "type": "string"
      },
      "conversationRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "cursor": {
        "type": "string"
      },
      "heartbeatIntervalMs": {
        "minimum": 1000,
        "type": "integer"
      },
      "ok": {
        "const": true
      },
      "pushWithheld": {
        "type": "boolean"
      },
      "queueItems": {
        "items": {
          "$ref": "#/components/schemas/ConversationQueueItem"
        },
        "type": "array"
      },
      "serverBootId": {
        "type": "string"
      },
      "settings": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "syncSeq": {
        "minimum": 0,
        "type": "integer"
      },
      "turns": {
        "items": {
          "$ref": "#/components/schemas/TurnRecord"
        },
        "type": "array"
      }
    },
    "required": [
      "ok",
      "contract",
      "conversationId",
      "conversationRevision",
      "syncSeq",
      "cursor",
      "serverBootId",
      "heartbeatIntervalMs",
      "settings",
      "turns",
      "attempts",
      "queueItems"
    ],
    "type": "object"
  },
  "CreateAttemptRequest": {
    "additionalProperties": false,
    "properties": {
      "commandId": {
        "maxLength": 256,
        "minLength": 1,
        "type": "string"
      },
      "config": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "expectedInputProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "expectedProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "inputUpdate": {},
      "operation": {
        "$ref": "#/components/schemas/TurnResumeOperation"
      },
      "resumeAnchor": {
        "$ref": "#/components/schemas/JsonObject"
      }
    },
    "required": [
      "commandId",
      "operation",
      "expectedProjectionRevision",
      "config"
    ],
    "type": "object"
  },
  "CreateLaneRequest": {
    "additionalProperties": false,
    "properties": {
      "anchorText": {
        "type": "string"
      },
      "expectedProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "kind": {
        "type": "string"
      },
      "parentSelection": {
        "type": "string"
      },
      "title": {
        "maxLength": 500,
        "type": "string"
      }
    },
    "required": [
      "expectedProjectionRevision"
    ],
    "type": "object"
  },
  "CreateTurnRequest": {
    "additionalProperties": false,
    "properties": {
      "actor": {
        "$ref": "#/components/schemas/TurnActor"
      },
      "commandId": {
        "maxLength": 256,
        "minLength": 1,
        "type": "string"
      },
      "config": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "conversation": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "injectMode": {
        "enum": [
          "steer",
          "queue"
        ],
        "type": "string"
      },
      "inputTurn": {},
      "kind": {
        "type": "string"
      },
      "laneId": {
        "type": "string"
      },
      "message": {},
      "parentTurnId": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "runId": {
        "type": "string"
      }
    },
    "required": [
      "commandId",
      "config"
    ],
    "type": "object"
  },
  "DeleteTurnsRequest": {
    "additionalProperties": false,
    "properties": {
      "turnIds": {
        "items": {
          "type": "string"
        },
        "maxItems": 2000,
        "type": "array"
      }
    },
    "required": [
      "turnIds"
    ],
    "type": "object"
  },
  "ExecutePlanRequest": {
    "additionalProperties": false,
    "properties": {
      "commandId": {
        "maxLength": 256,
        "minLength": 1,
        "type": "string"
      },
      "config": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "contextMode": {
        "enum": [
          "current",
          "fresh"
        ],
        "type": "string"
      },
      "expectedProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "planId": {
        "$ref": "#/components/schemas/PlanId"
      }
    },
    "required": [
      "commandId",
      "expectedProjectionRevision",
      "planId",
      "contextMode",
      "config"
    ],
    "type": "object"
  },
  "FileChangesCommandRequest": {
    "additionalProperties": false,
    "properties": {
      "commandId": {
        "maxLength": 256,
        "minLength": 1,
        "type": "string"
      },
      "expectedProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "commandId",
      "expectedProjectionRevision"
    ],
    "type": "object"
  },
  "JsonObject": {
    "additionalProperties": true,
    "type": "object"
  },
  "PlanId": {
    "pattern": "^plan_[0-9a-f]{24}$",
    "type": "string"
  },
  "ProjectionPatch": {
    "additionalProperties": false,
    "properties": {
      "baseRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "operations": {
        "items": {
          "$ref": "#/components/schemas/ProjectionPatchOperation"
        },
        "maxItems": 20000,
        "type": "array"
      },
      "targetRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "version": {
        "const": 1
      }
    },
    "required": [
      "version",
      "baseRevision",
      "targetRevision",
      "operations"
    ],
    "type": "object"
  },
  "ProjectionPatchOperation": {
    "oneOf": [
      {
        "additionalProperties": false,
        "properties": {
          "op": {
            "const": "set"
          },
          "path": {
            "$ref": "#/components/schemas/ProjectionPatchPath"
          },
          "value": {}
        },
        "required": [
          "op",
          "path",
          "value"
        ],
        "type": "object"
      },
      {
        "additionalProperties": false,
        "properties": {
          "op": {
            "const": "remove"
          },
          "path": {
            "$ref": "#/components/schemas/ProjectionPatchPath"
          }
        },
        "required": [
          "op",
          "path"
        ],
        "type": "object"
      },
      {
        "additionalProperties": false,
        "properties": {
          "op": {
            "const": "append"
          },
          "path": {
            "$ref": "#/components/schemas/ProjectionPatchPath"
          },
          "value": {
            "items": {},
            "type": "array"
          }
        },
        "required": [
          "op",
          "path",
          "value"
        ],
        "type": "object"
      },
      {
        "additionalProperties": false,
        "properties": {
          "length": {
            "minimum": 0,
            "type": "integer"
          },
          "op": {
            "const": "truncate"
          },
          "path": {
            "$ref": "#/components/schemas/ProjectionPatchPath"
          }
        },
        "required": [
          "op",
          "path",
          "length"
        ],
        "type": "object"
      },
      {
        "additionalProperties": false,
        "properties": {
          "op": {
            "const": "append_text"
          },
          "path": {
            "$ref": "#/components/schemas/ProjectionPatchPath"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "op",
          "path",
          "value"
        ],
        "type": "object"
      }
    ]
  },
  "ProjectionPatchPath": {
    "items": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "minimum": 0,
          "type": "integer"
        }
      ]
    },
    "type": "array"
  },
  "ProviderStreamState": {
    "enum": [
      "provider_finished",
      "client_aborted",
      "premature_close",
      "malformed_stream",
      "semantic_progress_timeout",
      "no_actionable_output",
      "empty_response",
      "tool_payload_missing",
      "unknown"
    ],
    "type": "string"
  },
  "SyncHeartbeat": {
    "additionalProperties": false,
    "properties": {
      "contract": {
        "const": "tofu.conversation-sync.event/v1"
      },
      "conversationId": {
        "type": "string"
      },
      "cursor": {
        "type": "string"
      },
      "degraded": {
        "type": "boolean"
      },
      "pushWithheld": {
        "type": "boolean"
      },
      "serverBootId": {
        "type": "string"
      },
      "type": {
        "const": "sync.heartbeat"
      }
    },
    "required": [
      "contract",
      "type",
      "conversationId",
      "cursor",
      "serverBootId",
      "degraded"
    ],
    "type": "object"
  },
  "SyncResetRequired": {
    "additionalProperties": false,
    "properties": {
      "contract": {
        "const": "tofu.conversation-sync.event/v1"
      },
      "conversationId": {
        "type": "string"
      },
      "cursor": {
        "type": "string"
      },
      "reason": {
        "enum": [
          "cursor_expired",
          "cursor_invalid",
          "server_restarted",
          "protocol_mismatch"
        ],
        "type": "string"
      },
      "type": {
        "const": "sync.reset_required"
      }
    },
    "required": [
      "contract",
      "type",
      "conversationId",
      "cursor",
      "reason"
    ],
    "type": "object"
  },
  "TurnActivityEntry": {
    "additionalProperties": false,
    "properties": {
      "action": {
        "maxLength": 48,
        "type": "string"
      },
      "archiveId": {
        "maxLength": 160,
        "type": "string"
      },
      "count": {
        "maximum": 2147483647,
        "minimum": 1,
        "type": "integer"
      },
      "detail": {
        "maxLength": 400,
        "type": "string"
      },
      "detailArgs": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "detailKey": {
        "maxLength": 160,
        "type": "string"
      },
      "durationMs": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "endedAt": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "failureStage": {
        "maxLength": 80,
        "type": "string"
      },
      "fromModel": {
        "maxLength": 160,
        "type": "string"
      },
      "id": {
        "maxLength": 160,
        "minLength": 1,
        "type": "string"
      },
      "kind": {
        "enum": [
          "model",
          "tool",
          "status",
          "error",
          "system"
        ],
        "type": "string"
      },
      "llmRound": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "messagesAfter": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "messagesBefore": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "model": {
        "maxLength": 160,
        "type": "string"
      },
      "occurredAt": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "parentSpanId": {
        "maxLength": 160,
        "type": "string"
      },
      "phase": {
        "maxLength": 80,
        "type": "string"
      },
      "providerId": {
        "maxLength": 160,
        "type": "string"
      },
      "reasonCode": {
        "maxLength": 160,
        "type": "string"
      },
      "reductionPercent": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      },
      "requestTag": {
        "maxLength": 80,
        "type": "string"
      },
      "roundNum": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "routeDecision": {
        "maxLength": 80,
        "type": "string"
      },
      "routeId": {
        "maxLength": 160,
        "type": "string"
      },
      "routeMode": {
        "maxLength": 24,
        "type": "string"
      },
      "seq": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "severity": {
        "enum": [
          "info",
          "warning",
          "error"
        ],
        "type": "string"
      },
      "spanId": {
        "maxLength": 160,
        "minLength": 1,
        "type": "string"
      },
      "startedAt": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "status": {
        "enum": [
          "started",
          "running",
          "waiting",
          "succeeded",
          "failed",
          "skipped",
          "switched",
          "aborted"
        ],
        "type": "string"
      },
      "statusCode": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "summary": {
        "maxLength": 180,
        "type": "string"
      },
      "summaryArgs": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "summaryKey": {
        "maxLength": 160,
        "type": "string"
      },
      "timingMode": {
        "maxLength": 24,
        "type": "string"
      },
      "toModel": {
        "maxLength": 160,
        "type": "string"
      },
      "tokenCountKind": {
        "maxLength": 24,
        "type": "string"
      },
      "tokensAfter": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "tokensBefore": {
        "maximum": 9007199254740991,
        "minimum": 0,
        "type": "integer"
      },
      "toolCallId": {
        "maxLength": 160,
        "type": "string"
      },
      "toolName": {
        "maxLength": 160,
        "type": "string"
      },
      "trigger": {
        "maxLength": 80,
        "type": "string"
      }
    },
    "required": [
      "id",
      "spanId",
      "seq",
      "occurredAt",
      "kind",
      "status",
      "severity",
      "count"
    ],
    "type": "object"
  },
  "TurnActivityTimeline": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "const": "activity-timeline"
      },
      "droppedCount": {
        "maximum": 2147483647,
        "minimum": 0,
        "type": "integer"
      },
      "entries": {
        "items": {
          "$ref": "#/components/schemas/TurnActivityEntry"
        },
        "maxItems": 128,
        "type": "array"
      },
      "version": {
        "const": 1
      }
    },
    "required": [
      "blockId",
      "version",
      "entries"
    ],
    "type": "object"
  },
  "TurnActor": {
    "enum": [
      "human",
      "assistant",
      "planner",
      "critic",
      "virtual_user"
    ],
    "type": "string"
  },
  "TurnBrainDispatch": {
    "additionalProperties": false,
    "properties": {
      "answered": {
        "type": "boolean"
      },
      "epicId": {
        "type": "string"
      },
      "epicTitle": {
        "type": "string"
      },
      "method": {
        "type": "string"
      },
      "originatorConv": {
        "type": "string"
      },
      "originatorTitle": {
        "type": "string"
      },
      "route": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TurnCommandResponse": {
    "additionalProperties": true,
    "properties": {
      "aborted": {
        "type": "boolean"
      },
      "attempt": {
        "$ref": "#/components/schemas/AttemptRecord"
      },
      "conversationId": {
        "type": "string"
      },
      "conversationRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "cursor": {
        "type": "string"
      },
      "deletedTurnIds": {
        "description": "Turns discarded atomically by this command. A regenerate retry supersedes the whole lane tail: every turn after the regenerated turn (plus branch lanes rooted inside that tail) is truncated in the same transaction, so no client can observe a half-rewritten history.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "idempotentReplay": {
        "type": "boolean"
      },
      "latestTurn": {
        "$ref": "#/components/schemas/TurnRecord"
      },
      "ok": {
        "const": true
      },
      "position": {
        "minimum": 0,
        "type": "integer"
      },
      "queueId": {
        "type": "string"
      },
      "queueItem": {
        "$ref": "#/components/schemas/ConversationQueueItem"
      },
      "queued": {
        "type": "boolean"
      },
      "steered": {
        "type": "boolean"
      },
      "submittedTurn": {
        "$ref": "#/components/schemas/TurnRecord"
      },
      "turn": {
        "$ref": "#/components/schemas/TurnRecord"
      }
    },
    "required": [
      "ok",
      "conversationId",
      "conversationRevision"
    ],
    "type": "object"
  },
  "TurnCompaction": {
    "additionalProperties": false,
    "properties": {
      "archiveId": {
        "type": "string"
      },
      "blockId": {
        "type": "string"
      },
      "conversationId": {
        "type": "string"
      },
      "estimatedPromptTokens": {
        "minimum": 0,
        "type": "integer"
      },
      "foldedToolRounds": {
        "minimum": 0,
        "type": "integer"
      },
      "messagesAfter": {
        "minimum": 0,
        "type": "integer"
      },
      "messagesBefore": {
        "minimum": 0,
        "type": "integer"
      },
      "reductionPercent": {
        "maximum": 100,
        "minimum": 0,
        "type": "integer"
      },
      "timestamp": {
        "minimum": 0,
        "type": "integer"
      },
      "tokensAfter": {
        "minimum": 0,
        "type": "integer"
      },
      "tokensBefore": {
        "minimum": 0,
        "type": "integer"
      },
      "trigger": {
        "type": "string"
      }
    },
    "required": [
      "blockId"
    ],
    "type": "object"
  },
  "TurnContentSegment": {
    "oneOf": [
      {
        "$ref": "#/components/schemas/TurnTextSegment"
      },
      {
        "$ref": "#/components/schemas/TurnThinkingSegment"
      },
      {
        "$ref": "#/components/schemas/TurnToolUseSegment"
      }
    ]
  },
  "TurnContextSnapshot": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "type": "string"
      },
      "snapshot": {
        "$ref": "#/components/schemas/JsonObject"
      }
    },
    "required": [
      "blockId",
      "snapshot"
    ],
    "type": "object"
  },
  "TurnContinuation": {
    "additionalProperties": false,
    "properties": {
      "attemptId": {
        "type": "string"
      },
      "turnId": {
        "type": "string"
      }
    },
    "required": [
      "turnId",
      "attemptId"
    ],
    "type": "object"
  },
  "TurnConversationReference": {
    "additionalProperties": true,
    "properties": {
      "id": {
        "type": "string"
      },
      "title": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TurnDocumentAttachment": {
    "additionalProperties": true,
    "properties": {
      "isScanned": {
        "type": "boolean"
      },
      "method": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "pages": {
        "minimum": 0,
        "type": "integer"
      },
      "text": {
        "type": "string"
      },
      "textLength": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "TurnFileChange": {
    "additionalProperties": true,
    "properties": {
      "action": {
        "type": "string"
      },
      "count": {
        "minimum": 0,
        "type": "integer"
      },
      "ok": {
        "type": "boolean"
      },
      "path": {
        "type": "string"
      },
      "pending": {
        "type": "boolean"
      },
      "root": {
        "type": "string"
      }
    },
    "required": [
      "path"
    ],
    "type": "object"
  },
  "TurnFileChangesBlock": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "type": "string"
      },
      "commandId": {
        "type": "string"
      },
      "count": {
        "minimum": 0,
        "type": "integer"
      },
      "effect": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "error": {},
      "files": {
        "items": {
          "$ref": "#/components/schemas/TurnFileChange"
        },
        "type": "array"
      },
      "state": {
        "enum": [
          "applied",
          "undoing",
          "undone",
          "redoing",
          "error"
        ],
        "type": "string"
      },
      "taskId": {
        "type": "string"
      }
    },
    "required": [
      "blockId",
      "count",
      "files"
    ],
    "type": "object"
  },
  "TurnImageAttachment": {
    "additionalProperties": true,
    "properties": {
      "attachmentId": {
        "type": "string"
      },
      "caption": {
        "type": "string"
      },
      "pdfImageSource": {
        "type": "string"
      },
      "pdfName": {
        "type": "string"
      },
      "pdfPage": {
        "minimum": 1,
        "type": "integer"
      },
      "pdfTotal": {
        "minimum": 1,
        "type": "integer"
      },
      "preview": {
        "type": "string"
      },
      "sizeKB": {
        "oneOf": [
          {
            "type": "number"
          },
          {
            "type": "string"
          }
        ]
      }
    },
    "type": "object"
  },
  "TurnImageGeneration": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "type": "string"
      },
      "error": {},
      "mode": {
        "enum": [
          "generate",
          "edit",
          "batch"
        ],
        "type": "string"
      },
      "results": {
        "items": {
          "$ref": "#/components/schemas/TurnImageGenerationResult"
        },
        "type": "array"
      },
      "status": {
        "enum": [
          "running",
          "completed",
          "failed",
          "cancelled"
        ],
        "type": "string"
      }
    },
    "required": [
      "blockId",
      "mode",
      "status",
      "results"
    ],
    "type": "object"
  },
  "TurnImageGenerationResult": {
    "additionalProperties": false,
    "properties": {
      "aspectRatio": {
        "type": "string"
      },
      "elapsedSeconds": {
        "minimum": 0,
        "type": "number"
      },
      "error": {
        "type": "string"
      },
      "errorType": {
        "type": "string"
      },
      "fileSize": {
        "minimum": 0,
        "type": "integer"
      },
      "imageUrl": {
        "type": "string"
      },
      "model": {
        "type": "string"
      },
      "ok": {
        "type": "boolean"
      },
      "prompt": {
        "type": "string"
      },
      "providerId": {
        "type": "string"
      },
      "remoteImageUrl": {
        "type": "string"
      },
      "resolution": {
        "type": "string"
      },
      "responseText": {
        "type": "string"
      }
    },
    "required": [
      "ok",
      "prompt",
      "model"
    ],
    "type": "object"
  },
  "TurnInjectionPreview": {
    "additionalProperties": true,
    "properties": {
      "agentId": {
        "type": "string"
      },
      "fromConv": {
        "type": "string"
      },
      "text": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TurnMessageInjection": {
    "additionalProperties": true,
    "properties": {
      "agentIds": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "blockId": {
        "type": "string"
      },
      "count": {
        "minimum": 0,
        "type": "integer"
      },
      "previews": {
        "items": {
          "$ref": "#/components/schemas/TurnInjectionPreview"
        },
        "type": "array"
      },
      "round": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "blockId"
    ],
    "type": "object"
  },
  "TurnMutationResponse": {
    "additionalProperties": true,
    "properties": {
      "conversationRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "cursor": {
        "type": "string"
      },
      "deletedTurnIds": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "ok": {
        "const": true
      },
      "turn": {
        "$ref": "#/components/schemas/TurnRecord"
      },
      "turns": {
        "items": {
          "$ref": "#/components/schemas/TurnRecord"
        },
        "type": "array"
      }
    },
    "required": [
      "ok",
      "conversationRevision"
    ],
    "type": "object"
  },
  "TurnOrchestration": {
    "additionalProperties": false,
    "properties": {
      "approved": {
        "type": "boolean"
      },
      "flowNodeId": {
        "type": "string"
      },
      "flowRunId": {
        "type": "string"
      },
      "iteration": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "nextPhase": {
        "type": "string"
      },
      "stuck": {
        "type": "boolean"
      }
    },
    "type": "object"
  },
  "TurnOrigin": {
    "additionalProperties": false,
    "properties": {
      "autopilotRunId": {
        "type": "string"
      },
      "blockId": {
        "type": "string"
      },
      "boardTaskId": {
        "type": "string"
      },
      "brain": {
        "$ref": "#/components/schemas/TurnBrainDispatch"
      },
      "initiator": {
        "enum": [
          "human",
          "autopilot",
          "proactive",
          "timer",
          "brain",
          "peer",
          "operator",
          "swarm"
        ],
        "type": "string"
      },
      "peerHuman": {
        "type": "boolean"
      },
      "scheduledTaskId": {
        "type": "string"
      },
      "sourceConversationId": {
        "type": "string"
      }
    },
    "required": [
      "blockId",
      "initiator"
    ],
    "type": "object"
  },
  "TurnOutcome": {
    "enum": [
      "completed",
      "interrupted",
      "truncated",
      "failed"
    ],
    "type": "string"
  },
  "TurnPlanExecution": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "const": "plan-execution"
      },
      "contextMode": {
        "enum": [
          "current",
          "fresh"
        ],
        "type": "string"
      },
      "planId": {
        "$ref": "#/components/schemas/PlanId"
      },
      "planText": {
        "maxLength": 64000,
        "minLength": 1,
        "type": "string"
      },
      "sourceProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "sourceTurnId": {
        "type": "string"
      }
    },
    "required": [
      "blockId",
      "planId",
      "sourceTurnId",
      "sourceProjectionRevision",
      "contextMode",
      "planText"
    ],
    "type": "object"
  },
  "TurnProjection": {
    "additionalProperties": false,
    "properties": {
      "_autopilotRunId": {
        "type": "string"
      },
      "_boardTaskId": {
        "type": "string"
      },
      "_brainDispatch": {
        "type": "boolean"
      },
      "_brainEpic": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "_branchLanes": {
        "items": {
          "$ref": "#/components/schemas/BranchLaneDescriptor"
        },
        "type": "array"
      },
      "_compactionArchiveId": {
        "type": "string"
      },
      "_compactions": {
        "items": {
          "$ref": "#/components/schemas/JsonObject"
        },
        "type": "array"
      },
      "_ctx": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "_estimatedPromptTokens": {
        "minimum": 0,
        "type": "integer"
      },
      "_flowApproved": {
        "type": "boolean"
      },
      "_flowIteration": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "_flowNextPhase": {
        "type": "string"
      },
      "_flowNodeId": {
        "type": "string"
      },
      "_flowPlannerIteration": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "string"
          }
        ]
      },
      "_flowRunId": {
        "type": "string"
      },
      "_foldedToolRounds": {
        "minimum": 0,
        "type": "integer"
      },
      "_fromConv": {
        "type": "string"
      },
      "_inboxInjects": {
        "items": {
          "$ref": "#/components/schemas/TurnMessageInjection"
        },
        "type": "array"
      },
      "_initiator": {
        "type": "string"
      },
      "_isCompactionSummary": {
        "type": "boolean"
      },
      "_isFlowPlanner": {
        "type": "boolean"
      },
      "_isFlowReview": {
        "type": "boolean"
      },
      "_isStuck": {
        "type": "boolean"
      },
      "_isVirtualUser": {
        "type": "boolean"
      },
      "_peerHuman": {
        "type": "boolean"
      },
      "_peerInjects": {
        "items": {
          "$ref": "#/components/schemas/TurnMessageInjection"
        },
        "type": "array"
      },
      "_peerMessage": {
        "type": "boolean"
      },
      "_proactive": {
        "type": "boolean"
      },
      "_proactiveTaskId": {
        "type": "string"
      },
      "_showingTranslation": {
        "type": "boolean"
      },
      "_stallNudges": {
        "items": {
          "$ref": "#/components/schemas/TurnStallInjection"
        },
        "type": "array"
      },
      "_swarmAutoContinue": {
        "type": "boolean"
      },
      "_timer": {
        "type": "boolean"
      },
      "_translateDone": {
        "type": "boolean"
      },
      "_translateError": {},
      "_translateFailed": {},
      "_translateModel": {
        "type": "string"
      },
      "_translatePartial": {
        "type": "string"
      },
      "_translatePartialByRound": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "_translateSkippedReason": {
        "type": "string"
      },
      "_translateStatus": {
        "type": "string"
      },
      "_translateStatusKind": {
        "type": "string"
      },
      "_translateTaskId": {
        "type": "string"
      },
      "_userSteerInjects": {
        "items": {
          "$ref": "#/components/schemas/TurnMessageInjection"
        },
        "type": "array"
      },
      "activityTimeline": {
        "$ref": "#/components/schemas/TurnActivityTimeline"
      },
      "apiRounds": {
        "items": {
          "$ref": "#/components/schemas/JsonObject"
        },
        "type": "array"
      },
      "boardTaskId": {
        "type": "string"
      },
      "compaction": {
        "$ref": "#/components/schemas/TurnCompaction"
      },
      "content": {
        "type": "string"
      },
      "contextSnapshot": {
        "$ref": "#/components/schemas/TurnContextSnapshot"
      },
      "convRefs": {
        "items": {
          "$ref": "#/components/schemas/TurnConversationReference"
        },
        "type": "array"
      },
      "error": {},
      "fallbackFrom": {
        "type": "string"
      },
      "fallbackKind": {
        "type": "string"
      },
      "fallbackModel": {
        "type": "string"
      },
      "fallbackReason": {
        "type": "string"
      },
      "fileChanges": {
        "$ref": "#/components/schemas/TurnFileChangesBlock"
      },
      "imageGeneration": {
        "$ref": "#/components/schemas/TurnImageGeneration"
      },
      "images": {
        "items": {
          "$ref": "#/components/schemas/TurnImageAttachment"
        },
        "type": "array"
      },
      "lastRoundUsage": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "model": {
        "type": "string"
      },
      "modifiedFileList": {
        "items": {
          "$ref": "#/components/schemas/TurnFileChange"
        },
        "type": "array"
      },
      "modifiedFiles": {
        "minimum": 0,
        "type": "integer"
      },
      "orchestration": {
        "$ref": "#/components/schemas/TurnOrchestration"
      },
      "origin": {
        "$ref": "#/components/schemas/TurnOrigin"
      },
      "originalContent": {
        "type": "string"
      },
      "pdfTexts": {
        "items": {
          "$ref": "#/components/schemas/TurnDocumentAttachment"
        },
        "type": "array"
      },
      "planExecution": {
        "$ref": "#/components/schemas/TurnPlanExecution"
      },
      "preset": {
        "type": "string"
      },
      "proposedPlan": {
        "$ref": "#/components/schemas/TurnProposedPlan"
      },
      "provenance": {
        "$ref": "#/components/schemas/TurnProvenance"
      },
      "providerId": {
        "type": "string"
      },
      "provider_id": {
        "type": "string"
      },
      "replyQuotes": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "segments": {
        "items": {
          "$ref": "#/components/schemas/TurnContentSegment"
        },
        "type": "array"
      },
      "thinking": {
        "type": "string"
      },
      "thinkingDepth": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "number"
          }
        ]
      },
      "timestamp": {
        "oneOf": [
          {
            "type": "number"
          },
          {
            "type": "string"
          }
        ]
      },
      "todoState": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "toolRounds": {
        "items": {
          "$ref": "#/components/schemas/TurnToolRound"
        },
        "type": "array"
      },
      "translatedContent": {
        "type": "string"
      },
      "translation": {
        "$ref": "#/components/schemas/TurnTranslation"
      },
      "usage": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "videos": {
        "items": {
          "$ref": "#/components/schemas/TurnVideoAttachment"
        },
        "type": "array"
      }
    },
    "type": "object"
  },
  "TurnProjectionChange": {
    "additionalProperties": false,
    "properties": {
      "baseProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "projectionPatch": {
        "$ref": "#/components/schemas/ProjectionPatch"
      },
      "targetProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "turnId": {
        "type": "string"
      },
      "updatedAt": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "turnId",
      "baseProjectionRevision",
      "targetProjectionRevision",
      "updatedAt",
      "projectionPatch"
    ],
    "type": "object"
  },
  "TurnProposedPlan": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "const": "proposed-plan"
      },
      "format": {
        "const": "markdown"
      },
      "planId": {
        "$ref": "#/components/schemas/PlanId"
      },
      "revision": {
        "const": 1
      },
      "text": {
        "maxLength": 64000,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "blockId",
      "planId",
      "revision",
      "format",
      "text"
    ],
    "type": "object"
  },
  "TurnProvenance": {
    "additionalProperties": false,
    "properties": {
      "blockId": {
        "type": "string"
      },
      "mcpLoginHint": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "memoryPrefetch": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "preferencesApplied": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "preferencesLearned": {
        "items": {
          "$ref": "#/components/schemas/JsonObject"
        },
        "type": "array"
      },
      "relatedConversations": {
        "$ref": "#/components/schemas/JsonObject"
      }
    },
    "required": [
      "blockId"
    ],
    "type": "object"
  },
  "TurnRecord": {
    "additionalProperties": false,
    "properties": {
      "actor": {
        "$ref": "#/components/schemas/TurnActor"
      },
      "conversationId": {
        "type": "string"
      },
      "createdAt": {
        "minimum": 0,
        "type": "integer"
      },
      "currentAttemptId": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "kind": {
        "type": "string"
      },
      "laneId": {
        "type": "string"
      },
      "ordinal": {
        "minimum": 0,
        "type": "integer"
      },
      "parentTurnId": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "projection": {
        "$ref": "#/components/schemas/TurnProjection"
      },
      "projectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "runId": {
        "type": "string"
      },
      "settlement": {
        "$ref": "#/components/schemas/TurnSettlement"
      },
      "status": {
        "$ref": "#/components/schemas/TurnStatus"
      },
      "turnId": {
        "type": "string"
      },
      "updatedAt": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "turnId",
      "conversationId",
      "laneId",
      "ordinal",
      "actor",
      "kind",
      "runId",
      "status",
      "projection",
      "projectionRevision",
      "settlement",
      "createdAt",
      "updatedAt"
    ],
    "type": "object"
  },
  "TurnResumeOperation": {
    "enum": [
      "continue",
      "checkpoint_resume",
      "regenerate"
    ],
    "type": "string"
  },
  "TurnResumeOption": {
    "additionalProperties": false,
    "properties": {
      "anchor": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "operation": {
        "$ref": "#/components/schemas/TurnResumeOperation"
      }
    },
    "required": [
      "operation",
      "anchor"
    ],
    "type": "object"
  },
  "TurnRuntimeStateChange": {
    "additionalProperties": false,
    "properties": {
      "currentAttemptId": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "settlement": {
        "$ref": "#/components/schemas/TurnSettlement"
      },
      "status": {
        "$ref": "#/components/schemas/TurnStatus"
      },
      "turnId": {
        "type": "string"
      },
      "updatedAt": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "required": [
      "turnId",
      "status",
      "currentAttemptId",
      "settlement",
      "updatedAt"
    ],
    "type": "object"
  },
  "TurnSettlement": {
    "additionalProperties": false,
    "properties": {
      "cause": {
        "type": "string"
      },
      "continuation": {
        "$ref": "#/components/schemas/TurnContinuation"
      },
      "error": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/JsonObject"
          },
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "evidence": {
        "$ref": "#/components/schemas/TurnTerminationEvidence"
      },
      "outcome": {
        "$ref": "#/components/schemas/TurnOutcome"
      },
      "providerFinishReason": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "resumeOptions": {
        "items": {
          "$ref": "#/components/schemas/TurnResumeOption"
        },
        "type": "array"
      },
      "streamState": {
        "oneOf": [
          {
            "$ref": "#/components/schemas/ProviderStreamState"
          },
          {
            "type": "null"
          }
        ]
      }
    },
    "type": "object"
  },
  "TurnStallInjection": {
    "additionalProperties": true,
    "properties": {
      "badge": {
        "type": "string"
      },
      "blockId": {
        "type": "string"
      },
      "failedRound": {
        "minimum": 0,
        "type": "integer"
      },
      "max": {
        "minimum": 0,
        "type": "integer"
      },
      "prompt": {
        "type": "string"
      },
      "round": {
        "minimum": 0,
        "type": "integer"
      },
      "tool": {
        "type": "string"
      }
    },
    "required": [
      "blockId"
    ],
    "type": "object"
  },
  "TurnStatus": {
    "enum": [
      "pending",
      "running",
      "completed",
      "interrupted",
      "truncated",
      "failed"
    ],
    "type": "string"
  },
  "TurnTerminationEvidence": {
    "enum": [
      "provider_finish",
      "legacy_finish",
      "provider_limit",
      "user_abort",
      "provider_stream_failure",
      "generation_error",
      "missing_completion_evidence",
      "external_authority",
      "system_recovery"
    ],
    "type": "string"
  },
  "TurnTextSegment": {
    "additionalProperties": true,
    "properties": {
      "blockId": {
        "type": "string"
      },
      "deliverable": {
        "type": "boolean"
      },
      "llmRound": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "resumable": {
        "type": "boolean"
      },
      "terminal": {
        "type": "boolean"
      },
      "text": {
        "type": "string"
      },
      "translatedText": {
        "type": "string"
      },
      "type": {
        "const": "text"
      }
    },
    "required": [
      "type",
      "blockId",
      "text"
    ],
    "type": "object"
  },
  "TurnThinkingSegment": {
    "additionalProperties": true,
    "properties": {
      "blockId": {
        "type": "string"
      },
      "deliverable": {
        "type": "boolean"
      },
      "llmRound": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "signature": {
        "type": "string"
      },
      "terminal": {
        "type": "boolean"
      },
      "text": {
        "type": "string"
      },
      "translatedText": {
        "type": "string"
      },
      "type": {
        "const": "thinking"
      }
    },
    "required": [
      "type",
      "blockId",
      "text"
    ],
    "type": "object"
  },
  "TurnToolRejection": {
    "additionalProperties": true,
    "properties": {
      "attempted": {
        "maxLength": 256,
        "type": "string"
      },
      "kind": {
        "maxLength": 128,
        "minLength": 1,
        "type": "string"
      },
      "reason": {
        "maxLength": 4096,
        "type": "string"
      },
      "retryable": {
        "type": "boolean"
      },
      "suggestions": {
        "items": {
          "maxLength": 256,
          "type": "string"
        },
        "maxItems": 16,
        "type": "array"
      },
      "tool": {
        "maxLength": 256,
        "type": "string"
      }
    },
    "required": [
      "kind"
    ],
    "type": "object"
  },
  "TurnToolResult": {
    "additionalProperties": true,
    "properties": {
      "_rejected": {
        "$ref": "#/components/schemas/TurnToolRejection",
        "deprecated": true
      },
      "content": {},
      "rejected": {
        "$ref": "#/components/schemas/TurnToolRejection",
        "deprecated": true
      },
      "rejection": {
        "$ref": "#/components/schemas/TurnToolRejection"
      },
      "status": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TurnToolRound": {
    "additionalProperties": true,
    "properties": {
      "_rejected": {
        "$ref": "#/components/schemas/TurnToolRejection",
        "deprecated": true
      },
      "assistantContent": {
        "type": "string"
      },
      "deadlineTs": {
        "type": "number"
      },
      "execStartTs": {
        "type": "number"
      },
      "llmRound": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "query": {
        "type": "string"
      },
      "rejection": {
        "$ref": "#/components/schemas/TurnToolRejection"
      },
      "result": {
        "$ref": "#/components/schemas/TurnToolResult"
      },
      "results": {
        "items": {},
        "type": "array"
      },
      "roundNum": {
        "minimum": 0,
        "type": "integer"
      },
      "status": {
        "type": "string"
      },
      "tStart": {
        "type": "number"
      },
      "thinking": {
        "type": "string"
      },
      "thinkingSignature": {
        "type": "string"
      },
      "toolArgs": {},
      "toolCallId": {
        "type": "string"
      },
      "toolContent": {},
      "toolName": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TurnToolUseSegment": {
    "additionalProperties": true,
    "properties": {
      "_round": {
        "$ref": "#/components/schemas/TurnToolRound"
      },
      "blockId": {
        "type": "string"
      },
      "id": {
        "type": "string"
      },
      "input": {},
      "llmRound": {
        "oneOf": [
          {
            "minimum": 0,
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "name": {
        "type": "string"
      },
      "result": {
        "$ref": "#/components/schemas/TurnToolResult"
      },
      "type": {
        "const": "tool_use"
      }
    },
    "required": [
      "type",
      "blockId",
      "id",
      "name",
      "result"
    ],
    "type": "object"
  },
  "TurnTranslation": {
    "additionalProperties": false,
    "properties": {
      "error": {},
      "model": {
        "type": "string"
      },
      "partial": {
        "type": "string"
      },
      "partialByRound": {
        "$ref": "#/components/schemas/JsonObject"
      },
      "sendFailure": {},
      "skippedReason": {
        "type": "string"
      },
      "status": {
        "enum": [
          "pending",
          "completed",
          "skipped",
          "failed"
        ],
        "type": "string"
      },
      "statusKind": {
        "type": "string"
      },
      "statusMessage": {
        "type": "string"
      },
      "taskId": {
        "type": "string"
      }
    },
    "type": "object"
  },
  "TurnVideoAttachment": {
    "additionalProperties": true,
    "properties": {
      "avg_frame_bytes": {
        "minimum": 0,
        "type": "number"
      },
      "duration_s": {
        "minimum": 0,
        "type": "number"
      },
      "frame_count": {
        "minimum": 0,
        "type": "integer"
      },
      "frames": {
        "items": {},
        "type": "array"
      },
      "height": {
        "minimum": 0,
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "poster": {
        "type": "string"
      },
      "storyboard": {
        "type": "string"
      },
      "storyboard_model": {
        "type": "string"
      },
      "transcript": {
        "type": "string"
      },
      "transcript_model": {
        "type": "string"
      },
      "transcript_status": {
        "type": "string"
      },
      "video_id": {
        "type": "string"
      },
      "video_url": {
        "type": "string"
      },
      "width": {
        "minimum": 0,
        "type": "integer"
      }
    },
    "type": "object"
  },
  "UpdateTurnRequest": {
    "additionalProperties": false,
    "properties": {
      "expectedProjectionRevision": {
        "minimum": 0,
        "type": "integer"
      },
      "projection": {
        "$ref": "#/components/schemas/TurnProjection"
      }
    },
    "required": [
      "expectedProjectionRevision",
      "projection"
    ],
    "type": "object"
  }
} as const;

export type JsonObject = {
  [key: string]: unknown;
};

export type TurnStatus = "pending" | "running" | "completed" | "interrupted" | "truncated" | "failed";

export type AttemptStatus = "pending" | "running" | "completed" | "interrupted" | "truncated" | "failed" | "superseded";

export type TurnActor = "human" | "assistant" | "planner" | "critic" | "virtual_user";

export type TurnToolResult = {
  "content"?: unknown;
  "status"?: string;
  "rejection"?: TurnToolRejection;
  "_rejected"?: TurnToolRejection;
  "rejected"?: TurnToolRejection;
  [key: string]: unknown;
};

export type TurnToolRejection = {
  "kind": string;
  "tool"?: string;
  "attempted"?: string;
  "reason"?: string;
  "retryable"?: boolean;
  "suggestions"?: ReadonlyArray<string>;
  [key: string]: unknown;
};

export type TurnToolRound = {
  "roundNum"?: number;
  "llmRound"?: (number) | (null);
  "toolCallId"?: string;
  "toolName"?: string;
  "toolArgs"?: unknown;
  "toolContent"?: unknown;
  "query"?: string;
  "status"?: string;
  "rejection"?: TurnToolRejection;
  "_rejected"?: TurnToolRejection;
  "assistantContent"?: string;
  "thinking"?: string;
  "thinkingSignature"?: string;
  "result"?: TurnToolResult;
  "results"?: ReadonlyArray<unknown>;
  "tStart"?: number;
  "execStartTs"?: number;
  "deadlineTs"?: number;
  [key: string]: unknown;
};

export type TurnTextSegment = {
  "type": "text";
  "blockId": string;
  "text": string;
  "translatedText"?: string;
  "deliverable"?: boolean;
  "terminal"?: boolean;
  "resumable"?: boolean;
  "llmRound"?: (number) | (null);
  [key: string]: unknown;
};

export type TurnThinkingSegment = {
  "type": "thinking";
  "blockId": string;
  "text": string;
  "translatedText"?: string;
  "deliverable"?: boolean;
  "terminal"?: boolean;
  "signature"?: string;
  "llmRound"?: (number) | (null);
  [key: string]: unknown;
};

export type TurnToolUseSegment = {
  "type": "tool_use";
  "blockId": string;
  "id": string;
  "name": string;
  "input"?: unknown;
  "llmRound"?: (number) | (null);
  "result": TurnToolResult;
  "_round"?: TurnToolRound;
  [key: string]: unknown;
};

export type TurnContentSegment = (TurnTextSegment) | (TurnThinkingSegment) | (TurnToolUseSegment);

export type BranchLaneDescriptor = {
  "laneId": string;
  "title"?: string;
  "label"?: string;
  "icon"?: string;
  "kind"?: string;
  "anchorText"?: string;
  "parentSelection"?: string;
  [key: string]: unknown;
};

export type TurnImageAttachment = {
  "attachmentId"?: string;
  "preview"?: string;
  "caption"?: string;
  "sizeKB"?: (number) | (string);
  "pdfPage"?: number;
  "pdfTotal"?: number;
  "pdfName"?: string;
  "pdfImageSource"?: string;
  [key: string]: unknown;
};

export type TurnVideoAttachment = {
  "video_id"?: string;
  "name"?: string;
  "video_url"?: string;
  "poster"?: string;
  "duration_s"?: number;
  "width"?: number;
  "height"?: number;
  "frames"?: ReadonlyArray<unknown>;
  "frame_count"?: number;
  "avg_frame_bytes"?: number;
  "transcript"?: string;
  "transcript_status"?: string;
  "transcript_model"?: string;
  "storyboard"?: string;
  "storyboard_model"?: string;
  [key: string]: unknown;
};

export type TurnDocumentAttachment = {
  "name"?: string;
  "text"?: string;
  "textLength"?: number;
  "pages"?: number;
  "isScanned"?: boolean;
  "method"?: string;
  [key: string]: unknown;
};

export type TurnConversationReference = {
  "id"?: string;
  "title"?: string;
  [key: string]: unknown;
};

export type TurnInjectionPreview = {
  "text"?: string;
  "agentId"?: string;
  "fromConv"?: string;
  [key: string]: unknown;
};

export type TurnMessageInjection = {
  "blockId": string;
  "round"?: number;
  "count"?: number;
  "agentIds"?: ReadonlyArray<string>;
  "previews"?: ReadonlyArray<TurnInjectionPreview>;
  [key: string]: unknown;
};

export type TurnStallInjection = {
  "blockId": string;
  "round"?: number;
  "tool"?: string;
  "failedRound"?: number;
  "badge"?: string;
  "prompt"?: string;
  "max"?: number;
  [key: string]: unknown;
};

export type TurnFileChange = {
  "path": string;
  "action"?: string;
  "root"?: string;
  "count"?: number;
  "ok"?: boolean;
  "pending"?: boolean;
  [key: string]: unknown;
};

export type TurnFileChangesBlock = {
  "blockId": string;
  "taskId"?: string;
  "count": number;
  "state"?: "applied" | "undoing" | "undone" | "redoing" | "error";
  "commandId"?: string;
  "error"?: unknown;
  "effect"?: JsonObject;
  "files": ReadonlyArray<TurnFileChange>;
};

export type TurnOrchestration = {
  "iteration"?: (number) | (string);
  "approved"?: boolean;
  "nextPhase"?: string;
  "stuck"?: boolean;
  "flowNodeId"?: string;
  "flowRunId"?: string;
};

export type TurnProvenance = {
  "blockId": string;
  "memoryPrefetch"?: JsonObject;
  "mcpLoginHint"?: JsonObject;
  "preferencesApplied"?: JsonObject;
  "preferencesLearned"?: ReadonlyArray<JsonObject>;
  "relatedConversations"?: JsonObject;
};

export type TurnBrainDispatch = {
  "epicId"?: string;
  "epicTitle"?: string;
  "originatorConv"?: string;
  "originatorTitle"?: string;
  "route"?: string;
  "method"?: string;
  "answered"?: boolean;
};

export type TurnOrigin = {
  "blockId": string;
  "initiator": "human" | "autopilot" | "proactive" | "timer" | "brain" | "peer" | "operator" | "swarm";
  "sourceConversationId"?: string;
  "peerHuman"?: boolean;
  "brain"?: TurnBrainDispatch;
  "autopilotRunId"?: string;
  "boardTaskId"?: string;
  "scheduledTaskId"?: string;
};

export type TurnContextSnapshot = {
  "blockId": string;
  "snapshot": JsonObject;
};

export type TurnCompaction = {
  "blockId": string;
  "archiveId"?: string;
  "conversationId"?: string;
  "trigger"?: string;
  "timestamp"?: number;
  "tokensBefore"?: number;
  "tokensAfter"?: number;
  "messagesBefore"?: number;
  "messagesAfter"?: number;
  "reductionPercent"?: number;
  "foldedToolRounds"?: number;
  "estimatedPromptTokens"?: number;
};

export type TurnTranslation = {
  "status"?: "pending" | "completed" | "skipped" | "failed";
  "model"?: string;
  "error"?: unknown;
  "taskId"?: string;
  "statusMessage"?: string;
  "statusKind"?: string;
  "partial"?: string;
  "partialByRound"?: JsonObject;
  "sendFailure"?: unknown;
  "skippedReason"?: string;
};

export type TurnImageGenerationResult = {
  "ok": boolean;
  "prompt": string;
  "model": string;
  "providerId"?: string;
  "aspectRatio"?: string;
  "resolution"?: string;
  "imageUrl"?: string;
  "remoteImageUrl"?: string;
  "fileSize"?: number;
  "elapsedSeconds"?: number;
  "responseText"?: string;
  "error"?: string;
  "errorType"?: string;
};

export type TurnImageGeneration = {
  "blockId": string;
  "mode": "generate" | "edit" | "batch";
  "status": "running" | "completed" | "failed" | "cancelled";
  "results": ReadonlyArray<TurnImageGenerationResult>;
  "error"?: unknown;
};

export type PlanId = string;

export type TurnProposedPlan = {
  "blockId": "proposed-plan";
  "planId": PlanId;
  "revision": 1;
  "format": "markdown";
  "text": string;
};

export type TurnPlanExecution = {
  "blockId": "plan-execution";
  "planId": PlanId;
  "sourceTurnId": string;
  "sourceProjectionRevision": number;
  "contextMode": "current" | "fresh";
  "planText": string;
};

export type TurnActivityEntry = {
  "id": string;
  "spanId": string;
  "parentSpanId"?: string;
  "seq": number;
  "occurredAt": number;
  "startedAt"?: number;
  "endedAt"?: number;
  "kind": "model" | "tool" | "status" | "error" | "system";
  "status": "started" | "running" | "waiting" | "succeeded" | "failed" | "skipped" | "switched" | "aborted";
  "severity": "info" | "warning" | "error";
  "summary"?: string;
  "summaryKey"?: string;
  "summaryArgs"?: JsonObject;
  "detail"?: string;
  "detailKey"?: string;
  "detailArgs"?: JsonObject;
  "roundNum"?: number;
  "llmRound"?: number;
  "model"?: string;
  "providerId"?: string;
  "toolName"?: string;
  "toolCallId"?: string;
  "reasonCode"?: string;
  "action"?: string;
  "fromModel"?: string;
  "toModel"?: string;
  "requestTag"?: string;
  "phase"?: string;
  "archiveId"?: string;
  "trigger"?: string;
  "tokenCountKind"?: string;
  "tokensBefore"?: number;
  "tokensAfter"?: number;
  "messagesBefore"?: number;
  "messagesAfter"?: number;
  "reductionPercent"?: number;
  "timingMode"?: string;
  "routeId"?: string;
  "routeMode"?: string;
  "routeDecision"?: string;
  "failureStage"?: string;
  "count": number;
  "durationMs"?: number;
  "statusCode"?: number;
};

export type TurnActivityTimeline = {
  "blockId": "activity-timeline";
  "version": 1;
  "entries": ReadonlyArray<TurnActivityEntry>;
  "droppedCount"?: number;
};

export type TurnProjection = {
  "content"?: string;
  "thinking"?: string;
  "toolRounds"?: ReadonlyArray<TurnToolRound>;
  "activityTimeline"?: TurnActivityTimeline;
  "segments"?: ReadonlyArray<TurnContentSegment>;
  "usage"?: JsonObject;
  "apiRounds"?: ReadonlyArray<JsonObject>;
  "lastRoundUsage"?: JsonObject;
  "model"?: string;
  "preset"?: string;
  "providerId"?: string;
  "provider_id"?: string;
  "thinkingDepth"?: (string) | (number);
  "modifiedFiles"?: number;
  "modifiedFileList"?: ReadonlyArray<TurnFileChange>;
  "fileChanges"?: TurnFileChangesBlock;
  "todoState"?: JsonObject;
  "fallbackModel"?: string;
  "fallbackFrom"?: string;
  "fallbackReason"?: string;
  "fallbackKind"?: string;
  "translatedContent"?: string;
  "originalContent"?: string;
  "translation"?: TurnTranslation;
  "imageGeneration"?: TurnImageGeneration;
  "proposedPlan"?: TurnProposedPlan;
  "planExecution"?: TurnPlanExecution;
  "_translateDone"?: boolean;
  "_translateSkippedReason"?: string;
  "_translateModel"?: string;
  "_translateFailed"?: unknown;
  "_translateError"?: unknown;
  "_translateTaskId"?: string;
  "_translateStatus"?: string;
  "_translateStatusKind"?: string;
  "_translatePartial"?: string;
  "_translatePartialByRound"?: JsonObject;
  "_showingTranslation"?: boolean;
  "timestamp"?: (number) | (string);
  "images"?: ReadonlyArray<TurnImageAttachment>;
  "videos"?: ReadonlyArray<TurnVideoAttachment>;
  "pdfTexts"?: ReadonlyArray<TurnDocumentAttachment>;
  "convRefs"?: ReadonlyArray<TurnConversationReference>;
  "replyQuotes"?: ReadonlyArray<string>;
  "_branchLanes"?: ReadonlyArray<BranchLaneDescriptor>;
  "orchestration"?: TurnOrchestration;
  "provenance"?: TurnProvenance;
  "origin"?: TurnOrigin;
  "contextSnapshot"?: TurnContextSnapshot;
  "compaction"?: TurnCompaction;
  "_initiator"?: string;
  "_peerMessage"?: boolean;
  "_peerHuman"?: boolean;
  "_fromConv"?: string;
  "_brainDispatch"?: boolean;
  "_brainEpic"?: JsonObject;
  "_boardTaskId"?: string;
  "boardTaskId"?: string;
  "_isVirtualUser"?: boolean;
  "_autopilotRunId"?: string;
  "_proactive"?: boolean;
  "_proactiveTaskId"?: string;
  "_timer"?: boolean;
  "_swarmAutoContinue"?: boolean;
  "_ctx"?: JsonObject;
  "_isCompactionSummary"?: boolean;
  "_compactionArchiveId"?: string;
  "_estimatedPromptTokens"?: number;
  "_compactions"?: ReadonlyArray<JsonObject>;
  "_foldedToolRounds"?: number;
  "_isFlowReview"?: boolean;
  "_isFlowPlanner"?: boolean;
  "_flowNodeId"?: string;
  "_flowRunId"?: string;
  "_flowIteration"?: (number) | (string);
  "_flowPlannerIteration"?: (number) | (string);
  "_flowApproved"?: boolean;
  "_flowNextPhase"?: string;
  "_isStuck"?: boolean;
  "error"?: unknown;
  "_inboxInjects"?: ReadonlyArray<TurnMessageInjection>;
  "_peerInjects"?: ReadonlyArray<TurnMessageInjection>;
  "_userSteerInjects"?: ReadonlyArray<TurnMessageInjection>;
  "_stallNudges"?: ReadonlyArray<TurnStallInjection>;
};

export type TurnResumeOperation = "continue" | "checkpoint_resume" | "regenerate";

export type TurnResumeOption = {
  "operation": TurnResumeOperation;
  "anchor": JsonObject;
};

export type TurnContinuation = {
  "turnId": string;
  "attemptId": string;
};

export type ProviderStreamState = "provider_finished" | "client_aborted" | "premature_close" | "malformed_stream" | "semantic_progress_timeout" | "no_actionable_output" | "empty_response" | "tool_payload_missing" | "unknown";

export type TurnOutcome = "completed" | "interrupted" | "truncated" | "failed";

export type TurnTerminationEvidence = "provider_finish" | "legacy_finish" | "provider_limit" | "user_abort" | "provider_stream_failure" | "generation_error" | "missing_completion_evidence" | "external_authority" | "system_recovery";

export type TurnSettlement = {
  "outcome"?: TurnOutcome;
  "cause"?: string;
  "evidence"?: TurnTerminationEvidence;
  "streamState"?: (ProviderStreamState) | (null);
  "providerFinishReason"?: (string) | (null);
  "error"?: (JsonObject) | (string) | (null);
  "resumeOptions"?: ReadonlyArray<TurnResumeOption>;
  "continuation"?: TurnContinuation;
};

export type ConversationQueueItem = {
  "queueId": string;
  "position": number;
  "kind": string;
  "priority": number;
  "timestamp": number;
  "text": string;
  "sourceMessageId"?: string;
  "hasImages"?: boolean;
  "hasPdfs"?: boolean;
  "hasRefs"?: boolean;
  "hasQuotes"?: boolean;
  "isPeerMessage"?: boolean;
  "fromConv"?: string;
  "isPeerHuman"?: boolean;
};

export type AttemptOperation = "generate" | "continue" | "checkpoint_resume" | "regenerate" | "ingest";

export type ProjectionPatchPath = ReadonlyArray<(string) | (number)>;

export type ProjectionPatchOperation = ({
  "op": "set";
  "path": ProjectionPatchPath;
  "value": unknown;
}) | ({
  "op": "remove";
  "path": ProjectionPatchPath;
}) | ({
  "op": "append";
  "path": ProjectionPatchPath;
  "value": ReadonlyArray<unknown>;
}) | ({
  "op": "truncate";
  "path": ProjectionPatchPath;
  "length": number;
}) | ({
  "op": "append_text";
  "path": ProjectionPatchPath;
  "value": string;
});

export type ProjectionPatch = {
  "version": 1;
  "baseRevision": number;
  "targetRevision": number;
  "operations": ReadonlyArray<ProjectionPatchOperation>;
};

export type TurnProjectionChange = {
  "turnId": string;
  "baseProjectionRevision": number;
  "targetProjectionRevision": number;
  "updatedAt": number;
  "projectionPatch": ProjectionPatch;
};

export type TurnRuntimeStateChange = {
  "turnId": string;
  "status": TurnStatus;
  "currentAttemptId": (string) | (null);
  "settlement": TurnSettlement;
  "updatedAt": number;
};

export type TurnRecord = {
  "turnId": string;
  "conversationId": string;
  "laneId": string;
  "parentTurnId"?: (string) | (null);
  "ordinal": number;
  "actor": TurnActor;
  "kind": string;
  "runId": string;
  "status": TurnStatus;
  "currentAttemptId"?: (string) | (null);
  "projection": TurnProjection;
  "projectionRevision": number;
  "settlement": TurnSettlement;
  "createdAt": number;
  "updatedAt": number;
};

export type AttemptRecord = {
  "attemptId": string;
  "conversationId": string;
  "turnId": string;
  "commandId": string;
  "taskId": string;
  "operation": AttemptOperation;
  "status": AttemptStatus;
  "baseProjectionRevision": number;
  "resumeAnchor": JsonObject;
  "createdAt": number;
  "startedAt"?: (number) | (null);
  "settledAt"?: (number) | (null);
};

export type AttemptEvent = {
  "conversationId": string;
  "turnId": string;
  "attemptId": string;
  "seq": number;
  "projectionRevision": number;
  "type": "projection_updated" | "interaction_request" | "status_changed" | "terminal_settlement";
  "payload": {
  "projection"?: TurnProjection;
  "projectionPatch"?: ProjectionPatch;
  "turnState"?: TurnRuntimeStateChange;
  "status"?: TurnStatus;
  "settlement"?: TurnSettlement;
  "request"?: unknown;
  "turns"?: ReadonlyArray<TurnRecord>;
  "attempts"?: ReadonlyArray<AttemptRecord>;
  "phase"?: unknown;
  [key: string]: unknown;
};
};

export type ConversationChangeType = "turn.upsert" | "turn.patch" | "turn.deleted" | "attempt.event" | "conversation.activity";

export type ConversationChange = {
  "contract": "tofu.conversation-sync.event/v1";
  "type": ConversationChangeType;
  "conversationId": string;
  "syncSeq": number;
  "occurredAt": number;
  "turnId"?: string;
  "attemptId"?: string;
  "payload": JsonObject;
};

export type SyncHeartbeat = {
  "contract": "tofu.conversation-sync.event/v1";
  "type": "sync.heartbeat";
  "conversationId": string;
  "cursor": string;
  "serverBootId": string;
  "degraded": boolean;
  "pushWithheld"?: boolean;
};

export type SyncResetRequired = {
  "contract": "tofu.conversation-sync.event/v1";
  "type": "sync.reset_required";
  "conversationId": string;
  "cursor": string;
  "reason": "cursor_expired" | "cursor_invalid" | "server_restarted" | "protocol_mismatch";
};

export type ConversationSyncEvent = (ConversationChange) | (SyncHeartbeat) | (SyncResetRequired);

export type ConversationSyncSnapshot = {
  "ok": true;
  "contract": "tofu.conversation-sync.snapshot/v1";
  "conversationId": string;
  "conversationRevision": number;
  "syncSeq": number;
  "cursor": string;
  "serverBootId": string;
  "heartbeatIntervalMs": number;
  "settings": JsonObject;
  "turns": ReadonlyArray<TurnRecord>;
  "attempts": ReadonlyArray<AttemptRecord>;
  "queueItems": ReadonlyArray<ConversationQueueItem>;
  "pushWithheld"?: boolean;
};

export type ConversationInvalidation = {
  "channel": "notify";
  "taskId": string;
  "contract": "tofu.conversation-sync.invalidation/v1";
  "type": "conversation.invalidated";
  "conversationId": string;
  "cursorHint": string;
  "userId": (string) | (number);
};

export type ConnectionHealthState = "idle" | "connecting" | "live" | "recovering" | "degraded" | "offline" | "closed";

export type ConnectionHealth = {
  "state": ConnectionHealthState;
  "transport": "conversation-sse" | "task-sse" | "push-websocket";
  "observedAt": number;
  "generation": number;
  "lastFrameAt"?: number;
  "retryCount"?: number;
  "reason"?: string;
};

export type CreateTurnRequest = {
  "commandId": string;
  "inputTurn"?: unknown;
  "message"?: unknown;
  "config": JsonObject;
  "laneId"?: string;
  "parentTurnId"?: (string) | (null);
  "kind"?: string;
  "actor"?: TurnActor;
  "runId"?: string;
  "injectMode"?: "steer" | "queue";
  "conversation"?: JsonObject;
};

export type AppendSettledTurnRequest = {
  "commandId": string;
  "actor": TurnActor;
  "projection": TurnProjection;
  "kind"?: string;
  "status"?: "completed" | "interrupted" | "truncated" | "failed";
  "settlement"?: TurnSettlement;
  "createdAt"?: number;
  "laneId"?: string;
  "runId"?: string;
  "conversation"?: JsonObject;
};

export type UpdateTurnRequest = {
  "expectedProjectionRevision": number;
  "projection": TurnProjection;
};

export type FileChangesCommandRequest = {
  "commandId": string;
  "expectedProjectionRevision": number;
};

export type ExecutePlanRequest = {
  "commandId": string;
  "expectedProjectionRevision": number;
  "planId": PlanId;
  "contextMode": "current" | "fresh";
  "config": JsonObject;
};

export type CreateAttemptRequest = {
  "commandId": string;
  "operation": TurnResumeOperation;
  "expectedProjectionRevision": number;
  "config": JsonObject;
  "resumeAnchor"?: JsonObject;
  "inputUpdate"?: unknown;
  "expectedInputProjectionRevision"?: number;
};

export type CreateLaneRequest = {
  "expectedProjectionRevision": number;
  "title"?: string;
  "anchorText"?: string;
  "parentSelection"?: string;
  "kind"?: string;
};

export type DeleteTurnsRequest = {
  "turnIds": ReadonlyArray<string>;
};

export type TurnCommandResponse = {
  "ok": true;
  "conversationId": string;
  "conversationRevision": number;
  "cursor"?: string;
  "submittedTurn"?: TurnRecord;
  "turn"?: TurnRecord;
  "attempt"?: AttemptRecord;
  "idempotentReplay"?: boolean;
  "aborted"?: boolean;
  "steered"?: boolean;
  "queued"?: boolean;
  "queueId"?: string;
  "position"?: number;
  "queueItem"?: ConversationQueueItem;
  "latestTurn"?: TurnRecord;
  "deletedTurnIds"?: ReadonlyArray<string>;
  [key: string]: unknown;
};

export type TurnMutationResponse = {
  "ok": true;
  "conversationRevision": number;
  "cursor"?: string;
  "turn"?: TurnRecord;
  "turns"?: ReadonlyArray<TurnRecord>;
  "deletedTurnIds"?: ReadonlyArray<string>;
  [key: string]: unknown;
};

export type AbortAttemptResponse = {
  "ok": true;
  [key: string]: unknown;
};

type ContractSchema = Record<string, unknown>;

function record(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown> : null;
}

function schemaRefName(ref: string): string {
  const prefix = '#/components/schemas/';
  if (!ref.startsWith(prefix)) throw new Error(`Unsupported contract reference ${ref}`);
  return ref.slice(prefix.length);
}

function validateNode(schemaValue: unknown, value: unknown, path: string): string[] {
  const schema = record(schemaValue) ?? {};
  const ref = typeof schema.$ref === 'string' ? schema.$ref : '';
  if (ref) {
    const name = schemaRefName(ref);
    const target = (CONVERSATION_SYNC_SCHEMAS as Record<string, unknown>)[name];
    return target ? validateNode(target, value, path) : [`${path}: unknown schema ${name}`];
  }
  if (Array.isArray(schema.oneOf)) {
    const matches = schema.oneOf.filter((item) => validateNode(item, value, path).length === 0);
    return matches.length === 1 ? [] : [`${path}: expected exactly one contract variant`];
  }
  if (Array.isArray(schema.anyOf)) {
    return schema.anyOf.some((item) => validateNode(item, value, path).length === 0)
      ? [] : [`${path}: expected a contract variant`];
  }
  if (Object.prototype.hasOwnProperty.call(schema, 'const') && value !== schema.const) {
    return [`${path}: expected ${JSON.stringify(schema.const)}`];
  }
  if (Array.isArray(schema.enum) && !schema.enum.includes(value)) {
    return [`${path}: value is outside the declared vocabulary`];
  }
  const kind = schema.type;
  if (kind === 'null') return value === null ? [] : [`${path}: expected null`];
  if (kind === 'string') {
    if (typeof value !== 'string') return [`${path}: expected string`];
    if (typeof schema.minLength === 'number' && value.length < schema.minLength) {
      return [`${path}: string is shorter than ${schema.minLength}`];
    }
    if (typeof schema.maxLength === 'number' && value.length > schema.maxLength) {
      return [`${path}: string is longer than ${schema.maxLength}`];
    }
    return [];
  }
  if (kind === 'integer' || kind === 'number') {
    if (typeof value !== 'number' || !Number.isFinite(value)
        || (kind === 'integer' && !Number.isInteger(value))) {
      return [`${path}: expected ${kind}`];
    }
    if (typeof schema.minimum === 'number' && value < schema.minimum) {
      return [`${path}: number is below ${schema.minimum}`];
    }
    if (typeof schema.maximum === 'number' && value > schema.maximum) {
      return [`${path}: number is above ${schema.maximum}`];
    }
    return [];
  }
  if (kind === 'boolean') return typeof value === 'boolean' ? [] : [`${path}: expected boolean`];
  if (kind === 'array') {
    if (!Array.isArray(value)) return [`${path}: expected array`];
    if (typeof schema.maxItems === 'number' && value.length > schema.maxItems) {
      return [`${path}: array exceeds ${schema.maxItems} items`];
    }
    const errors: string[] = [];
    value.forEach((item, index) => errors.push(...validateNode(schema.items, item, `${path}[${index}]`)));
    return errors;
  }
  if (kind === 'object' || schema.properties) {
    const object = record(value);
    if (!object) return [`${path}: expected object`];
    const properties = record(schema.properties) ?? {};
    const required = Array.isArray(schema.required) ? schema.required : [];
    const errors: string[] = [];
    for (const field of required) {
      if (typeof field === 'string' && !Object.prototype.hasOwnProperty.call(object, field)) {
        errors.push(`${path}.${field}: required`);
      }
    }
    for (const [field, child] of Object.entries(properties)) {
      if (Object.prototype.hasOwnProperty.call(object, field)) {
        errors.push(...validateNode(child, object[field], `${path}.${field}`));
      }
    }
    if (schema.additionalProperties === false) {
      for (const field of Object.keys(object)) {
        if (!Object.prototype.hasOwnProperty.call(properties, field)) {
          errors.push(`${path}.${field}: undeclared field`);
        }
      }
    }
    return errors;
  }
  return [];
}

export class ConversationSyncContractError extends Error {
  readonly schemaName: string;
  readonly violations: readonly string[];

  constructor(schemaName: string, violations: readonly string[]) {
    super(`${schemaName} contract violation: ${violations.slice(0, 3).join('; ')}`);
    this.name = 'ConversationSyncContractError';
    this.schemaName = schemaName;
    this.violations = violations;
  }
}

export function assertConversationSyncSchema<T>(schemaName: string, value: unknown): T {
  const schema = (CONVERSATION_SYNC_SCHEMAS as Record<string, unknown>)[schemaName];
  if (!schema) throw new ConversationSyncContractError(schemaName, ['schema is not registered']);
  const violations = validateNode(schema, value, '$');
  if (violations.length) throw new ConversationSyncContractError(schemaName, violations);
  return value as T;
}

function snapshotConversationCommand<T>(schemaName: string, value: unknown): T {
  const validated = assertConversationSyncSchema<T>(schemaName, value);
  // Retry the exact accepted document even if application code mutates its
  // original object while the first network attempt is in flight.
  return JSON.parse(JSON.stringify(validated)) as T;
}

export const decodeConversationSyncSnapshot = (value: unknown): ConversationSyncSnapshot =>
  assertConversationSyncSchema<ConversationSyncSnapshot>('ConversationSyncSnapshot', value);

export const decodeConversationSyncEvent = (value: unknown): ConversationSyncEvent =>
  assertConversationSyncSchema<ConversationSyncEvent>('ConversationSyncEvent', value);

export const decodeConversationInvalidation = (value: unknown): ConversationInvalidation =>
  assertConversationSyncSchema<ConversationInvalidation>('ConversationInvalidation', value);

const RETRYABLE_COMMAND_HTTP_STATUSES = new Set<number>(
  CONVERSATION_SYNC_COMMAND_RETRY_POLICY.httpStatuses,
);
const RETRYABLE_COMMAND_STORAGE_CODES = new Set<string>(
  CONVERSATION_SYNC_COMMAND_RETRY_POLICY.storageCodes,
);
const RETRYABLE_COMMAND_TRANSPORT_CODES = new Set<string>(
  CONVERSATION_SYNC_COMMAND_RETRY_POLICY.transportCodes,
);

function commandFailureCode(error: unknown): string {
  const failure = record(error) ?? {};
  const body = record(failure.body) ?? {};
  const bodyError = record(body.error);
  const envelope = record(failure.envelope);
  return String(envelope?.storageCode ?? bodyError?.storageCode
    ?? body.storageCode ?? envelope?.kind ?? bodyError?.kind ?? '');
}

function retryableCommandFailure(
  error: unknown, options: RequestOptions,
): boolean {
  if (options.signal?.aborted) return false;
  const failure = record(error) ?? {};
  const status = Number(failure.status || 0);
  const transportCode = String(failure.code || '');
  return RETRYABLE_COMMAND_HTTP_STATUSES.has(status)
    || RETRYABLE_COMMAND_STORAGE_CODES.has(commandFailureCode(error))
    || RETRYABLE_COMMAND_TRANSPORT_CODES.has(transportCode);
}

function abortReason(signal?: AbortSignal): Error {
  if (signal?.reason instanceof Error) return signal.reason;
  const error = new Error('The conversation command was aborted.');
  error.name = 'AbortError';
  return error;
}

async function waitForRetry(delayMs: number, signal?: AbortSignal): Promise<void> {
  if (signal?.aborted) throw abortReason(signal);
  await new Promise<void>((resolve, reject) => {
    const finish = (): void => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    };
    const timer = setTimeout(finish, delayMs);
    const onAbort = (): void => {
      clearTimeout(timer);
      signal?.removeEventListener('abort', onAbort);
      reject(abortReason(signal));
    };
    signal?.addEventListener('abort', onAbort, { once: true });
  });
}

async function idempotentCommand<T>(
  send: () => Promise<T>, body: { commandId: string }, options: RequestOptions,
): Promise<T> {
  const policy = CONVERSATION_SYNC_COMMAND_RETRY_POLICY;
  for (let attempt = 0; attempt < policy.maxAttempts; attempt += 1) {
    try {
      return await send();
    } catch (error) {
      const failure = record(error) ?? {};
      if (!retryableCommandFailure(error, options)
          || attempt + 1 >= policy.maxAttempts) throw error;
      const bodyValue = record(failure.body) ?? {};
      const declaredRetryAfter = Number(bodyValue.retryAfterMs || 0)
        || Number(bodyValue.retryAfter || 0) * 1000;
      const exponentialDelay = policy.baseDelayMs * (2 ** attempt);
      const jitter = 1 + ((Math.random() * 2 - 1) * policy.jitterRatio);
      const delay = declaredRetryAfter > 0
        ? declaredRetryAfter
        : Math.round(exponentialDelay * jitter);
      await waitForRetry(
        Math.max(policy.minDelayMs, Math.min(policy.maxDelayMs, delay)),
        options.signal,
      );
    }
  }
  throw new Error(`Command ${body.commandId} retry loop exited unexpectedly`);
}

export interface ConversationSyncApi {
  snapshot(conversationId: string, options?: RequestOptions): Promise<ConversationSyncSnapshot>;
  eventsUrl(conversationId: string, after?: string, streamClientId?: string, streamGeneration?: number): string;
  createTurn(conversationId: string, body: CreateTurnRequest, options?: RequestOptions): Promise<TurnCommandResponse>;
  appendSettledTurn(conversationId: string, body: AppendSettledTurnRequest, options?: RequestOptions): Promise<TurnMutationResponse>;
  updateTurn(conversationId: string, turnId: string, body: UpdateTurnRequest, options?: RequestOptions): Promise<TurnMutationResponse>;
  executePlan(conversationId: string, turnId: string, body: ExecutePlanRequest, options?: RequestOptions): Promise<TurnCommandResponse>;
  createAttempt(conversationId: string, turnId: string, body: CreateAttemptRequest, options?: RequestOptions): Promise<TurnCommandResponse>;
  createLane(conversationId: string, turnId: string, body: CreateLaneRequest, options?: RequestOptions): Promise<TurnMutationResponse>;
  deleteLane(conversationId: string, turnId: string, laneId: string, options?: RequestOptions): Promise<TurnMutationResponse>;
  undoFileChanges(conversationId: string, turnId: string, body: FileChangesCommandRequest, options?: RequestOptions): Promise<TurnMutationResponse>;
  redoFileChanges(conversationId: string, turnId: string, body: FileChangesCommandRequest, options?: RequestOptions): Promise<TurnMutationResponse>;
  deleteTurns(conversationId: string, body: DeleteTurnsRequest, options?: RequestOptions): Promise<TurnMutationResponse>;
  abortAttempt(attemptId: string, options?: RequestOptions): Promise<AbortAttemptResponse>;
}

const segment = (value: string): string => encodeURIComponent(value);

export const conversationSyncApi = Object.freeze<ConversationSyncApi>({
  async snapshot(conversationId, options = {}) {
    const value = await request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/sync`,
      { ...options, method: 'GET' },
    );
    return assertConversationSyncSchema<ConversationSyncSnapshot>('ConversationSyncSnapshot', value);
  },
  eventsUrl(conversationId, after = '', streamClientId = '', streamGeneration = 0) {
    const base = resolvePath(`/api/v3/conversations/${segment(conversationId)}/events`);
    const query = [
      after ? `after=${encodeURIComponent(after)}` : '',
      streamClientId
        ? `streamClientId=${encodeURIComponent(streamClientId)}` : '',
      streamGeneration > 0
        ? `streamGeneration=${encodeURIComponent(String(streamGeneration))}` : '',
    ].filter(Boolean).join('&');
    return query ? `${base}?${query}` : base;
  },
  async createTurn(conversationId, body, options = {}) {
    const command = snapshotConversationCommand<CreateTurnRequest>('CreateTurnRequest', body);
    const value = await idempotentCommand(() => request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns`,
      { ...options, method: 'POST', json: command, timeout: 0 },
    ), command, options);
    return assertConversationSyncSchema<TurnCommandResponse>('TurnCommandResponse', value);
  },
  async appendSettledTurn(conversationId, body, options = {}) {
    const command = snapshotConversationCommand<AppendSettledTurnRequest>('AppendSettledTurnRequest', body);
    const value = await idempotentCommand(() => request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/settled`,
      { ...options, method: 'POST', json: command },
    ), command, options);
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async updateTurn(conversationId, turnId, body, options = {}) {
    const command = assertConversationSyncSchema<UpdateTurnRequest>('UpdateTurnRequest', body);
    const value = await request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}`,
      { ...options, method: 'PATCH', json: command },
    );
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async executePlan(conversationId, turnId, body, options = {}) {
    const command = snapshotConversationCommand<ExecutePlanRequest>('ExecutePlanRequest', body);
    const value = await idempotentCommand(() => request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}/plan/execute`,
      { ...options, method: 'POST', json: command, timeout: 0 },
    ), command, options);
    return assertConversationSyncSchema<TurnCommandResponse>('TurnCommandResponse', value);
  },
  async createAttempt(conversationId, turnId, body, options = {}) {
    const command = snapshotConversationCommand<CreateAttemptRequest>('CreateAttemptRequest', body);
    const value = await idempotentCommand(() => request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}/attempts`,
      { ...options, method: 'POST', json: command, timeout: 0 },
    ), command, options);
    return assertConversationSyncSchema<TurnCommandResponse>('TurnCommandResponse', value);
  },
  async createLane(conversationId, turnId, body, options = {}) {
    const command = assertConversationSyncSchema<CreateLaneRequest>('CreateLaneRequest', body);
    const value = await request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}/lanes`,
      { ...options, method: 'POST', json: command },
    );
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async deleteLane(conversationId, turnId, laneId, options = {}) {
    const value = await request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}/lanes/${segment(laneId)}`,
      { ...options, method: 'DELETE' },
    );
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async undoFileChanges(conversationId, turnId, body, options = {}) {
    const command = snapshotConversationCommand<FileChangesCommandRequest>('FileChangesCommandRequest', body);
    const value = await idempotentCommand(() => request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}/file-changes/undo`,
      { ...options, method: 'POST', json: command },
    ), command, options);
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async redoFileChanges(conversationId, turnId, body, options = {}) {
    const command = snapshotConversationCommand<FileChangesCommandRequest>('FileChangesCommandRequest', body);
    const value = await idempotentCommand(() => request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/${segment(turnId)}/file-changes/redo`,
      { ...options, method: 'POST', json: command },
    ), command, options);
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async deleteTurns(conversationId, body, options = {}) {
    const command = assertConversationSyncSchema<DeleteTurnsRequest>('DeleteTurnsRequest', body);
    const value = await request<unknown>(
      `/api/v3/conversations/${segment(conversationId)}/turns/delete`,
      { ...options, method: 'POST', json: command },
    );
    return assertConversationSyncSchema<TurnMutationResponse>('TurnMutationResponse', value);
  },
  async abortAttempt(attemptId, options = {}) {
    const value = await request<unknown>(
      `/api/v3/attempts/${segment(attemptId)}/abort`,
      { ...options, method: 'POST', json: {} },
    );
    return assertConversationSyncSchema<AbortAttemptResponse>('AbortAttemptResponse', value);
  },
});
