/* AUTO-GENERATED by scripts/gen_event_contract.py.
 * Canonical source: lib/agent_core/events.py (EventSpec.schema and
 * PushFrameSpec.schema).
 * DO NOT EDIT BY HAND.
 *
 * Field-level streaming-event contract. Each interface mirrors the
 * FieldSpec tuple the backend validates at emission (build_event
 * raises on an undeclared field under TOFU_EVENT_SCHEMA=strict), so
 * reading an undeclared field here is a typecheck error — the two
 * sides of the contract cannot drift in either direction. The push
 * frame section mirrors owner-scoped push-hub frames the same way
 * (build_push_frame is the backend gate).
 */

export const EVENT_CONTRACT_VERSION = 1 as const;

/** Full task state snapshot — emitted first on (re)connect / cold replay so a client can rebuild the live assistant bubble without recomputing it: carries the authoritative content, thinking, tool rounds and terminal status. */
export interface StateEvent {
  type: 'state';
  /** assistant text so far */
  content?: string;
  /** reasoning text so far */
  thinking?: string;
  /** task status (running|done|error|aborted) */
  status?: string;
  /** authoritative tool-round list (status per round) */
  toolRounds?: unknown[];
  /** (optional) error envelope */
  error?: Record<string, unknown>;
  /** (optional) terminal finish reason */
  finishReason?: string;
  /** (optional) token usage */
  usage?: Record<string, unknown>;
  /** (optional) model id */
  model?: string;
  /** (optional, running tasks only) authoritative current phase snapshot — same shape as the poll fallback task.phase, so reconnects resume the real working label instead of a bare waiting placeholder */
  phase?: string;
}

/** Progress / status hint for the current turn. */
export interface PhaseEvent {
  type: 'phase';
  /** phase key — the declared vocabulary lives in the Phase registry below (phase_values() / the capabilities `phases` block); the chat domain is the streaming status row, the rest are production-channel stage pushes */
  phase: string;
  /** human-readable detail (English fallback; headless / non-i18n clients render this verbatim) */
  detail?: string;
  /** (optional) stable i18n key the client resolves through its translation table so the label reads in the UI language; falls back to `detail` when absent */
  detailKey?: string;
  /** (optional) interpolation args for `detailKey` (e.g. {"round": 3, "model": "claude-4"}) */
  detailArgs?: Record<string, unknown>;
  /** (optional) resolved model id */
  model?: string;
  /** (optional, retrying) physical provider for the current attempt */
  providerId?: string;
  /** (optional, retrying) strict_model or pool_rescue */
  dispatchMode?: string;
  /** (optional) selected→resolved orchestration route (selectedModel/resolvedModel/role/tier/kind) */
  modelRoute?: Record<string, unknown>;
  /** round number */
  roundNum?: number;
  /** (optional, tool_exec phase) raw tool-name list of this dispatch — the i18n client composes its localized label from these; `detail` is the English fallback */
  tools?: unknown[];
  /** (optional, llm_thinking round-open phase) pre-joined English label string of the PREVIOUS round's tools (headless fallback) */
  toolContext?: string;
  /** (optional) the structured raw tool names behind `toolContext` — compose the suffix in the UI language from THESE when present */
  toolContextTools?: unknown[];
  /** (optional) retry/nudge counter */
  attempt?: number;
  /** (optional) retry/nudge budget */
  max?: number;
  /** (optional) retry signature bucket */
  bucket?: string;
  /** (optional) backoff seconds before retry */
  backoff_s?: number;
  /** (optional) typed transient failure kind */
  errorKind?: string;
  /** (optional) retry continuation mode */
  continuationMode?: string;
  /** (optional) HTTP status that triggered the cycle */
  statusCode?: number;
  /** (optional) todo-continuation incomplete count */
  incomplete?: number;
  /** (optional) tool-history rebuild stats */
  stats?: Record<string, unknown>;
  /** (optional) tool-history rebuild token overhead */
  overhead?: number;
  /** (optional) executor FIFO position */
  queuePosition?: number;
  /** (optional) executor queued root-task count */
  queued?: number;
  /** (optional) executor active worker count */
  active?: number;
  /** (optional) executor worker-slot capacity */
  capacity?: number;
  /** (optional) executor FIFO residence seconds */
  waitSeconds?: number;
  /** (optional, motion_video) job topic */
  topic?: string;
  /** (optional, motion_video) scene list or count */
  scenes?: number | unknown[];
  /** (optional, motion_video) SRT timing source */
  timed_from_audio?: boolean;
  /** (optional, motion_video) parsed cue count */
  cues?: number;
  /** (optional, motion_video) [start, end] seconds */
  span_s?: unknown[];
  /** (optional, motion_video) narration degraded flag */
  degraded?: boolean;
  /** (optional, motion_video) manifest-reuse flag */
  reused?: boolean;
  /** (optional, motion_video) agent-authored scene count */
  authored?: number;
  /** (optional, motion_video) template-fallback count */
  templated?: number;
  /** (optional, motion_video) advisory gate finding scene ids */
  gate_failed_scenes?: unknown[];
  /** (optional, motion_video) clip seconds */
  duration_s?: number;
  /** (optional, motion_video) concat mode */
  mode?: string;
  /** (optional, motion_video) auto burn-in flag */
  auto?: boolean;
  /** (optional, motion_video) regen target scene */
  scene_id?: string;
  /** (optional, motion_video) regen source job id */
  regen_of?: string;
  /** (optional, podcast) audio segment count */
  total?: number;
  /** (optional, research) mined direction */
  direction?: string;
  /** (optional, research) workspace action */
  action?: string;
  /** (optional, research) bound tool-epoch size */
  toolCount?: number;
  /** (optional, retrying) credential-free concrete network route id */
  routeId?: string;
  /** (optional, retrying) direct|proxy|env|desktop|unknown */
  routeMode?: string;
  /** (optional, retrying) connect/provider_response/midstream/progress stage */
  failureStage?: string;
  /** (optional, motion_video) scene-author creative mode */
  creative_mode?: string;
  /** (optional, motion_video) director brief */
  director?: Record<string, unknown>;
}

/** Explicit start boundary of an LLM round (the orchestrator loop index). Emitted at the TOP of every round the model actually runs — INCLUDING a prose-only round (streams text, no tool calls) and BEFORE the phase hint — so the client keys round attribution off a real boundary instead of inferring it from the first `tool_start` (a round with no tools had NO signal before). Non-terminal. */
export interface RoundStartEvent {
  type: 'round_start';
  /** the round index this boundary opens */
  roundNum: number;
}

/** Explicit end boundary of an LLM round — the complement of `round_start`. Emitted when a round concludes on EVERY exit path: it issued tool calls (loop continues), it finished with prose and no tools (terminal), or it was aborted/budget-capped. `reason` distinguishes them so the client can close the round without inferring end-of-round from the next `round_start` or a `done`. Non-terminal (a `done` still follows on the terminal path). */
export interface RoundEndEvent {
  type: 'round_end';
  /** the round index this boundary closes */
  roundNum: number;
  /** tools|final|aborted|budget|error|tool_timeout|tool_loop|success_poll — why the round ended */
  reason: string;
}

/** Terminal event — the turn finished (success or, with `error`, failure). */
export interface DoneEvent {
  type: 'done';
  /** error envelope if failed (else absent) */
  error?: Record<string, unknown>;
  /** provider/normalized terminal reason */
  finishReason?: string;
  /** closed ProviderStreamState evidence; provider_finished is the only success state */
  streamState?: string;
  /** (optional) owning task id (orchestrator post-loop settle path) */
  taskId?: string;
  /** (optional) accumulated token usage */
  usage?: Record<string, unknown>;
  /** (optional) generation preset name */
  preset?: string;
  /** (optional) model id that produced the answer */
  model?: string;
  /** (optional) resolved thinking depth */
  thinkingDepth?: string;
  /** (optional) tool-summary text carried on the terminal frame */
  toolSummary?: string;
  /** (optional) public checklist state when the turn drove a todo list */
  todoState?: Record<string, unknown>;
  /** (optional) true when the checklist blocked completion */
  todoBlocked?: boolean;
  /** (optional) structured wait descriptor (e.g. a pending sub-agent set) */
  waitingOn?: Record<string, unknown>;
  /** (optional) true when the flow loop finished with finishReason=incomplete */
  incomplete?: boolean;
  /** (optional) flow loop stop reason (orchestration terminal path only) */
  flowReason?: string;
  /** (optional) true when stamped by the flow orchestration terminal path */
  flowMode?: boolean;
  /** (optional) orchestration projection label (orchestration path only) */
  flowProjection?: string;
  /** (optional) TerminalOutcome dict (orchestration path only) */
  orchestrationOutcome?: Record<string, unknown>;
  /** (optional) server-authoritative model after mid-turn fallback/preset switch */
  actualModel?: string;
  /** (optional) server-authoritative thinking depth at done */
  actualDepth?: string;
  /** (optional) active mode labels (flow/goal) as {label,tone} dicts */
  actualModes?: unknown[];
  /** (optional) stable _msgId of the user turn that triggered this task */
  userMsgId?: string;
  /** (optional) per-API-round evidence dicts (usage/model/provider/cost per round) */
  apiRounds?: unknown[];
  /** (optional) model fell back to */
  fallbackModel?: string;
  /** (optional) model fell back from */
  fallbackFrom?: string;
  /** (optional) why fallback happened */
  fallbackReason?: string;
  /** (optional) fallback classification */
  fallbackKind?: string;
  /** (optional) checkpoint-merged modified path list */
  modifiedFiles?: unknown[];
  /** (optional) checkpoint-merged rich modified-file dicts */
  modifiedFileList?: unknown[];
  /** (optional) priced cost snapshot for the turn */
  cost?: Record<string, unknown>;
  /** (optional) cost-experiment outcome dict when an arm is active */
  costExperiment?: Record<string, unknown>;
  /** (optional) successor live task id (autopilot VU chain) */
  latestLiveTaskId?: string;
  /** (optional) true when the successor is a VU sub-task */
  latestLiveTaskIsVu?: boolean;
  /** (optional) internal loop-exit diagnostics on suspicion */
  _diagnostics?: Record<string, unknown>;
}

/** Legacy terminal error envelope. New fatal paths normally emit a `done` with `error`, but Turn authority still settles this frame for compatibility. */
export interface ErrorEvent {
  type: 'error';
  /** error text */
  content?: string;
  /** structured detail */
  detail?: Record<string, unknown>;
}

/** A transient-error turn is being auto-re-run from scratch. The client MUST clear the live bubble's accumulated content / thinking (and tool rounds) so the about-to-be-re-streamed deltas do not stack on top of the failed attempt's partial output. Non-terminal: the task stays `running`; a `phase:retrying` frame carrying the attempt/backoff detail accompanies it. */
export interface RetryResetEvent {
  type: 'retry_reset';
  /** whole-turn retry number (1-based) */
  attempt: number;
  /** retry budget */
  max: number;
  /** error kind that triggered the re-run */
  kind: string;
  /** monotonic text generation after this reset */
  contentEpoch: number;
}

/** A logical model dispatch started. This low-frequency boundary opens the durable activity span used to correlate subsequent wait/retry frames and the terminal request result. */
export interface ModelRequestStartEvent {
  type: 'model_request_start';
  /** task-local stable request span id */
  spanId: string;
  /** requested model id */
  model: string;
  /** (optional) provider id when already known */
  providerId?: string;
  /** (optional) model round number */
  roundNum?: number;
  /** task-local request label (R1/FALLBACK/etc.) */
  requestTag: string;
  /** epoch ms when the backend handed this frame to the event chokepoint */
  emittedAt?: number;
}

/** A logical model-dispatch span settled successfully or failed. This is diagnostic state only and does not itself settle the Turn. */
export interface ModelRequestCompleteEvent {
  type: 'model_request_complete';
  /** matching model_request_start span id */
  spanId: string;
  /** model id */
  model: string;
  /** (optional) provider that served the request */
  providerId?: string;
  /** succeeded|failed|aborted */
  status: string;
  /** (optional) provider finish reason */
  finishReason?: string;
  /** (optional) closed ProviderStreamState */
  streamState?: string;
  /** wall-clock request duration in milliseconds */
  durationMs: number;
  /** (failure only) typed exception/error kind */
  errorKind?: string;
  /** (failure only) bounded safe detail */
  errorDetail?: string;
  /** (failure only) request URL the error is bound to (abort/endpoint diagnostics) */
  errorUrl?: string;
  /** (failure only) HTTP status when known */
  statusCode?: number;
  /** (optional) credential-free concrete network route id */
  routeId?: string;
  /** (optional) direct|proxy|env|desktop|unknown */
  routeMode?: string;
  /** (optional) why this route was selected */
  routeDecision?: string;
  /** (optional) connect/provider_response/midstream/progress stage */
  failureStage?: string;
  /** (optional) model round number */
  roundNum?: number;
  /** task-local request label */
  requestTag: string;
  /** (optional) tofu.provider-ingress-isolation/v1 receipt when provider dispatches were guarded this span */
  observerIsolation?: Record<string, unknown>;
  /** epoch ms when the backend handed this frame to the event chokepoint */
  emittedAt?: number;
}

/** The primary model failed and the turn is being re-streamed on the configured fallback model. Emitted EARLY, at the decision moment — BEFORE the fallback stream starts — so the client can paint an in-bubble fallback banner for the whole (potentially minutes-long) fallback generation and a cold reload can repaint it from the task stamps. Non-terminal; the terminal `done` still follows. */
export interface ModelFallbackEvent {
  type: 'model_fallback';
  /** the model the turn fell back TO */
  fallbackModel: string;
  /** the original model that failed */
  fallbackFrom: string;
  /** error kind that triggered the fallback */
  fallbackKind: string;
  /** human-readable reason (kind: detail, capped at 300 chars) */
  fallbackReason: string;
  /** epoch ms when the backend handed this frame to the event chokepoint */
  emittedAt?: number;
}

/** Incremental assistant output — append to the live bubble. */
export interface DeltaEvent {
  type: 'delta';
  /** text delta (may be absent) */
  content?: string;
  /** reasoning delta (may be absent) */
  thinking?: string;
}

/** The just-ended LLM round issued TOOL CALLS, so any prose it streamed before those calls was inter-round narration (e.g. "Now let me check the utility functions."), NOT the final answer. The client MUST clear the live bubble's accumulated content / thinking so this narration does not get concatenated in front of the terminal round's real answer. Unlike `retry_reset`, it MUST NOT touch tool rounds — the tool calls from this turn are legitimate and keep rendering. Non-terminal. With `discard: true` (the canned-greeting upstream-artifact retry — the ONLY retry bucket whose discarded round HAS content) the round issued NO tool calls, so there is no batch to stamp the prose onto: the client clears UNCONDITIONALLY (still keeping tool rounds). */
export interface DeltaResetEvent {
  type: 'delta_reset';
  /** the tool-call round number whose prose is dropped */
  roundNum: number;
  /** optional; true = unconditional clear, no prose-capture */
  discard?: boolean;
  /** monotonic text generation after this reset */
  contentEpoch: number;
}

/** A tool call began executing. */
export interface ToolStartEvent {
  type: 'tool_start';
  /** round index */
  roundNum: number;
  /** tool name */
  toolName?: string;
  /** (optional, swarm emissions) owning sub-agent id; the Request Inspector stream for this call is `{parentTaskId}#agent:{agentId}` */
  agentId?: string;
  /** tool-call id */
  toolCallId?: string;
  /** display string */
  query: string;
  /** serialized args */
  toolArgs?: string | Record<string, unknown>;
  /** (optional) Responses nested-call owner */
  caller?: Record<string, unknown>;
  /** (optional) parent program call id */
  programCallId?: string;
  /** (optional) presentation-only parent for nested/recovery calls */
  parentToolCallId?: string;
  /** (optional) stable routine, important, or interactive semantic importance */
  attentionKind?: string;
  /** (optional) 'rejected' when the tool was a hallucination and never ran */
  status?: string;
  /** (optional, swarm emissions) provider LLM round index when it differs from the task roundNum */
  llmRound?: number;
  /** (optional) {attempted, suggestions} for a rejected hallucinated tool */
  _rejected?: Record<string, unknown>;
  /** (optional) stable ToolContractV2 error for a call rejected before execution */
  _contractError?: Record<string, unknown>;
  /** (optional) resolved workspace root for multi-root fs tools (path display) */
  _toolRoot?: string;
  /** (optional) provider wire origin (native_direct/program/…), stamped on every parsed call */
  source?: string;
  /** (optional) typed rejection descriptor when status=rejected */
  rejection?: Record<string, unknown>;
  /** (optional, first call of the round) prose the model emitted alongside its tool calls */
  assistantContent?: string;
  /** (optional, first call of the round) reasoning text for Continue replay */
  thinking?: string;
  /** (optional, first call of the round) thinking-continuity signature */
  thinkingSignature?: string;
  /** (optional) full query list of a batch web_search call for structured rendering */
  _batchQueries?: unknown[];
  /** (optional) full URL list of a batch fetch call for structured rendering */
  _batchUrls?: unknown[];
  /** (optional) structured provenance twin of the display label on a continuation round (origin chip) */
  _artifactOrigin?: Record<string, unknown>;
  /** (optional) true when this row is the presentation adapter of a hidden gateway call (execute_tools) */
  _hiddenToolAdapter?: boolean;
  /** (optional) {label → href} clickable-link map re-keyed to fresh MCP labels */
  _mcpLinks?: Record<string, unknown>;
  /** (optional) true when the file is staged server-side for download */
  _serverDownload?: boolean;
  /** (optional) true on the spawn_agents round (swarm panel presentation) */
  _swarm?: boolean;
  /** epoch ms when the tool actually began executing — present on EVERY tool frame so a still-running row can render a truthful elapsed time instead of a client stopwatch that re-mints on each paint */
  tStart?: number;
  /** epoch ms when the backend handed this frame to the event chokepoint. Transport latency = receivedAt - emittedAt */
  emittedAt?: number;
}

/** Streaming progress emitted by a long-running tool. */
export interface ToolProgressEvent {
  type: 'tool_progress';
  /** round index */
  roundNum?: number;
  /** tool-call id */
  toolCallId?: string;
  /** progress text */
  detail?: string;
  /** (optional, swarm emissions) owning sub-agent id (see tool_start) */
  agentId?: string;
  /** (optional) epoch ms when the subprocess was actually SPAWNED. Distinct from tStart (round ANNOUNCE time): a write approval or serial-write wait sits between them, so an elapsed derived from tStart over-reports execution */
  execStartTs?: number;
  /** (optional) epoch ms at which the backend will SIGKILL this command. Absolute, and authoritative: the client must NOT derive it from the requested timeout, because the effective budget is the requested one AFTER the cross-DC multiplier, the MAX_COMMAND_TIMEOUT clamp and the remote bridge formula. Absent = no deadline (the default: run_command has no ceiling) */
  deadlineTs?: number;
  /** (optional) the ONE item of a batch call (query string / URL) this frame reports */
  batchItem?: string;
  /** (optional) how many batch items have settled so far (1-based, monotonic) */
  batchDone?: number;
  /** (optional) total items in the batch call */
  batchTotal?: number;
  /** (optional) False when THIS item failed — a failed item must still advance the counter, else the row looks stuck on a dead query */
  batchOk?: boolean;
  /** (optional) True when this frame is the tool-heartbeat pinging ITSELF (transport keepalive, NOT evidence the tool is alive — ). The reaper ignores it for liveness; the frontend stalled-card reads it to tell self-ticks from real output */
  _selfTick?: boolean;
  /** (optional) REPAIRED display string — present only on the display-patch frame the dispatcher sends when a late args repair rebuilt the round display (the early announce was built from truncated/unrepaired args). The client patches the live row WITHOUT settling the round (2026-08-06 mid-arguments cut rendered "$ ?" for the whole command duration) */
  query?: string;
  /** (optional) {label, detail, patterns} — rides with query on the display-patch frame so the row gains the auto-fixed badge together with the new text */
  _repaired?: Record<string, unknown>;
  /** (optional) tool name (stream/batch frames) */
  toolName?: string;
  /** (optional) heartbeat-reported elapsed seconds */
  elapsed?: number;
  /** (optional) stream-chunk payload contract tag (tool_runtime/progress, e.g. 'tofu.tool-progress/v1') */
  contractVersion?: string;
  /** (optional) stream-chunk format version */
  version?: number;
  /** (optional) owning task id (stream-chunk frames stamp their own before the transport setdefault) */
  taskId?: string;
  /** (optional) per-tool stream-chunk sequence (stream-chunk frames stamp their own before the transport re-assigns) */
  seq?: number;
  /** (optional) stdout|stderr for stream chunks */
  stream?: string;
  /** (optional) stream chunk text */
  chunk?: string;
  /** (optional) chunk byte length */
  bytes?: number;
  /** (optional) chunk char length */
  chars?: number;
  /** (optional) true while output is being spooled */
  spooling?: boolean;
  /** (optional) true when the chunk tail was truncated */
  truncated?: boolean;
  /** (optional) why the stream group closed (final frame only) */
  terminalReason?: string;
  /** (optional) true on the display-only frame published when run_command delegates a file grep to the runtime grep_search engine */
  grepSearchIntercepted?: boolean;
  /** epoch ms when the tool actually began executing — present on EVERY tool frame so a still-running row can render a truthful elapsed time instead of a client stopwatch that re-mints on each paint */
  tStart?: number;
  /** epoch ms when the backend handed this frame to the event chokepoint. Transport latency = receivedAt - emittedAt */
  emittedAt?: number;
}

/** A tool produced a (possibly partial) result payload. */
export interface ToolResultEvent {
  type: 'tool_result';
  /** round index */
  roundNum: number;
  /** (optional, swarm emissions) owning sub-agent id (see tool_start) */
  agentId?: string;
  /** tool-call id */
  toolCallId?: string;
  /** canonical tool name */
  toolName?: string;
  /** list of {toolName,title,snippet,source} */
  results: unknown[];
  /** display string */
  query: string;
  /** terminal VERDICT, always present on frames emitted via _finalize_tool_round: 'done' on success, else the backend's failure verdict ('error' / 'rejected' / 'aborted' / 'unanswerable'). The client renders this field as the ONLY truth — it must never infer success from the frame's arrival (older backends omitted it except 'rejected'; a missing status on an in-flight round is the only case the client may settle as 'done') */
  status?: string;
  /** (optional) {attempted, suggestions} for a rejected hallucinated tool */
  _rejected?: Record<string, unknown>;
  /** (optional) stable ToolContractV2 error preserved when validation rejected the call */
  _contractError?: Record<string, unknown>;
  /** (optional) normalized tool-rejection descriptor (see tool_complete) */
  rejection?: Record<string, unknown>;
  /** (optional) {label, detail, patterns} — args auto-repair badge metadata */
  _repaired?: Record<string, unknown>;
  /** (optional, swarm emissions) provider LLM round index when it differs from the task roundNum */
  llmRound?: number;
  /** (optional) prefetch|cache — the result was served from a cached tool call */
  cacheSource?: string;
  /** (optional) per-engine result counts on a cache-hit search frame */
  engineBreakdown?: Record<string, unknown>;
  /** (optional) batch web_search vertical list */
  verticals?: unknown[];
  /** (optional) structured vertical of a cache-hit search (academic/finance/…) */
  vertical?: string;
  /** (optional) search-diagnostics dict carried through a cache hit */
  searchDiag?: Record<string, unknown>;
  /** (optional) search_tools total catalogue hits */
  toolSearchTotal?: number;
  /** (optional) search_tools pagination cursor (null = end) */
  toolSearchNextCursor?: string | null;
  /** (optional) true when search_tools degraded to fail-open listing */
  toolSearchFailOpen?: boolean;
  /** (optional) true on an orphan early-announced round superseded by a provider retry */
  _providerAttemptDiscarded?: boolean;
  /** (optional) full query list of a batch web_search call for structured rendering */
  _batchQueries?: unknown[];
  /** epoch ms when the tool actually began executing — present on EVERY tool frame so a still-running row can render a truthful elapsed time instead of a client stopwatch that re-mints on each paint */
  tStart?: number;
  /** epoch ms when the tool returned (terminal frames only). Execution time = tEnd - tStart */
  tEnd?: number;
  /** epoch ms when the backend handed this frame to the event chokepoint. Transport latency = receivedAt - emittedAt */
  emittedAt?: number;
}

/** A tool call finished; carries the final tool message. */
export interface ToolCompleteEvent {
  type: 'tool_complete';
  /** round index */
  roundNum: number;
  /** tool-call id */
  toolCallId: string;
  /** canonical tool name */
  toolName: string;
  /** final model-visible tool result */
  toolContent: string;
  /** (optional) real tokens of the final model-visible toolContent */
  toolTokens?: number;
  /** (optional) 'L0'/'unchanged' when the result was budget-enveloped or receipt-replaced before first entering context */
  compactionLayer?: string;
  /** pre-compaction producer chars */
  compactedFromChars?: number | null;
  /** post-compaction model-visible chars */
  compactedToChars?: number | null;
  /** (optional) real tokens of the pre-compaction producer result (never entered context) */
  rawToolTokens?: number;
  /** (optional) bounded non-model tofu.tool-result-evidence/v1 sidecar for runtime/evaluation */
  toolResultEvidence?: Record<string, unknown>;
  /** bool */
  isError?: boolean;
  /** (optional) terminal NON-SUCCESS verdict — 'rejected' / 'aborted' / 'error' (tool raised or pool-timeout-cancelled, 2026-08-06 silent-timeout incident). ABSENT on success; the client must never promote a verdict-bearing round to 'done' */
  status?: string;
  /** (optional) normalized tool-rejection descriptor (kind/tool/reason/suggestions); stamped together with the `_rejected` legacy alias by stamp_tool_rejection */
  rejection?: Record<string, unknown>;
  /** (optional) legacy alias of `rejection` (same normalized descriptor object) */
  _rejected?: Record<string, unknown>;
  /** (optional, swarm emissions) provider LLM round index when it differs from the task roundNum */
  llmRound?: number;
  /** (optional, swarm emissions) owning sub-agent id (see tool_start) */
  agentId?: string;
  /** epoch ms when the tool actually began executing — present on EVERY tool frame so a still-running row can render a truthful elapsed time instead of a client stopwatch that re-mints on each paint */
  tStart?: number;
  /** epoch ms when the tool returned (terminal frames only). Execution time = tEnd - tStart */
  tEnd?: number;
  /** epoch ms when the backend handed this frame to the event chokepoint. Transport latency = receivedAt - emittedAt */
  emittedAt?: number;
}

/** A malformed provider-visible tool schema was isolated before the request left the process. The tool is omitted for this request; execution authority and the LLM transcript are unchanged. */
export interface ToolSchemaRejectedEvent {
  type: 'tool_schema_rejected';
  /** isolated tool name (or unknown tool) */
  toolName: string;
  /** provider-boundary validation stage */
  stage: string;
  /** stable rejection class */
  reasonCode: string;
  /** bounded structural validation detail */
  detail: string;
  /** omitted */
  action: string;
  /** request model id */
  model: string;
  /** owning model request span */
  parentSpanId: string;
  /** (optional) model round number */
  roundNum?: number;
  /** epoch ms when the backend handed this frame to the event chokepoint */
  emittedAt?: number;
}

/** Bounded Request Inspector evidence for the final provider tool surface. This diagnostic grants no execution authority and never enters the LLM transcript. */
export interface ToolWireProjectionEvent {
  type: 'tool_wire_projection';
  /** model round number */
  roundNum?: number;
  /** (optional) Flow node phase */
  turn: string;
  /** wire model id */
  model: string;
  /** resolved tool discovery backend */
  backend: string;
  /** ordered bounded final provider tool names */
  toolNames: unknown[];
  /** exact final provider tool count */
  toolCount: number;
  /** model-tokenizer schema estimate */
  schemaTokens: number;
  /** opaque exact provider-schema digest */
  schemaFingerprint: string;
  /** explicit cost target, zero=uncapped */
  schemaBudgetTokens: number;
  /** names omitted by explicit budget */
  budgetDroppedNames: unknown[];
  /** names annotation-compacted by budget */
  compactedNames: unknown[];
  /** server-authorized catalog size */
  executableToolCount: number;
  /** owning model request span */
  parentSpanId: string;
}

/** A prior tool result was compacted out of context to save tokens. */
export interface ToolCompactedEvent {
  type: 'tool_compacted';
  /** tool-call id */
  toolCallId: string;
  /** round index */
  roundNum?: number | null;
  /** canonical tool name */
  toolName: string;
  /** replacement compaction layer */
  compactionLayer: string;
  /** prior model-visible chars */
  compactedFromChars: number;
  /** replacement model-visible chars */
  compactedToChars: number;
  /** replacement model-visible tokens */
  toolTokens: number;
  /** replacement model-visible result */
  compactedContent: string;
  /** (optional) replacement bounded non-model evidence sidecar */
  toolResultEvidence?: Record<string, unknown>;
}

/** A previously settled idempotent tool call was reused without executing the tool again. */
export interface ToolCallReplayEvent {
  type: 'tool_call_replay';
  /** canonical tool name */
  toolName?: string;
  /** replayed settled result */
  content?: string;
  /** replayed */
  badge?: string;
}

/** A native or local orchestration program started. Its nested function calls remain ordinary tool lifecycle events. */
export interface ProgramStartEvent {
  type: 'program_start';
  /** display-only parent round index */
  roundNum: number;
  /** model round that authored the program */
  llmRound?: number | null;
  /** program call id used by child callers */
  programCallId: string;
  /** JavaScript authored by the model */
  code: string;
  /** nested function-call ids */
  childCallIds: unknown[];
  /** nested function names */
  childToolNames: unknown[];
  /** enforced calls/output/continuation ceilings */
  limits: Record<string, unknown>;
  /** openai_ptc or execute_program */
  source: string;
  /** native_openai or local_toolscript */
  backend: string;
  /** running */
  status: string;
  /** program start epoch ms */
  tStart?: number | null;
}

/** A native or local program produced its aggregate output. */
export interface ProgramOutputEvent {
  type: 'program_output';
  /** display-only parent round index */
  roundNum: number;
  /** originating model round */
  llmRound?: number | null;
  /** program call id */
  programCallId: string;
  /** program aggregate result */
  result: string | Record<string, unknown> | null;
  /** completed, incomplete, or error */
  status: string;
  /** final nested function-call ids */
  childCallIds: unknown[];
  /** final nested function names */
  childToolNames: unknown[];
  /** openai_ptc or execute_program */
  source: string;
  /** native_openai or local_toolscript */
  backend: string;
  /** program start epoch ms */
  tStart?: number | null;
  /** program completion epoch ms */
  tEnd: number;
}

/** Token-usage accounting for a completed round. */
export interface RoundUsageEvent {
  type: 'round_usage';
  /** usage dict */
  usage: Record<string, unknown>;
  /** round number */
  roundNum: number;
  /** model id */
  model: string;
  /** request label (R1/FALLBACK/etc.) */
  tag: string;
  /** flow phase label (empty when no flow) */
  turn: string;
  /** input tokens this round */
  tokensIn: number;
  /** output tokens this round */
  tokensOut: number;
}

/** A round was persisted server-side (durable checkpoint). */
export interface RoundCommittedEvent {
  type: 'round_committed';
  /** owning task id */
  taskId: string;
  /** file-history snapshot id when available */
  snapshotId?: string;
  /** legacy alias for snapshotId */
  gitSha?: string;
  /** task-attributed changed paths */
  modifiedFileList?: unknown[] | null;
  /** task-attributed changed-path count */
  modifiedFiles?: number | null;
  /** single-checkout checkpoint/stable settlement receipt */
  linearGitCheckpoint?: Record<string, unknown>;
  /** paths the file-history diff attributes to this round beyond the task-attributed list */
  addedByGit?: unknown[];
}

/** A point-in-time copy of the message list (fallback/branch sync). */
export interface MessagesSnapshotEvent {
  type: 'messages_snapshot';
  /** message list */
  messages: unknown[];
  /** request|state — pre-flight request vs post-hoc state snapshot */
  kind: string;
  /** model id */
  model: string;
  /** round id/label (may be a string label like final/fallback) */
  roundNum: number | string;
  /** human label */
  label: string;
  /** (optional) bounded context-manifest entries */
  contextManifest?: unknown[];
  /** (optional) flow phase label */
  turn?: string;
  /** (optional, request kind) sampling params {maxTokens, temperature, thinkingEnabled, …} */
  params?: Record<string, unknown>;
  /** (optional, request kind) provider-visible tool schemas */
  tools?: unknown[];
  /** (optional, swarm) owning sub-agent id */
  agentId?: string;
  /** (optional, swarm) sub-agent role */
  agentRole?: string;
}

/** A pre-compaction transcript snapshot was archived. */
export interface CompactionEvent {
  type: 'compaction';
  /** owner-scoped archive id */
  archiveId: string | number;
  /** conversation id */
  convId: string;
  /** working_set|window|force|reactive|manual */
  trigger: string;
  /** task round number */
  roundNum: number;
  /** estimated pre-compaction input tokens */
  tokensBefore: number;
  /** estimated post tokens; zero until complete */
  tokensAfter: number;
  /** estimated */
  tokenCountKind: string;
  /** pre-compaction message count */
  msgsBefore: number;
  /** post-compaction count; zero until complete */
  msgsAfter: number;
  /** task model id, not summary-model attribution */
  model: string;
  /** bounded trigger explanation */
  reason: string;
  /** pre_compaction_transcript */
  snapshotKind: string;
  /** epoch seconds */
  ts: number;
}

/** A compaction archive received its final estimated counts. */
export interface CompactionDoneEvent {
  type: 'compaction_done';
  /** owner-scoped archive id */
  archiveId: string;
  /** conversation id */
  convId: string;
  /** working_set|window|force|reactive|manual */
  trigger: string;
  /** estimated pre-compaction input tokens */
  tokensBefore: number;
  /** estimated complete post-compaction tokens */
  tokensAfter: number;
  /** estimated */
  tokenCountKind: string;
  /** pre-compaction message count */
  msgsBefore: number;
  /** complete post-compaction message count */
  msgsAfter: number;
  /** estimated percentage token reduction */
  reductionPct: number;
  /** task round number */
  roundNum: number;
  /** bounded tofu.compaction-receipt/v1 result */
  receipt: Record<string, unknown>;
}

/** Memory-prefetch pipeline stage update. */
export interface MemoryPrefetchEvent {
  type: 'memory_prefetch';
  /** started|done|skipped|failed */
  phase: string;
  /** (skipped/failed) why the prefetch did not run */
  reason?: string;
  /** (started) memory catalogue size */
  total_memories?: number;
  /** (started) selection budget */
  candidate_target?: number;
  /** (started/done) selection strategy label */
  strategy?: string;
  /** (done) memories injected */
  selected?: number;
  /** (done) candidate count considered */
  candidates?: number;
  /** (done) candidates dropped by the confidence floor */
  rejectedLowConfidence?: number;
  /** (done) pipeline wall time */
  total_ms?: number;
  /** (done) extra LLM calls spent */
  auxiliaryLlmCalls?: number;
  /** (done) selected {name, description, reason} */
  memories?: unknown[];
}

/** The bounded structured user context was injected into this turn (all categories always-on and cache-safe). */
export interface PreferencesAppliedEvent {
  type: 'preferences_applied';
  /** profile size in chars */
  chars: number;
  /** flat list of injected bullets (core + relevant detail) for the chip */
  items: unknown[];
}

/** A durable user-context item was learned or updated by the post-turn consolidation pass and can be undone. */
export interface PreferenceLearnedEvent {
  type: 'preference_learned';
  /** reinforced|pending */
  kind: string;
  /** one-line description of what was learned */
  summary: string;
  /** true when awaiting user confirm (new pref) */
  pending: boolean;
  /** legacy alias for change_id */
  id: string;
  /** bounded undo-log change identifier */
  change_id: string;
  /** stable context item identifier */
  item_id: string;
  /** identity|work_rule|response_preference */
  context_type: string;
}

/** The bounded cross-conversation project digest (sibling conversations of the same project) was injected into this turn for ambient awareness. Drives a quiet "related conversations" provenance segment so the user can see — and audit — the same siblings the model was told about. */
export interface RelatedConversationsEvent {
  type: 'related_conversations';
  /** number of siblings surfaced */
  count?: number;
  /** list of {id, title, summary} */
  items?: unknown[];
  /** whether get_conversation/list_conversations were registered this turn */
  toolsAvailable?: boolean;
}

/** Off-agent (IDE) drift to a tracked file was snapshotted into file-history. Pure audit/provenance record — the frontend deliberately does NOT render it (the drift toast advertised an undo the UI had no path for; the snapshot's real consumer is the file-history timeline itself). */
export interface ProjectExternalEditEvent {
  type: 'project_external_edit';
  /** list of drifted project-relative paths */
  files: unknown[];
  /** file-history snapshot id (null when the drift snapshot could not be written) */
  sha: string | null;
}

/** An absolute-path write auto-registered a NEW extra workspace root (the silent workspace expansion that was previously invisible — no tool round, only an app.log line). Surfaces a brief "added workspace root X" notice so the user knows the agent widened the project scope. */
export interface WorkspaceRootAddedEvent {
  type: 'workspace_root_added';
  /** list of {rootName, path} auto-registered this tool call */
  roots: unknown[];
}

/** Agent asked the human a question (ask_human tool); turn pauses. */
export interface HumanGuidanceRequestEvent {
  type: 'human_guidance_request';
  /** round index */
  roundNum: number;
  /** ask_human tool-call id */
  toolCallId: string;
  /** reply correlation id */
  guidanceId: string;
  /** prompt text */
  question: string;
  /** free_text|choice */
  responseType: string;
  /** choice options (normalized dicts) */
  options: unknown[];
}

/** A write/exec tool needs explicit approval before running. */
export interface WriteApprovalRequestEvent {
  type: 'write_approval_request';
  /** round index */
  roundNum: number;
  /** id of the tool call awaiting approval */
  toolCallId: string;
  /** reply correlation id */
  approvalId: string;
  /** {approvalId, toolName, path, description, + tool-specific enricher fields} preview payload */
  meta: Record<string, unknown>;
}

/** Generic approval gate (mode-based backends). */
export interface ApprovalRequiredEvent {
  type: 'approval_required';
  /** what needs approval */
  detail?: string;
}

/** A running command requested interactive stdin. */
export interface StdinRequestEvent {
  type: 'stdin_request';
  /** round index */
  roundNum: number;
  /** run_command tool-call id */
  toolCallId: string;
  /** reply correlation id */
  stdinId: string;
  /** stdin prompt */
  prompt: string;
  /** bounded command line awaiting input */
  command: string;
}

/** A pending stdin request was satisfied (clears the prompt UI). */
export interface StdinResolvedEvent {
  type: 'stdin_resolved';
  /** round index */
  roundNum: number;
  /** run_command tool-call id */
  toolCallId: string;
  /** correlation id */
  stdinId: string;
}

/** Flow loop entered a new Planner/Worker/Critic/VU iteration. */
export interface FlowIterationEvent {
  type: 'flow_iteration';
  /** index */
  iteration: number;
  /** planner|worker|critic */
  phase: string;
  /** (optional) orchestration projection label (absent on the synthetic guard frame) */
  flowProjection?: string;
  /** (optional) planner|worker|virtual_user turn role */
  turnRole?: string;
  /** (optional) declared emit surface of the role */
  emits?: string;
  /** (optional, virtual_user role) VU bubble id */
  vuMsgId?: string;
  /** (optional) owning autopilot run id */
  autopilotRunId?: string;
}

/** Planner produced a plan. */
export interface FlowPlannerDoneEvent {
  type: 'flow_planner_done';
  /** plan content */
  content: string;
  /** planner reasoning text */
  thinking: string;
}

/** Critic verdict + feedback. */
export interface FlowCriticMsgEvent {
  type: 'flow_critic_msg';
  /** flow iteration index */
  iteration: number;
  /** critic verdict text */
  content: string;
  /** (optional) critic reasoning (absent on the synthetic guard frame) */
  thinking?: string;
  /** planner|worker|stop */
  next_phase: string;
  /** (optional) true when the VU discarded this candidate */
  discard?: boolean;
  /** (optional) true on the backend guard frame */
  synthetic?: boolean;
  /** (optional) orchestration projection label */
  flowProjection?: string;
  /** (optional) turn role */
  turnRole?: string;
  /** (optional) declared emit surface of the role */
  emits?: string;
  /** (optional, virtual_user role) VU bubble id */
  vuMsgId?: string;
  /** (optional) owning autopilot run id */
  autopilotRunId?: string;
}

/** A fresh Worker/Planner turn began (new assistant bubble). */
export interface FlowNewTurnEvent {
  type: 'flow_new_turn';
  /** planner|worker */
  phase?: string;
}

/** Flow loop terminated (approved or replan-capped). Sole emitter: OrchestrationChatCompletion.finish. */
export interface FlowCompleteEvent {
  type: 'flow_complete';
  /** flow iteration count */
  totalIterations?: number;
  /** loop stop reason */
  reason?: string;
  /** replans consumed (always 0 today) */
  replanCount?: number;
  /** orchestration projection label */
  flowProjection?: string;
  /** TerminalOutcome dict */
  orchestrationOutcome?: Record<string, unknown>;
}

/** Top-level swarm orchestration phase. */
export interface SwarmPhaseEvent {
  type: 'swarm_phase';
  /** spawning|error|complete|spawn_more */
  phase: string;
  /** human-readable phase detail */
  content: string;
  /** (optional) swarm grouping key */
  swarmKey?: string;
  /** (optional) spawned agent descriptors {agentId, role, objective, model, depends_on} */
  agents?: unknown[];
  /** (optional) driver error text */
  error?: string;
  /** (complete) total agents */
  agentCount?: number;
  /** (complete) failed agents */
  failedCount?: number;
  /** (complete) aggregate token usage */
  totalTokens?: number;
}

/** A completed sub-agent result was injected into the main thread. */
export interface SwarmInboxInjectEvent {
  type: 'swarm_inbox_inject';
  /** round index the results were injected before */
  roundNum: number;
  /** number of sub-agent results injected */
  count: number;
  /** delivering sub-agent ids */
  agentIds: unknown[];
  /** list of {agentId, text} result previews */
  previews: unknown[];
}

/** A sub-agent changed phase (e.g. running). */
export interface SwarmAgentPhaseEvent {
  type: 'swarm_agent_phase';
  /** sub-agent id */
  agentId?: string;
  /** phase */
  phase?: string;
  /** human-readable phase detail */
  content: string;
  /** (optional) sub-agent role */
  role?: string;
  /** (optional) sub-agent objective */
  objective?: string;
  /** (optional) sub-agent model id */
  model?: string;
  /** (optional) retrying marker on agent_retry */
  status?: string;
  /** (optional) elapsed seconds */
  duration_s?: number;
  /** (optional) aggregate tokens */
  tokens?: number;
  /** (optional) sub-agent round index */
  roundNum?: number;
  /** (optional) swarm size */
  total_agents?: number;
  /** (optional) settled count */
  completed_agents?: number;
}

/** Sub-agent progress update. */
export interface SwarmAgentProgressEvent {
  type: 'swarm_agent_progress';
  /** sub-agent id */
  agentId?: string;
  /** progress text */
  content: string;
  /** running */
  status?: string;
  /** done|tool_use|stalled|no_progress|tool_authority */
  phase?: string;
  /** sub-agent round index */
  roundNum?: number;
  /** sub-agent role */
  role?: string;
  /** (optional, done) full final answer */
  preview?: string;
  /** (optional, tool_use) tools in flight */
  toolNames?: unknown[];
}

/** Sub-agent finished (status may be error). */
export interface SwarmAgentCompleteEvent {
  type: 'swarm_agent_complete';
  /** sub-agent id */
  agentId?: string;
  /** ok|error */
  status?: string;
  /** result/preview */
  content: string;
  /** (optional) sub-agent role */
  role?: string;
  /** (optional) sub-agent objective */
  objective?: string;
  /** (optional) sub-agent model id */
  model?: string;
  /** (optional) wall-clock seconds */
  elapsed?: number;
  /** (optional) aggregate tokens */
  tokens?: number;
  /** (optional) bounded result summary */
  summary?: string;
  /** (optional) error text on failure */
  error?: string;
  /** (optional) changed-path count */
  modifiedFiles?: number;
}

/** Sub-agent errored. */
export interface SwarmAgentErrorEvent {
  type: 'swarm_agent_error';
  /** sub-agent id */
  agentId?: string;
  /** error text */
  error?: string;
}

/** A sub-agent invoked a tool (for live trace UI). */
export interface SwarmAgentToolCallEvent {
  type: 'swarm_agent_tool_call';
  /** sub-agent id */
  agentId?: string;
  /** tool */
  toolName?: string;
  /** display text */
  content: string;
  /** running */
  status?: string;
  /** tool_use */
  phase?: string;
  /** sub-agent round index */
  roundNum?: number;
  /** sub-agent role */
  role?: string;
  /** tool-call correlation id */
  callId?: string;
  /** bounded args summary */
  argsBrief?: string;
  /** running|done|error status */
  callStatus?: string;
  /** (finish) call wall-clock seconds */
  callElapsed?: number;
  /** (finish) bounded result preview */
  preview?: string;
  /** (finish) preview was truncated */
  previewTruncated?: boolean;
  /** (finish) untruncated preview chars */
  previewFullChars?: number;
  /** (finish, failure) bounded error text */
  error?: string;
  /** (finish) error was truncated */
  errorTruncated?: boolean;
  /** (finish) untruncated error chars */
  errorFullChars?: number;
}

/** Autopilot kicked in — create the simulated-user bubble eagerly (in-memory only; not persisted until autopilot_vu_done). */
export interface AutopilotVuStartEvent {
  type: 'autopilot_vu_start';
  /** stable id for the VU message bubble */
  vuMsgId: string;
}

/** Autopilot value-unit progress event. */
export interface AutopilotVuEventEvent {
  type: 'autopilot_vu_event';
  /** owning VU bubble id */
  vuMsgId: string;
  /** the wrapped forward event dict (delta/phase/tool_* /interaction) */
  inner: Record<string, unknown>;
}

/** Autopilot value-unit completed. */
export interface AutopilotVuDoneEvent {
  type: 'autopilot_vu_done';
  /** owning VU bubble id */
  vuMsgId: string;
  /** persisted VU message row */
  vuMessage: Record<string, unknown>;
}

/** Autopilot value-unit cancelled. */
export interface AutopilotVuCancelEvent {
  type: 'autopilot_vu_cancel';
  /** owning VU bubble id */
  vuMsgId: string;
}

/** An autopilot run reached its terminal boundary — the single BACKEND-AUTHORITATIVE "this run is over" fact the frontend folds on. Emitted on BOTH close-out paths, symmetrically: a clean [VU: TASK_DONE] (reason=task_done, usually with a close-out report) AND a manual stop / toggle-off / new-message supersede (reason=stopped, no report). The frontend NEVER infers run-end from stream/task state anymore — it folds the run's VU<->agent transcript iff a concluded record exists, and shows the report (when present) as the fold's read-only PANEL. The record is human-only: it lives in the conversation SIDECAR (settings.autopilotSummaries[runId]), NEVER as a chat message, so it never enters the transcript nor the LLM context. Also durably persisted server-side, so a disarm with no live stream still folds on the next load. */
export interface AutopilotRunConcludedEvent {
  type: 'autopilot_run_concluded';
  /** autopilot run id grouping the folded turns */
  runId: string;
  /** the sidecar run record {runId, status:"concluded", reason:"task_done"|"stopped", content?, translatedContent?, ts, _summaryId} — NOT a message (no role, no _msgId); content is absent on a manual stop */
  record: Record<string, unknown>;
}

/** Cross-conversation live-presence delta — the "who is working in this project right now" feed (the shared-document cursor analog). Broadcast to ALL push clients (taskId="*"); the frontend filters by the root it is displaying. The backend is the single source of truth: every status word (active|idle) and conflict string is fully formed server-side — the frontend NEVER derives liveness from mere presence, only renders what this frame carries. Emitted on announce / heartbeat / file-set change / idle / depart and on a detected file-set overlap between two active peers (notify-only, no locking). */
export interface PresenceEvent {
  type: 'presence';
  /** update|depart|conflict|snapshot */
  kind: string;
  /** project root path this peer/conflict belongs to */
  root: string;
  /** (update/depart) {convId, agentId, parentTitle, taskId, runId, title, objective, status, statusLabel, phase, currentFile, files, lastBeatTs, startedTs}. agentId="" = a conversation peer; agentId set = a SUB-AGENT peer that the frontend nests under its parent conversation (grouped by convId). parentTitle = the parent conversation title for the nested-row label. */
  peer?: Record<string, unknown>;
  /** (snapshot) full active-peer list for the root */
  peers?: unknown[];
  /** (conflict) fully-formed advisory {path, message, peers:[peerKey…]} where a peerKey is convId or convId#agentId — so a sub-agent-vs-sub-agent overlap within ONE conversation is flagged like a cross-conversation one */
  conflict?: Record<string, unknown>;
}

/** A peer message from a sibling conversation was delivered at a round boundary of THIS live turn (the fast-path lane of Pillar #6). Injected as a user-role message right before the next LLM round — never mid-stream, never splitting a tool_call/tool_result pair. The durable message_queue row is deleted in the same step (de-dup by queueId), so the message is delivered exactly once. Drives an in-timeline chip mirroring swarm_inbox_inject; the idle-target queue-lane case renders the persisted .peer-msg-banner instead. */
export interface PeerInboxInjectEvent {
  type: 'peer_inbox_inject';
  /** round number the peer message was injected before */
  roundNum: number;
  /** number of peer messages injected this round */
  count: number;
  /** list of {fromConv, text} — sender short-id + the original (unframed) message text */
  previews: unknown[];
}

/** A human "steer" message the user sent WHILE this turn was still generating (composer inject-mode = steer) was drained from the model-facing inbox and injected as a user-role message right before the next LLM round — never mid-stream, never splitting a tool_call/tool_result pair (postponed to the next CLEAN round boundary after any open tool_result closes). Distinct from a sibling peer message (peer_inbox_inject) and from a completed sub-agent result (swarm_inbox_inject): it is the OPERATOR talking to their own running turn. Delivered exactly once — the chip is emitted only AFTER the LLM call confirms consumption (deferred-confirm), and an abort before that re-routes the undelivered steer to the durable message_queue as a fresh next turn (never zero, never double). Drives an in-timeline chip mirroring peer_inbox_inject. */
export interface UserSteerInjectEvent {
  type: 'user_steer_inject';
  /** round number the steer was injected before */
  roundNum: number;
  /** number of steer messages injected this round */
  count: number;
  /** list of {text} — the steer message text */
  previews: unknown[];
}

/** A run_command call that was handed off to a daemon worker for an operator steer has finished, and its authoritative result reached the model MID-TURN: the fast-path inbox twin was drained at a round boundary, injected as a user-role message (coalesced with any swarm/peer/steer items), and the LLM call confirmed consumption (deferred-confirm — this chip fires only after that confirmation). The durable message_queue row (the delivery authority) is deleted in the same step (de-dup by queueId); an abort before it re-dispatches the row as a fresh turn instead, so the result is delivered exactly once. Mirrors peer_inbox_inject; the settled-turn queue-lane case renders as a normal queued-turn user message instead. */
export interface BackgroundCommandInjectEvent {
  type: 'background_command_inject';
  /** round number the completion was injected before */
  roundNum: number;
  /** number of background-command completions injected this round */
  count: number;
  /** list of {commandId, text} — the detached command id + its result payload */
  previews: unknown[];
}

/** An artifact (document/canvas) was created or updated. */
export interface ArtifactEvent {
  type: 'artifact';
  /** artifact id */
  id: string;
  /** owning conversation id */
  conv_id: string;
  /** owning task id */
  task_id: string;
  /** owning message id */
  msg_id: string;
  /** write_file|inline_fence|inline_doc */
  source: string;
  /** producer-specific source reference */
  source_ref: Record<string, unknown>;
  /** markdown|html|svg */
  format: string;
  /** artifact title */
  title: string;
  /** payload size in bytes */
  size_bytes: number;
  /** artifact version counter */
  version: number;
  /** parent artifact id (empty when root) */
  parent_id: string;
  /** true when pinned */
  pinned: boolean;
  /** epoch ms creation stamp */
  created_at: number;
  /** /api/artifacts/<id>/raw fetch URL */
  url: string;
}

/** Inline timer/scheduler poll heartbeat — one per poll cycle. */
export interface TimerPollCheckEvent {
  type: 'timer_poll_check';
  /** tool round index */
  roundNum: number;
  /** tool-call id */
  toolCallId: string;
  /** timer id */
  timerId: string;
  /** poll counter */
  pollNum: number;
  /** stable per-poll id ({timerId}.p{N}) for log/DB/UI correlation */
  pollId?: string;
  /** started|wait|ready|skipped|error|parse_error */
  decision: string;
  /** LLM/decision rationale */
  reason: string;
  /** current decision tier (llm|hybrid|code) — sent every poll so the UI reflects a mid-run hybrid→code auto-promotion, not just the creation-time kind */
  conditionKind: string;
  /** the LLM's full raw output (sent only on parse_error/error) */
  rawContent?: string;
  /** tokens spent on this poll */
  tokensUsed?: number;
  /** (started) what is being verified */
  checkInstruction: string;
  /** (started) shell command run before each poll */
  checkCommand: string;
  /** truncated check_command output (the evidence) */
  cmdOutput?: string;
  /** true if the decision could not be parsed */
  parseError?: boolean;
  /** concrete model the poll LLM resolved to */
  model?: string;
  /** list of {name,argsBrief,elapsed,isError} the poll agent invoked */
  toolTrace?: unknown[];
  /** (started) seconds between polls */
  pollInterval: number;
  /** (started) poll ceiling */
  maxPolls: number;
  /** (started) command gating code-tier decisions */
  conditionCommand: string;
  /** (started) true — polls run in background */
  background: boolean;
  /** epoch-ms of the next scheduled poll */
  nextPollTs: number;
}

/** Server signalled the stream idle-timed-out; client may reconnect. */
export interface SseTimeoutEvent {
  type: 'sse_timeout';
}

/** Keepalive frame on the push WebSocket (ignore). */
export interface PingEvent {
  type: 'ping';
  /** push channel (system) */
  channel?: string;
}

/** Events with a field-level contract (the gated set). */
export type ContractedWireEvent =
  StateEvent |
  PhaseEvent |
  RoundStartEvent |
  RoundEndEvent |
  DoneEvent |
  ErrorEvent |
  RetryResetEvent |
  ModelRequestStartEvent |
  ModelRequestCompleteEvent |
  ModelFallbackEvent |
  DeltaEvent |
  DeltaResetEvent |
  ToolStartEvent |
  ToolProgressEvent |
  ToolResultEvent |
  ToolCompleteEvent |
  ToolSchemaRejectedEvent |
  ToolWireProjectionEvent |
  ToolCompactedEvent |
  ToolCallReplayEvent |
  ProgramStartEvent |
  ProgramOutputEvent |
  RoundUsageEvent |
  RoundCommittedEvent |
  MessagesSnapshotEvent |
  CompactionEvent |
  CompactionDoneEvent |
  MemoryPrefetchEvent |
  PreferencesAppliedEvent |
  PreferenceLearnedEvent |
  RelatedConversationsEvent |
  ProjectExternalEditEvent |
  WorkspaceRootAddedEvent |
  HumanGuidanceRequestEvent |
  WriteApprovalRequestEvent |
  ApprovalRequiredEvent |
  StdinRequestEvent |
  StdinResolvedEvent |
  FlowIterationEvent |
  FlowPlannerDoneEvent |
  FlowCriticMsgEvent |
  FlowNewTurnEvent |
  FlowCompleteEvent |
  SwarmPhaseEvent |
  SwarmInboxInjectEvent |
  SwarmAgentPhaseEvent |
  SwarmAgentProgressEvent |
  SwarmAgentCompleteEvent |
  SwarmAgentErrorEvent |
  SwarmAgentToolCallEvent |
  AutopilotVuStartEvent |
  AutopilotVuEventEvent |
  AutopilotVuDoneEvent |
  AutopilotVuCancelEvent |
  AutopilotRunConcludedEvent |
  PresenceEvent |
  PeerInboxInjectEvent |
  UserSteerInjectEvent |
  BackgroundCommandInjectEvent |
  ArtifactEvent |
  TimerPollCheckEvent |
  SseTimeoutEvent |
  PingEvent;

/** Any wire event; un-migrated types stay permissive. */
export interface UnknownWireEvent {
  type: string;
  [field: string]: unknown;
}

export const PUSH_FRAME_CONTRACT_VERSION = 1 as const;

/** Wake hint: a conversation catalog entry or transcript changed; clients reconcile exclusively through Conversation Sync v3, so a lost/duplicated hint never loses data. (push channel `notify`, task `conversation-id`) */
export interface ConvChangedPushFrame {
  type: 'conv_changed';
  /** Changed conversation id. */
  convId: string;
  /** Owner user id; the browser frame-ownership check is mandatory. */
  userId: number;
  /** Positive transcript-revision hint; lets the browser suppress a catalog read it has already reached. */
  rev?: number;
}

/** Wake hint: a conversation was deleted; clients dispose local state without a fetch. (push channel `notify`, task `conversation-id`) */
export interface ConvDeletedPushFrame {
  type: 'conv_deleted';
  /** Deleted conversation id. */
  convId: string;
  /** Owner user id; the browser frame-ownership check is mandatory. */
  userId: number;
}

/** Folder tree changed (create/rename/delete); clients refresh the tree in place. With deletedFolderId every device unassigns local conversations off the removed folder, not just the one that clicked delete. (push channel `notify`, task `__folders__`) */
export interface FoldersChangedPushFrame {
  type: 'folders_changed';
  /** Owner user id; the browser frame-ownership check is mandatory. */
  userId: number;
  /** Present only when a folder was deleted. */
  deletedFolderId?: string;
}

/** Passive completion receipt: the bounded earned-reset daemon settled. reset_offer is byte-compatible with the projection on GET /api/v1/oauth/status (length-bounded, no token or raw account id). Never durable authority: consumers keep a bounded HTTP reconciliation path and must never redeem a credit from the frame. (push channel `oauth`, task `codex-reset`) */
export interface CodexResetOfferUpdatedPushFrame {
  type: 'codex.reset_offer.updated';
  /** Always 'codex'. */
  provider: string;
  /** Account-scoped reset-offer projection mirroring the OAuth status endpoint. */
  reset_offer: Record<string, unknown>;
}

/** Declared owner-scoped push-hub frames. */
export type ContractedPushFrame =
  ConvChangedPushFrame |
  ConvDeletedPushFrame |
  FoldersChangedPushFrame |
  CodexResetOfferUpdatedPushFrame;

/** Wire `type` tags of every declared push frame. */
export const CONTRACTED_PUSH_FRAME_TYPES = [
  'conv_changed',
  'conv_deleted',
  'folders_changed',
  'codex.reset_offer.updated',
] as const satisfies readonly ContractedPushFrame['type'][];
