"""Machine-readable resource bounds shared by paper read/fan-in pipelines.

Responsibility: define dependency-free limits consumed by report/reopen,
podcast, survey, harvest, repositories, and the storage Sidecar. This module
performs no I/O.
"""

PAPER_FANIN_MAX_PAPERS = 40
PAPER_FANIN_MAX_TEXT_CHARS = 6_000
PAPER_AGENT_MAX_CONSECUTIVE_NO_PROGRESS_ROUNDS = 3
PAPER_PODCAST_MAX_SOURCE_CHARS = 40_000
PAPER_QA_HISTORY_MAX_CHARS = 24_000
PAPER_QA_HISTORY_MAX_MESSAGES = 10
PAPER_QA_HISTORY_MESSAGE_MAX_CHARS = 8_000
PAPER_QA_MAX_QUESTION_CHARS = 8_000
PAPER_QA_MAX_SOURCE_CHARS = 1_000_000
PAPER_QA_SOURCE_CONTEXT_MAX_CHARS = 60_000
PAPER_REPORT_MAX_SOURCE_CHARS = 120_000
PAPER_REPORT_REOPEN_MAX_SIBLINGS = 8
PAPER_TITLE_BATCH_MAX_IDS = 20
PAPER_TITLE_HINT_MAX_CHARS = 500
PAPER_TRANSLATION_MAX_OUTPUT_CHARS = 2_000_000
PAPER_TRANSLATION_MAX_OUTPUT_BYTES = 4_000_000
PAPER_SURVEY_MAX_CLUSTERS = 12
PAPER_SURVEY_MAX_GAPS = 20
PAPER_SURVEY_MAX_GROUND_PROBES = PAPER_TITLE_BATCH_MAX_IDS
PAPER_SURVEY_MAX_IDS_PER_ENTRY = PAPER_FANIN_MAX_PAPERS
PAPER_SURVEY_MAX_MATRIX_ROWS = PAPER_FANIN_MAX_PAPERS

__all__ = [
    'PAPER_FANIN_MAX_PAPERS',
    'PAPER_FANIN_MAX_TEXT_CHARS',
    'PAPER_AGENT_MAX_CONSECUTIVE_NO_PROGRESS_ROUNDS',
    'PAPER_PODCAST_MAX_SOURCE_CHARS',
    'PAPER_QA_HISTORY_MAX_CHARS',
    'PAPER_QA_HISTORY_MAX_MESSAGES',
    'PAPER_QA_HISTORY_MESSAGE_MAX_CHARS',
    'PAPER_QA_MAX_QUESTION_CHARS',
    'PAPER_QA_MAX_SOURCE_CHARS',
    'PAPER_QA_SOURCE_CONTEXT_MAX_CHARS',
    'PAPER_REPORT_MAX_SOURCE_CHARS',
    'PAPER_REPORT_REOPEN_MAX_SIBLINGS',
    'PAPER_TITLE_BATCH_MAX_IDS',
    'PAPER_TITLE_HINT_MAX_CHARS',
    'PAPER_TRANSLATION_MAX_OUTPUT_CHARS',
    'PAPER_TRANSLATION_MAX_OUTPUT_BYTES',
    'PAPER_SURVEY_MAX_CLUSTERS',
    'PAPER_SURVEY_MAX_GAPS',
    'PAPER_SURVEY_MAX_GROUND_PROBES',
    'PAPER_SURVEY_MAX_IDS_PER_ENTRY',
    'PAPER_SURVEY_MAX_MATRIX_ROWS',
]
