# Generated by scripts/gen_api_v4_contract.py; DO NOT EDIT.
"""Typed server boundary and canonical OpenAPI document for API v4."""

from __future__ import annotations

from typing import Annotated, Any, Literal, NotRequired, TypedDict, cast

from pydantic import ConfigDict, Field, StringConstraints, TypeAdapter

NonEmptyString = Annotated[str, StringConstraints(min_length=1)]
NumericBuildString = Annotated[
    str, StringConstraints(pattern=r'^[0-9]+(?:\.[0-9]+)*$')]
PositiveInteger = Annotated[int, Field(ge=1)]
NonNegativeInteger = Annotated[int, Field(ge=0)]
ProblemStatus = Annotated[int, Field(ge=400, le=599)]
ProblemCode = Annotated[
    str, StringConstraints(pattern=r'^[a-z][a-z0-9_]*$')]


class ApiMeta(TypedDict):
    __pydantic_config__ = ConfigDict(extra='forbid', strict=True)

    apiMajor: Literal[4]
    schemaVersion: PositiveInteger
    serverBuild: NonEmptyString
    minDesktopBuild: NumericBuildString
    minAndroidBuild: PositiveInteger


class ResponseMeta(TypedDict):
    __pydantic_config__ = ConfigDict(extra='forbid', strict=True)

    requestId: NonEmptyString
    serverTimeMs: NonNegativeInteger


class ApiMetaResponse(TypedDict):
    __pydantic_config__ = ConfigDict(extra='forbid', strict=True)

    data: ApiMeta
    meta: ResponseMeta


class Problem(TypedDict):
    __pydantic_config__ = ConfigDict(extra='forbid', strict=True)

    type: NonEmptyString
    title: NonEmptyString
    status: ProblemStatus
    detail: NonEmptyString
    instance: NonEmptyString
    code: ProblemCode
    requestId: NonEmptyString
    upgradeUrl: NotRequired[NonEmptyString]


API_META_RESPONSE_ADAPTER = TypeAdapter(ApiMetaResponse)
PROBLEM_ADAPTER = TypeAdapter(Problem)


def validate_api_meta_response(value: Any) -> ApiMetaResponse:
    """Validate one response at the HTTP boundary and reject extra fields."""
    return cast(ApiMetaResponse, API_META_RESPONSE_ADAPTER.validate_python(value))


def validate_problem(value: Any) -> Problem:
    """Validate one RFC 7807 body at the HTTP boundary."""
    return cast(Problem, PROBLEM_ADAPTER.validate_python(value))


OPENAPI_DOCUMENT: dict[str, Any] = {'openapi': '3.1.0',
 'info': {'title': 'Tofu API v4 bootstrap contract',
          'version': '4.0.0',
          'description': 'Canonical bootstrap surface for API-major negotiation. '
                         'Product operations are added here only when their v4 server '
                         'route and all generated clients ship together.'},
 'x-tofu-contract': 'tofu.api/v4',
 'x-tofu-api-major': 4,
 'x-tofu-release-stage': 'bootstrap',
 'x-tofu-minimum-builds': {'desktop': '0.16.0', 'android': 17},
 'x-tofu-legacy-upgrade': {'activeByDefault': False,
                           'prefixes': ['/api/v1', '/api/v3'],
                           'status': 426,
                           'upgradeUrl': '/api/v4/meta'},
 'paths': {'/api/v4/meta': {'get': {'operationId': 'getApiMeta',
                                    'summary': 'Report the server and minimum '
                                               'compatible client builds',
                                    'security': [],
                                    'responses': {'200': {'description': 'API-major '
                                                                         'and build '
                                                                         'compatibility '
                                                                         'metadata',
                                                          'headers': {'X-Request-ID': {'schema': {'type': 'string'}}},
                                                          'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ApiMetaResponse'}}}},
                                                  '500': {'$ref': '#/components/responses/ProblemResponse'}}}},
           '/api/v4/openapi.json': {'get': {'operationId': 'getApiV4OpenApi',
                                            'summary': 'Return this canonical OpenAPI '
                                                       'document',
                                            'description': 'This self-describing '
                                                           'endpoint returns the raw '
                                                           'OpenAPI document rather '
                                                           'than the normal data/meta '
                                                           'success envelope.',
                                            'security': [],
                                            'responses': {'200': {'description': 'Canonical '
                                                                                 'OpenAPI '
                                                                                 '3.1 '
                                                                                 'document',
                                                                  'headers': {'X-Request-ID': {'schema': {'type': 'string'}}},
                                                                  'content': {'application/json': {'schema': {'type': 'object',
                                                                                                              'required': ['openapi',
                                                                                                                           'info',
                                                                                                                           'paths'],
                                                                                                              'additionalProperties': True}}}},
                                                          '500': {'$ref': '#/components/responses/ProblemResponse'}}}}},
 'components': {'responses': {'ProblemResponse': {'description': 'RFC 7807 problem '
                                                                 'details',
                                                  'content': {'application/problem+json': {'schema': {'$ref': '#/components/schemas/Problem'}}}}},
                'schemas': {'ApiMeta': {'type': 'object',
                                        'additionalProperties': False,
                                        'required': ['apiMajor',
                                                     'schemaVersion',
                                                     'serverBuild',
                                                     'minDesktopBuild',
                                                     'minAndroidBuild'],
                                        'properties': {'apiMajor': {'type': 'integer',
                                                                    'const': 4},
                                                       'schemaVersion': {'type': 'integer',
                                                                         'minimum': 1},
                                                       'serverBuild': {'type': 'string',
                                                                       'minLength': 1},
                                                       'minDesktopBuild': {'type': 'string',
                                                                           'pattern': '^[0-9]+(?:\\.[0-9]+)*$'},
                                                       'minAndroidBuild': {'type': 'integer',
                                                                           'minimum': 1}}},
                            'ResponseMeta': {'type': 'object',
                                             'additionalProperties': False,
                                             'required': ['requestId', 'serverTimeMs'],
                                             'properties': {'requestId': {'type': 'string',
                                                                          'minLength': 1},
                                                            'serverTimeMs': {'type': 'integer',
                                                                             'minimum': 0}}},
                            'ApiMetaResponse': {'type': 'object',
                                                'additionalProperties': False,
                                                'required': ['data', 'meta'],
                                                'properties': {'data': {'$ref': '#/components/schemas/ApiMeta'},
                                                               'meta': {'$ref': '#/components/schemas/ResponseMeta'}}},
                            'Problem': {'type': 'object',
                                        'additionalProperties': False,
                                        'required': ['type',
                                                     'title',
                                                     'status',
                                                     'detail',
                                                     'instance',
                                                     'code',
                                                     'requestId'],
                                        'properties': {'type': {'type': 'string',
                                                                'format': 'uri-reference'},
                                                       'title': {'type': 'string',
                                                                 'minLength': 1},
                                                       'status': {'type': 'integer',
                                                                  'minimum': 400,
                                                                  'maximum': 599},
                                                       'detail': {'type': 'string',
                                                                  'minLength': 1},
                                                       'instance': {'type': 'string',
                                                                    'format': 'uri-reference'},
                                                       'code': {'type': 'string',
                                                                'pattern': '^[a-z][a-z0-9_]*$'},
                                                       'requestId': {'type': 'string',
                                                                     'minLength': 1},
                                                       'upgradeUrl': {'type': 'string',
                                                                      'format': 'uri-reference'}}}}}}
