"""AUTO-GENERATED by scripts/gen_api_v1_model_routing_contract.py.

Canonical sources: contracts/api_v1_model_routing.yaml and
contracts/model_routing_v2.schema.json.
DO NOT EDIT BY HAND.
"""

from __future__ import annotations

from collections.abc import Mapping
import re
from typing import Any

CONTRACT_ID = 'tofu.api-v1-model-routing/v1'
ROUTES_BLUEPRINT = 'routes.api_v1.providers:api_v1_providers_bp'
OPENAPI_SCHEMAS = {'CompiledProviderBundle': {'additionalProperties': False,
                            'properties': {'connections': {'items': {'$ref': '#/$defs/connection'},
                                                           'maxItems': 64,
                                                           'type': 'array'},
                                           'creators': {'items': {'$ref': '#/$defs/creator'},
                                                        'maxItems': 256,
                                                        'type': 'array'},
                                           'credential_extra_headers': {'additionalProperties': {'maxLength': 2048,
                                                                                                 'type': 'string'},
                                                                        'maxProperties': 32,
                                                                        'type': 'object'},
                                           'credentials': {'items': {'$ref': '#/$defs/credentialMetadata'},
                                                           'maxItems': 128,
                                                           'type': 'array'},
                                           'deployments': {'items': {'$ref': '#/$defs/deployment'},
                                                           'maxItems': 1024,
                                                           'type': 'array'},
                                           'models': {'items': {'$ref': '#/$defs/model'},
                                                      'maxItems': 1024,
                                                      'type': 'array'},
                                           'offerings': {'items': {'$ref': '#/$defs/offering'},
                                                         'maxItems': 512,
                                                         'type': 'array'},
                                           'provider': {'$ref': '#/$defs/provider'},
                                           'provider_access': {'$ref': '#/$defs/providerAccess'}},
                            'required': ['provider',
                                         'provider_access',
                                         'connections',
                                         'credentials',
                                         'offerings',
                                         'deployments',
                                         'creators',
                                         'models',
                                         'credential_extra_headers'],
                            'type': 'object'},
 'CredentialSecretPutRequest': {'additionalProperties': False,
                                'properties': {'expected_revision': {'$ref': '#/components/schemas/Revision'},
                                               'secret': {'type': 'string'}},
                                'required': ['expected_revision', 'secret'],
                                'type': 'object'},
 'CredentialSecretPutResponse': {'additionalProperties': False,
                                 'properties': {'credential_id': {'minLength': 1, 'type': 'string'},
                                                'key_hint': {'maxLength': 64, 'type': 'string'},
                                                'revision': {'$ref': '#/components/schemas/Revision'}},
                                 'required': ['credential_id', 'key_hint', 'revision'],
                                 'type': 'object'},
 'CredentialSecretRevealResponse': {'additionalProperties': False,
                                    'properties': {'credential_id': {'minLength': 1,
                                                                     'type': 'string'},
                                                   'secret': {'type': 'string'}},
                                    'required': ['credential_id', 'secret'],
                                    'type': 'object'},
 'MigrationCommitResponse': {'additionalProperties': False,
                             'properties': {'migration_receipt': {'additionalProperties': True,
                                                                  'type': 'object'},
                                            'model_routing': {'anyOf': [{'$ref': '#/components/schemas/ModelRoutingDocument'},
                                                                        {'type': 'null'}]},
                                            'revision': {'$ref': '#/components/schemas/Revision'}},
                             'required': ['model_routing', 'revision', 'migration_receipt'],
                             'type': 'object'},
 'MigrationPlan': {'additionalProperties': False,
                   'properties': {'contract_version': {'const': 'tofu.model-routing/v2'},
                                  'entity_counts': {'additionalProperties': False,
                                                    'properties': {'connections': {'minimum': 0,
                                                                                   'type': 'integer'},
                                                                   'creators': {'minimum': 0,
                                                                                'type': 'integer'},
                                                                   'credentials': {'minimum': 0,
                                                                                   'type': 'integer'},
                                                                   'deployments': {'minimum': 0,
                                                                                   'type': 'integer'},
                                                                   'models': {'minimum': 0,
                                                                              'type': 'integer'},
                                                                   'offerings': {'minimum': 0,
                                                                                 'type': 'integer'},
                                                                   'provider_accesses': {'minimum': 0,
                                                                                         'type': 'integer'},
                                                                   'providers': {'minimum': 0,
                                                                                 'type': 'integer'}},
                                                    'required': ['creators',
                                                                 'models',
                                                                 'providers',
                                                                 'provider_accesses',
                                                                 'connections',
                                                                 'credentials',
                                                                 'offerings',
                                                                 'deployments'],
                                                    'type': 'object'},
                                  'issues': {'items': {'additionalProperties': False,
                                                       'properties': {'candidates': {'items': {'additionalProperties': {'type': 'string'},
                                                                                               'type': 'object'},
                                                                                     'maxItems': 64,
                                                                                     'type': 'array'},
                                                                      'code': {'type': 'string'},
                                                                      'message': {'type': 'string'},
                                                                      'path': {'type': 'string'},
                                                                      'severity': {'type': 'string'}},
                                                       'required': ['severity', 'code', 'message'],
                                                       'type': 'object'},
                                             'maxItems': 4096,
                                             'type': 'array'},
                                  'ready': {'type': 'boolean'},
                                  'secrets': {'items': {'additionalProperties': False,
                                                        'properties': {'credential_id': {'type': 'string'},
                                                                       'key_hint': {'type': 'string'},
                                                                       'secret_reference': {'type': 'string'}},
                                                        'required': ['credential_id',
                                                                     'secret_reference',
                                                                     'key_hint'],
                                                        'type': 'object'},
                                              'maxItems': 1024,
                                              'type': 'array'},
                                  'source_digest': {'type': 'string'}},
                   'required': ['contract_version',
                                'source_digest',
                                'entity_counts',
                                'secrets',
                                'issues',
                                'ready'],
                   'type': 'object'},
 'MigrationPlanResponse': {'additionalProperties': False,
                           'properties': {'migration_plan': {'$ref': '#/components/schemas/MigrationPlan'}},
                           'required': ['migration_plan'],
                           'type': 'object'},
 'ModelRoutingAuthorityResponse': {'additionalProperties': False,
                                   'properties': {'model_routing': {'$ref': '#/components/schemas/ModelRoutingDocument'},
                                                  'revision': {'$ref': '#/components/schemas/Revision'}},
                                   'required': ['model_routing', 'revision'],
                                   'type': 'object'},
 'ModelRoutingDocument': {'$ref': '#/$defs/__document'},
 'ModelRoutingPutRequest': {'additionalProperties': False,
                            'properties': {'expected_revision': {'$ref': '#/components/schemas/Revision'},
                                           'model_routing': {'$ref': '#/components/schemas/ModelRoutingDocument'}},
                            'required': ['expected_revision', 'model_routing'],
                            'type': 'object'},
 'ProbeCellsSnapshot': {'additionalProperties': True,
                        'properties': {'attempts': {'type': 'integer'},
                                       'cells': {'additionalProperties': True, 'type': 'object'},
                                       'done_count': {'type': 'integer'},
                                       'error': {'anyOf': [{'type': 'string'}, {'type': 'null'}]},
                                       'finished_at': {'anyOf': [{'type': 'number'},
                                                                 {'type': 'null'}]},
                                       'probe_schema_version': {'type': 'integer'},
                                       'provider_id': {'type': 'string'},
                                       'started_at': {'type': 'number'},
                                       'status': {'type': 'string'},
                                       'summary': {'additionalProperties': True,
                                                   'properties': {'disable': {'type': 'integer'},
                                                                  'failed': {'type': 'integer'},
                                                                  'neutral': {'type': 'integer'},
                                                                  'ok': {'type': 'integer'},
                                                                  'skipped': {'type': 'integer'}},
                                                   'type': 'object'},
                                       'total': {'type': 'integer'}},
                        'required': ['status'],
                        'type': 'object'},
 'ProbeCellsStartRequest': {'additionalProperties': False,
                            'properties': {'attempts': {'type': 'integer'},
                                           'force': {'type': 'boolean'},
                                           'only': {'additionalProperties': False,
                                                    'properties': {'key_idxs': {'items': {'type': 'integer'},
                                                                                'maxItems': 128,
                                                                                'type': 'array'},
                                                                   'model_ids': {'items': {'type': 'string'},
                                                                                 'maxItems': 1024,
                                                                                 'type': 'array'}},
                                                    'type': 'object'},
                                           'timeout': {'type': 'integer'}},
                            'type': 'object'},
 'ProviderBundle': {'additionalProperties': False,
                    'properties': {'connections': {'items': {'$ref': '#/$defs/connection'},
                                                   'maxItems': 64,
                                                   'type': 'array'},
                                   'credentials': {'items': {'$ref': '#/$defs/credentialMetadata'},
                                                   'maxItems': 128,
                                                   'type': 'array'},
                                   'deployments': {'items': {'$ref': '#/$defs/deployment'},
                                                   'maxItems': 1024,
                                                   'type': 'array'},
                                   'offerings': {'items': {'$ref': '#/$defs/offering'},
                                                 'maxItems': 512,
                                                 'type': 'array'},
                                   'provider': {'$ref': '#/$defs/provider'},
                                   'provider_access': {'anyOf': [{'$ref': '#/$defs/providerAccess'},
                                                                 {'type': 'null'}]}},
                    'required': ['provider',
                                 'provider_access',
                                 'connections',
                                 'credentials',
                                 'offerings',
                                 'deployments'],
                    'type': 'object'},
 'ProviderDeleteRequest': {'additionalProperties': False,
                           'properties': {'expected_revision': {'$ref': '#/components/schemas/Revision'}},
                           'required': ['expected_revision'],
                           'type': 'object'},
 'ProviderDeleteResponse': {'additionalProperties': False,
                            'properties': {'deleted': {'minLength': 1, 'type': 'string'},
                                           'revision': {'$ref': '#/components/schemas/Revision'}},
                            'required': ['deleted', 'revision'],
                            'type': 'object'},
 'ProviderListResponse': {'additionalProperties': False,
                          'properties': {'providers': {'items': {'$ref': '#/components/schemas/ProviderBundle'},
                                                       'maxItems': 256,
                                                       'type': 'array'},
                                         'revision': {'$ref': '#/components/schemas/Revision'}},
                          'required': ['providers', 'revision'],
                          'type': 'object'},
 'ProviderProbeRequest': {'additionalProperties': False,
                          'properties': {'api_key': {'type': 'string'},
                                         'base_url': {'type': 'string'},
                                         'models_path': {'type': 'string'}},
                          'required': ['base_url'],
                          'type': 'object'},
 'ProviderProbeResponse': {'additionalProperties': True,
                           'properties': {'base_url': {'type': 'string'},
                                          'brand': {'type': 'string'},
                                          'credential_id': {'type': 'string'},
                                          'error': {'type': 'string'},
                                          'model_count': {'minimum': 0, 'type': 'integer'},
                                          'name': {'type': 'string'},
                                          'ok': {'type': 'boolean'},
                                          'provider_bundle': {'$ref': '#/components/schemas/CompiledProviderBundle'}},
                           'type': 'object'},
 'ProviderResponse': {'additionalProperties': False,
                      'properties': {'provider': {'$ref': '#/components/schemas/ProviderBundle'},
                                     'revision': {'$ref': '#/components/schemas/Revision'}},
                      'required': ['provider', 'revision'],
                      'type': 'object'},
 'ProviderTemplate': {'additionalProperties': True,
                      'properties': {'base_url': {'type': 'string'},
                                     'brand': {'type': 'string'},
                                     'category': {'type': 'string'},
                                     'key': {'minLength': 1, 'type': 'string'},
                                     'name': {'type': 'string'}},
                      'required': ['key'],
                      'type': 'object'},
 'ProviderTemplateCompileRequest': {'additionalProperties': False,
                                    'properties': {'selected_model_ids': {'items': {'type': 'string'},
                                                                          'maxItems': 1024,
                                                                          'type': 'array'},
                                                   'template_key': {'type': 'string'}},
                                    'required': ['template_key'],
                                    'type': 'object'},
 'ProviderTemplateCompileResponse': {'additionalProperties': False,
                                     'properties': {'provider_bundle': {'$ref': '#/components/schemas/CompiledProviderBundle'}},
                                     'required': ['provider_bundle'],
                                     'type': 'object'},
 'ProviderTemplateListResponse': {'additionalProperties': False,
                                  'properties': {'items': {'items': {'$ref': '#/components/schemas/ProviderTemplate'},
                                                           'maxItems': 256,
                                                           'type': 'array'}},
                                  'required': ['items'],
                                  'type': 'object'},
 'ProviderWriteRequest': {'additionalProperties': False,
                          'properties': {'connections': {'items': {'$ref': '#/$defs/connection'},
                                                         'maxItems': 64,
                                                         'type': 'array'},
                                         'creators': {'items': {'$ref': '#/$defs/creator'},
                                                      'maxItems': 256,
                                                      'type': 'array'},
                                         'credential_secrets': {'additionalProperties': {'maxLength': 8192,
                                                                                         'type': 'string'},
                                                                'maxProperties': 128,
                                                                'type': 'object'},
                                         'credentials': {'items': {'$ref': '#/$defs/credentialMetadata'},
                                                         'maxItems': 128,
                                                         'type': 'array'},
                                         'deployments': {'items': {'$ref': '#/$defs/deployment'},
                                                         'maxItems': 1024,
                                                         'type': 'array'},
                                         'expected_revision': {'$ref': '#/components/schemas/Revision'},
                                         'models': {'items': {'$ref': '#/$defs/model'},
                                                    'maxItems': 1024,
                                                    'type': 'array'},
                                         'offerings': {'items': {'$ref': '#/$defs/offering'},
                                                       'maxItems': 512,
                                                       'type': 'array'},
                                         'provider': {'$ref': '#/$defs/provider'},
                                         'provider_access': {'$ref': '#/$defs/providerAccess'}},
                          'required': ['expected_revision',
                                       'provider',
                                       'provider_access',
                                       'connections',
                                       'credentials',
                                       'offerings',
                                       'deployments'],
                          'type': 'object'},
 'Revision': {'minimum': 0, 'type': 'integer'}}
EXTERNAL_DEFS = {'__document': {'$defs': {'capabilities': {'items': {'$ref': '#/$defs/identifier'},
                                           'maxItems': 64,
                                           'type': 'array',
                                           'uniqueItems': True},
                          'connection': {'additionalProperties': False,
                                         'properties': {'adapter': {'$ref': '#/$defs/desktopAdapter'},
                                                        'base_url': {'maxLength': 2048,
                                                                     'minLength': 1,
                                                                     'type': 'string'},
                                                        'connection_id': {'$ref': '#/$defs/identifier'},
                                                        'enabled': {'type': 'boolean'},
                                                        'extra_headers': {'additionalProperties': {'maxLength': 2048,
                                                                                                   'type': 'string'},
                                                                          'maxProperties': 32,
                                                                          'type': 'object'},
                                                        'gateway_namespace': {'maxLength': 256,
                                                                              'type': 'string'},
                                                        'priority': {'maximum': 1000000,
                                                                     'minimum': 0,
                                                                     'type': 'integer'},
                                                        'protocol': {'enum': ['openai',
                                                                              'openai_responses',
                                                                              'anthropic',
                                                                              'local',
                                                                              'custom']},
                                                        'provider_access_id': {'$ref': '#/$defs/identifier'},
                                                        'region': {'maxLength': 128,
                                                                   'type': 'string'}},
                                         'required': ['connection_id',
                                                      'provider_access_id',
                                                      'base_url',
                                                      'protocol',
                                                      'enabled',
                                                      'priority',
                                                      'extra_headers'],
                                         'type': 'object'},
                          'creator': {'additionalProperties': False,
                                      'properties': {'creator_id': {'$ref': '#/$defs/identifier'},
                                                     'name': {'maxLength': 256,
                                                              'minLength': 1,
                                                              'type': 'string'},
                                                     'website': {'maxLength': 1024,
                                                                 'type': 'string'}},
                                      'required': ['creator_id', 'name'],
                                      'type': 'object'},
                          'credentialAuthorization': {'additionalProperties': False,
                                                      'properties': {'connection_ids': {'$ref': '#/$defs/identifierList'},
                                                                     'models': {'items': {'$ref': '#/$defs/modelRef'},
                                                                                'maxItems': 4096,
                                                                                'type': 'array',
                                                                                'uniqueItems': True}},
                                                      'required': ['connection_ids', 'models'],
                                                      'type': 'object'},
                          'credentialMetadata': {'additionalProperties': False,
                                                 'properties': {'authorization': {'$ref': '#/$defs/credentialAuthorization'},
                                                                'credential_id': {'$ref': '#/$defs/identifier'},
                                                                'enabled': {'type': 'boolean'},
                                                                'key_hint': {'maxLength': 64,
                                                                             'type': 'string'},
                                                                'kind': {'enum': ['api_key',
                                                                                  'oauth',
                                                                                  'local_identity',
                                                                                  'subscription']},
                                                                'provider_access_id': {'$ref': '#/$defs/identifier'},
                                                                'quota_policy': {'$ref': '#/$defs/quotaPolicy'},
                                                                'secret_reference': {'maxLength': 256,
                                                                                     'type': 'string'}},
                                                 'required': ['credential_id',
                                                              'provider_access_id',
                                                              'kind',
                                                              'secret_reference',
                                                              'key_hint',
                                                              'enabled',
                                                              'authorization',
                                                              'quota_policy'],
                                                 'type': 'object'},
                          'deployment': {'additionalProperties': False,
                                         'properties': {'connection_id': {'$ref': '#/$defs/identifier'},
                                                        'deployment_id': {'$ref': '#/$defs/identifier'},
                                                        'enabled': {'type': 'boolean'},
                                                        'identity_confidence': {'enum': ['high',
                                                                                         'medium',
                                                                                         'low',
                                                                                         'pending']},
                                                        'max_output_tokens': {'maximum': 1000000,
                                                                              'minimum': 1,
                                                                              'type': 'integer'},
                                                        'offering_id': {'$ref': '#/$defs/identifier'},
                                                        'priority': {'maximum': 1000000,
                                                                     'minimum': 0,
                                                                     'type': 'integer'},
                                                        'probe_status': {'enum': ['passed',
                                                                                  'failed',
                                                                                  'unprobed',
                                                                                  'stale']},
                                                        'wire_model_id': {'$ref': '#/$defs/identifier'}},
                                         'required': ['deployment_id',
                                                      'offering_id',
                                                      'connection_id',
                                                      'wire_model_id',
                                                      'enabled',
                                                      'identity_confidence',
                                                      'probe_status',
                                                      'priority'],
                                         'type': 'object'},
                          'desktopAdapter': {'additionalProperties': False,
                                             'properties': {'agent_id': {'$ref': '#/$defs/identifier'},
                                                            'port': {'maximum': 65535,
                                                                     'minimum': 1,
                                                                     'type': 'integer'}},
                                             'required': ['agent_id', 'port'],
                                             'type': 'object'},
                          'identifier': {'maxLength': 256,
                                         'minLength': 1,
                                         'pattern': '^[^\\u0000-\\u001f]+$',
                                         'type': 'string'},
                          'identifierList': {'items': {'$ref': '#/$defs/identifier'},
                                             'maxItems': 512,
                                             'type': 'array',
                                             'uniqueItems': True},
                          'migrationMetadata': {'additionalProperties': False,
                                                'properties': {'migrated_at': {'minimum': 0,
                                                                               'type': 'number'},
                                                               'receipt_id': {'$ref': '#/$defs/identifier'},
                                                               'source': {'maxLength': 128,
                                                                          'type': 'string'}},
                                                'required': ['source', 'migrated_at', 'receipt_id'],
                                                'type': 'object'},
                          'model': {'additionalProperties': False,
                                    'properties': {'capabilities': {'$ref': '#/$defs/capabilities'},
                                                   'context_window': {'minimum': 1,
                                                                      'type': 'integer'},
                                                   'creator_id': {'$ref': '#/$defs/identifier'},
                                                   'display_name': {'maxLength': 256,
                                                                    'minLength': 1,
                                                                    'type': 'string'},
                                                   'lifecycle': {'enum': ['stable',
                                                                          'preview',
                                                                          'dated_snapshot',
                                                                          'retired']},
                                                   'list_pricing': {'$ref': '#/$defs/pricing'},
                                                   'model_id': {'$ref': '#/$defs/identifier'},
                                                   'quality_rank': {'type': 'number'},
                                                   'release_date': {'pattern': '^\\d{4}-\\d{2}(-\\d{2})?$',
                                                                    'type': 'string'}},
                                    'required': ['creator_id',
                                                 'model_id',
                                                 'display_name',
                                                 'capabilities',
                                                 'context_window',
                                                 'quality_rank'],
                                    'type': 'object'},
                          'modelRef': {'additionalProperties': False,
                                       'properties': {'creator_id': {'$ref': '#/$defs/identifier'},
                                                      'model_id': {'$ref': '#/$defs/identifier'}},
                                       'required': ['creator_id', 'model_id'],
                                       'type': 'object'},
                          'offering': {'additionalProperties': False,
                                       'allOf': [{'else': {'not': {'required': ['model']},
                                                           'required': ['pending_model_id']},
                                                  'if': {'properties': {'identity_state': {'const': 'confirmed'}}},
                                                  'then': {'not': {'required': ['pending_model_id']},
                                                           'required': ['model']}}],
                                       'properties': {'actual_pricing': {'$ref': '#/$defs/pricing'},
                                                      'capabilities': {'$ref': '#/$defs/capabilities'},
                                                      'context_window': {'minimum': 1,
                                                                         'type': 'integer'},
                                                      'enabled': {'type': 'boolean'},
                                                      'identity_state': {'enum': ['confirmed',
                                                                                  'pending_identity']},
                                                      'model': {'$ref': '#/$defs/modelRef'},
                                                      'offering_id': {'$ref': '#/$defs/identifier'},
                                                      'pending_model_id': {'maxLength': 256,
                                                                           'type': 'string'},
                                                      'priority': {'maximum': 1000000,
                                                                   'minimum': 0,
                                                                   'type': 'integer'},
                                                      'provider_access_id': {'$ref': '#/$defs/identifier'},
                                                      'stale': {'type': 'boolean'}},
                                       'required': ['offering_id',
                                                    'provider_access_id',
                                                    'identity_state',
                                                    'enabled',
                                                    'capabilities',
                                                    'context_window',
                                                    'priority'],
                                       'type': 'object'},
                          'pricing': {'additionalProperties': False,
                                      'properties': {'cache_read': {'minimum': 0, 'type': 'number'},
                                                     'cache_write': {'minimum': 0,
                                                                     'type': 'number'},
                                                     'currency': {'enum': ['USD', 'CNY']},
                                                     'input': {'minimum': 0, 'type': 'number'},
                                                     'output': {'minimum': 0, 'type': 'number'},
                                                     'unit': {'const': 'per_million_tokens'}},
                                      'required': ['input', 'output', 'currency', 'unit'],
                                      'type': 'object'},
                          'provider': {'additionalProperties': False,
                                       'properties': {'brand': {'maxLength': 128, 'type': 'string'},
                                                      'name': {'maxLength': 256,
                                                               'minLength': 1,
                                                               'type': 'string'},
                                                      'provider_id': {'$ref': '#/$defs/identifier'},
                                                      'scope': {'enum': ['public', 'owner']},
                                                      'website': {'maxLength': 1024,
                                                                  'type': 'string'}},
                                       'required': ['provider_id', 'name', 'scope'],
                                       'type': 'object'},
                          'providerAccess': {'additionalProperties': False,
                                             'properties': {'display_name': {'maxLength': 256,
                                                                             'type': 'string'},
                                                            'enabled': {'type': 'boolean'},
                                                            'provider_access_id': {'$ref': '#/$defs/identifier'},
                                                            'provider_id': {'$ref': '#/$defs/identifier'},
                                                            'quota_policy': {'$ref': '#/$defs/quotaPolicy'}},
                                             'required': ['provider_access_id',
                                                          'provider_id',
                                                          'enabled',
                                                          'quota_policy'],
                                             'type': 'object'},
                          'quotaPolicy': {'additionalProperties': False,
                                          'properties': {'balance': {'minimum': 0,
                                                                     'type': 'number'},
                                                         'currency': {'enum': ['USD', 'CNY']},
                                                         'daily_tokens': {'minimum': 0,
                                                                          'type': 'integer'},
                                                         'rpm': {'minimum': 0, 'type': 'integer'},
                                                         'tpm': {'minimum': 0, 'type': 'integer'}},
                                          'type': 'object'}},
                '$id': 'https://tofu.local/contracts/model_routing_v2.schema.json',
                '$schema': 'https://json-schema.org/draft/2020-12/schema',
                'additionalProperties': False,
                'properties': {'connections': {'items': {'$ref': '#/$defs/connection'},
                                               'maxItems': 512,
                                               'type': 'array'},
                               'contract_version': {'const': 'tofu.model-routing/v2'},
                               'creators': {'items': {'$ref': '#/$defs/creator'},
                                            'maxItems': 1024,
                                            'type': 'array'},
                               'credentials': {'items': {'$ref': '#/$defs/credentialMetadata'},
                                               'maxItems': 1024,
                                               'type': 'array'},
                               'deployments': {'items': {'$ref': '#/$defs/deployment'},
                                               'maxItems': 8192,
                                               'type': 'array'},
                               'migration': {'$ref': '#/$defs/migrationMetadata'},
                               'models': {'items': {'$ref': '#/$defs/model'},
                                          'maxItems': 4096,
                                          'type': 'array'},
                               'offerings': {'items': {'$ref': '#/$defs/offering'},
                                             'maxItems': 4096,
                                             'type': 'array'},
                               'provider_accesses': {'items': {'$ref': '#/$defs/providerAccess'},
                                                     'maxItems': 256,
                                                     'type': 'array'},
                               'providers': {'items': {'$ref': '#/$defs/provider'},
                                             'maxItems': 256,
                                             'type': 'array'},
                               'revision': {'minimum': 0, 'type': 'integer'}},
                'required': ['contract_version',
                             'revision',
                             'creators',
                             'models',
                             'providers',
                             'provider_accesses',
                             'connections',
                             'credentials',
                             'offerings',
                             'deployments'],
                'title': 'Tofu model routing v2',
                'type': 'object'},
 'capabilities': {'items': {'$ref': '#/$defs/identifier'},
                  'maxItems': 64,
                  'type': 'array',
                  'uniqueItems': True},
 'connection': {'additionalProperties': False,
                'properties': {'adapter': {'$ref': '#/$defs/desktopAdapter'},
                               'base_url': {'maxLength': 2048, 'minLength': 1, 'type': 'string'},
                               'connection_id': {'$ref': '#/$defs/identifier'},
                               'enabled': {'type': 'boolean'},
                               'extra_headers': {'additionalProperties': {'maxLength': 2048,
                                                                          'type': 'string'},
                                                 'maxProperties': 32,
                                                 'type': 'object'},
                               'gateway_namespace': {'maxLength': 256, 'type': 'string'},
                               'priority': {'maximum': 1000000, 'minimum': 0, 'type': 'integer'},
                               'protocol': {'enum': ['openai',
                                                     'openai_responses',
                                                     'anthropic',
                                                     'local',
                                                     'custom']},
                               'provider_access_id': {'$ref': '#/$defs/identifier'},
                               'region': {'maxLength': 128, 'type': 'string'}},
                'required': ['connection_id',
                             'provider_access_id',
                             'base_url',
                             'protocol',
                             'enabled',
                             'priority',
                             'extra_headers'],
                'type': 'object'},
 'creator': {'additionalProperties': False,
             'properties': {'creator_id': {'$ref': '#/$defs/identifier'},
                            'name': {'maxLength': 256, 'minLength': 1, 'type': 'string'},
                            'website': {'maxLength': 1024, 'type': 'string'}},
             'required': ['creator_id', 'name'],
             'type': 'object'},
 'credentialAuthorization': {'additionalProperties': False,
                             'properties': {'connection_ids': {'$ref': '#/$defs/identifierList'},
                                            'models': {'items': {'$ref': '#/$defs/modelRef'},
                                                       'maxItems': 4096,
                                                       'type': 'array',
                                                       'uniqueItems': True}},
                             'required': ['connection_ids', 'models'],
                             'type': 'object'},
 'credentialMetadata': {'additionalProperties': False,
                        'properties': {'authorization': {'$ref': '#/$defs/credentialAuthorization'},
                                       'credential_id': {'$ref': '#/$defs/identifier'},
                                       'enabled': {'type': 'boolean'},
                                       'key_hint': {'maxLength': 64, 'type': 'string'},
                                       'kind': {'enum': ['api_key',
                                                         'oauth',
                                                         'local_identity',
                                                         'subscription']},
                                       'provider_access_id': {'$ref': '#/$defs/identifier'},
                                       'quota_policy': {'$ref': '#/$defs/quotaPolicy'},
                                       'secret_reference': {'maxLength': 256, 'type': 'string'}},
                        'required': ['credential_id',
                                     'provider_access_id',
                                     'kind',
                                     'secret_reference',
                                     'key_hint',
                                     'enabled',
                                     'authorization',
                                     'quota_policy'],
                        'type': 'object'},
 'deployment': {'additionalProperties': False,
                'properties': {'connection_id': {'$ref': '#/$defs/identifier'},
                               'deployment_id': {'$ref': '#/$defs/identifier'},
                               'enabled': {'type': 'boolean'},
                               'identity_confidence': {'enum': ['high',
                                                                'medium',
                                                                'low',
                                                                'pending']},
                               'max_output_tokens': {'maximum': 1000000,
                                                     'minimum': 1,
                                                     'type': 'integer'},
                               'offering_id': {'$ref': '#/$defs/identifier'},
                               'priority': {'maximum': 1000000, 'minimum': 0, 'type': 'integer'},
                               'probe_status': {'enum': ['passed', 'failed', 'unprobed', 'stale']},
                               'wire_model_id': {'$ref': '#/$defs/identifier'}},
                'required': ['deployment_id',
                             'offering_id',
                             'connection_id',
                             'wire_model_id',
                             'enabled',
                             'identity_confidence',
                             'probe_status',
                             'priority'],
                'type': 'object'},
 'desktopAdapter': {'additionalProperties': False,
                    'properties': {'agent_id': {'$ref': '#/$defs/identifier'},
                                   'port': {'maximum': 65535, 'minimum': 1, 'type': 'integer'}},
                    'required': ['agent_id', 'port'],
                    'type': 'object'},
 'identifier': {'maxLength': 256,
                'minLength': 1,
                'pattern': '^[^\\u0000-\\u001f]+$',
                'type': 'string'},
 'identifierList': {'items': {'$ref': '#/$defs/identifier'},
                    'maxItems': 512,
                    'type': 'array',
                    'uniqueItems': True},
 'migrationMetadata': {'additionalProperties': False,
                       'properties': {'migrated_at': {'minimum': 0, 'type': 'number'},
                                      'receipt_id': {'$ref': '#/$defs/identifier'},
                                      'source': {'maxLength': 128, 'type': 'string'}},
                       'required': ['source', 'migrated_at', 'receipt_id'],
                       'type': 'object'},
 'model': {'additionalProperties': False,
           'properties': {'capabilities': {'$ref': '#/$defs/capabilities'},
                          'context_window': {'minimum': 1, 'type': 'integer'},
                          'creator_id': {'$ref': '#/$defs/identifier'},
                          'display_name': {'maxLength': 256, 'minLength': 1, 'type': 'string'},
                          'lifecycle': {'enum': ['stable', 'preview', 'dated_snapshot', 'retired']},
                          'list_pricing': {'$ref': '#/$defs/pricing'},
                          'model_id': {'$ref': '#/$defs/identifier'},
                          'quality_rank': {'type': 'number'},
                          'release_date': {'pattern': '^\\d{4}-\\d{2}(-\\d{2})?$',
                                           'type': 'string'}},
           'required': ['creator_id',
                        'model_id',
                        'display_name',
                        'capabilities',
                        'context_window',
                        'quality_rank'],
           'type': 'object'},
 'modelRef': {'additionalProperties': False,
              'properties': {'creator_id': {'$ref': '#/$defs/identifier'},
                             'model_id': {'$ref': '#/$defs/identifier'}},
              'required': ['creator_id', 'model_id'],
              'type': 'object'},
 'offering': {'additionalProperties': False,
              'allOf': [{'else': {'not': {'required': ['model']}, 'required': ['pending_model_id']},
                         'if': {'properties': {'identity_state': {'const': 'confirmed'}}},
                         'then': {'not': {'required': ['pending_model_id']},
                                  'required': ['model']}}],
              'properties': {'actual_pricing': {'$ref': '#/$defs/pricing'},
                             'capabilities': {'$ref': '#/$defs/capabilities'},
                             'context_window': {'minimum': 1, 'type': 'integer'},
                             'enabled': {'type': 'boolean'},
                             'identity_state': {'enum': ['confirmed', 'pending_identity']},
                             'model': {'$ref': '#/$defs/modelRef'},
                             'offering_id': {'$ref': '#/$defs/identifier'},
                             'pending_model_id': {'maxLength': 256, 'type': 'string'},
                             'priority': {'maximum': 1000000, 'minimum': 0, 'type': 'integer'},
                             'provider_access_id': {'$ref': '#/$defs/identifier'},
                             'stale': {'type': 'boolean'}},
              'required': ['offering_id',
                           'provider_access_id',
                           'identity_state',
                           'enabled',
                           'capabilities',
                           'context_window',
                           'priority'],
              'type': 'object'},
 'pricing': {'additionalProperties': False,
             'properties': {'cache_read': {'minimum': 0, 'type': 'number'},
                            'cache_write': {'minimum': 0, 'type': 'number'},
                            'currency': {'enum': ['USD', 'CNY']},
                            'input': {'minimum': 0, 'type': 'number'},
                            'output': {'minimum': 0, 'type': 'number'},
                            'unit': {'const': 'per_million_tokens'}},
             'required': ['input', 'output', 'currency', 'unit'],
             'type': 'object'},
 'provider': {'additionalProperties': False,
              'properties': {'brand': {'maxLength': 128, 'type': 'string'},
                             'name': {'maxLength': 256, 'minLength': 1, 'type': 'string'},
                             'provider_id': {'$ref': '#/$defs/identifier'},
                             'scope': {'enum': ['public', 'owner']},
                             'website': {'maxLength': 1024, 'type': 'string'}},
              'required': ['provider_id', 'name', 'scope'],
              'type': 'object'},
 'providerAccess': {'additionalProperties': False,
                    'properties': {'display_name': {'maxLength': 256, 'type': 'string'},
                                   'enabled': {'type': 'boolean'},
                                   'provider_access_id': {'$ref': '#/$defs/identifier'},
                                   'provider_id': {'$ref': '#/$defs/identifier'},
                                   'quota_policy': {'$ref': '#/$defs/quotaPolicy'}},
                    'required': ['provider_access_id', 'provider_id', 'enabled', 'quota_policy'],
                    'type': 'object'},
 'quotaPolicy': {'additionalProperties': False,
                 'properties': {'balance': {'minimum': 0, 'type': 'number'},
                                'currency': {'enum': ['USD', 'CNY']},
                                'daily_tokens': {'minimum': 0, 'type': 'integer'},
                                'rpm': {'minimum': 0, 'type': 'integer'},
                                'tpm': {'minimum': 0, 'type': 'integer'}},
                 'type': 'object'}}
OPERATIONS = {'commitModelRoutingMigration': {'method': 'POST',
                                 'path': '/api/v1/model-routing/migration/commit',
                                 'request': None,
                                 'response': 'MigrationCommitResponse',
                                 'success': 200},
 'compileProviderTemplate': {'method': 'POST',
                             'path': '/api/v1/providers/templates/compile',
                             'request': 'ProviderTemplateCompileRequest',
                             'response': 'ProviderTemplateCompileResponse',
                             'success': 200},
 'createProvider': {'method': 'POST',
                    'path': '/api/v1/providers',
                    'request': 'ProviderWriteRequest',
                    'response': 'ProviderResponse',
                    'success': 201},
 'deleteProvider': {'method': 'DELETE',
                    'path': '/api/v1/providers/{provider_id}',
                    'request': 'ProviderDeleteRequest',
                    'response': 'ProviderDeleteResponse',
                    'success': 200},
 'getModelRouting': {'method': 'GET',
                     'path': '/api/v1/model-routing',
                     'request': None,
                     'response': 'ModelRoutingAuthorityResponse',
                     'success': 200},
 'getProvider': {'method': 'GET',
                 'path': '/api/v1/providers/{provider_id}',
                 'request': None,
                 'response': 'ProviderResponse',
                 'success': 200},
 'getProviderProbeCellsStatus': {'method': 'GET',
                                 'path': '/api/v1/providers/{provider_id}/probe-cells/status',
                                 'request': None,
                                 'response': 'ProbeCellsSnapshot',
                                 'success': 200},
 'listProviderTemplates': {'method': 'GET',
                           'path': '/api/v1/providers/templates',
                           'request': None,
                           'response': 'ProviderTemplateListResponse',
                           'success': 200},
 'listProviders': {'method': 'GET',
                   'path': '/api/v1/providers',
                   'request': None,
                   'response': 'ProviderListResponse',
                   'success': 200},
 'planModelRoutingMigration': {'method': 'POST',
                               'path': '/api/v1/model-routing/migration/plan',
                               'request': None,
                               'response': 'MigrationPlanResponse',
                               'success': 200},
 'probeProvider': {'method': 'POST',
                   'path': '/api/v1/providers/probe',
                   'request': 'ProviderProbeRequest',
                   'response': 'ProviderProbeResponse',
                   'success': 200},
 'putCredentialSecret': {'method': 'PUT',
                         'path': '/api/v1/model-routing/credentials/{credential_id}/secret',
                         'request': 'CredentialSecretPutRequest',
                         'response': 'CredentialSecretPutResponse',
                         'success': 200},
 'putModelRouting': {'method': 'PUT',
                     'path': '/api/v1/model-routing',
                     'request': 'ModelRoutingPutRequest',
                     'response': 'ModelRoutingAuthorityResponse',
                     'success': 200},
 'revealCredentialSecret': {'method': 'POST',
                            'path': '/api/v1/model-routing/credentials/{credential_id}/secret/reveal',
                            'request': None,
                            'response': 'CredentialSecretRevealResponse',
                            'success': 200},
 'startProviderProbeCells': {'method': 'POST',
                             'path': '/api/v1/providers/{provider_id}/probe-cells/start',
                             'request': 'ProbeCellsStartRequest',
                             'response': 'ProbeCellsSnapshot',
                             'success': 200},
 'updateProvider': {'method': 'PATCH',
                    'path': '/api/v1/providers/{provider_id}',
                    'request': 'ProviderWriteRequest',
                    'response': 'ProviderResponse',
                    'success': 200}}

class ContractViolation(ValueError):
    def __init__(self, schema_name: str, violations: list[str]):
        self.schema_name = schema_name
        self.violations = tuple(violations)
        super().__init__(
            f"{schema_name} contract violation: " + "; ".join(violations[:3])
        )


def _json_values_equal(left: Any, right: Any) -> bool:
    if left is right or left == right:
        if isinstance(left, bool) != isinstance(right, bool):
            return False
        return type(left) is type(right) or not isinstance(
            left, (int, float),
        )
    return False


def _resolve_ref(ref: str) -> Mapping[str, Any] | None:
    local_prefix = "#/components/schemas/"
    defs_prefix = "#/$defs/"
    if ref.startswith(local_prefix):
        return OPENAPI_SCHEMAS.get(ref[len(local_prefix):])
    if ref.startswith(defs_prefix):
        return EXTERNAL_DEFS.get(ref[len(defs_prefix):])
    return None


def _validate(schema_value: Any, value: Any, path: str) -> list[str]:
    schema = schema_value if isinstance(schema_value, Mapping) else {}
    ref = schema.get("$ref")
    if isinstance(ref, str):
        target = _resolve_ref(ref)
        return (
            _validate(target, value, path)
            if target is not None
            else [f"{path}: unknown schema reference"]
        )
    errors: list[str] = []
    variants = schema.get("oneOf")
    if isinstance(variants, list):
        matches = sum(not _validate(item, value, path) for item in variants)
        if matches != 1:
            errors.append(f"{path}: expected exactly one variant")
    variants = schema.get("anyOf")
    if isinstance(variants, list) and not any(
        not _validate(item, value, path) for item in variants
    ):
        errors.append(f"{path}: expected a declared variant")
    conjunction = schema.get("allOf")
    if isinstance(conjunction, list):
        for item in conjunction:
            errors.extend(_validate(item, value, path))
    condition = schema.get("if")
    if isinstance(condition, Mapping):
        branch = schema.get("then") if not _validate(condition, value, path) \
            else schema.get("else")
        if isinstance(branch, Mapping):
            errors.extend(_validate(branch, value, path))
    negation = schema.get("not")
    if isinstance(negation, Mapping) and not _validate(negation, value, path):
        errors.append(f"{path}: value matches a forbidden shape")
    if errors:
        return errors
    if "const" in schema and not _json_values_equal(value, schema["const"]):
        return [f"{path}: unexpected constant value"]
    choices = schema.get("enum")
    if isinstance(choices, list) and not any(
        _json_values_equal(value, choice) for choice in choices
    ):
        return [f"{path}: value is outside the declared vocabulary"]
    kind = schema.get("type")
    if kind == "null":
        return [] if value is None else [f"{path}: expected null"]
    if kind == "string":
        if not isinstance(value, str):
            return [f"{path}: expected string"]
        if isinstance(schema.get("minLength"), int) \
                and len(value) < schema["minLength"]:
            return [f"{path}: string is too short"]
        if isinstance(schema.get("maxLength"), int) \
                and len(value) > schema["maxLength"]:
            return [f"{path}: string is too long"]
        pattern = schema.get("pattern")
        if isinstance(pattern, str):
            try:
                matches = re.search(pattern, value)
            except re.error:
                return [f"{path}: contract has an invalid string pattern"]
            if matches is None:
                return [f"{path}: string does not match the declared pattern"]
        return []
    if kind in {"integer", "number"}:
        if (not isinstance(value, (int, float)) or isinstance(value, bool)
                or (kind == "integer" and not isinstance(value, int))):
            return [f"{path}: expected {kind}"]
        if isinstance(schema.get("minimum"), (int, float)) \
                and not isinstance(schema["minimum"], bool) \
                and value < schema["minimum"]:
            return [f"{path}: number is below minimum"]
        if isinstance(schema.get("maximum"), (int, float)) \
                and not isinstance(schema["maximum"], bool) \
                and value > schema["maximum"]:
            return [f"{path}: number is above maximum"]
        return []
    if kind == "boolean":
        return [] if isinstance(value, bool) else [f"{path}: expected boolean"]
    if kind == "array":
        if not isinstance(value, list):
            return [f"{path}: expected array"]
        if isinstance(schema.get("maxItems"), int) \
                and len(value) > schema["maxItems"]:
            return [f"{path}: array is too large"]
        if schema.get("uniqueItems") is True:
            for index, item in enumerate(value):
                if any(
                    _json_values_equal(item, other)
                    for other in value[index + 1:]
                ):
                    return [f"{path}: array items are not unique"]
        errors = []
        for index, item in enumerate(value):
            errors.extend(
                _validate(schema.get("items", {}), item, f"{path}[{index}]")
            )
        return errors
    if kind == "object" or any(
        keyword in schema
        for keyword in (
            "properties",
            "required",
            "minProperties",
            "maxProperties",
            "propertyNames",
            "additionalProperties",
        )
    ):
        if not isinstance(value, Mapping):
            # Applicator keywords ignore non-object instances unless the
            # schema explicitly requires an object.
            return [] if kind != "object" else [f"{path}: expected object"]
        properties = schema.get("properties")
        properties = properties if isinstance(properties, Mapping) else {}
        errors = []
        if isinstance(schema.get("minProperties"), int) \
                and len(value) < schema["minProperties"]:
            errors.append(f"{path}: object has too few properties")
        if isinstance(schema.get("maxProperties"), int) \
                and len(value) > schema["maxProperties"]:
            errors.append(f"{path}: object has too many properties")
        property_names = schema.get("propertyNames")
        if isinstance(property_names, Mapping):
            for field in value:
                errors.extend(
                    _validate(property_names, field, f"{path}.{field}")
                )
        for field in schema.get("required") or []:
            if isinstance(field, str) and field not in value:
                errors.append(f"{path}.{field}: required")
        for field, child in properties.items():
            if field in value:
                errors.extend(_validate(child, value[field], f"{path}.{field}"))
        if schema.get("additionalProperties") is False:
            errors.extend(
                f"{path}.{field}: undeclared field"
                for field in value
                if field not in properties
            )
        elif isinstance(schema.get("additionalProperties"), Mapping):
            additional_schema = schema["additionalProperties"]
            for field, child_value in value.items():
                if field not in properties:
                    errors.extend(
                        _validate(
                            additional_schema, child_value, f"{path}.{field}",
                        )
                    )
        return errors
    return []


def violations(schema_name: str, value: Any) -> list[str]:
    schema = OPENAPI_SCHEMAS.get(schema_name)
    if schema is None:
        return ["schema is not registered"]
    return _validate(schema, value, "$")


def decode(schema_name: str, value: Any) -> Any:
    found = violations(schema_name, value)
    if found:
        raise ContractViolation(schema_name, found)
    return value


def decode_request(operation_id: str, value: Any) -> Any:
    spec = OPERATIONS.get(operation_id)
    if spec is None or spec["request"] is None:
        raise ContractViolation(operation_id, ["operation has no request schema"])
    return decode(spec["request"], value)


def decode_response(operation_id: str, value: Any) -> Any:
    spec = OPERATIONS.get(operation_id)
    if spec is None:
        raise ContractViolation(operation_id, ["operation is not registered"])
    return decode(spec["response"], value)


__all__ = [
    "CONTRACT_ID",
    "EXTERNAL_DEFS",
    "OPENAPI_SCHEMAS",
    "OPERATIONS",
    "ROUTES_BLUEPRINT",
    "ContractViolation",
    "decode",
    "decode_request",
    "decode_response",
    "violations",
]
