# Generated by scripts/gen_api_v4_contract.py; DO NOT EDIT.
"""Dependency-free API v4 release constants for the server boot boundary."""

API_CONTRACT_ID = 'tofu.api/v4'
API_MAJOR = 4
API_RELEASE_STAGE = 'bootstrap'
MIN_DESKTOP_BUILD = '0.16.0'
MIN_ANDROID_BUILD = 17
LEGACY_API_PREFIXES = ('/api/v1', '/api/v3')
LEGACY_UPGRADE_STATUS = 426
UPGRADE_URL = '/api/v4/meta'
