"""Shared bounds for owner-scoped recent-project navigation writes."""

RECENT_PROJECT_PATH_MAX_CHARS = 4096
RECENT_PROJECT_TOUCH_BATCH_LIMIT = 32
PROJECT_RELINK_CONVERSATION_LIMIT = 10_000
PROJECT_RELINK_STORAGE_DEADLINE_SECONDS = 120.0


__all__ = [
    "PROJECT_RELINK_CONVERSATION_LIMIT",
    "PROJECT_RELINK_STORAGE_DEADLINE_SECONDS",
    "RECENT_PROJECT_PATH_MAX_CHARS",
    "RECENT_PROJECT_TOUCH_BATCH_LIMIT",
]
