/* ===== migrated source: settings/provider_templates.js ===== */
/* Provider onboarding recipes and their optional external loader.
 * Depends on the shared runtime scope and Api.providers.templates. */

const _PROVIDER_TEMPLATES = [
  {
    key: 'minimax', brand: 'minimax', category: 'official',
    name: 'MiniMax',
    base_url: 'https://api.minimax.chat/v1',
    balance_url: '',
    offering_recipes: [
      { model_id: 'MiniMax-M3',             capabilities: ['text', 'vision', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2.7',           capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2.7-highspeed', capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2.5',           capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2.5-highspeed', capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2.1',           capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2.1-highspeed', capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'MiniMax-M2',             capabilities: ['text', 'vision', 'cheap'],    rpm: 60 },
      { model_id: 'M2-her',                 capabilities: ['text', 'cheap'],              rpm: 60 },
    ],
  },
  {
    key: 'glm', brand: 'glm', category: 'official',
    name: 'GLM (Zhipu AI)',
    base_url: 'https://open.bigmodel.cn/api/paas/v4',
    balance_url: 'https://open.bigmodel.cn/api/paas/v4/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'glm-5.3',         capabilities: ['text', 'thinking'],  rpm: 60,
        context_window: 1000000,
        pricing: { input: 3.45, output: 13.81, currency: 'USD', cacheWriteMul: 1.0, cacheReadMul: 0.1, name: 'GLM-5.3' } },
      { model_id: 'glm-5.2',         capabilities: ['text', 'thinking'],  rpm: 60 },
      { model_id: 'glm-5.1',         capabilities: ['text', 'thinking'],  rpm: 60 },
      { model_id: 'glm-5',           capabilities: ['text', 'thinking'],  rpm: 60 },
      { model_id: 'glm-4.7',         capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'glm-4.5-air',     capabilities: ['text', 'cheap'],     rpm: 120 },
      { model_id: 'glm-4.5-flash',   capabilities: ['text', 'cheap'],     rpm: 200 },
    ],
  },
  {
    key: 'kimi', brand: 'kimi', category: 'official',
    name: 'Moonshot (Kimi)',
    base_url: 'https://api.moonshot.ai/v1',
    balance_url: '',
    offering_recipes: [
      { model_id: 'kimi-k3',                  capabilities: ['text', 'vision', 'video', 'thinking', 'cheap'], rpm: 60 },
      { model_id: 'kimi-k2.6',                capabilities: ['text', 'vision', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'kimi-k2.5',                capabilities: ['text', 'vision', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'kimi-k2-0905-preview',     capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'kimi-k2-thinking',         capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'kimi-k2-turbo-preview',    capabilities: ['text', 'cheap'],                        rpm: 60 },
      { model_id: 'kimi-k2-thinking-turbo',   capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'kimi-k2-0711-preview',     capabilities: ['text', 'cheap'],                        rpm: 60 },
    ],
  },
  {
    key: 'deepseek', brand: 'deepseek', category: 'official',
    name: 'DeepSeek',
    base_url: 'https://api.deepseek.com',
    balance_url: 'https://api.deepseek.com/user/balance',
    offering_recipes: [
      { model_id: 'deepseek-v4-pro',   capabilities: ['text', 'thinking', 'cheap'],  rpm: 30 },
      { model_id: 'deepseek-v4-flash', capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'deepseek-chat',     capabilities: ['text', 'cheap'],                       rpm: 60 },
      { model_id: 'deepseek-reasoner', capabilities: ['text', 'thinking', 'cheap'],           rpm: 30 },
    ],
  },
  {
    key: 'openai', brand: 'openai', category: 'official',
    name: 'OpenAI',
    base_url: 'https://api.openai.com/v1',
    balance_url: 'https://api.openai.com/v1/dashboard/billing/subscription',
    protocol: 'responses',
    responses_profile: 'openai',
    offering_recipes: [
      { model_id: 'gpt-5.6',       capabilities: ['text', 'vision', 'thinking'],            rpm: 30 },
      { model_id: 'gpt-5.6-sol',   capabilities: ['text', 'vision', 'thinking'],            rpm: 30 },
      { model_id: 'gpt-5.6-terra', capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 60 },
      { model_id: 'gpt-5.6-luna',  capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 200 },
      { model_id: 'gpt-5.4',       capabilities: ['text', 'vision', 'thinking'],   rpm: 30 },
      { model_id: 'gpt-5.4-mini',  capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 60 },
      { model_id: 'o3',            capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 30 },
      { model_id: 'o4-mini',       capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 30 },
      { model_id: 'gpt-4.1',       capabilities: ['text', 'vision', 'cheap'],               rpm: 30 },
      { model_id: 'gpt-4.1-mini',  capabilities: ['text', 'vision', 'cheap'],      rpm: 60 },
      { model_id: 'gpt-4o-transcribe',      capabilities: ['transcription'],        rpm: 60 },
      { model_id: 'gpt-4o-mini-transcribe', capabilities: ['transcription'],        rpm: 60 },
      { model_id: 'gpt-image-2',   capabilities: ['image_gen'],                    rpm: 10 },
      { model_id: 'gpt-image-1.5', capabilities: ['image_gen'],                    rpm: 10 },
      { model_id: 'gpt-image-1',   capabilities: ['image_gen'],                    rpm: 10 },
    ],
  },
  {
    key: 'groq', brand: 'groq', category: 'official',
    name: 'Groq',
    base_url: 'https://api.groq.com/openai/v1',
    balance_url: '',
    offering_recipes: [
      { model_id: 'whisper-large-v3-turbo', capabilities: ['transcription'],                    rpm: 120 },
      { model_id: 'whisper-large-v3',       capabilities: ['transcription'],                    rpm: 120 },
      { model_id: 'llama-3.3-70b-versatile', capabilities: ['text', 'cheap'],                   rpm: 60 },
    ],
  },
  {
    key: 'anthropic', brand: 'claude', category: 'official',
    name: 'Anthropic',
    base_url: 'https://api.anthropic.com/v1',
    balance_url: 'https://api.anthropic.com/v1/dashboard/billing/subscription',
    protocol: 'anthropic',
    offering_recipes: [
      { model_id: 'fable-5',                     capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-opus-4-8',            capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-opus-4-7',            capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-opus-4-6',            capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-sonnet-4-6',           capabilities: ['text', 'vision', 'thinking'], rpm: 50 },
      { model_id: 'claude-sonnet-4-5',           capabilities: ['text', 'vision', 'thinking'], rpm: 50 },
      { model_id: 'claude-opus-4-5',             capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-haiku-4-5',            capabilities: ['text', 'vision', 'cheap'],    rpm: 100 },
    ],
  },
  {
    key: 'bedrock', brand: 'bedrock', category: 'official',
    name: 'Amazon Bedrock (OpenAI-compat)',
    // Replace <region> with your AWS region (us-east-1, us-west-2, eu-west-1, etc.)
    // Authenticate with an Amazon Bedrock API key (Bearer token).
    base_url: 'https://bedrock-runtime.us-east-1.amazonaws.com/openai/v1',
    balance_url: '',
    offering_recipes: [
      { model_id: 'fable-5', request_ids: ['us.anthropic.fable-5-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-opus-4-8', request_ids: ['us.anthropic.claude-opus-4-8-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-opus-4-7', request_ids: ['us.anthropic.claude-opus-4-7-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-opus-4-6', request_ids: ['us.anthropic.claude-opus-4-6-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-sonnet-4-6', request_ids: ['us.anthropic.claude-sonnet-4-6-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 50 },
      { model_id: 'claude-sonnet-4-5', request_ids: ['us.anthropic.claude-sonnet-4-5-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 50 },
      { model_id: 'claude-opus-4-5', request_ids: ['us.anthropic.claude-opus-4-5-v1:0'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-haiku-4-5', request_ids: ['us.anthropic.claude-haiku-4-5-v1:0'], capabilities: ['text', 'vision', 'cheap'], rpm: 100 },
      { model_id: 'openai.gpt-oss-120b-1:0',                capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'openai.gpt-oss-20b-1:0',                 capabilities: ['text', 'cheap'],              rpm: 120 },
    ],
  },
  {
    key: 'doubao', brand: 'doubao', category: 'official',
    name: 'Doubao (Volcengine)',
    base_url: 'https://ark.cn-beijing.volces.com/api/v3',
    balance_url: 'https://ark.cn-beijing.volces.com/api/v3/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'doubao-seed-2-0-pro-260215',           capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 60 },
      { model_id: 'doubao-seed-2-0-lite-260215',          capabilities: ['text', 'cheap'],              rpm: 120 },
      { model_id: 'doubao-seed-2-0-code-preview-260215',  capabilities: ['text', 'thinking', 'cheap'],           rpm: 60 },
      { model_id: 'doubao-seed-1.8-thinking',              capabilities: ['text', 'thinking', 'cheap'],           rpm: 60 },
      { model_id: 'doubao-seed-1.6-thinking',              capabilities: ['text', 'thinking', 'cheap'],           rpm: 60 },
      { model_id: 'doubao-seed-1.6',                       capabilities: ['text', 'cheap'],                       rpm: 120 },
    ],
  },
  {
    key: 'mistral', brand: 'mistral', category: 'official',
    name: 'Mistral AI',
    base_url: 'https://api.mistral.ai/v1',
    balance_url: 'https://api.mistral.ai/v1/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'mistral-large-latest',   capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'mistral-small-latest',   capabilities: ['text', 'cheap'],              rpm: 60 },
      { model_id: 'codestral-latest',       capabilities: ['text', 'cheap'],                       rpm: 60 },
    ],
  },
  {
    key: 'xai', brand: 'grok', category: 'official',
    name: 'xAI (Grok)',
    base_url: 'https://api.x.ai/v1',
    balance_url: 'https://api.x.ai/v1/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'grok-4.20',      capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'grok-4',         capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'grok-4.1',       capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'grok-4.1-mini',  capabilities: ['text', 'vision', 'cheap'],    rpm: 60 },
      { model_id: 'grok-3',         capabilities: ['text', 'thinking'],           rpm: 30 },
      { model_id: 'grok-3-mini',    capabilities: ['text', 'thinking', 'cheap'],  rpm: 60 },
    ],
  },
  {
    key: 'qwen', brand: 'qwen', category: 'official',
    name: 'Qwen (DashScope)',
    base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    balance_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'qwen3-max',              capabilities: ['text', 'thinking', 'cheap'],                rpm: 30 },
      { model_id: 'qwen-plus',              capabilities: ['text', 'thinking', 'cheap'],                rpm: 60 },
      { model_id: 'qwen-max',               capabilities: ['text', 'cheap'],                            rpm: 30 },
      { model_id: 'qwq-plus',               capabilities: ['text', 'thinking', 'cheap'],                rpm: 60 },
      { model_id: 'qwen-turbo',             capabilities: ['text', 'cheap'],                   rpm: 200 },
      { model_id: 'MiniMax-M2.1',           capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax-M2.5',           capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax/MiniMax-M2.1',   capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax/MiniMax-M2.5',   capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax/MiniMax-M2.7',   capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax/speech-02-hd',   capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax/speech-02-turbo', capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'MiniMax/speech-2.8-hd',  capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'MiniMax/speech-2.8-turbo', capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'codeqwen1.5-7b-chat',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1',            capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1-distill-llama-70b', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1-distill-llama-8b', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1-distill-qwen-1.5b', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1-distill-qwen-14b', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1-distill-qwen-32b', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-r1-distill-qwen-7b', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-v3',            capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-v3.1',          capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'deepseek-v3.2',          capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'glm-4.7',                capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'glm-5',                  capabilities: ['text'],                   rpm: 60 },
      { model_id: 'gui-plus',               capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'kimi-k3',                capabilities: ['cheap', 'text', 'vision', 'video', 'thinking'], rpm: 60 },
      { model_id: 'kimi/kimi-k3',           capabilities: ['cheap', 'text', 'vision', 'video', 'thinking'], rpm: 60 },
      { model_id: 'kimi-k2-thinking',       capabilities: ['cheap', 'text', 'thinking'],       rpm: 60 },
      { model_id: 'kimi-k2.5',              capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'kimi/kimi-k2.5',         capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qvq-max',                capabilities: ['cheap', 'text'],                   rpm: 30 },
      { model_id: 'qvq-max-2025-05-15',     capabilities: ['text'],                            rpm: 30 },
      { model_id: 'qvq-plus',               capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qvq-plus-2025-05-15',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-1.8b-chat',         capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-1.8b-longcontext-chat', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-14b-chat',          capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-72b-chat',          capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-7b-chat',           capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-coder-plus',        capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-coder-plus-1106',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-coder-plus-latest', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-coder-turbo',       capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-coder-turbo-0919',  capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-coder-turbo-latest', capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-deep-research-2025-12-15', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-deep-search-planning', capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen-flash',             capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen-flash-character',   capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen-flash-character-2026-02-26', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen-long',              capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-math-plus',         capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-math-plus-0919',    capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-math-plus-latest',  capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-math-turbo',        capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-math-turbo-0919',   capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-math-turbo-latest', capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-max-0107',          capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-max-0428',          capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-max-0919',          capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-max-1201',          capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-max-2025-01-25',    capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-max-latest',        capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-max-longcontext',   capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-mt-flash',          capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen-mt-lite',           capabilities: ['cheap', 'text'],                   rpm: 120 },
      { model_id: 'qwen-mt-plus',           capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-mt-turbo',          capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-omni-turbo',        capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-plus-2025-01-25',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-plus-2025-04-28',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-plus-2025-07-14',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-plus-2025-09-11',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-plus-2025-11-05',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-plus-2025-12-01',   capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-plus-latest',       capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-tts-2025-05-22',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen-turbo-0919',        capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-turbo-2024-11-01',  capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-turbo-2025-04-28',  capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-turbo-2025-07-15',  capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-turbo-latest',      capabilities: ['cheap', 'text'],                   rpm: 200 },
      { model_id: 'qwen-vl-max',            capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-vl-max-2025-04-02', capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-vl-max-2025-04-08', capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-vl-max-latest',     capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen-vl-ocr',            capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-ocr-2025-11-20', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-ocr-latest',     capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-plus',           capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-plus-2025-01-25', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-plus-2025-05-07', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-plus-2025-08-15', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen-vl-plus-latest',    capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen1.5-0.5b-chat',      capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen1.5-1.8b-chat',      capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen1.5-110b-chat',      capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen1.5-14b-chat',       capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen1.5-32b-chat',       capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen1.5-72b-chat',       capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen1.5-7b-chat',        capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2-0.5b-instruct',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2-1.5b-instruct',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2-57b-a14b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2-7b-instruct',      capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-0.5b-instruct',  capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-1.5b-instruct',  capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-14b-instruct',   capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-14b-instruct-1m', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-32b-instruct',   capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-3b-instruct',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-72b-instruct',   capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-7b-instruct',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-7b-instruct-1m', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-coder-14b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-coder-32b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-coder-7b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-math-1.5b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-math-72b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-math-7b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen2.5-vl-32b-instruct', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3-0.6b',             capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen3-1.7b',             capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-14b',              capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-235b-a22b',        capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-235b-a22b-instruct-2507', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-235b-a22b-thinking-2507', capabilities: ['cheap', 'text', 'thinking'],       rpm: 60 },
      { model_id: 'qwen3-30b-a3b',          capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-30b-a3b-instruct-2507', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-30b-a3b-thinking-2507', capabilities: ['cheap', 'text', 'thinking'],       rpm: 60 },
      { model_id: 'qwen3-32b',              capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-4b',               capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen3-8b',               capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-asr-flash-2026-02-10', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-asr-flash-realtime', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-asr-flash-realtime-2025-10-27', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-asr-flash-realtime-2026-02-10', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-coder-480b-a35b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-coder-flash',      capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-coder-next',       capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-coder-plus',       capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3-coder-plus-2025-07-22', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3-coder-plus-2025-09-23', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3-livetranslate-flash', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-livetranslate-flash-2025-12-01', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-livetranslate-flash-realtime', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-livetranslate-flash-realtime-2025-09-22', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-max-2025-09-23',   capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen3-max-2026-01-23',   capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen3-max-preview',      capabilities: ['cheap', 'text', 'vision'],         rpm: 30 },
      { model_id: 'qwen3-next-80b-a3b-instruct', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-next-80b-a3b-thinking', capabilities: ['cheap', 'text', 'thinking'],       rpm: 60 },
      { model_id: 'qwen3-omni-flash',       capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-omni-flash-2025-09-15', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-omni-flash-2025-12-01', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-omni-flash-realtime', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-omni-flash-realtime-2025-09-15', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-omni-flash-realtime-2025-12-01', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-s2s-flash-realtime-2025-09-22', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-flash',        capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-flash-2025-09-18', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-flash-2025-11-27', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-flash-realtime', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-flash-realtime-2025-09-18', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-flash-realtime-2025-11-27', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-instruct-flash', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-instruct-flash-2026-01-26', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-instruct-flash-realtime', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-instruct-flash-realtime-2026-01-22', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3-tts-vc-2026-01-22', capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen3-tts-vc-realtime-2025-11-27', capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen3-tts-vc-realtime-2026-01-15', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-tts-vd-2026-01-26', capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen3-tts-vd-realtime-2025-12-16', capabilities: ['text', 'cheap'],                            rpm: 60 },
      { model_id: 'qwen3-tts-vd-realtime-2026-01-15', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3-vl-flash',         capabilities: ['cheap', 'text', 'vision'],         rpm: 100 },
      { model_id: 'qwen3-vl-flash-2025-10-15', capabilities: ['cheap', 'text', 'vision'],         rpm: 100 },
      { model_id: 'qwen3-vl-flash-2026-01-22', capabilities: ['cheap', 'text', 'vision'],         rpm: 100 },
      { model_id: 'qwen3-vl-plus',          capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3-vl-plus-2025-09-23', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3-vl-plus-2025-12-19', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3.5-122b-a10b',      capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3.5-27b',            capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3.5-35b-a3b',        capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3.5-397b-a17b',      capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'qwen3.5-flash',          capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3.5-flash-2026-02-23', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'qwen3.5-plus',           capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3.5-plus-2026-02-15', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3.6-plus',           capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3.6-plus-2026-04-02', capabilities: ['cheap', 'text', 'vision'],         rpm: 60 },
      { model_id: 'qwen3.7-max',            capabilities: ['text', 'thinking'],                rpm: 30 },
      { model_id: 'qwen3.7-max-2026-05-20', capabilities: ['text', 'thinking'],                rpm: 30 },
      { model_id: 'qwen3.7-plus',           capabilities: ['cheap', 'text', 'vision', 'thinking'], rpm: 60 },
      { model_id: 'qwq-plus-2025-03-05',    capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'siliconflow/deepseek-r1-0528', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'siliconflow/deepseek-v3-0324', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'siliconflow/deepseek-v3.1-terminus', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'siliconflow/deepseek-v3.2', capabilities: ['cheap', 'text'],                   rpm: 60 },
      { model_id: 'tongyi-xiaomi-analysis-flash', capabilities: ['cheap', 'text'],                   rpm: 100 },
      { model_id: 'tongyi-xiaomi-analysis-pro', capabilities: ['cheap', 'text'],                   rpm: 30 },
      { model_id: 'qwen-image-2.0',         capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-2.0-2026-03-03', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-2.0-pro',     capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-2.0-pro-2026-03-03', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-edit-max',    capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-edit-max-2026-01-16', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-edit-plus',   capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-edit-plus-2025-10-30', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-edit-plus-2025-12-15', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-max',         capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-max-2025-12-30', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'qwen-image-plus-2026-01-09', capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'wan2.7-image',           capabilities: ['image_gen'],                       rpm: 10 },
      { model_id: 'wan2.7-image-pro',       capabilities: ['cheap', 'image_gen'],              rpm: 10 },
      { model_id: 'z-image-turbo',          capabilities: ['cheap', 'image_gen'],              rpm: 10 },
    ],
  },
  {
    key: 'gemini', brand: 'gemini', category: 'official',
    name: 'Google Gemini',
    base_url: 'https://generativelanguage.googleapis.com/v1beta/openai',
    balance_url: '',
    offering_recipes: [
      { model_id: 'gemini-3.1-pro-preview',       capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 15 },
      { model_id: 'gemini-3-flash-preview',        capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'gemini-3.1-flash-lite-preview', capabilities: ['text', 'cheap'],              rpm: 200 },
      { model_id: 'gemini-2.5-pro',                capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'gemini-2.5-flash',              capabilities: ['text', 'vision', 'cheap'],    rpm: 100 },
      { model_id: 'gemini-2.5-flash-lite',         capabilities: ['text', 'cheap'],              rpm: 200 },
    ],
  },
  {
    key: 'openrouter', brand: 'openrouter', category: 'relay',
    name: 'OpenRouter',
    base_url: 'https://openrouter.ai/api/v1',
    balance_url: 'https://openrouter.ai/api/v1/credits',
    offering_recipes: [
      { model_id: 'claude-opus-4-6', request_ids: ['anthropic/claude-opus-4.6'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'claude-sonnet-4-6', request_ids: ['anthropic/claude-sonnet-4.6'], capabilities: ['text', 'vision', 'thinking'], rpm: 50 },
      { model_id: 'gpt-5.6', request_ids: ['openai/gpt-5.6'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'gemini-3.1-pro-preview', request_ids: ['google/gemini-3.1-pro-preview'], capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 15 },
      { model_id: 'gemini-2.5-flash', request_ids: ['google/gemini-2.5-flash'], capabilities: ['text', 'vision', 'cheap'], rpm: 100 },
      { model_id: 'grok-4.20', request_ids: ['x-ai/grok-4.20'], capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'grok-4', request_ids: ['x-ai/grok-4'], capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'deepseek-chat', request_ids: ['deepseek/deepseek-chat'], capabilities: ['text', 'cheap'], rpm: 60 },
      { model_id: 'deepseek-r1', request_ids: ['deepseek/deepseek-r1'], capabilities: ['text', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'o3', request_ids: ['openai/o3'], capabilities: ['text', 'vision', 'thinking'], rpm: 30 },
      { model_id: 'gpt-5.4-mini', request_ids: ['openai/gpt-5.4-mini'], capabilities: ['text', 'vision', 'cheap'], rpm: 60 },
      { model_id: 'openai/gpt-5.4-image-2',            capabilities: ['image_gen'],                   rpm: 10 },
      { model_id: 'openai/gpt-5-image',                capabilities: ['image_gen'],                   rpm: 10 },
      { model_id: 'openai/gpt-5-image-mini',           capabilities: ['image_gen'],                   rpm: 15 },
      { model_id: 'google/gemini-3-pro-image-preview', capabilities: ['image_gen'],                   rpm: 10 },
      { model_id: 'google/gemini-2.5-flash-image',     capabilities: ['image_gen'],                   rpm: 10 },
    ],
  },
  {
    key: 'mimo', brand: 'mimo', category: 'official',
    name: 'Xiaomi MiMo',
    base_url: 'https://api.xiaomimimo.com/v1',
    balance_url: 'https://api.xiaomimimo.com/v1/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'MiMo-V2-Pro',    capabilities: ['text', 'vision', 'thinking', 'cheap'], rpm: 30 },
      { model_id: 'MiMo-V2-Omni',   capabilities: ['text', 'vision', 'cheap'],             rpm: 60 },
      { model_id: 'MiMo-V2-Flash',  capabilities: ['text', 'cheap'],              rpm: 200 },
    ],
  },
  {
    key: 'qianfan', brand: 'baiducloud', category: 'official',
    name: 'Baidu Qianfan (百度千帆)',
    base_url: 'https://qianfan.baidubce.com/v2',
    balance_url: '',
    offering_recipes: [
      { model_id: 'ernie-5.0',                       capabilities: ['text', 'vision', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'ernie-5.0-thinking-preview',      capabilities: ['text', 'vision', 'thinking', 'cheap'],  rpm: 60 },
      { model_id: 'ernie-x1.1',                      capabilities: ['text', 'thinking', 'cheap'],            rpm: 300 },
      { model_id: 'ernie-x1-turbo-32k',              capabilities: ['text', 'thinking', 'cheap'],            rpm: 900 },
      { model_id: 'ernie-4.5-turbo-128k',            capabilities: ['text', 'cheap'],                        rpm: 5000 },
      { model_id: 'ernie-4.5-turbo-vl',              capabilities: ['text', 'vision', 'cheap'],              rpm: 1000 },
      { model_id: 'ernie-speed-pro-128k',             capabilities: ['text', 'cheap'],               rpm: 10000 },
      { model_id: 'ernie-lite-pro-128k',              capabilities: ['text', 'cheap'],               rpm: 10000 },
      { model_id: 'deepseek-r1',                      capabilities: ['text', 'thinking', 'cheap'],            rpm: 5000 },
      { model_id: 'deepseek-v3',                      capabilities: ['text', 'cheap'],                        rpm: 5000 },
      { model_id: 'deepseek-v3.2',                    capabilities: ['text', 'cheap'],                        rpm: 5000 },
      { model_id: 'deepseek-v3.2-think',              capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'qwen3.5-397b-a17b',               capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'qwen3-235b-a22b-instruct-2507',   capabilities: ['text', 'cheap'],                        rpm: 60 },
      { model_id: 'qwen3-coder-480b-a35b-instruct',  capabilities: ['text', 'cheap'],                        rpm: 60 },
      { model_id: 'glm-5.1',                          capabilities: ['text', 'thinking'],            rpm: 60 },
      { model_id: 'kimi-k3',                          capabilities: ['text', 'vision', 'video', 'thinking', 'cheap'], rpm: 60 },
      { model_id: 'kimi-k2.5',                        capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'minimax-m2.5',                     capabilities: ['text', 'thinking', 'cheap'],            rpm: 60 },
      { model_id: 'qwen3-embedding-8b',               capabilities: ['embedding'],                   rpm: 60 },
      { model_id: 'bge-large-zh',                     capabilities: ['embedding'],                   rpm: 60 },
    ],
  },
  {
    key: 'shubiaobiao', brand: 'shubiaobiao', category: 'relay',
    name: 'ShuBiaoBiao (数标标)',
    base_url: 'https://api.shubiaobiao.com/v1',
    balance_url: '',
    offering_recipes: [
      { model_id: 'deepseek-r1',                     capabilities: ['text', 'thinking', 'cheap'],             rpm: 60 },
      { model_id: 'deepseek-v3',                     capabilities: ['text', 'cheap'],                         rpm: 60 },
      { model_id: 'deepseek-chat',                   capabilities: ['text', 'cheap'],                         rpm: 60 },
      { model_id: 'gpt-4o',                          capabilities: ['text', 'vision', 'cheap'],               rpm: 60 },
      { model_id: 'gpt-4o-mini',                     capabilities: ['text', 'vision', 'cheap'],      rpm: 120 },
      { model_id: 'gpt-4.5-preview',                 capabilities: ['text', 'vision'],               rpm: 30 },
      { model_id: 'gpt-4-turbo',                     capabilities: ['text', 'vision'],               rpm: 30 },
      { model_id: 'o1',                              capabilities: ['text', 'thinking'],             rpm: 30 },
      { model_id: 'o1-mini',                         capabilities: ['text', 'thinking', 'cheap'],    rpm: 60 },
      { model_id: 'o3-mini',                         capabilities: ['text', 'thinking', 'cheap'],    rpm: 60 },
      { model_id: 'gpt-3.5-turbo',                   capabilities: ['text', 'cheap'],                rpm: 200 },
      { model_id: 'claude-opus-4-6',                 capabilities: ['text', 'vision', 'thinking'],   rpm: 30 },
      { model_id: 'claude-sonnet-4-6',               capabilities: ['text', 'vision', 'thinking'],   rpm: 50 },
      { model_id: 'claude-sonnet-4-5',               capabilities: ['text', 'vision', 'thinking'],   rpm: 50 },
      { model_id: 'claude-haiku-4-5',                capabilities: ['text', 'vision', 'cheap'],      rpm: 100 },
      { model_id: 'gemini-2.5-pro',                  capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 30 },
      { model_id: 'gemini-2.5-flash',                capabilities: ['text', 'vision', 'cheap'],      rpm: 120 },
      { model_id: 'grok-4.20',                       capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 30 },
      { model_id: 'grok-4',                          capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 30 },
    ],
  },
  {
    key: 'yeysai', brand: 'tsinghua', category: 'relay',
    name: 'YEYSAI (THUNLP / Tsinghua)',
    base_url: 'https://yeysai.com/v1',
    balance_url: 'https://yeysai.com/v1/dashboard/billing/subscription',
    offering_recipes: [
      { model_id: 'claude-opus-4-6-thinking',       capabilities: ['text', 'vision', 'thinking'],   rpm: 30 },
      { model_id: 'claude-opus-4-6',                 capabilities: ['text', 'vision'],               rpm: 30 },
      { model_id: 'gpt-5.4',                         capabilities: ['text', 'vision'],               rpm: 60 },
      { model_id: 'gpt-5.4-pro',                     capabilities: ['text', 'vision', 'thinking'],   rpm: 20 },
      { model_id: 'gpt-5.4-mini',                    capabilities: ['text', 'vision', 'cheap'],      rpm: 120 },
      { model_id: 'gpt-5.4-nano',                    capabilities: ['text', 'cheap'],                rpm: 200 },
      { model_id: 'gemini-3.1-pro-preview-thinking',  capabilities: ['text', 'vision', 'thinking', 'cheap'],   rpm: 30 },
      { model_id: 'gemini-3.1-flash-lite-preview',    capabilities: ['text', 'cheap'],                rpm: 200 },
      { model_id: 'gemini-3-pro-image-preview',       capabilities: ['image_gen'],                    rpm: 10 },
      { model_id: 'gemini-2.5-flash-image-preview',   capabilities: ['image_gen'],                    rpm: 10 },
      { model_id: 'text-embedding-3-large',           capabilities: ['embedding'],                    rpm: 60 },
      { model_id: 'text-embedding-3-small',           capabilities: ['embedding'],                    rpm: 60 },
    ],
  },
].map(function(template) {
  template.recipe_version = 'tofu.provider-offering-recipe/v1';
  return template;
});

function _templateOfferingRecipes(template) {
  if (!template || typeof template !== 'object') return [];
  var recipes = template.offering_recipes;
  if (!Array.isArray(recipes)) recipes = template.models; // legacy import
  return Array.isArray(recipes) ? recipes : [];
}

function _normalizeProviderTemplateRecipe(template) {
  if (!template || typeof template !== 'object') return template;
  var normalized = Object.assign({}, template);
  normalized.recipe_version = 'tofu.provider-offering-recipe/v1';
  normalized.offering_recipes = _templateOfferingRecipes(template);
  delete normalized.models;
  return normalized;
}

/** Merge optional external recipes by key. */
let _externalTemplatesLoaded = false;
async function _loadExternalProviderTemplates() {
  if (_externalTemplatesLoaded) return;
  _externalTemplatesLoaded = true;
  try {
    var templates = await Api.providers.templates();
    if (!Array.isArray(templates)) return;
    for (var i = 0; i < templates.length; i++) {
      var tpl = _normalizeProviderTemplateRecipe(templates[i]);
      if (!tpl || !tpl.key) continue;
      var existingIdx = _PROVIDER_TEMPLATES.findIndex(function(item) {
        return item.key === tpl.key;
      });
      if (existingIdx >= 0) _PROVIDER_TEMPLATES[existingIdx] = tpl;
      else _PROVIDER_TEMPLATES.push(tpl);
      debugLog('[Settings] Loaded authoritative provider template: ' + tpl.key, 'info');
    }
  } catch (e) {
    debugLog('[Settings] External provider templates not available: ' + e.message, 'info');
  }
}
