// Generated by scripts/gen_api_v4_contract.py; DO NOT EDIT.
package com.tofu.client.api

object ApiV4Contract {
    const val API_MAJOR: Int = 4
    const val MIN_DESKTOP_BUILD: String = "0.16.0"
    const val MIN_ANDROID_BUILD: Int = 17
    const val META_PATH: String = "/api/v4/meta"
}

data class ApiMeta(
    val apiMajor: Int,
    val schemaVersion: Int,
    val serverBuild: String,
    val minDesktopBuild: String,
    val minAndroidBuild: Int,
)

data class ResponseMeta(
    val requestId: String,
    val serverTimeMs: Long,
)

data class ApiMetaResponse(
    val data: ApiMeta,
    val meta: ResponseMeta,
)

fun desktopBuildIsCompatible(
    currentBuild: String,
    minimumBuild: String = ApiV4Contract.MIN_DESKTOP_BUILD,
): Boolean {
    val current = numericBuild(currentBuild)
    val minimum = numericBuild(minimumBuild)
    val length = maxOf(current.size, minimum.size)
    for (index in 0 until length) {
        val difference = current.getOrElse(index) { 0 } - minimum.getOrElse(index) { 0 }
        if (difference != 0) return difference > 0
    }
    return true
}

fun androidBuildIsCompatible(
    currentVersionCode: Int,
    minimumVersionCode: Int = ApiV4Contract.MIN_ANDROID_BUILD,
): Boolean = currentVersionCode >= minimumVersionCode

fun requireAndroidApiCompatibility(
    meta: ApiMetaResponse,
    currentVersionCode: Int,
): ApiMetaResponse {
    require(meta.data.apiMajor == ApiV4Contract.API_MAJOR) {
        "server API major is not compatible with this client"
    }
    require(meta.data.schemaVersion >= 1)
    require(meta.data.serverBuild.isNotBlank())
    require(meta.data.minDesktopBuild.isNotBlank())
    require(meta.data.minAndroidBuild >= 1)
    require(meta.meta.requestId.isNotBlank())
    require(meta.meta.serverTimeMs >= 0)
    require(androidBuildIsCompatible(
        currentVersionCode,
        meta.data.minAndroidBuild,
    )) {
        "Android build $currentVersionCode is below server minimum " +
            "${meta.data.minAndroidBuild}"
    }
    return meta
}

private fun numericBuild(build: String): List<Int> {
    val components = build.split('.')
    require(components.isNotEmpty() && components.all { component ->
        component.isNotEmpty() && component.all(Char::isDigit)
    }) { "build must contain only dotted numeric components" }
    return components.map { component -> component.toInt() }
}
