// @ts-check
/* Generated once during the classic-to-ESM migration. Vite owns this module. */
import { _applyI18n, _i18nLang, _onLanguageChange, _syncLangPicker, setLanguage, t } from '../i18n';
import {
  errorEnvelopeFingerprint,
  isErrorEnvelope as isTypedErrorEnvelope,
  normalizeErrorEnvelope as normalizeTypedErrorEnvelope,
} from '../api/errors';
import { apiTransport as requiredApiTransport } from '../api/transport';
import {
  CONVERSATION_SYNC_STREAM_POLICY,
  conversationSyncApi,
  decodeConversationInvalidation,
} from '../api/conversation-sync.generated';
import { createLifecycleScope } from '../lifecycle';
import { conversationConnectionHealth } from '../core/connection-health';
import {
  createCookieCaptureConsentController,
  handleCookieCaptureFrame as handleTypedCookieCaptureFrame,
} from '../core/cookie-capture-consent';
import { buildTurnSubmissionExtra } from '../core/turn-command';
import { createProjectBrowseCoordinator } from '../core/project-browse-coordinator';
import { createConversationTurnRuntime } from '../core/turn-runtime';
import { createConversationSurfaceController } from '../conversation/application/conversation-surface-controller';
import { createBranchComposerSession } from '../conversation/application/branch-composer';
import {
  agentModeFlags,
  normalizeAgentMode,
  normalizeConversationInteractionModes,
  resolveAgentMode,
} from '../conversation/application/agent-mode';
import {
  activeConversationAttemptIds,
  activeMainConversationAttemptId,
  conversationHasActor,
  latestConversationTurn,
  orderedConversationTurns,
} from '../conversation/application/conversation-read-model';
import { createTransientTurnOverlay } from '../conversation/application/transient-turn-overlay';
import { createTransientStatusTurn } from '../conversation/application/transient-status-turn';
import { createOptimisticUserTurn } from '../conversation/application/optimistic-user-turn';
import { createHumanGuidancePresentationStore } from '../conversation/application/human-guidance-presentation';
import {
  autopilotVuTransientTurnId,
  createAutopilotVuTransientTurn,
  maskAutopilotVuMachineTokens,
  reduceAutopilotVuTransientTurn,
  settleAutopilotVuTransientTurn,
} from '../conversation/application/autopilot-vu-transient';
import {
  createClassicConversationRenderers,
} from '../conversation/ui/classic-conversation-renderers';
import { updateComposerSendControls } from '../conversation/ui/composer-send-controls';
import {
  openTurnInlineEditor,
  reconcileTurnInlineEditors,
} from '../conversation/ui/turn-inline-editor';
import { presentConversationRateLimit } from '../conversation/presentation/live-phase';
import {
  conversationDisplayTitle as _conversationDisplayTitle,
  conversationTimestampLabels,
  stripNoTranslateTags,
} from '../conversation/presentation/shell-localization';
import { createPlanDecisionBar } from '../conversation/ui/plan-decision-bar';
import { createSendStartupLease } from '../core/send-startup';
import {
  DOMPurify, ensureHljsLanguage, hljs, loadHtml2Canvas, loadKatex, marked,
} from '../vendor-runtime';
const moduleTranslate = t;
// The retained orchestration compatibility controllers below are composed at
// module evaluation time. Their typed service/presentation ports must be
// registered first; loading them only from the later feature entry leaves the
// constructors unresolved and aborts the entire application boot.
import '../features/orchestration-core-owners';
import '../features/orchestration-view-owners';
import '../features/orchestration-studio-view-owners';
import { orchestrationRegistry } from '../features/orchestration/registry';

// BEGIN MODULE-PRIVATE ORCHESTRATION BINDINGS
const {
  ORCHESTRATION_LAYOUT_BREAKPOINTS,
  ORCHESTRATION_RUNTIME_SECTION_VALIDATORS,
  ORCHESTRATION_RUN_FILTERS,
  _ORCHESTRATION_HTTP_READ_PROJECTORS,
  _ORCHESTRATION_REQUEST_CONTRACTS,
  _normalizeOrchestrationReplayRead,
  _normalizeOrchestrationRuntimeStart,
  _orchestrationActionRead,
  _orchestrationActionReason,
  _orchestrationContractFieldsMatch,
  _orchestrationContractRecord,
  _orchestrationDefinitionActionRead,
  _orchestrationDefinitionEntryMatches,
  _orchestrationDefinitionFields,
  _orchestrationDefinitionListMatches,
  _orchestrationDefinitionVersion,
  _orchestrationDefinitionVersionMatches,
  _orchestrationDefinitionWriteContract,
  _orchestrationDurableListEnvelope,
  _orchestrationDurableRunFields,
  _orchestrationDurableRunMatches,
  _orchestrationHttpFailureReason,
  _orchestrationHttpRead,
  _orchestrationLiveReplayMatches,
  _orchestrationMutationLegacyValue,
  _orchestrationNormalizedHttpRead,
  _orchestrationReplayEventMatches,
  _orchestrationRequestLimitValue,
  _orchestrationRequireArray,
  _orchestrationRequireArraySubset,
  _orchestrationRequireBoolean,
  _orchestrationRequireFieldSpecs,
  _orchestrationRequireMapValues,
  _orchestrationRequireOptional,
  _orchestrationRequirePositiveInteger,
  _orchestrationRequireString,
  _orchestrationRequireStringFields,
  _orchestrationRequireStringVocabulary,
  _orchestrationRequiredResponseFieldsMatch,
  _orchestrationRunStatuses,
  _orchestrationRuntimeSectionNames,
  _orchestrationTraceContract,
  _projectOrchestrationOutcomeText,
  _tmAbortRun,
  _tmAdoptRunSnapshot,
  _tmAfterClose,
  _tmAgo,
  _tmApiClient,
  _tmBindImageFallbacks,
  _tmClearRunSurface,
  _tmContracts,
  _tmControlDef,
  _tmDeleteRun,
  _tmDuration,
  _tmEnsureActions,
  _tmEnsureCommands,
  _tmEnsureContractController,
  _tmEnsureControllerHub,
  _tmEnsureEventController,
  _tmEnsureGraphView,
  _tmEnsureInspectorView,
  _tmEnsureModal,
  _tmEnsureMutationReconciler,
  _tmEnsureNodePresentation,
  _tmEnsurePanelLayout,
  _tmEnsureRunController,
  _tmEnsureRunListController,
  _tmEnsureRunListView,
  _tmEnsureRunView,
  _tmEnsureShell,
  _tmEnsureTimelineView,
  _tmEnsureWorkspace,
  _tmEsc,
  _tmGateCard,
  _tmHumanApprove,
  _tmHumanInput,
  _tmIco,
  _tmIsTerminal,
  _tmLimitPolicy,
  _tmLine,
  _tmNodeAccent,
  _tmNodeGlyph,
  _tmNodeIconHtml,
  _tmNodeLabel,
  _tmNodeSub,
  _tmOpenRun,
  _tmOpenStudio,
  _tmProjectRunTransition,
  _tmReconcileRunMutation,
  _tmRefreshAuthoringContract,
  _tmRefreshRuns,
  _tmRenderEvent,
  _tmRenderGraph,
  _tmRenderInspector,
  _tmRenderRunList,
  _tmRenderTimelineEvent,
  _tmRenderTitle,
  _tmReportTaskFailure,
  _tmRerun,
  _tmResetEventState,
  _tmResyncRun,
  _tmRoleDef,
  _tmRunSession,
  _tmRunStore,
  _tmSelectNode,
  _tmSelectPanel,
  _tmServices,
  _tmSetRunListBusy,
  _tmSetTimelineBusy,
  _tmShowFinal,
  _tmStatusChip,
  _tmStatusLabel,
  _tmStudioClient,
  _tmSyncChip,
  _tmT,
  _tmTaskClient,
  _tmToast,
  _tmTraceDetail,
  _validateDurableRunRuntimeSection,
  _validateEventRuntimeSection,
  _validateMutationRuntimeSection,
  _validateOutcomeRuntimeSection,
  _validateReplayRuntimeSection,
  _validateRequestLimitsRuntimeSection,
  _validateRunRuntimeSection,
  _validateRuntimeStartRuntimeSection,
  _validateTraceRuntimeSection,
  applyOrchestrationInputLimit,
  applyOrchestrationStudioRequestLimits,
  applyOrchestrationTraceActivity,
  bindOrchestrationPointerSession,
  closeTaskMode,
  createOrchestrationActionLock,
  createOrchestrationApiRequestInvoker,
  createOrchestrationBoundedState,
  createOrchestrationComposerRequestClient,
  createOrchestrationCursorPoller,
  createOrchestrationDefinitionMutationCoordinator,
  createOrchestrationDefinitionRequestClient,
  createOrchestrationDefinitionSnapshotPort,
  createOrchestrationDialogFocusManager,
  createOrchestrationDirtyGuard,
  createOrchestrationDisclosureState,
  createOrchestrationDocumentController,
  createOrchestrationDocumentValidationController,
  createOrchestrationDocumentView,
  createOrchestrationDraftState,
  createOrchestrationDurableRunCommand,
  createOrchestrationEditLifecycle,
  createOrchestrationEditorControllerHub,
  createOrchestrationEditorState,
  createOrchestrationEndpointRequestClient,
  createOrchestrationEphemeralAbortController,
  createOrchestrationEphemeralRunController,
  createOrchestrationEventState,
  createOrchestrationGraphActions,
  createOrchestrationGraphSelectionActions,
  createOrchestrationGraphTools,
  createOrchestrationHistoryController,
  createOrchestrationHumanGateController,
  createOrchestrationHumanGateInteraction,
  createOrchestrationHumanGatePresentation,
  createOrchestrationHumanGateView,
  createOrchestrationKeyedActionLock,
  createOrchestrationMutationCommand,
  createOrchestrationMutationRequestClient,
  createOrchestrationNodeCatalogue,
  createOrchestrationPanelFocusReturn,
  createOrchestrationRequestLimits,
  createOrchestrationRequestReader,
  createOrchestrationRovingItemsController,
  createOrchestrationRunController,
  createOrchestrationRunDrawerView,
  createOrchestrationRunEventController,
  createOrchestrationRunFilter,
  createOrchestrationRunPlanCommand,
  createOrchestrationRunPlanView,
  createOrchestrationRunRequestClient,
  createOrchestrationRunSession,
  createOrchestrationRuntimeContractPort,
  createOrchestrationScrollState,
  createOrchestrationSelectionFocus,
  createOrchestrationSessionController,
  createOrchestrationSingleFlight,
  createOrchestrationStudioApi,
  createOrchestrationSurfaceHandoff,
  createOrchestrationTaskRequestClient,
  createOrchestrationTraceState,
  createOrchestrationValidationClient,
  createOrchestrationValidationCoordinator,
  createOrchestrationValidationState,
  createOrchestrationWorkspaceDeleteCommand,
  createOrchestrationWorkspaceLoadCommand,
  createOrchestrationWorkspacePersistence,
  createOrchestrationWorkspacePersistenceContext,
  createOrchestrationWorkspaceRequestClient,
  createOrchestrationWorkspaceSaveCommand,
  createOrchestrationWorkspaceSessionPort,
  createTaskModeActionController,
  createTaskModeCommandController,
  createTaskModeContractController,
  createTaskModeContractSession,
  createTaskModeControllerHub,
  createTaskModeEventController,
  createTaskModeGatePresentation,
  createTaskModeGateView,
  createTaskModeGraphProjection,
  createTaskModeGraphView,
  createTaskModeInspectorPresentation,
  createTaskModeInspectorView,
  createTaskModeListErrorView,
  createTaskModeListFocusController,
  createTaskModeListPaging,
  createTaskModeMutationReconciler,
  createTaskModeNodePresentation,
  createTaskModePanelLayoutController,
  createTaskModePanelSelection,
  createTaskModeRootController,
  createTaskModeRunCommandController,
  createTaskModeRunController,
  createTaskModeRunFinalView,
  createTaskModeRunListController,
  createTaskModeRunListPresentation,
  createTaskModeRunListView,
  createTaskModeRunReader,
  createTaskModeRunReplayController,
  createTaskModeRunStatusPresentation,
  createTaskModeRunStore,
  createTaskModeRunTime,
  createTaskModeRunTitleView,
  createTaskModeRunView,
  createTaskModeServices,
  createTaskModeShell,
  createTaskModeTimelineView,
  createTaskModeTransitionProjector,
  createTaskModeViewRegistry,
  createTaskModeWorkspace,
  focusOrchestrationPanel,
  formatOrchestrationEventLines,
  formatOrchestrationRichCopy,
  inspectOrchestrationWireFormat,
  normalizeOrchestrationAuthoringContractRead,
  normalizeOrchestrationBuiltinRead,
  normalizeOrchestrationComposeResult,
  normalizeOrchestrationDefinitionAdoption,
  normalizeOrchestrationDefinitionDelete,
  normalizeOrchestrationDefinitionListRead,
  normalizeOrchestrationDefinitionRead,
  normalizeOrchestrationDefinitionSave,
  normalizeOrchestrationDefinitionWrite,
  normalizeOrchestrationInspection,
  normalizeOrchestrationLayoutRead,
  normalizeOrchestrationMutation,
  normalizeOrchestrationMutationRead,
  normalizeOrchestrationOutcome,
  normalizeOrchestrationPlanRead,
  normalizeOrchestrationRunPollRead,
  normalizeOrchestrationRunStart,
  normalizeOrchestrationTaskCreate,
  normalizeOrchestrationTaskEventsRead,
  normalizeOrchestrationTaskListRead,
  normalizeOrchestrationTaskRead,
  normalizeOrchestrationValidationRead,
  normalizeTaskReplayPage,
  openTaskMode,
  orchestrationCompactMedia,
  orchestrationCompatibilityContract,
  orchestrationDefinitionSelection,
  orchestrationDefinitionWriteConflict,
  orchestrationDirectContract,
  orchestrationEventCapability,
  orchestrationEventContractSpec,
  orchestrationEventGateEffect,
  orchestrationEventPreviewLimit,
  orchestrationEventShouldReduce,
  orchestrationEventShouldTimeline,
  orchestrationEventStringCapability,
  orchestrationExecutionOptionLabel,
  orchestrationFitMinScale,
  orchestrationFlowPickerDisplayName,
  orchestrationFlowPickerIcon,
  orchestrationHttpReadProjector,
  orchestrationInspectionMatchesContract,
  orchestrationIssueMessages,
  orchestrationMutationMessage,
  orchestrationNodeTraceSnapshot,
  orchestrationOutcomeMessage,
  orchestrationPublishedContract,
  orchestrationRequestContract,
  orchestrationRequestFailureKey,
  orchestrationRequestFailureMessage,
  orchestrationRequestLimitPolicy,
  orchestrationRequestMaxDepth,
  orchestrationRequestMaxItems,
  orchestrationRequestMaxLength,
  orchestrationRequestRetainedItems,
  orchestrationResultData,
  orchestrationResultError,
  orchestrationResultOk,
  orchestrationRunContract,
  orchestrationRunHasStatus,
  orchestrationRunIsTerminal,
  orchestrationRunPresentation,
  orchestrationRunStatus,
  orchestrationRuntimeContractPort,
  orchestrationScrollScope,
  orchestrationSheetMedia,
  orchestrationSheetMediaQuery,
  orchestrationShortLandscapeMedia,
  orchestrationShortLandscapeMediaQuery,
  orchestrationSummaryNodeParam,
  orchestrationTraceHistoryLimit,
  orchestrationWireContractSpec,
  orchestrationWireFormat,
  projectOrchestrationActionState,
  projectOrchestrationControlSummary,
  projectOrchestrationDefinitionAdoption,
  projectOrchestrationDocumentStatus,
  projectOrchestrationDurableRunSnapshot,
  projectOrchestrationDurableStartOutcome,
  projectOrchestrationEventPresentation,
  projectOrchestrationEventPreview,
  projectOrchestrationFinalResult,
  projectOrchestrationFlowCatalogNotice,
  projectOrchestrationFlowPickerItems,
  projectOrchestrationHttpRead,
  projectOrchestrationInspection,
  projectOrchestrationRequestFailure,
  projectOrchestrationRoleExecutionSummary,
  projectOrchestrationRuntimeContracts,
  projectOrchestrationSavedWorkflowItems,
  projectOrchestrationSubflowSummary,
  projectOrchestrationTraceActivity,
  projectOrchestrationTraceAttemptDelta,
  projectOrchestrationTraceAttemptDeltaPresentation,
  projectOrchestrationTraceAttempts,
  projectOrchestrationTraceSections,
  projectOrchestrationTraceStatus,
  projectOrchestrationTraceStatusPresentation,
  projectOrchestrationTraceText,
  reportOrchestrationDiagnostic,
  recordOrchestrationTraceAttempt,
  reconcileOrchestrationFlowSelection,
  reduceOrchestrationEvent,
  reduceOrchestrationTraceEvent,
  registerOrchestrationHttpReadProjectors,
  resetOrchestrationEventState,
  renderOrchestrationFlowCatalogNotice,
  setOrchestrationPanelState,
  taskModeCompactMedia,
  taskModeShellMarkup,
  validateOrchestrationDurableListEnvelope,
  wireOrchestrationFlowPicker,
} = orchestrationRegistry;
// END MODULE-PRIVATE ORCHESTRATION BINDINGS

// Former file-scope exports live here instead of leaking onto `window`.
// The ESM entry exposes only selected functions through TofuModules v3.
const runtimeScope = Object.create(null);
runtimeScope.t = t;

let katex;
let html2canvas;
let _featureFlags = {};

let markRuntimeReady;
export const runtimeReady = new Promise((resolve) => { markRuntimeReady = resolve; });
function _markScriptsLoaded() { markRuntimeReady(); }
