#!/usr/bin/env python3
"""Generate the typed browser orchestration wire-format registry from Python."""

from __future__ import annotations

import argparse
import json
import os
import sys


ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
TYPESCRIPT_OUTPUT = os.path.join(
    ROOT, 'frontend', 'src', 'features', 'orchestration',
    'wire-formats.generated.ts')
sys.path.insert(0, ROOT)

from lib.orchestration.wire_formats import (  # noqa: E402
    orchestration_wire_formats,
)


def render_typescript() -> str:
    """Render the ESM registry from the backend-owned identifiers."""
    serialized = json.dumps(
        orchestration_wire_formats(), ensure_ascii=True, indent=2)
    indented = '\n'.join(
        f'  {line}' for line in serialized.splitlines())
    return '\n'.join((
        '/* AUTO-GENERATED by scripts/gen_orchestration_wire_formats.py.',
        ' * Canonical source: lib/orchestration/wire_formats.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        'export const ORCHESTRATION_WIRE_FORMATS: '
        'Readonly<Record<string, string>> = Object.freeze(',
        f'{indented},',
        ');',
        '',
    ))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = {
        TYPESCRIPT_OUTPUT: render_typescript(),
    }
    if args.check:
        stale = []
        for path, content in expected.items():
            try:
                with open(path, encoding='utf-8') as handle:
                    actual = handle.read()
            except FileNotFoundError:
                actual = ''
            if actual != content:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print(
                'Generated orchestration wire formats are stale: '
                f'{", ".join(stale)}; run '
                'python3 scripts/gen_orchestration_wire_formats.py',
                file=sys.stderr,
            )
            return 1
        print(
            'OK: orchestration wire formats are up to date '
            f'({len(orchestration_wire_formats())} formats)')
        return 0
    for path, content in expected.items():
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write(content)
        print(os.path.relpath(path, ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
