#!/usr/bin/env python3
"""Generate deeply frozen browser fallbacks from backend wire contracts."""

from __future__ import annotations

import argparse
import json
import os
import sys


ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
TYPESCRIPT_OUTPUT = os.path.join(
    ROOT, 'frontend', 'src', 'features', 'orchestration',
    'compatibility-defaults.generated.ts')
sys.path.insert(0, ROOT)

from lib.orchestration.authoring_contract import (  # noqa: E402
    authoring_object_sections,
)


COMPATIBILITY_CONTRACT_SECTIONS = (
    'eventContract',
    'runContract',
    'outcomeContract',
    'traceContract',
    'mutationContract',
    'replayContract',
    'inspectionContract',
    'definitionListContract',
    'definitionEntryContract',
    'runtimeStartContract',
    'durableRunContract',
    'definitionWriteContract',
)


def compatibility_defaults() -> dict[str, dict]:
    """Project only contracts used when a rolling server omits metadata."""
    sections = authoring_object_sections()
    return {
        name: sections[name]
        for name in COMPATIBILITY_CONTRACT_SECTIONS
    }


def render_typescript() -> str:
    """Render the Native-module fallback from the same backend snapshot."""
    payload = json.dumps(
        compatibility_defaults(), ensure_ascii=True, indent=2)
    return '\n'.join((
        '/* AUTO-GENERATED by',
        ' * scripts/gen_orchestration_compatibility_defaults.py.',
        ' * Canonical source: backend authoring wire-contract owners.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        'const defaults: Record<string, Record<string, unknown>> = '
        f'{payload};',
        '',
        'function deepFreeze<T>(value: T): T {',
        "  if (!value || typeof value !== 'object'",
        '      || Object.isFrozen(value)) return value;',
        '  Object.keys(value).forEach((key) => {',
        '    deepFreeze((value as Record<string, unknown>)[key]);',
        '  });',
        '  return Object.freeze(value) as T;',
        '}',
        '',
        'export const ORCHESTRATION_COMPATIBILITY_DEFAULTS = deepFreeze(',
        '  defaults,',
        ') as Readonly<Record<string, Readonly<Record<string, unknown>>>>;',
        '',
    ))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = {TYPESCRIPT_OUTPUT: render_typescript()}
    if args.check:
        stale = []
        for path, content in expected.items():
            try:
                with open(path, encoding='utf-8') as handle:
                    actual = handle.read()
            except FileNotFoundError:
                actual = ''
            if actual != content:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print(
                'Generated orchestration compatibility defaults are stale: '
                f'{", ".join(stale)}; '
                'run python3 '
                'scripts/gen_orchestration_compatibility_defaults.py',
                file=sys.stderr,
            )
            return 1
        print(
            'OK: orchestration compatibility defaults are up to date '
            f'({len(COMPATIBILITY_CONTRACT_SECTIONS)} contracts)')
        return 0
    for path, content in expected.items():
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write(content)
        print(os.path.relpath(path, ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
