#!/usr/bin/env python3
"""Generate the typed browser orchestration request catalogue from Python."""

from __future__ import annotations

import argparse
import json
import os
import sys


ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
TYPESCRIPT_OUTPUT = os.path.join(
    ROOT, 'frontend', 'src', 'features', 'orchestration',
    'request-contracts.generated.ts')
sys.path.insert(0, ROOT)

from lib.orchestration.browser_endpoint_contract import (  # noqa: E402
    orchestration_browser_request_contract_dicts,
)


def render_typescript() -> str:
    """Render a self-contained Native request projection registry."""
    serialized = json.dumps(
        orchestration_browser_request_contract_dicts(),
        ensure_ascii=True,
        indent=2,
    )
    return '\n'.join((
        '/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.',
        ' * Canonical sources: lib/orchestration/http_endpoint_registry.py',
        ' * and lib/orchestration/browser_endpoint_policy.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        "export type OrchestrationHttpMethod =",
        "  'GET' | 'POST' | 'PUT' | 'DELETE';",
        'export interface OrchestrationRequestContract {',
        '  readonly route: string;',
        '  readonly method: OrchestrationHttpMethod;',
        '  readonly pathArgs?: Readonly<Record<string, number>>;',
        '  readonly queryArgs?: Readonly<Record<string, number>>;',
        '  readonly bodyArgs?: Readonly<Record<string, number>>;',
        '  readonly bodyArg?: number;',
        '  readonly requestOptionsArg?: number;',
        '  readonly writeOperation?: string;',
        '  readonly writeVersionArg?: number;',
        '  readonly writeContractArg?: number;',
        '  readonly resultMethod: string;',
        '  readonly directMethod: string;',
        '  readonly optionName: string;',
        '  readonly responseContract: string;',
        '  readonly responseRequiredFields: readonly string[];',
        '  readonly [key: string]: unknown;',
        '}',
        '',
        'const contracts: Record<string, OrchestrationRequestContract> = '
        f'{serialized};',
        'Object.values(contracts).forEach((contract) => {',
        "  for (const field of ['pathArgs', 'queryArgs', 'bodyArgs'] as const) {",
        '    if (contract[field]) Object.freeze(contract[field]);',
        '  }',
        '  Object.freeze(contract.responseRequiredFields);',
        '  Object.freeze(contract);',
        '});',
        'export const ORCHESTRATION_REQUEST_CONTRACTS: Readonly<',
        '  Record<string, OrchestrationRequestContract>',
        '> = Object.freeze(contracts);',
        '',
    ))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = {TYPESCRIPT_OUTPUT: render_typescript()}
    if args.check:
        stale = []
        for path, content in expected.items():
            try:
                with open(path, encoding='utf-8') as handle:
                    actual = handle.read()
            except FileNotFoundError:
                actual = ''
            if actual != content:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print(
                'Generated orchestration endpoint contracts are stale: '
                f'{", ".join(stale)}; run '
                'python3 scripts/gen_orchestration_http_contract.py',
                file=sys.stderr,
            )
            return 1
        print(
            'OK: typed orchestration endpoint contracts are up to date '
            f'({len(orchestration_browser_request_contract_dicts())} endpoints)')
        return 0
    for path, content in expected.items():
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write(content)
        print(os.path.relpath(path, ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
