#!/usr/bin/env python3
"""Generate browser authoring-section, wire, and request-limit metadata."""

from __future__ import annotations

import argparse
import json
import os
import sys


ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
OUTPUT = os.path.join(
    ROOT, 'frontend', 'src', 'runtime', 'sections',
    'orchestration-authoring-metadata.generated.js')
SECTION_NAME = 'orchestration-authoring-metadata.generated.js'
SECTION_MARKER = f'/* ===== migrated source: {SECTION_NAME} ===== */'
sys.path.insert(0, ROOT)

from lib.orchestration.authoring_contract import (  # noqa: E402
    authoring_object_sections,
)
from lib.orchestration.authoring_contract_registry import (  # noqa: E402
    AUTHORING_OBJECT_SECTION_NAMES,
    RUNTIME_CONTRACT_SECTION_NAMES,
    rolling_optional_section_fields,
)
from lib.orchestration.field_spec_contract import field_spec_schema  # noqa: E402
from lib.orchestration.request_limit_contract import (  # noqa: E402
    request_limits_contract,
)
from lib.orchestration.wire_formats import (  # noqa: E402
    orchestration_wire_formats,
)


def _json(value: object) -> str:
    return json.dumps(value, ensure_ascii=True, indent=2)


def render() -> str:
    sections = authoring_object_sections()
    fields_by_limit = limit_fields()
    sections_by_wire = wire_sections(sections)
    validation_metadata = authoring_validation_metadata(sections)
    limit_lines = []
    for index, (name, fields) in enumerate(fields_by_limit.items()):
        suffix = ',' if index + 1 < len(fields_by_limit) else ''
        limit_lines.append(
            f'  {json.dumps(name)}: Object.freeze('
            f'{json.dumps(fields, ensure_ascii=True)}){suffix}')
    return '\n'.join((
        '/* AUTO-GENERATED by '
        'scripts/gen_orchestration_authoring_metadata.py.',
        ' * Canonical sources: authoring_contract.py,',
        ' * authoring_contract_registry.py, and request_limit_contract.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        'var ORCHESTRATION_AUTHORING_OBJECT_SECTIONS = Object.freeze('
        f'{_json(list(AUTHORING_OBJECT_SECTION_NAMES))});',
        'var ORCHESTRATION_RUNTIME_CONTRACT_SECTIONS = Object.freeze('
        f'{_json(list(RUNTIME_CONTRACT_SECTION_NAMES))});',
        'var ORCHESTRATION_AUTHORING_WIRE_SECTIONS = Object.freeze('
        f'{_json(sections_by_wire)});',
        'var ORCHESTRATION_REQUEST_LIMIT_FIELDS = Object.freeze({',
        *limit_lines,
        '});',
        'var ORCHESTRATION_AUTHORING_VALIDATION_METADATA = (function () {',
        f'  var metadata = {_json(validation_metadata)};',
        '  function deepFreeze(value) {',
        "    if (!value || typeof value !== 'object'",
        '        || Object.isFrozen(value)) return value;',
        '    Object.keys(value).forEach(function (key) {',
        '      deepFreeze(value[key]);',
        '    });',
        '    return Object.freeze(value);',
        '  }',
        '  return deepFreeze(metadata);',
        '})();',
        '',
    ))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = SECTION_MARKER + '\n' + render() + '\n'
    with open(OUTPUT, encoding='utf-8') as handle:
        actual = handle.read()
    if args.check:
        if actual != expected:
            print(
                'Generated orchestration authoring metadata is stale; run '
                'python3 scripts/gen_orchestration_authoring_metadata.py',
                file=sys.stderr,
            )
            return 1
        print(
            'OK: orchestration authoring metadata is up to date '
            f'({len(AUTHORING_OBJECT_SECTION_NAMES)} sections, '
            f'{len(wire_sections())} wire sections, '
            f'{len(limit_fields())} request fields)')
        return 0
    with open(OUTPUT, 'w', encoding='utf-8') as handle:
        handle.write(expected)
    print(f'{os.path.relpath(OUTPUT, ROOT)} [{SECTION_NAME}]')
    return 0


def limit_fields() -> dict[str, list[str]]:
    return {name: list(fields) for name, fields in request_limits_contract().items()}


def authoring_validation_metadata(
    sections: dict | None = None,
) -> dict[str, dict]:
    """Project compact browser checks from backend-owned editor schemas."""
    sections = sections or authoring_object_sections()
    spec_schema = field_spec_schema()
    properties = spec_schema['properties']
    required = spec_schema['required']
    option_schema = properties['options']['items']
    option_properties = option_schema['properties']
    field_values = sections['fieldValueContract']
    kind_specs = field_values['kinds']
    common_kind_fields = [
        name for name, value in next(iter(kind_specs.values())).items()
        if isinstance(value, str)
        and all(isinstance(spec.get(name), str)
                for spec in kind_specs.values())
    ]
    personas = sections['personas']
    persona_specs = list(personas.values())
    persona_string_fields = [
        name for name, value in persona_specs[0].items()
        if isinstance(value, str)
        and all(isinstance(spec.get(name), str) for spec in persona_specs)
    ]
    node_defaults = sections['nodeDefaults']
    blank_subflow = node_defaults['blankSubflow']
    execution_options = sections['executionOptions']

    def execution_axis_fields(defaults: dict) -> dict[str, str]:
        fields = {}
        for field, value in defaults.items():
            axes = [
                axis for axis, choices in execution_options.items()
                if isinstance(choices, list) and value in choices
            ]
            if len(axes) == 1:
                fields[field] = axes[0]
        return fields
    default_output = sections['ioContract']['defaultOutput']
    rolling_optional_fields = rolling_optional_section_fields()
    runtime_sections = {
        name: _runtime_section_validation_metadata(
            sections[name], rolling_optional_fields.get(name, ()))
        for name in RUNTIME_CONTRACT_SECTION_NAMES
    }
    runtime_defaults = sections['nodeRuntimeDefaults']
    runtime_default_metadata = runtime_sections['nodeRuntimeDefaults']
    runtime_default_metadata['role'] = _runtime_section_validation_metadata(
        runtime_defaults['role'], ())
    runtime_default_metadata['subflow'] = \
        _runtime_section_validation_metadata(runtime_defaults['subflow'], ())
    runtime_default_metadata['controls'] = {
        kind: _runtime_section_validation_metadata(defaults, ())
        for kind, defaults in runtime_defaults['controls'].items()
    }
    runtime_default_metadata['roleExecutionAxes'] = execution_axis_fields(
        runtime_defaults['role'])
    runtime_default_metadata['subflowExecutionAxes'] = execution_axis_fields(
        runtime_defaults['subflow'])
    event_type_specs = list(sections['eventContract']['types'].values())
    event_type_fields = list(dict.fromkeys(
        name for spec in event_type_specs for name in spec
    ))
    runtime_sections['eventContract']['eventTypeBooleanFields'] = [
        name for name, value in event_type_specs[0].items()
        if isinstance(value, bool)
        and all(isinstance(spec.get(name), bool)
                for spec in event_type_specs)
    ]
    runtime_sections['eventContract']['eventTypeOptionalStringFields'] = [
        name for name in event_type_fields
        if any(isinstance(spec.get(name), str) for spec in event_type_specs)
        and all(spec.get(name) is None or isinstance(spec.get(name), str)
                for spec in event_type_specs)
    ]
    replay = sections['replayContract']
    replay_cursor = replay['cursor']
    replay_metadata = runtime_sections['replayContract']
    replay_metadata['cursor'] = _runtime_section_validation_metadata(
        replay_cursor, (), ignored_fields=('description',))
    replay_metadata['terminalSnapshot'] = \
        _runtime_section_validation_metadata(replay['terminalSnapshot'], ())
    replay_metadata['terminalSnapshotWhen'] = \
        _runtime_section_validation_metadata(
            replay['terminalSnapshot']['when'], ())
    dynamic_page_fields = {
        replay['eventsField'], replay['nextCursorField'],
        replay['statusField'], replay['terminalField'], replay_cursor['field'],
    }
    replay_metadata['staticPageFields'] = [
        field for field in replay['pageFields']
        if field not in dynamic_page_fields
    ]
    durable_envelope = sections['durableRunContract']['listEnvelope']
    runtime_sections['durableRunContract']['listEnvelope'] = \
        _runtime_section_validation_metadata(durable_envelope, ())
    definition_write = sections['definitionWriteContract']
    field_spec_registry_sections = [
        name for name, section in sections.items()
        if isinstance(section, dict) and section
        and all(isinstance(fields, list) for fields in section.values())
        and all(
            isinstance(field, dict)
            and {'key', 'kind', 'label'} <= set(field)
            for fields in section.values() for field in fields
        )
    ]
    return {
        'rollingOptionalFields': rolling_optional_fields,
        'runtimeSections': runtime_sections,
        'fieldSpecRegistrySections': field_spec_registry_sections,
        'fieldSpec': {
            'requiredStringFields': [
                name for name in required
                if properties.get(name, {}).get('type') == 'string'
            ],
            'positiveIntegerFields': [
                name for name, schema in properties.items()
                if schema.get('type') == 'integer'
                and schema.get('minimum') == 1
            ],
            'arrayFields': [
                name for name, schema in properties.items()
                if schema.get('type') == 'array'
            ],
            'objectFields': [
                name for name, schema in properties.items()
                if schema.get('type') == 'object'
            ],
            'optionRequiredStringFields': [
                name for name in option_schema['required']
                if option_properties.get(name, {}).get('type') == 'string'
            ],
            'optionBooleanFields': [
                name for name, schema in option_properties.items()
                if schema.get('type') == 'boolean'
            ],
        },
        'fieldValueContract': {
            'optionalEmpty': field_values['optionalEmpty'],
            'failureCodes': dict(field_values['failureCodes']),
            'kinds': list(kind_specs),
            'kindRequiredStringFields': common_kind_fields,
        },
        'personas': {
            'requiredStringFields': persona_string_fields,
        },
        'executionOptions': {
            'arrayFields': [
                name for name, value in sections['executionOptions'].items()
                if isinstance(value, list)
            ],
        },
        'nodeDefaults': {
            'objectFields': [
                name for name, value in node_defaults.items()
                if isinstance(value, dict)
            ],
            'blankSubflowArrayFields': [
                name for name, value in blank_subflow.items()
                if isinstance(value, list)
            ],
            'roleExecutionAxes': execution_axis_fields(
                node_defaults['genericRole']),
            'subflowExecutionAxes': execution_axis_fields(
                node_defaults['subflow']),
        },
        'ioContract': {
            'defaultOutputStringFields': [
                name for name, value in default_output.items()
                if isinstance(value, str)
            ],
            'failureCodes': sections['ioContract']['failureCodes'],
        },
        'definitionWriteContract': {
            'requiredStringFields': [
                name for name, value in definition_write.items()
                if name != 'format' and isinstance(value, str)
            ],
        },
    }


def _runtime_section_validation_metadata(
    section: dict,
    rolling_optional_fields: tuple[str, ...] | list[str],
    *,
    ignored_fields: tuple[str, ...] = (),
) -> dict[str, list[str]]:
    """Group required top-level fields by their backend-owned value type."""
    optional = set(rolling_optional_fields)
    identity_field = 'format' if 'format' in section else (
        'schema' if 'schema' in section else None)
    groups: dict[str, list[str]] = {
        'requiredStringFields': [],
        'requiredStringArrayFields': [],
        'requiredArrayFields': [],
        'requiredObjectFields': [],
        'requiredBooleanFields': [],
        'requiredPositiveIntegerFields': [],
        'requiredNonNegativeIntegerFields': [],
    }
    for name, value in section.items():
        if name == identity_field or name in optional \
                or name in ignored_fields:
            continue
        if isinstance(value, bool):
            groups['requiredBooleanFields'].append(name)
        elif isinstance(value, str):
            groups['requiredStringFields'].append(name)
        elif isinstance(value, list):
            group = 'requiredStringArrayFields' \
                if all(isinstance(item, str) for item in value) \
                else 'requiredArrayFields'
            groups[group].append(name)
        elif isinstance(value, dict):
            groups['requiredObjectFields'].append(name)
        elif isinstance(value, int):
            group = 'requiredPositiveIntegerFields' if value > 0 \
                else 'requiredNonNegativeIntegerFields'
            groups[group].append(name)
    return groups


def wire_sections(sections: dict | None = None) -> dict[str, str]:
    """Derive section-to-wire keys from backend-published format values."""
    keys_by_format = {
        value: key for key, value in orchestration_wire_formats().items()
    }
    projected = {}
    for name, section in (sections or authoring_object_sections()).items():
        wire_format = None
        if isinstance(section, dict):
            identity_field = (
                'format' if 'format' in section
                else 'schema' if 'schema' in section else None
            )
            wire_format = section.get(identity_field) if identity_field else None
        if wire_format is None:
            continue
        wire_key = keys_by_format.get(wire_format)
        if wire_key is None:
            raise RuntimeError(
                f'authoring section {name!r} publishes unknown wire format '
                f'{wire_format!r}')
        projected[name] = wire_key
    return projected


if __name__ == '__main__':
    raise SystemExit(main())
