#!/usr/bin/env python3
"""Generate the browser route/verb/argument catalogue from Python."""

from __future__ import annotations

import argparse
import json
import os
import sys


ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))
OUTPUT = os.path.join(
    ROOT, 'static', 'js', 'api', 'orchestration-http-contract.generated.js')
RESPONSE_OUTPUT = os.path.join(
    ROOT, 'static', 'js', 'api', 'orchestration-response-contracts.js')
METHOD_OUTPUT = os.path.join(
    ROOT, 'static', 'js', 'api', 'orchestration-client-methods.js')
TYPESCRIPT_OUTPUT = os.path.join(
    ROOT, 'frontend', 'src', 'features', 'orchestration',
    'request-contracts.generated.ts')
sys.path.insert(0, ROOT)

from lib.orchestration.browser_endpoint_contract import (  # noqa: E402
    orchestration_browser_request_contract_dicts,
    orchestration_client_methods,
    orchestration_response_contract_dicts,
)
from lib.orchestration.http_endpoint_contract import (  # noqa: E402
    orchestration_http_endpoint_dicts,
)


def render() -> str:
    serialized = json.dumps(
        orchestration_http_endpoint_dicts(),
        ensure_ascii=True,
        indent=2,
    )
    lines = [
        '/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.',
        ' * Canonical source: lib/orchestration/http_endpoint_contract.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        '(function (global) {',
        "  'use strict';",
        '',
        f'  const raw = {serialized};',
        '  const contracts = {};',
        '  Object.keys(raw).forEach((name) => {',
        "    ['pathArgs', 'queryArgs', 'bodyArgs'].forEach((field) => {",
        '      if (raw[name][field]) {',
        '        raw[name][field] = Object.freeze(raw[name][field]);',
        '      }',
        '    });',
        '    contracts[name] = Object.freeze(raw[name]);',
        '  });',
        '  const registry = Object.freeze(contracts);',
        '',
        '  global.ApiOrchestrationHttpContract = Object.freeze({',
        '    contract: (name) => registry[name] || null,',
        '    contracts: () => registry,',
        '  });',
        "})(typeof window !== 'undefined' ? window : globalThis);",
        '',
    ]
    return '\n'.join(lines)


def render_response_contracts() -> str:
    """Render response contract -> Native projector option policy."""
    serialized = json.dumps(
        orchestration_response_contract_dicts(), ensure_ascii=True,
        separators=(',', ': '))
    return '\n'.join((
        '/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.',
        ' * Canonical sources: lib/orchestration/browser_endpoint_policy.py',
        ' * and lib/orchestration/response_required_fields.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        '(function (global) {',
        "  'use strict';",
        '',
        f'  const raw = Object.freeze({serialized});',
        '  const contracts = {};',
        '  Object.keys(raw).forEach((name) => {',
        '    contracts[name] = Object.freeze({',
        '      name: name, optionName: raw[name].optionName,',
        '      requiredFields: Object.freeze(raw[name].requiredFields),',
        '    });',
        '  });',
        '  const registry = Object.freeze(contracts);',
        '',
        '  global.ApiOrchestrationResponseContracts = Object.freeze({',
        '    contract: (name) => registry[name] || null,',
        '    contracts: () => registry,',
        '  });',
        "})(typeof window !== 'undefined' ? window : globalThis);",
        '',
    ))


def render_client_methods() -> str:
    """Render endpoint -> public browser method policy."""
    serialized = json.dumps(
        dict(orchestration_client_methods()), ensure_ascii=True,
        separators=(',', ':'))
    return '\n'.join((
        '/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.',
        ' * Canonical source: '
        'lib/orchestration/browser_endpoint_policy.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        '(function (global) {',
        "  'use strict';",
        '',
        f'  const raw = Object.freeze({serialized});',
        '  const contracts = {};',
        '  Object.keys(raw).forEach((name) => {',
        '    contracts[name] = Object.freeze({',
        '      name: name,',
        '      resultMethod: raw[name][0],',
        '      directMethod: raw[name][1],',
        '    });',
        '  });',
        '  const registry = Object.freeze(contracts);',
        '',
        '  global.ApiOrchestrationClientMethods = Object.freeze({',
        '    contract: (name) => registry[name] || null,',
        '    contracts: () => registry,',
        '  });',
        "})(typeof window !== 'undefined' ? window : globalThis);",
        '',
    ))


def render_typescript() -> str:
    """Render a self-contained Native request projection registry."""
    serialized = json.dumps(
        orchestration_browser_request_contract_dicts(),
        ensure_ascii=True,
        indent=2,
    )
    return '\n'.join((
        '/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.',
        ' * Canonical sources: lib/orchestration/http_endpoint_registry.py',
        ' * and lib/orchestration/browser_endpoint_policy.py.',
        ' * DO NOT EDIT BY HAND.',
        ' */',
        'export interface OrchestrationRequestContract {',
        '  readonly resultMethod: string;',
        '  readonly directMethod: string;',
        '  readonly optionName: string;',
        '  readonly responseContract: string;',
        '  readonly responseRequiredFields: readonly string[];',
        '  readonly [key: string]: unknown;',
        '}',
        '',
        'const contracts: Record<string, OrchestrationRequestContract> = '
        f'{serialized};',
        'Object.values(contracts).forEach((contract) => {',
        '  Object.freeze(contract.responseRequiredFields);',
        '  Object.freeze(contract);',
        '});',
        'export const ORCHESTRATION_REQUEST_CONTRACTS: Readonly<',
        '  Record<string, OrchestrationRequestContract>',
        '> = Object.freeze(contracts);',
        '',
    ))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = {
        TYPESCRIPT_OUTPUT: render_typescript(),
    }
    if args.check:
        stale = []
        for path, content in expected.items():
            try:
                with open(path, encoding='utf-8') as handle:
                    actual = handle.read()
            except FileNotFoundError:
                actual = ''
            if actual != content:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print(
                'Generated orchestration endpoint contracts are stale: '
                f'{", ".join(stale)}; run '
                'python3 scripts/gen_orchestration_http_contract.py',
                file=sys.stderr,
            )
            return 1
        print(
            'OK: orchestration endpoint contracts are up to date '
            f'({len(orchestration_http_endpoint_dicts())} endpoints)')
        return 0
    for path, content in expected.items():
        with open(path, 'w', encoding='utf-8') as handle:
            handle.write(content)
        print(os.path.relpath(path, ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
