#!/usr/bin/env node

/**
 * Generate the frontend i18n type contract from the two locale authorities.
 *
 * The authored locale JSON files remain the only language authority. This
 * generator turns their shared vocabulary into a compile-time contract and
 * compact generated JSON delivery assets. Vite serves those assets as data,
 * so thousands of message keys never enter the JavaScript parse/compile path.
 */

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const localeDirectory = path.join(repositoryRoot, 'frontend/src/i18n/locales');
const outputPath = path.join(repositoryRoot, 'frontend/src/i18n/contract.generated.ts');
const deliveryDirectory = path.join(repositoryRoot, 'frontend/src/i18n/generated');
const supportedLanguages = ['zh', 'en'];
const keyPattern = /^[A-Za-z0-9_.-]+$/;
const placeholderPattern = /\{([A-Za-z0-9_]+)\}/g;

function relativeToRepository(value) {
  return path.relative(repositoryRoot, value).split(path.sep).join('/');
}

async function readLocale(language) {
  const filePath = path.join(localeDirectory, `${language}.json`);
  const source = await fs.readFile(filePath, 'utf8');
  let messages;
  try {
    messages = JSON.parse(source);
  } catch (error) {
    throw new Error(`${relativeToRepository(filePath)} is not valid JSON: ${error.message}`);
  }
  if (!messages || typeof messages !== 'object' || Array.isArray(messages)) {
    throw new Error(`${relativeToRepository(filePath)} must contain one object`);
  }
  for (const [key, value] of Object.entries(messages)) {
    if (!keyPattern.test(key)) {
      throw new Error(`${relativeToRepository(filePath)} has invalid key ${JSON.stringify(key)}`);
    }
    if (typeof value !== 'string') {
      throw new Error(`${relativeToRepository(filePath)}.${key} must be a string`);
    }
  }
  return { language, filePath, source, messages };
}

function placeholders(value) {
  return [...value.matchAll(placeholderPattern)].map((match) => match[1]);
}

export async function readI18nCatalog() {
  const locales = await Promise.all(supportedLanguages.map(readLocale));
  const authorityKeys = Object.keys(locales[0].messages).sort();
  const authoritySet = new Set(authorityKeys);
  for (const locale of locales.slice(1)) {
    const localeKeys = Object.keys(locale.messages);
    const localeSet = new Set(localeKeys);
    const missing = authorityKeys.filter((key) => !localeSet.has(key));
    const extra = localeKeys.filter((key) => !authoritySet.has(key)).sort();
    if (missing.length || extra.length) {
      throw new Error(
        `${relativeToRepository(locale.filePath)} key drift: `
        + `missing=${JSON.stringify(missing.slice(0, 20))} `
        + `extra=${JSON.stringify(extra.slice(0, 20))}`,
      );
    }
  }

  const paramsByKey = new Map();
  for (const key of authorityKeys) {
    const names = new Set();
    for (const locale of locales) {
      for (const name of placeholders(locale.messages[key])) names.add(name);
    }
    paramsByKey.set(key, [...names].sort());
  }

  const digest = crypto.createHash('sha256');
  digest.update('tofu-i18n-catalog-v1\0');
  for (const locale of locales) {
    digest.update(`${locale.language}\0`);
    digest.update(locale.source);
    digest.update('\0');
  }
  return {
    digest: digest.digest('hex'),
    keys: authorityKeys,
    locales,
    paramsByKey,
  };
}

function renderContract(catalog) {
  const lines = [
    '/**',
    ' * Generated by scripts/gen_i18n_contract.mjs.',
    ' * Source authority: frontend/src/i18n/locales/{zh,en}.json.',
    ' * Do not edit this file directly.',
    ' */',
    '',
    `export const I18N_CATALOG_DIGEST = '${catalog.digest}' as const;`,
    '',
    'export type I18nKey =',
    ...catalog.keys.map((key, index) => (
      `  | ${JSON.stringify(key)}${index === catalog.keys.length - 1 ? ';' : ''}`
    )),
    '',
    'export interface I18nParamsByKey {',
  ];
  for (const key of catalog.keys) {
    const names = catalog.paramsByKey.get(key);
    const value = names.length
      ? `Readonly<{ ${names.map((name) => `${JSON.stringify(name)}: unknown`).join('; ')} }>`
      : 'never';
    lines.push(`  ${JSON.stringify(key)}: ${value};`);
  }
  lines.push(
    '}',
    '',
    'export type I18nParamsFor<K extends I18nKey> = I18nParamsByKey[K];',
    '',
    'export type I18nArgs<K extends I18nKey> =',
    '  [I18nParamsFor<K>] extends [never]',
    '    ? readonly [params?: never]',
    '    : readonly [params: I18nParamsFor<K>];',
    '',
    'export type Translator = <K extends I18nKey>(',
    '  key: K,',
    '  ...args: I18nArgs<K>',
    ') => string;',
    '',
  );
  return `${lines.join('\n')}\n`;
}

export async function generateI18nContract({ check = false } = {}) {
  const catalog = await readI18nCatalog();
  const artifacts = [
    [outputPath, renderContract(catalog)],
    ...catalog.locales.map((locale) => [
      path.join(deliveryDirectory, `${locale.language}.generated.json`),
      `${JSON.stringify(locale.messages)}\n`,
    ]),
  ];
  const stale = [];
  for (const [artifactPath, expected] of artifacts) {
    let actual = '';
    try {
      actual = await fs.readFile(artifactPath, 'utf8');
    } catch (error) {
      if (!error || error.code !== 'ENOENT') throw error;
    }
    if (actual !== expected) stale.push([artifactPath, expected]);
  }
  if (check && stale.length > 0) {
    throw new Error(
      `${stale.map(([artifactPath]) => relativeToRepository(artifactPath)).join(', ')} `
      + 'is stale; run npm run generate:i18n',
    );
  }
  for (const [artifactPath, expected] of stale) {
    await fs.mkdir(path.dirname(artifactPath), { recursive: true });
    await fs.writeFile(artifactPath, expected, 'utf8');
  }
  return {
    changed: stale.length > 0,
    digest: catalog.digest,
    keyCount: catalog.keys.length,
  };
}

async function main() {
  const mode = process.argv[2] || '--write';
  if (!['--write', '--check'].includes(mode)) {
    throw new Error('usage: gen_i18n_contract.mjs [--write|--check]');
  }
  const result = await generateI18nContract({ check: mode === '--check' });
  process.stdout.write(
    `i18n contract ${result.changed ? 'generated' : 'verified'} `
    + `(${result.keyCount} keys, ${result.digest.slice(0, 12)})\n`,
  );
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (invokedPath === import.meta.url) {
  await main();
}
