/* AUTO-GENERATED by
 * scripts/gen_orchestration_compatibility_defaults.py.
 * Canonical source: backend authoring wire-contract owners.
 * DO NOT EDIT BY HAND.
 */
const defaults: Record<string, Record<string, unknown>> = {
  "eventContract": {
    "schema": "tofu.orchestration.events/v1",
    "previewLimits": {
      "wire": 200,
      "timeline": 120
    },
    "types": {
      "flow_start": {
        "durable": true,
        "reduce": true,
        "timeline": true,
        "runStatus": "running"
      },
      "flow_complete": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "step_start": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "step_complete": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "error": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "loop_start": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "loop_iteration": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "zero_deliverable_guard": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "goal_completion_evidence_missing": {
        "durable": true,
        "reduce": false,
        "timeline": false
      },
      "stuck_detected": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "no_progress": {
        "durable": true,
        "reduce": true,
        "timeline": true
      },
      "replan": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "parallel_start": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "branch_pick": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "artifact_declared": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "human_notify": {
        "durable": true,
        "reduce": false,
        "timeline": true
      },
      "human_request": {
        "durable": true,
        "reduce": true,
        "timeline": true,
        "runStatus": "paused",
        "gateEffect": "open"
      },
      "human_resolved": {
        "durable": true,
        "reduce": true,
        "timeline": true,
        "runStatus": "running",
        "gateEffect": "close"
      },
      "step_phase": {
        "durable": false,
        "reduce": true,
        "timeline": false
      },
      "step_delta": {
        "durable": false,
        "reduce": true,
        "timeline": false
      },
      "step_trace": {
        "durable": true,
        "reduce": true,
        "timeline": false
      }
    }
  },
  "runContract": {
    "schema": "tofu.orchestration.run-status/v1",
    "initial": "pending",
    "statuses": [
      "pending",
      "running",
      "paused",
      "done",
      "error",
      "aborted"
    ],
    "terminal": [
      "done",
      "error",
      "aborted"
    ],
    "categories": {
      "pending": "queued",
      "running": "active",
      "paused": "blocked",
      "done": "success",
      "error": "failure",
      "aborted": "cancelled"
    }
  },
  "outcomeContract": {
    "format": "tofu.orchestration.outcome/v1",
    "categories": [
      "success",
      "incomplete",
      "failure",
      "aborted"
    ],
    "engineStatuses": [
      "completed",
      "failed",
      "aborted"
    ],
    "lifecycleStatuses": [
      "done",
      "error",
      "aborted"
    ],
    "chatStatuses": [
      "done",
      "error",
      "aborted"
    ],
    "finishReasons": [
      "stop",
      "incomplete",
      "error",
      "aborted"
    ],
    "incompleteStopReasons": [
      "aborted_mid_vu",
      "budget_exhausted",
      "max_iterations",
      "max_replans",
      "no_progress",
      "replan_exhausted",
      "stuck",
      "superseded",
      "yielded_to_human"
    ],
    "displayLimits": {
      "final": 16000,
      "error": 4000
    }
  },
  "traceContract": {
    "format": "tofu.orchestration.trace/v1",
    "historyLimit": 12,
    "statusMap": {
      "running": "running",
      "completed": "done",
      "failed": "error",
      "done": "done",
      "error": "error"
    },
    "activityFields": {
      "stateChanging": "state_changing",
      "exploratory": "exploratory",
      "stateChangingTools": "state_changing_tools"
    },
    "textLimits": {
      "brief": 8000,
      "input": 8000,
      "output": 16000,
      "thinking": 16000,
      "error": 4000
    },
    "truncationFlags": {
      "brief": "brief_truncated",
      "input": "input_truncated",
      "output": "output_truncated",
      "thinking": "thinking_truncated",
      "error": "error_truncated"
    }
  },
  "mutationContract": {
    "format": "tofu.orchestration.mutation/v1",
    "actions": [
      "abort_run",
      "delete_run",
      "approve_gate",
      "input_gate",
      "transition_run"
    ],
    "reasons": [
      "accepted",
      "not_found",
      "terminal",
      "active",
      "conflict",
      "persistence_failed"
    ],
    "retryableReasons": [
      "persistence_failed"
    ],
    "transportFailureReason": "transport_failed",
    "clientRetryableReasons": [
      "persistence_failed",
      "transport_failed"
    ],
    "httpStatusByReason": {
      "accepted": 200,
      "not_found": 404,
      "terminal": 409,
      "active": 409,
      "conflict": 409,
      "persistence_failed": 500
    },
    "reconcileField": "reconcile_required",
    "targetExistsField": "target_exists",
    "resourceTerminalField": "resource_terminal",
    "payloadFields": {
      "format": {
        "name": "format",
        "type": "string"
      },
      "ok": {
        "name": "ok",
        "type": "boolean"
      },
      "action": {
        "name": "action",
        "type": "string"
      },
      "reason": {
        "name": "reason",
        "type": "string"
      },
      "targetId": {
        "name": "target_id",
        "type": "string"
      },
      "resourceStatus": {
        "name": "resource_status",
        "type": "string"
      },
      "resourceTerminal": {
        "name": "resource_terminal",
        "type": "nullable_boolean"
      },
      "targetExists": {
        "name": "target_exists",
        "type": "nullable_boolean"
      },
      "retryable": {
        "name": "retryable",
        "type": "boolean"
      },
      "reconcileRequired": {
        "name": "reconcile_required",
        "type": "boolean"
      }
    }
  },
  "replayContract": {
    "format": "tofu.task-replay/v1",
    "httpStatuses": {
      "success": 200,
      "notFound": 404,
      "failure": 500
    },
    "notFoundReason": "not_found",
    "statusField": "status",
    "nextCursorField": "next_cursor",
    "pageFields": [
      "format",
      "ok",
      "events",
      "next_cursor",
      "status",
      "done",
      "cursor"
    ],
    "cursor": {
      "queryField": "cursor",
      "minimum": 0,
      "default": 0,
      "description": "Producer-owned next event sequence.",
      "field": "cursor",
      "requestedField": "requested",
      "nextField": "next",
      "resetField": "reset",
      "unit": "next event sequence",
      "producerOwned": true,
      "futureCursorReset": true
    },
    "terminalField": "done",
    "caughtUpField": "caught_up",
    "eventsField": "events",
    "eventTypeField": "type",
    "eventSequenceField": "seq",
    "eventRequiredFields": [
      "type",
      "seq"
    ],
    "unknownEventTypes": "allow",
    "terminalEventTypes": [
      "done",
      "error",
      "aborted"
    ],
    "terminalSnapshot": {
      "field": "run",
      "when": {
        "field": "done",
        "equals": true
      },
      "optional": true
    }
  },
  "inspectionContract": {
    "format": "tofu.orchestration.inspection/v1",
    "responseFields": [
      "format",
      "ok",
      "errors",
      "warnings",
      "diagnostics",
      "contract"
    ],
    "responseStringArrayFields": [
      "errors",
      "warnings"
    ],
    "diagnosticSeverities": [
      "error",
      "warning"
    ],
    "diagnosticFields": [
      "severity",
      "code",
      "path",
      "message"
    ],
    "diagnosticStringFields": [
      "code",
      "path",
      "message"
    ],
    "diagnosticPathFormat": "json-pointer",
    "contractFields": [
      "schema",
      "projection",
      "initialPhase",
      "nodes",
      "edges"
    ],
    "contractStringFields": [
      "schema",
      "projection",
      "initialPhase"
    ],
    "contractNonNegativeIntegerFields": [
      "nodes",
      "edges"
    ]
  },
  "definitionListContract": {
    "format": "tofu.orchestration.definition-list/v1",
    "itemFields": [
      "id",
      "name",
      "nodeCount",
      "createdAt",
      "updatedAt"
    ],
    "definitionIncluded": false,
    "orderBy": [
      {
        "field": "updatedAt",
        "direction": "desc"
      },
      {
        "field": "createdAt",
        "direction": "desc"
      },
      {
        "field": "id",
        "direction": "asc"
      }
    ]
  },
  "definitionEntryContract": {
    "format": "tofu.orchestration.definition-entry/v1",
    "fields": [
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt"
    ],
    "versionField": "updatedAt",
    "versionRequiredOnWrite": true,
    "inspectionIncludedOnWrite": true
  },
  "runtimeStartContract": {
    "format": "tofu.orchestration.runtime-start/v1",
    "kinds": [
      "ephemeral",
      "durable"
    ],
    "idField": "id",
    "kindField": "kind",
    "successStatuses": {
      "ephemeral": 200,
      "durable": 201
    }
  },
  "durableRunContract": {
    "format": "tofu.orchestration.durable-run/v1",
    "idField": "id",
    "statusField": "status",
    "terminalField": "terminal",
    "outcomeField": "outcome",
    "listFields": [
      "id",
      "orch_id",
      "name",
      "status",
      "terminal",
      "final",
      "error",
      "created_by",
      "created_at",
      "updated_at",
      "finished_at"
    ],
    "readFields": [
      "id",
      "orch_id",
      "name",
      "status",
      "terminal",
      "final",
      "error",
      "created_by",
      "created_at",
      "updated_at",
      "finished_at",
      "definition",
      "input"
    ],
    "optionalFields": [
      "outcome"
    ],
    "listEnvelope": {
      "itemsField": "runs",
      "pageField": "page",
      "pageFields": [
        "limit",
        "has_more",
        "next_limit"
      ],
      "limitField": "limit",
      "hasMoreField": "has_more",
      "nextLimitField": "next_limit",
      "defaultLimit": 50,
      "pageStep": 50,
      "maxLimit": 150
    }
  },
  "definitionWriteContract": {
    "format": "tofu.orchestration.definition-write/v1",
    "versionField": "updatedAt",
    "versionResponseHeader": "ETag",
    "preconditionHeader": "If-Match",
    "tokenSyntax": "quoted-decimal",
    "conflictStatus": 409,
    "conflictReason": "stale_definition",
    "operations": [
      "replace",
      "delete"
    ],
    "conflictFields": {
      "format": {
        "name": "format",
        "type": "string"
      },
      "reason": {
        "name": "reason",
        "type": "string"
      },
      "operation": {
        "name": "operation",
        "type": "string"
      },
      "expectedUpdatedAt": {
        "name": "expectedUpdatedAt",
        "type": "non_negative_integer"
      },
      "currentUpdatedAt": {
        "name": "currentUpdatedAt",
        "type": "non_negative_integer"
      }
    }
  }
};

function deepFreeze<T>(value: T): T {
  if (!value || typeof value !== 'object'
      || Object.isFrozen(value)) return value;
  Object.keys(value).forEach((key) => {
    deepFreeze((value as Record<string, unknown>)[key]);
  });
  return Object.freeze(value) as T;
}

export const ORCHESTRATION_COMPATIBILITY_DEFAULTS = deepFreeze(
  defaults,
) as Readonly<Record<string, Readonly<Record<string, unknown>>>>;
