/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.
 * Canonical sources: lib/orchestration/http_endpoint_registry.py
 * and lib/orchestration/browser_endpoint_policy.py.
 * DO NOT EDIT BY HAND.
 */
export interface OrchestrationRequestContract {
  readonly resultMethod: string;
  readonly directMethod: string;
  readonly optionName: string;
  readonly responseContract: string;
  readonly responseRequiredFields: readonly string[];
  readonly [key: string]: unknown;
}

const contracts: Record<string, OrchestrationRequestContract> = {
  "definition-list": {
    "resultMethod": "listResult",
    "directMethod": "list",
    "optionName": "normalizeList",
    "responseContract": "definition-list",
    "responseRequiredFields": [
      "ok",
      "format",
      "items"
    ]
  },
  "definition-read": {
    "resultMethod": "getResult",
    "directMethod": "get",
    "optionName": "normalizeRead",
    "responseContract": "definition-read",
    "responseRequiredFields": [
      "ok",
      "format",
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt"
    ]
  },
  "definition-create": {
    "resultMethod": "save",
    "directMethod": "create",
    "optionName": "normalizeSave",
    "responseContract": "definition-save",
    "responseRequiredFields": [
      "ok",
      "format",
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "definition-update": {
    "resultMethod": "save",
    "directMethod": "update",
    "optionName": "normalizeSave",
    "responseContract": "definition-save",
    "responseRequiredFields": [
      "ok",
      "format",
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "definition-delete": {
    "resultMethod": "remove",
    "directMethod": "remove",
    "optionName": "normalizeDelete",
    "responseContract": "definition-delete",
    "responseRequiredFields": [
      "ok"
    ]
  },
  "validation": {
    "resultMethod": "validateResult",
    "directMethod": "validate",
    "optionName": "normalizeRead",
    "responseContract": "validation",
    "responseRequiredFields": [
      "format",
      "ok",
      "errors",
      "warnings",
      "diagnostics",
      "contract"
    ]
  },
  "compose": {
    "resultMethod": "composeResult",
    "directMethod": "compose",
    "optionName": "normalizeComposeResult",
    "responseContract": "compose",
    "responseRequiredFields": [
      "ok",
      "reply",
      "definition",
      "validation",
      "error"
    ]
  },
  "builtin": {
    "resultMethod": "builtinResult",
    "directMethod": "builtin",
    "optionName": "normalizeBuiltin",
    "responseContract": "builtin",
    "responseRequiredFields": [
      "ok",
      "definition",
      "inspection"
    ]
  },
  "layout": {
    "resultMethod": "layoutResult",
    "directMethod": "layout",
    "optionName": "normalizeLayout",
    "responseContract": "layout",
    "responseRequiredFields": [
      "ok",
      "definition",
      "definitionSource"
    ]
  },
  "authoring-contract": {
    "resultMethod": "authoringContractResult",
    "directMethod": "authoringContract",
    "optionName": "normalizeRead",
    "responseContract": "authoring-contract",
    "responseRequiredFields": [
      "ok",
      "format",
      "schema",
      "roleNames",
      "generic",
      "controls",
      "kinds",
      "builtins",
      "contractSections",
      "ioTypes",
      "defaultOutput",
      "roles",
      "controlSchemas",
      "personas",
      "defaultEmits",
      "executionOptions",
      "nodeDefaults",
      "nodeRuntimeDefaults",
      "eventContract",
      "runContract",
      "outcomeContract",
      "traceContract",
      "mutationContract",
      "replayContract",
      "inspectionContract",
      "definitionListContract",
      "definitionEntryContract",
      "runtimeStartContract",
      "fieldValueContract",
      "durableRunContract",
      "definitionWriteContract",
      "requestLimits",
      "ioContract"
    ]
  },
  "role-schema": {
    "resultMethod": "roleSchemaResult",
    "directMethod": "roleSchema",
    "optionName": "normalizeRead",
    "responseContract": "authoring-contract",
    "responseRequiredFields": [
      "ok",
      "format",
      "schema",
      "roleNames",
      "generic",
      "controls",
      "kinds",
      "builtins",
      "contractSections",
      "ioTypes",
      "defaultOutput",
      "roles",
      "controlSchemas",
      "personas",
      "defaultEmits",
      "executionOptions",
      "nodeDefaults",
      "nodeRuntimeDefaults",
      "eventContract",
      "runContract",
      "outcomeContract",
      "traceContract",
      "mutationContract",
      "replayContract",
      "inspectionContract",
      "definitionListContract",
      "definitionEntryContract",
      "runtimeStartContract",
      "fieldValueContract",
      "durableRunContract",
      "definitionWriteContract",
      "requestLimits",
      "ioContract"
    ]
  },
  "plan": {
    "resultMethod": "planResult",
    "directMethod": "plan",
    "optionName": "normalizePlan",
    "responseContract": "plan",
    "responseRequiredFields": [
      "ok",
      "steps",
      "error",
      "inspection",
      "warnings",
      "contract",
      "definitionSource"
    ]
  },
  "run-start": {
    "resultMethod": "runResult",
    "directMethod": "run",
    "optionName": "normalizeStart",
    "responseContract": "run-start",
    "responseRequiredFields": [
      "ok",
      "task_id",
      "start",
      "definitionSource",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "run-poll": {
    "resultMethod": "runPollResult",
    "directMethod": "runPoll",
    "optionName": "normalizePoll",
    "responseContract": "run-poll",
    "responseRequiredFields": [
      "format",
      "ok",
      "events",
      "next_cursor",
      "status",
      "done",
      "cursor",
      "taskId",
      "createdAt",
      "updatedAt"
    ]
  },
  "run-abort": {
    "resultMethod": "runAbort",
    "directMethod": "runAbort",
    "optionName": "normalizeMutation",
    "responseContract": "mutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "human-approve": {
    "resultMethod": "humanApprove",
    "directMethod": "humanApprove",
    "optionName": "normalizeMutation",
    "responseContract": "mutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "human-input": {
    "resultMethod": "humanInput",
    "directMethod": "humanInput",
    "optionName": "normalizeMutation",
    "responseContract": "mutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "task-list": {
    "resultMethod": "taskListResult",
    "directMethod": "taskList",
    "optionName": "normalizeList",
    "responseContract": "task-list",
    "responseRequiredFields": [
      "ok",
      "runs",
      "page"
    ]
  },
  "task-read": {
    "resultMethod": "taskGet",
    "directMethod": "taskGet",
    "optionName": "normalizeRead",
    "responseContract": "task-read",
    "responseRequiredFields": [
      "ok",
      "run"
    ]
  },
  "task-create": {
    "resultMethod": "taskCreate",
    "directMethod": "taskCreate",
    "optionName": "normalizeCreate",
    "responseContract": "task-create",
    "responseRequiredFields": [
      "ok",
      "run_id",
      "start",
      "definitionSource",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "task-events": {
    "resultMethod": "taskEventsResult",
    "directMethod": "taskEvents",
    "optionName": "normalizeEvents",
    "responseContract": "task-events",
    "responseRequiredFields": [
      "format",
      "ok",
      "events",
      "next_cursor",
      "status",
      "done",
      "cursor",
      "caught_up"
    ]
  },
  "task-abort": {
    "resultMethod": "taskAbort",
    "directMethod": "taskAbort",
    "optionName": "normalizeMutation",
    "responseContract": "mutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "task-remove": {
    "resultMethod": "taskRemove",
    "directMethod": "taskRemove",
    "optionName": "normalizeMutation",
    "responseContract": "mutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  }
};
Object.values(contracts).forEach((contract) => {
  Object.freeze(contract.responseRequiredFields);
  Object.freeze(contract);
});
export const ORCHESTRATION_REQUEST_CONTRACTS: Readonly<
  Record<string, OrchestrationRequestContract>
> = Object.freeze(contracts);
