/* AUTO-GENERATED by scripts/gen_orchestration_http_contract.py.
 * Canonical sources: lib/orchestration/http_endpoint_registry.py
 * and lib/orchestration/browser_endpoint_policy.py.
 * DO NOT EDIT BY HAND.
 */
export type OrchestrationHttpMethod =
  'GET' | 'POST' | 'PUT' | 'DELETE';
export interface OrchestrationRequestContract {
  readonly route: string;
  readonly method: OrchestrationHttpMethod;
  readonly pathArgs?: Readonly<Record<string, number>>;
  readonly queryArgs?: Readonly<Record<string, number>>;
  readonly bodyArgs?: Readonly<Record<string, number>>;
  readonly bodyArg?: number;
  readonly requestOptionsArg?: number;
  readonly writeOperation?: string;
  readonly writeVersionArg?: number;
  readonly writeContractArg?: number;
  readonly resultMethod: string;
  readonly directMethod: string;
  readonly optionName: string;
  readonly responseContract: string;
  readonly responseRequiredFields: readonly string[];
  readonly [key: string]: unknown;
}

const contracts: Record<string, OrchestrationRequestContract> = {
  "definition-list": {
    "route": "/api/v1/orchestrations",
    "method": "GET",
    "responseContract": "definition-list",
    "resultMethod": "listResult",
    "directMethod": "list",
    "optionName": "normalizeList",
    "responseRequiredFields": [
      "ok",
      "format",
      "items"
    ]
  },
  "definition-read": {
    "route": "/api/v1/orchestrations/<orch_id>",
    "method": "GET",
    "responseContract": "definition-read",
    "pathArgs": {
      "orch_id": 0
    },
    "resultMethod": "getResult",
    "directMethod": "get",
    "optionName": "normalizeRead",
    "responseRequiredFields": [
      "ok",
      "format",
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt"
    ]
  },
  "definition-create": {
    "route": "/api/v1/orchestrations",
    "method": "POST",
    "responseContract": "definition-save",
    "bodyArg": 0,
    "writeOperation": "create",
    "resultMethod": "save",
    "directMethod": "create",
    "optionName": "normalizeSave",
    "responseRequiredFields": [
      "ok",
      "format",
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "definition-update": {
    "route": "/api/v1/orchestrations/<orch_id>",
    "method": "PUT",
    "responseContract": "definition-save",
    "pathArgs": {
      "orch_id": 0
    },
    "bodyArg": 1,
    "writeOperation": "replace",
    "writeVersionArg": 2,
    "writeContractArg": 3,
    "resultMethod": "save",
    "directMethod": "update",
    "optionName": "normalizeSave",
    "responseRequiredFields": [
      "ok",
      "format",
      "id",
      "name",
      "definition",
      "createdAt",
      "updatedAt",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "definition-delete": {
    "route": "/api/v1/orchestrations/<orch_id>",
    "method": "DELETE",
    "responseContract": "definition-delete",
    "pathArgs": {
      "orch_id": 0
    },
    "writeOperation": "delete",
    "writeVersionArg": 1,
    "writeContractArg": 2,
    "resultMethod": "remove",
    "directMethod": "remove",
    "optionName": "normalizeDelete",
    "responseRequiredFields": [
      "ok"
    ]
  },
  "validation": {
    "route": "/api/v1/orchestrations/validate",
    "method": "POST",
    "responseContract": "validation",
    "bodyArg": 0,
    "requestOptionsArg": 1,
    "resultMethod": "validateResult",
    "directMethod": "validate",
    "optionName": "normalizeRead",
    "responseRequiredFields": [
      "format",
      "ok",
      "errors",
      "warnings",
      "diagnostics",
      "contract"
    ]
  },
  "compose": {
    "route": "/api/v1/orchestrations/compose",
    "method": "POST",
    "responseContract": "compose",
    "bodyArgs": {
      "requirement": 0,
      "current": 1,
      "history": 2
    },
    "resultMethod": "composeResult",
    "directMethod": "compose",
    "optionName": "normalizeComposeResult",
    "responseRequiredFields": [
      "ok",
      "reply",
      "definition",
      "validation",
      "error"
    ]
  },
  "builtin": {
    "route": "/api/v1/orchestrations/builtin/<name>",
    "method": "GET",
    "responseContract": "builtin",
    "pathArgs": {
      "name": 0
    },
    "resultMethod": "builtinResult",
    "directMethod": "builtin",
    "optionName": "normalizeBuiltin",
    "responseRequiredFields": [
      "ok",
      "definition",
      "inspection"
    ]
  },
  "layout": {
    "route": "/api/v1/orchestrations/layout",
    "method": "POST",
    "responseContract": "layout",
    "bodyArgs": {
      "definition": 0,
      "id": 1
    },
    "resultMethod": "layoutResult",
    "directMethod": "layout",
    "optionName": "normalizeLayout",
    "responseRequiredFields": [
      "ok",
      "definition",
      "definitionSource"
    ]
  },
  "authoring-contract": {
    "route": "/api/v1/orchestrations/authoring-contract",
    "method": "GET",
    "responseContract": "authoring-contract",
    "resultMethod": "authoringContractResult",
    "directMethod": "authoringContract",
    "optionName": "normalizeRead",
    "responseRequiredFields": [
      "ok",
      "format",
      "schema",
      "roleNames",
      "generic",
      "controls",
      "kinds",
      "builtins",
      "contractSections",
      "roles",
      "controlSchemas",
      "personas",
      "defaultEmits",
      "executionOptions",
      "nodeDefaults",
      "nodeRuntimeDefaults",
      "eventContract",
      "runContract",
      "outcomeContract",
      "traceContract",
      "mutationContract",
      "replayContract",
      "inspectionContract",
      "definitionListContract",
      "definitionEntryContract",
      "runtimeStartContract",
      "fieldValueContract",
      "durableRunContract",
      "definitionWriteContract",
      "requestLimits",
      "ioContract"
    ]
  },
  "plan": {
    "route": "/api/v1/orchestrations/plan",
    "method": "POST",
    "responseContract": "plan",
    "bodyArgs": {
      "definition": 0,
      "id": 1
    },
    "resultMethod": "planResult",
    "directMethod": "plan",
    "optionName": "normalizePlan",
    "responseRequiredFields": [
      "ok",
      "steps",
      "error",
      "inspection",
      "warnings",
      "contract",
      "definitionSource"
    ]
  },
  "run-start": {
    "route": "/api/v1/orchestrations/run",
    "method": "POST",
    "responseContract": "run-start",
    "bodyArgs": {
      "definition": 0,
      "input": 1,
      "id": 2,
      "originId": 3
    },
    "resultMethod": "runResult",
    "directMethod": "run",
    "optionName": "normalizeStart",
    "responseRequiredFields": [
      "ok",
      "start",
      "definitionSource",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "run-poll": {
    "route": "/api/v1/orchestrations/run/poll/<task_id>",
    "method": "GET",
    "responseContract": "run-poll",
    "pathArgs": {
      "task_id": 0
    },
    "queryArgs": {
      "cursor": 1
    },
    "resultMethod": "runPollResult",
    "directMethod": "runPoll",
    "optionName": "normalizePoll",
    "responseRequiredFields": [
      "format",
      "ok",
      "events",
      "next_cursor",
      "status",
      "done",
      "cursor",
      "taskId",
      "createdAt",
      "updatedAt"
    ]
  },
  "run-abort": {
    "route": "/api/v1/orchestrations/run/abort/<task_id>",
    "method": "POST",
    "responseContract": "mutation",
    "pathArgs": {
      "task_id": 0
    },
    "resultMethod": "runAbort",
    "directMethod": "runAbort",
    "optionName": "normalizeMutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "human-approve": {
    "route": "/api/v1/orchestrations/run/human-approve",
    "method": "POST",
    "responseContract": "mutation",
    "bodyArgs": {
      "requestId": 0,
      "approved": 1
    },
    "resultMethod": "humanApprove",
    "directMethod": "humanApprove",
    "optionName": "normalizeMutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "human-input": {
    "route": "/api/v1/orchestrations/run/human-input",
    "method": "POST",
    "responseContract": "mutation",
    "bodyArgs": {
      "requestId": 0,
      "response": 1
    },
    "resultMethod": "humanInput",
    "directMethod": "humanInput",
    "optionName": "normalizeMutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "task-list": {
    "route": "/api/v1/orchestrations/tasks",
    "method": "GET",
    "responseContract": "task-list",
    "queryArgs": {
      "status": 0,
      "orch_id": 1,
      "limit": 2
    },
    "resultMethod": "taskListResult",
    "directMethod": "taskList",
    "optionName": "normalizeList",
    "responseRequiredFields": [
      "ok",
      "runs",
      "page"
    ]
  },
  "task-read": {
    "route": "/api/v1/orchestrations/tasks/<run_id>",
    "method": "GET",
    "responseContract": "task-read",
    "pathArgs": {
      "run_id": 0
    },
    "resultMethod": "taskGet",
    "directMethod": "taskGet",
    "optionName": "normalizeRead",
    "responseRequiredFields": [
      "ok",
      "run"
    ]
  },
  "task-create": {
    "route": "/api/v1/orchestrations/tasks",
    "method": "POST",
    "responseContract": "task-create",
    "bodyArgs": {
      "definition": 0,
      "input": 1,
      "id": 2,
      "originId": 3
    },
    "resultMethod": "taskCreate",
    "directMethod": "taskCreate",
    "optionName": "normalizeCreate",
    "responseRequiredFields": [
      "ok",
      "start",
      "definitionSource",
      "inspection",
      "warnings",
      "contract"
    ]
  },
  "task-events": {
    "route": "/api/v1/orchestrations/tasks/<run_id>/events",
    "method": "GET",
    "responseContract": "task-events",
    "pathArgs": {
      "run_id": 0
    },
    "queryArgs": {
      "cursor": 1
    },
    "resultMethod": "taskEventsResult",
    "directMethod": "taskEvents",
    "optionName": "normalizeEvents",
    "responseRequiredFields": [
      "format",
      "ok",
      "events",
      "next_cursor",
      "status",
      "done",
      "cursor",
      "caught_up"
    ]
  },
  "task-abort": {
    "route": "/api/v1/orchestrations/tasks/<run_id>/abort",
    "method": "POST",
    "responseContract": "mutation",
    "pathArgs": {
      "run_id": 0
    },
    "resultMethod": "taskAbort",
    "directMethod": "taskAbort",
    "optionName": "normalizeMutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  },
  "task-remove": {
    "route": "/api/v1/orchestrations/tasks/<run_id>",
    "method": "DELETE",
    "responseContract": "mutation",
    "pathArgs": {
      "run_id": 0
    },
    "resultMethod": "taskRemove",
    "directMethod": "taskRemove",
    "optionName": "normalizeMutation",
    "responseRequiredFields": [
      "ok",
      "mutation"
    ]
  }
};
Object.values(contracts).forEach((contract) => {
  for (const field of ['pathArgs', 'queryArgs', 'bodyArgs'] as const) {
    if (contract[field]) Object.freeze(contract[field]);
  }
  Object.freeze(contract.responseRequiredFields);
  Object.freeze(contract);
});
export const ORCHESTRATION_REQUEST_CONTRACTS: Readonly<
  Record<string, OrchestrationRequestContract>
> = Object.freeze(contracts);
