/* AUTO-GENERATED by scripts/gen_orchestration_wire_formats.py.
 * Canonical source: lib/orchestration/wire_formats.py.
 * DO NOT EDIT BY HAND.
 */
export const ORCHESTRATION_WIRE_FORMATS: Readonly<Record<string, string>> = Object.freeze(
  {
    "authoring-contract": "tofu.orchestration.authoring-contract/v1",
    "definition": "tofu.orchestration/v1",
    "inspection": "tofu.orchestration.inspection/v1",
    "definition-write": "tofu.orchestration.definition-write/v1",
    "definition-list": "tofu.orchestration.definition-list/v1",
    "definition-entry": "tofu.orchestration.definition-entry/v1",
    "events": "tofu.orchestration.events/v1",
    "run-status": "tofu.orchestration.run-status/v1",
    "trace": "tofu.orchestration.trace/v1",
    "outcome": "tofu.orchestration.outcome/v1",
    "mutation": "tofu.orchestration.mutation/v1",
    "task-replay": "tofu.task-replay/v1",
    "field-value": "tofu.orchestration.field-value/v1",
    "runtime-start": "tofu.orchestration.runtime-start/v1",
    "durable-run": "tofu.orchestration.durable-run/v1"
  },
);
