//! @generated by scripts/gen_tofudb_ir_contract.py; do not edit.

pub const SCHEMA_IR_VERSION: u32 = 1;
pub const TRANSACTION_IR_VERSION: u32 = 1;
pub const MIN_SEARCH_PROJECTION_BYTES: u64 = 134217728;
pub const MAX_SEARCH_PROJECTION_BYTES: u64 = 4294967296;
pub const SEARCH_PROJECTION_VOLUME_FREE_PERCENT: u64 = 2;
pub const MAX_TRANSACTION_IR_STEPS: usize = 128;
pub const MAX_TRANSACTION_IR_SLOTS: usize = 64;
pub const MAX_TRANSACTION_IR_LITERAL_BYTES: usize = 8388608;
pub const MAX_TASK_RESULT_DOCUMENT_BYTES: usize = 67108864;
pub const TASK_RESULT_DOCUMENT_NAMESPACE: &str = "task_result_documents";
pub const TASK_RESULT_HEADER_NAMESPACE: &str = "task_result_headers";
pub const TASK_RESULT_REPLAY_NAMESPACE: &str = "task_result_replay_projections";
pub const TASK_RESULT_SUMMARY_NAMESPACE: &str = "task_results_by_owner";
pub const TASK_RESULT_LIVE_NAMESPACE: &str = "task_results_live_by_owner";
pub const TASK_RESULT_COST_EXPERIMENT_NAMESPACE: &str = "task_results_by_cost_experiment";
pub const MAX_TASK_RESULT_SUMMARY_ROWS: usize = 1000;
pub const MAX_TASK_RESULT_SUMMARY_SCAN_ROWS: usize = 10000;
pub const TASK_RESULT_SUMMARY_PAGE_ROWS: usize = 1000;
pub const MAX_TASK_RESULT_RECOVERY_ROWS: usize = 500;
pub const MAX_TASK_RESULT_RECOVERY_SCAN_ROWS: usize = 100000;
pub const MAX_TASK_RESULT_COST_EXPERIMENT_ROWS: usize = 10000;
pub const MAX_TASK_RESULT_COST_EXPERIMENT_SCAN_ROWS: usize = 256;
pub const TASK_RESULT_CHECKPOINT_GUARD_CONTRACT: &str = "tofu.task-results.checkpoint.guard/v1";
pub const TASK_RESULT_CACHE_SETTINGS_CONTRACT: &str =
    "tofu.task-results.checkpoint.cache-settings/v1";
pub const MAX_TASK_RESULT_CACHE_FACT: u64 = 2147483647;
pub const MAX_ENTITY_KEY_BYTES: usize = 3072;
pub const MAX_ENTITY_INLINE_VALUE_BYTES: usize = 8192;
pub const MAX_ENTITY_RANGE_ROWS: usize = 1000;
pub const MAX_ENTITY_TRANSACTION_WRITES: usize = 14336;
pub const MAX_ENTITY_POINT_WITNESSES: usize = 6144;
pub const MAX_ENTITY_RANGE_WITNESSES: usize = 1024;
pub const MAX_AGGREGATE_ENTITY_TRANSACTION_BYTES: usize = 167772160;
pub const MAX_PINNED_ENTITY_SNAPSHOTS: usize = 64;
pub const MAX_ENTITY_REACHABILITY_PAGES: usize = 20000000;
pub const MAX_ENTITY_REACHABILITY_FRONTIER: usize = 8192;
pub const MAX_ENTITY_RETIRED_RANGES: usize = 64;
pub const MAX_ENTITY_ROOT_RANGE_MOUNTS: usize = 64;
pub const MAX_ENTITY_MOUNT_CONSOLIDATION_ROWS: usize = 999;
pub const MAX_ENTITY_MOUNT_CONSOLIDATION_BYTES: usize = 8388608;
pub const MAX_STREAM_EVENT_BYTES: usize = 262144;
pub const MAX_STREAM_APPEND_EVENTS: usize = 4096;
pub const MAX_STREAM_APPEND_BYTES: usize = 8388608;
pub const MAX_STREAM_READ_EVENTS: usize = 1000;
pub const MAX_STREAM_READ_BYTES: usize = 8388608;
pub const MAX_TRANSACTION_STREAM_APPENDS: usize = 500;
pub const PERSISTENT_ENTITY_ROOT_PIN_NAMESPACE: &str = "entity_root_pins";
pub const PERSISTENT_ENTITY_ROOT_PIN_CATALOG_NAMESPACE: &str = "entity_root_pin_catalog";
pub const MAX_PERSISTENT_ENTITY_ROOT_PINS: usize = 1000000;
pub const MAX_LEGACY_PERSISTENT_ENTITY_ROOT_PINS: usize = 64;
pub const MAX_PERSISTENT_ENTITY_ROOT_PIN_ID_BYTES: usize = 128;
pub const MAX_PERSISTENT_ENTITY_CAPSULE_RANGES: usize = 64;
pub const MAX_MAINTENANCE_WORKERS: usize = 1;
pub const MAX_MAINTENANCE_SCOPES: usize = 64;
pub const MAINTENANCE_WORKER_STACK_BYTES: usize = 524288;
pub const OBSERVED_MAINTENANCE_IDLE_INTERVAL_MILLISECONDS: u64 = 250;
pub const LEAN_MAINTENANCE_IDLE_INTERVAL_MILLISECONDS: u64 = 1000;
pub const MAX_MAINTENANCE_IDLE_INTERVAL_MILLISECONDS: u64 = 60000;
pub const OBSERVED_HISTORY_RETAINED_SEGMENTS: usize = 64;
pub const LEAN_HISTORY_RETAINED_SEGMENTS: usize = 16;
pub const MAX_HISTORY_RETAINED_SEGMENTS: usize = 64;
pub const TOOL_RESULT_PRUNE_ROWS_PER_MAINTENANCE_ROUND: usize = 128;
pub const FILESYSTEM_CERTIFICATION_PAYLOAD_BLOCK_BYTES: usize = 1048576;
pub const FILESYSTEM_CERTIFICATION_MAXIMUM_RETAINED_ENTRIES: usize = 4096;
pub const MAX_AUTHORITY_GC_VICTIM_BYTES: u64 = 268435456;
pub const MAX_AUTHORITY_GC_TEMPORARY_BYTES: u64 = 1073741824;
pub const AUTHORITY_GC_TEMPORARY_FREE_SPACE_PERCENT: u64 = 2;
pub const LEAN_AUTHORITY_GC_TEMPORARY_BYTES: u64 = 67108864;
pub const MAX_AUTHORITY_GC_BLOCKS_PER_ROUND: usize = 65536;
pub const MAX_AUTHORITY_GC_PHYSICAL_BLOCKS: usize = 20000000;
pub const AUTHORITY_GC_RPC_PHYSICAL_BLOCKS_PER_REQUESTED_MILLISECOND: usize = 256;
pub const MAX_AUTHORITY_GC_TEMPORARY_BLOCK_FILES_REMOVED: usize = 1;
pub const MAX_AUTHORITY_GC_PAYLOAD_SEGMENT_FILES_SCANNED: usize = 4097;
pub const MAX_AUTHORITY_GC_ORPHAN_PAYLOAD_SEGMENT_FILES_REMOVED: usize = 1;
pub const MAX_AUTHORITY_GC_PAYLOAD_SEGMENTS_SCANNED: usize = 16;
pub const MIN_AUTHORITY_GC_PAYLOAD_COMPACTION_BLOCKS: usize = 128;
pub const DESKTOP_PREFERENCE_NAMESPACE: &str = "desktop_egress_preferences";
pub const BILLING_WALLET_NAMESPACE: &str = "billing_wallets";
pub const BILLING_LEDGER_NAMESPACE: &str = "billing_ledger_entries";
pub const BILLING_LEDGER_ID_CLAIM_NAMESPACE: &str = "billing_ledger_id_claims";
pub const BILLING_IDEMPOTENCY_NAMESPACE: &str = "billing_ledger_idempotency";
pub const BILLING_USER_TIME_INDEX_NAMESPACE: &str = "billing_ledger_by_user_time_desc";
pub const BILLING_USER_AGGREGATE_NAMESPACE: &str = "billing_ledger_user_aggregates";
pub const BILLING_RESERVE_STATE_NAMESPACE: &str = "billing_reserve_states";
pub const BILLING_RESERVE_AGE_INDEX_NAMESPACE: &str = "billing_reserves_by_age";
pub const BILLING_PAYMENT_DOCUMENT_NAMESPACE: &str = "billing_payment_documents";
pub const BILLING_PAYMENT_ID_CLAIM_NAMESPACE: &str = "billing_payment_id_claims";
pub const BILLING_PAYMENT_PROVIDER_CLAIM_NAMESPACE: &str = "billing_payment_provider_claims";
pub const BILLING_PAYMENT_CREATED_INDEX_NAMESPACE: &str = "billing_payments_by_created_desc";
pub const BILLING_PAYMENT_COUNT_NAMESPACE: &str = "billing_payment_counts";
pub const BILLING_REDEEM_BATCH_DOCUMENT_NAMESPACE: &str = "billing_redeem_batches";
pub const BILLING_REDEEM_CODE_LOCATOR_NAMESPACE: &str = "billing_redeem_code_locators";
pub const BILLING_REDEEM_CODE_STATE_NAMESPACE: &str = "billing_redeem_code_states";
pub const BILLING_REDEEM_CREATED_INDEX_NAMESPACE: &str = "billing_redeem_batches_by_created_desc";
pub const BILLING_REDEEM_BATCH_CREATED_INDEX_NAMESPACE: &str =
    "billing_redeem_batches_by_label_created_desc";
pub const BILLING_REDEEM_COUNT_NAMESPACE: &str = "billing_redeem_code_counts";
pub const MAX_BILLING_LEDGER_ENTRIES_PER_USER: usize = 100000;
pub const MAX_BILLING_PAYMENTS: usize = 100000;
pub const MAX_BILLING_PAYMENT_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_BILLING_REDEEM_CODES: usize = 100000;
pub const MAX_BILLING_REDEEM_CODES_PER_MINT: usize = 10000;
pub const MAX_BILLING_REDEEM_BATCH_DOCUMENT_BYTES: usize = 8388608;
pub const BILLING_REDEEM_BATCH_SHARDS: usize = 4096;
pub const MAX_BILLING_REDEEM_BATCH_SHARD_BYTES: usize = 67108864;
pub const BILLING_REDEEM_LOCATOR_SHARDS: usize = 4096;
pub const MAX_BILLING_REDEEM_LOCATOR_SHARD_BYTES: usize = 67108864;
pub const MAX_BILLING_REDEEM_STATE_SHARD_BYTES: usize = 67108864;
pub const MAX_BILLING_LIST_ROWS: usize = 1000;
pub const MAX_BILLING_LIST_SCAN_ROWS: usize = 10000;
pub const MAX_BILLING_RESPONSE_BYTES: usize = 8388608;
pub const MAX_BILLING_NOTE_CHARACTERS: usize = 4000;
pub const TENANT_USER_PROFILE_NAMESPACE: &str = "tenant_user_profiles";
pub const TENANT_USER_STATE_NAMESPACE: &str = "tenant_user_states";
pub const TENANT_USER_EMAIL_INDEX_NAMESPACE: &str = "tenant_users_by_email_digest";
pub const TENANT_USER_CREATED_INDEX_NAMESPACE: &str = "tenant_users_by_created_desc";
pub const TENANT_USER_STATUS_INDEX_NAMESPACE: &str = "tenant_users_by_status_created_desc";
pub const TENANT_USER_OWNER_SEQUENCE_NAMESPACE: &str = "tenant_user_owner_sequence";
pub const MAX_TENANT_USER_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_TENANT_USER_LIST_ROWS: usize = 1000;
pub const MAX_TENANT_USER_LIST_SCAN_ROWS: usize = 10000;
pub const MAX_TENANT_USER_RESPONSE_BYTES: usize = 8388608;
pub const CREDENTIAL_CORE_NAMESPACE: &str = "credential_cores";
pub const CREDENTIAL_SETTINGS_NAMESPACE: &str = "credential_settings";
pub const CREDENTIAL_STATE_NAMESPACE: &str = "credential_states";
pub const CREDENTIAL_SECRET_INDEX_NAMESPACE: &str = "credentials_by_secret_hash";
pub const CREDENTIAL_OWNER_INDEX_NAMESPACE: &str = "credentials_by_owner_created_desc";
pub const CREDENTIAL_OWNER_COUNT_NAMESPACE: &str = "credential_owner_counts";
pub const MAX_CREDENTIAL_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_CREDENTIALS_PER_OWNER_BOUNDARY: usize = 1000;
pub const MAX_CREDENTIAL_SCOPES: usize = 128;
pub const MAX_CREDENTIAL_RESPONSE_BYTES: usize = 8388608;
pub const MAX_CREDENTIAL_TIMESTAMP_SECONDS: f64 = 32503680000.0;
pub const BROWSER_SITE_OBSERVATION_DOCUMENT_NAMESPACE: &str = "browser_site_observation_documents";
pub const BROWSER_SITE_OBSERVATION_LRU_NAMESPACE: &str =
    "browser_site_observations_by_last_observed";
pub const MAX_BROWSER_SITE_OBSERVATIONS_PER_OWNER: usize = 200;
pub const MAX_BROWSER_SITE_OBSERVATION_BYTES: usize = 4096;
pub const MAX_BROWSER_SITE_OBSERVATION_STORED_BYTES: usize = 8192;
pub const RECORD_DOCUMENT_NAMESPACE: &str = "storage_records";
pub const RATE_LIMIT_BUCKET_NAMESPACE: &str = "rate_limit_buckets";
pub const RATE_LIMIT_EVENT_NAMESPACE: &str = "rate_limit_events";
pub const RATE_LIMIT_EXPIRY_NAMESPACE: &str = "rate_limit_events_by_expiry";
pub const RATE_LIMIT_COUNT_NAMESPACE: &str = "rate_limit_radix_counts";
pub const DAILY_COST_DOCUMENT_NAMESPACE: &str = "daily_cost_documents";
pub const DAILY_COST_COUNT_NAMESPACE: &str = "daily_cost_counts";
pub const MAX_DAILY_COST_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_DAILY_COST_MONTH_ROWS: usize = 100;
pub const MAX_DAILY_COST_PERSISTED_DATES: usize = 366;
pub const ORCHESTRATION_DEFINITION_DOCUMENT_NAMESPACE: &str = "orchestration_definition_documents";
pub const ORCHESTRATION_DEFINITION_ID_CLAIM_NAMESPACE: &str = "orchestration_definition_id_claims";
pub const ORCHESTRATION_DEFINITION_UPDATED_INDEX_NAMESPACE: &str =
    "orchestration_definitions_by_updated_desc";
pub const ORCHESTRATION_DEFINITION_COUNT_NAMESPACE: &str = "orchestration_definition_counts";
pub const MAX_ORCHESTRATION_DEFINITIONS_PER_OWNER: usize = 1000;
pub const MAX_ORCHESTRATION_DEFINITION_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_ORCHESTRATION_DEFINITION_ID_CHARACTERS: usize = 200;
pub const MAX_ORCHESTRATION_RESPONSE_BYTES: usize = 8388608;
pub const ORCHESTRATION_RUN_CORE_NAMESPACE: &str = "orchestration_run_cores";
pub const ORCHESTRATION_RUN_STATE_NAMESPACE: &str = "orchestration_run_states";
pub const ORCHESTRATION_RUN_ID_CLAIM_NAMESPACE: &str = "orchestration_run_id_claims";
pub const ORCHESTRATION_RUN_CREATED_INDEX_NAMESPACE: &str = "orchestration_runs_by_created_desc";
pub const ORCHESTRATION_RUN_STATUS_CREATED_INDEX_NAMESPACE: &str =
    "orchestration_runs_by_status_created_desc";
pub const ORCHESTRATION_RUN_ORCHESTRATION_CREATED_INDEX_NAMESPACE: &str =
    "orchestration_runs_by_orchestration_created_desc";
pub const ORCHESTRATION_RUN_GLOBAL_ACTIVE_INDEX_NAMESPACE: &str =
    "orchestration_runs_global_active";
pub const ORCHESTRATION_GOAL_ACTIVE_CLAIM_NAMESPACE: &str = "orchestration_goal_active_runs";
pub const ORCHESTRATION_GOAL_CREATED_INDEX_NAMESPACE: &str =
    "orchestration_goal_runs_by_created_desc";
pub const ORCHESTRATION_RUN_EVENT_DOCUMENT_NAMESPACE: &str = "orchestration_run_event_documents";
pub const ORCHESTRATION_RUN_COUNT_NAMESPACE: &str = "orchestration_run_counts";
pub const MAX_ORCHESTRATION_RUNS_PER_OWNER: usize = 10000;
pub const MAX_ORCHESTRATION_RUN_CORE_BYTES: usize = 8388608;
pub const MAX_ORCHESTRATION_RUN_STATE_BYTES: usize = 8388608;
pub const MAX_ORCHESTRATION_EVENTS_PER_RUN: usize = 100000;
pub const MAX_ORCHESTRATION_EVENT_DOCUMENT_BYTES: usize = 1048576;
pub const MAX_ORCHESTRATION_EVENT_PAGE_ROWS: usize = 2000;
pub const MAX_ORCHESTRATION_RUN_LIST_ROWS: usize = 200;
pub const MAX_ORCHESTRATION_MAINTENANCE_ROWS: usize = 1000;
pub const MAX_ORCHESTRATION_RUN_ID_CHARACTERS: usize = 200;
pub const MAX_ORCHESTRATION_TENANT_LABEL_CHARACTERS: usize = 256;
pub const SWARM_SESSION_DOCUMENT_NAMESPACE: &str = "swarm_session_documents";
pub const SWARM_SESSION_STATE_NAMESPACE: &str = "swarm_session_states";
pub const SWARM_SESSION_KEY_CLAIM_NAMESPACE: &str = "swarm_session_key_claims";
pub const SWARM_RESUMABLE_INDEX_NAMESPACE: &str = "swarm_sessions_resumable_by_updated_desc";
pub const SWARM_SESSION_COUNT_NAMESPACE: &str = "swarm_session_counts";
pub const SWARM_AGENT_CORE_NAMESPACE: &str = "swarm_agent_cores";
pub const SWARM_AGENT_STATE_NAMESPACE: &str = "swarm_agent_states";
pub const SWARM_AGENT_COUNT_NAMESPACE: &str = "swarm_agent_counts";
pub const MAX_SWARM_SESSIONS_PER_OWNER: usize = 512;
pub const MAX_SWARM_AGENTS_PER_SESSION: usize = 1000;
pub const MAX_SWARM_SESSION_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_SWARM_AGENT_CORE_BYTES: usize = 8388608;
pub const MAX_SWARM_RESPONSE_BYTES: usize = 8388608;
pub const MAX_SWARM_KEY_CHARACTERS: usize = 512;
pub const MAX_SWARM_AGENT_ID_CHARACTERS: usize = 512;
pub const MAX_SWARM_OBJECTIVE_CHARACTERS: usize = 100000;
pub const MAX_SWARM_AGENT_IDS_PER_DELIVERY: usize = 1000;
pub const MAX_SWARM_ROUNDS_USED: u64 = 1000000;
pub const INTEGRATION_WORKSPACE_NAMESPACE: &str = "integration_workspace_documents";
pub const INTEGRATION_NATURAL_CLAIM_NAMESPACE: &str = "integration_workspace_natural_claims";
pub const INTEGRATION_ROW_LOCATOR_NAMESPACE: &str = "integration_workspace_row_locators";
pub const INTEGRATION_ROW_SEQUENCE_NAMESPACE: &str = "integration_workspace_row_sequence";
pub const INTEGRATION_READY_INDEX_NAMESPACE: &str = "integration_workspaces_ready_by_updated_asc";
pub const INTEGRATION_INTEGRATING_INDEX_NAMESPACE: &str =
    "integration_workspaces_integrating_by_updated_asc";
pub const INTEGRATION_PROJECT_ACTIVE_CLAIM_NAMESPACE: &str = "integration_project_active_claims";
pub const INTEGRATION_ACTIVE_COUNT_NAMESPACE: &str = "integration_active_count";
pub const INTEGRATION_PROJECT_UPDATED_INDEX_NAMESPACE: &str =
    "integration_workspaces_by_project_updated_desc";
pub const INTEGRATION_WORKSPACE_COUNT_NAMESPACE: &str = "integration_workspace_counts";
pub const INTEGRATION_EVENT_NAMESPACE: &str = "integration_event_documents";
pub const INTEGRATION_EVENT_SEQUENCE_NAMESPACE: &str = "integration_event_sequence";
pub const INTEGRATION_EVENT_COUNT_NAMESPACE: &str = "integration_event_counts";
pub const MAX_INTEGRATION_WORKSPACES_PER_OWNER: usize = 10000;
pub const MAX_INTEGRATION_ACTIVE_WORKSPACES: usize = 1000;
pub const MAX_INTEGRATION_STATUS_ROWS: usize = 1000;
pub const MAX_INTEGRATION_EVENTS_PER_PROJECT: usize = 300;
pub const MAX_INTEGRATION_STATUS_EVENTS: usize = 30;
pub const MAX_INTEGRATION_PROJECT_ROOT_CHARACTERS: usize = 4096;
pub const MAX_INTEGRATION_TASK_ID_CHARACTERS: usize = 512;
pub const MAX_INTEGRATION_WORKSPACE_DOCUMENT_BYTES: usize = 16384;
pub const MAX_INTEGRATION_RESPONSE_BYTES: usize = 8388608;
pub const INTEGRATION_STALE_SECONDS: f64 = 660.0;
pub const PROJECT_BRAIN_DOCUMENT_NAMESPACE: &str = "project_brain_documents";
pub const PROJECT_BRAIN_CHECKPOINT_NAMESPACE: &str = "project_brain_checkpoints";
pub const PROJECT_BRAIN_EVENT_INDEX_NAMESPACE: &str = "project_brain_event_positions";
pub const PROJECT_BRAIN_UPDATED_INDEX_NAMESPACE: &str = "project_brain_by_updated_desc";
pub const MAX_PROJECT_BRAIN_PROJECT_KEY_CHARACTERS: usize = 4096;
pub const MAX_PROJECT_BRAIN_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_PROJECT_BRAIN_ACTIVE_WORK: usize = 100;
pub const MAX_PROJECT_BRAIN_WORK_HISTORY: usize = 100;
pub const MAX_PROJECT_BRAIN_CHANGED_PATHS: usize = 200;
pub const MAX_PROJECT_BRAIN_ARTIFACTS_PER_WORK: usize = 100;
pub const MAX_PROJECT_BRAIN_NARRATIVES: usize = 500;
pub const MAX_PROJECT_BRAIN_NARRATIVE_TEXT_BYTES: usize = 720;
pub const MAX_PROJECT_BRAIN_WATCH_ITEMS: usize = 100;
pub const MAX_PROJECT_BRAIN_CHECKER_VERSIONS: usize = 128;
pub const MAX_PROJECT_BRAIN_CHARTER_DECISIONS: usize = 256;
pub const MAX_PROJECT_BRAIN_CURSORS: usize = 1000;
pub const MAX_PROJECT_BRAIN_EVENT_BYTES: usize = 8384512;
pub const PROJECT_BRAIN_EVENT_CHECKPOINT_THRESHOLD: u64 = 1200;
pub const PROJECT_BRAIN_EVENT_CHECKPOINT_TAIL: u64 = 600;
pub const SCHEDULER_TASK_DOCUMENT_NAMESPACE: &str = "scheduled_task_documents";
pub const SCHEDULER_TASK_ID_CLAIM_NAMESPACE: &str = "scheduled_task_id_claims";
pub const SCHEDULER_TASK_SYSTEM_KEY_CLAIM_NAMESPACE: &str = "scheduled_task_system_key_claims";
pub const SCHEDULER_TASK_CREATED_INDEX_NAMESPACE: &str = "scheduled_tasks_by_created_desc";
pub const SCHEDULER_TASK_ENABLED_CREATED_INDEX_NAMESPACE: &str =
    "scheduled_tasks_enabled_by_created_desc";
pub const SCHEDULER_TASK_GLOBAL_CREATED_INDEX_NAMESPACE: &str =
    "scheduled_tasks_global_by_created_desc";
pub const SCHEDULER_TASK_GLOBAL_ENABLED_CREATED_INDEX_NAMESPACE: &str =
    "scheduled_tasks_global_enabled_by_created_desc";
pub const SCHEDULER_TASK_COUNT_NAMESPACE: &str = "scheduled_task_counts";
pub const SCHEDULER_POLL_DOCUMENT_NAMESPACE: &str = "scheduler_poll_documents";
pub const SCHEDULER_POLL_TIME_INDEX_NAMESPACE: &str = "scheduler_polls_by_task_time_desc";
pub const SCHEDULER_POLL_SEQUENCE_NAMESPACE: &str = "scheduler_poll_global_sequence";
pub const MAX_SCHEDULER_TASKS_PER_OWNER: usize = 100;
pub const MAX_SCHEDULER_TASK_DOCUMENT_BYTES: usize = 1048576;
pub const MAX_SCHEDULER_TASK_ID_CHARACTERS: usize = 128;
pub const MAX_SCHEDULER_SYSTEM_KEY_CHARACTERS: usize = 128;
pub const MAX_SCHEDULER_TASK_LIST_ROWS: usize = 2000;
pub const MAX_SCHEDULER_POLL_ROWS: usize = 200;
pub const MAX_SCHEDULER_POLL_DOCUMENT_BYTES: usize = 16384;
pub const QUEUE_ITEM_CORE_NAMESPACE: &str = "queue_item_cores";
pub const QUEUE_ITEM_STATE_NAMESPACE: &str = "queue_item_states";
pub const QUEUE_ITEM_ID_CLAIM_NAMESPACE: &str = "queue_item_id_claims";
pub const QUEUE_CONVERSATION_ORDER_INDEX_NAMESPACE: &str = "queue_items_by_conversation_order";
pub const QUEUE_GLOBAL_CONVERSATION_INDEX_NAMESPACE: &str = "queue_conversations_by_kind_oldest";
pub const QUEUE_GLOBAL_LEASE_INDEX_NAMESPACE: &str = "queue_leases_by_expiry";
pub const QUEUE_AUTOPILOT_MARKER_NAMESPACE: &str = "queue_autopilot_markers";
pub const QUEUE_GLOBAL_AUTOPILOT_INDEX_NAMESPACE: &str = "queue_autopilot_by_owner_conversation";
pub const MAX_QUEUE_ITEMS_PER_CONVERSATION: usize = 512;
pub const MAX_QUEUE_ITEM_CORE_BYTES: usize = 1048576;
pub const MAX_QUEUE_GLOBAL_CONVERSATION_ROWS: usize = 1000;
pub const MAX_QUEUE_AUTOPILOT_MARKERS: usize = 1000;
pub const MAX_QUEUE_REAP_ITEMS: usize = 128;
pub const MAX_QUEUE_RESPONSE_BYTES: usize = 8388608;
pub const MAX_QUEUE_ID_CHARACTERS: usize = 256;
pub const MAX_QUEUE_CONVERSATION_ID_CHARACTERS: usize = 256;
pub const TIMER_DOCUMENT_NAMESPACE: &str = "timer_documents";
pub const TIMER_ID_CLAIM_NAMESPACE: &str = "timer_id_claims";
pub const TIMER_STATUS_CREATED_INDEX_NAMESPACE: &str = "timers_by_status_created_desc";
pub const TIMER_CONVERSATION_INDEX_NAMESPACE: &str = "timers_by_conversation";
pub const TIMER_GLOBAL_ACTIVE_CREATED_INDEX_NAMESPACE: &str = "timers_global_active_by_created_asc";
pub const TIMER_TOTAL_COUNT_NAMESPACE: &str = "timer_total_counts";
pub const TIMER_ACTIVE_COUNT_NAMESPACE: &str = "timer_active_counts";
pub const TIMER_POLL_DOCUMENT_NAMESPACE: &str = "timer_poll_documents";
pub const TIMER_POLL_TIME_INDEX_NAMESPACE: &str = "timer_polls_by_timer_time_desc";
pub const TIMER_POLL_ID_CLAIM_NAMESPACE: &str = "timer_poll_id_claims";
pub const TIMER_POLL_SEQUENCE_NAMESPACE: &str = "timer_poll_global_sequence";
pub const MAX_TIMERS_PER_OWNER: usize = 512;
pub const MAX_ACTIVE_TIMERS_PER_OWNER_HARD_CEILING: usize = 64;
pub const MAX_TIMER_DOCUMENT_BYTES: usize = 1048576;
pub const MAX_TIMER_ID_CHARACTERS: usize = 128;
pub const MAX_TIMER_LIST_ROWS: usize = 200;
pub const MAX_TIMER_GLOBAL_ACTIVE_ROWS: usize = 2000;
pub const MAX_TIMER_POLL_ROWS: usize = 200;
pub const MAX_TIMER_POLL_DOCUMENT_BYTES: usize = 16384;
pub const MAX_RATE_LIMIT_ENDPOINT_CHARACTERS: usize = 256;
pub const MAX_RATE_LIMIT_CLIENT_KEY_CHARACTERS: usize = 512;
pub const MAX_RATE_LIMIT_EVENT_ID_CHARACTERS: usize = 200;
pub const MAX_RATE_LIMIT_EVENTS_PER_WINDOW: u64 = 1000000;
pub const MAX_RATE_LIMIT_WINDOW_SECONDS: u64 = 604800;
pub const MAX_RATE_LIMIT_PRUNE_ROWS: usize = 256;
pub const RATE_LIMIT_COUNTER_RADIX: usize = 256;
pub const RATE_LIMIT_COUNTER_DEPTH: usize = 8;
pub const MAX_RATE_LIMIT_WINDOW_COUNTER_READS: usize = 2040;
pub const RECENT_PROJECT_DOCUMENT_NAMESPACE: &str = "recent_project_documents";
pub const RECENT_PROJECT_COUNT_NAMESPACE: &str = "recent_project_counts";
pub const MAX_RECENT_PROJECTS_PER_OWNER: usize = 1000;
pub const MAX_RECENT_PROJECT_TOUCH_BATCH: usize = 32;
pub const MAX_RECENT_PROJECT_PATH_CHARACTERS: usize = 4096;
pub const PROVIDER_DOCUMENT_NAMESPACE: &str = "byo_provider_documents";
pub const PROVIDER_CREATED_INDEX_NAMESPACE: &str = "byo_providers_by_created";
pub const PROVIDER_COUNT_NAMESPACE: &str = "byo_provider_counts";
pub const PROVIDER_ID_CLAIM_NAMESPACE: &str = "byo_provider_id_claims";
pub const ARTIFACT_DOCUMENT_NAMESPACE: &str = "artifact_documents";
pub const ARTIFACT_CONVERSATION_INDEX_NAMESPACE: &str = "artifacts_by_conversation_created";
pub const ARTIFACT_LIBRARY_INDEX_NAMESPACE: &str = "artifacts_by_pinned_created";
pub const ARTIFACT_DEDUPE_NAMESPACE: &str = "artifact_content_dedupe";
pub const ARTIFACT_PATH_HEAD_NAMESPACE: &str = "artifact_path_heads";
pub const ARTIFACT_PARENT_INDEX_NAMESPACE: &str = "artifact_children_by_version";
pub const MAX_ARTIFACT_BYTES: usize = 8388608;
pub const MAX_ARTIFACT_ROWS_PER_CONVERSATION: usize = 1000;
pub const TOOL_RESULT_ARTIFACT_NAMESPACE: &str = "tool_result_artifact_documents";
pub const TOOL_RESULT_EXPIRY_INDEX_NAMESPACE: &str = "tool_result_artifacts_by_expiry";
pub const MAX_TOOL_RESULT_ARTIFACT_BYTES: usize = 16777216;
pub const MAX_TOOL_RESULT_RANGE_BYTES: usize = 65536;
pub const MAX_TOOL_RESULT_TTL_MILLISECONDS: u64 = 604800000;
pub const MAX_TOOL_RESULT_PRUNE_ROWS: usize = 5000;
pub const LOG_AGGREGATE_DOCUMENT_NAMESPACE: &str = "log_aggregate_documents";
pub const LOG_AGGREGATE_SWEEP_INDEX_NAMESPACE: &str = "log_aggregates_by_last_seen";
pub const LOG_AGGREGATE_SEQUENCE_NAMESPACE: &str = "log_aggregate_sequences";
pub const MAX_LOG_AGGREGATE_DOCUMENT_BYTES: usize = 16384;
pub const MAX_LOG_AGGREGATE_FINGERPRINT_CHARACTERS: usize = 64;
pub const MAX_LOG_AGGREGATE_LEVEL_CHARACTERS: usize = 32;
pub const MAX_LOG_AGGREGATE_LOGGER_CHARACTERS: usize = 256;
pub const MAX_LOG_AGGREGATE_TEMPLATE_CHARACTERS: usize = 200;
pub const MAX_LOG_AGGREGATE_SAMPLE_CHARACTERS: usize = 2000;
pub const MAX_LOG_AGGREGATE_FLUSH_BATCH: usize = 500;
pub const MAX_LOG_AGGREGATE_QUERY_ROWS: usize = 500;
pub const MAX_LOG_AGGREGATE_SCAN_ROWS: usize = 4096;
pub const MAX_LOG_AGGREGATE_SWEEP_BATCH: usize = 500;
pub const MAX_LOG_AGGREGATE_ROW_COUNT: u64 = 1000000000;
pub const PAPER_LIBRARY_CORE_NAMESPACE: &str = "paper_library_core_documents";
pub const PAPER_LIBRARY_STATE_NAMESPACE: &str = "paper_library_state_documents";
pub const PAPER_LIBRARY_UPDATED_INDEX_NAMESPACE: &str = "paper_library_by_updated_desc";
pub const PAPER_LIBRARY_HASH_INDEX_NAMESPACE: &str = "paper_library_by_hash_updated_desc";
pub const PAPER_LIBRARY_ARXIV_INDEX_NAMESPACE: &str = "paper_library_by_arxiv_updated_desc";
pub const PAPER_LIBRARY_REPORT_PRESENCE_NAMESPACE: &str = "paper_report_presence";
pub const PAPER_LIBRARY_COUNT_NAMESPACE: &str = "paper_library_counts";
pub const MAX_PAPER_LIBRARY_ROWS_PER_OWNER: usize = 1024;
pub const MAX_PAPER_LIBRARY_CORE_DOCUMENT_BYTES: usize = 67108864;
pub const MAX_PAPER_LIBRARY_STATE_DOCUMENT_BYTES: usize = 65536;
pub const MAX_PAPER_LIBRARY_RESPONSE_BYTES: usize = 67108864;
pub const MAX_PAPER_LIBRARY_FANIN_PAPERS: usize = 40;
pub const MAX_PAPER_LIBRARY_FANIN_TEXT_CHARACTERS: usize = 6000;
pub const MAX_PAPER_LIBRARY_QA_TEXT_CHARACTERS: usize = 1000000;
pub const PAPER_NOTE_DOCUMENT_NAMESPACE: &str = "paper_note_documents";
pub const PAPER_NOTE_LIST_INDEX_NAMESPACE: &str = "paper_notes_by_paper_lang_created";
pub const PAPER_NOTE_COUNT_NAMESPACE: &str = "paper_note_counts";
pub const MAX_PAPER_NOTES_PER_OWNER: usize = 4096;
pub const MAX_PAPER_NOTE_DOCUMENT_BYTES: usize = 524288;
pub const MAX_PAPER_NOTE_RESPONSE_BYTES: usize = 67108864;
pub const PLUGIN_MANIFEST_DOCUMENT_NAMESPACE: &str = "plugin_manifest_documents";
pub const MAX_PLUGIN_NAMESPACE_CHARACTERS: usize = 128;
pub const MAX_PLUGIN_MANIFEST_BYTES: usize = 4194304;
pub const KNOWLEDGE_DOCUMENT_NAMESPACE: &str = "knowledge_document_documents";
pub const KNOWLEDGE_CHUNK_DOCUMENT_NAMESPACE: &str = "knowledge_chunk_documents";
pub const KNOWLEDGE_ASSET_DOCUMENT_NAMESPACE: &str = "knowledge_asset_documents";
pub const KNOWLEDGE_ASSET_ORDINAL_INDEX_NAMESPACE: &str = "knowledge_asset_ordinals";
pub const KNOWLEDGE_ASSET_CHUNK_REVERSE_NAMESPACE: &str = "knowledge_asset_chunk_reverse";
pub const KNOWLEDGE_TERM_NAMESPACE: &str = "knowledge_terms";
pub const KNOWLEDGE_DIGEST_INDEX_NAMESPACE: &str = "knowledge_documents_by_sha256";
pub const KNOWLEDGE_SETTINGS_NAMESPACE: &str = "knowledge_settings";
pub const KNOWLEDGE_CHUNK_ASSET_LINK_NAMESPACE: &str = "knowledge_chunk_asset_links";
pub const KNOWLEDGE_ENRICHMENT_QUEUE_NAMESPACE: &str = "knowledge_enrichment_queue";
pub const KNOWLEDGE_ENRICHMENT_OWNER_INDEX_NAMESPACE: &str = "knowledge_enrichment_owners";
pub const MAX_KNOWLEDGE_DOCUMENT_ID_CHARACTERS: usize = 128;
pub const MAX_KNOWLEDGE_ASSET_ID_CHARACTERS: usize = 128;
pub const MAX_KNOWLEDGE_NAME_CHARACTERS: usize = 240;
pub const MAX_KNOWLEDGE_STORED_NAME_CHARACTERS: usize = 512;
pub const MAX_KNOWLEDGE_DOCUMENT_KIND_CHARACTERS: usize = 32;
pub const MAX_KNOWLEDGE_ASSET_KIND_CHARACTERS: usize = 64;
pub const MAX_KNOWLEDGE_MIME_TYPE_CHARACTERS: usize = 255;
pub const MAX_KNOWLEDGE_METHOD_CHARACTERS: usize = 255;
pub const MAX_KNOWLEDGE_RELATION_CHARACTERS: usize = 64;
pub const MAX_KNOWLEDGE_STATUS_CHARACTERS: usize = 32;
pub const MAX_KNOWLEDGE_SCOPE_CHARACTERS: usize = 32;
pub const MAX_KNOWLEDGE_SECTION_CHARACTERS: usize = 20000;
pub const MAX_KNOWLEDGE_LOCATION_CHARACTERS: usize = 20000;
pub const MAX_KNOWLEDGE_CHUNK_CONTENT_CHARACTERS: usize = 4000000;
pub const MAX_KNOWLEDGE_SEARCH_TEXT_CHARACTERS: usize = 4000000;
pub const MAX_KNOWLEDGE_ASSET_TEXT_CHARACTERS: usize = 1000000;
pub const MAX_KNOWLEDGE_CAPTION_CHARACTERS: usize = 20000;
pub const MAX_KNOWLEDGE_ENRICHMENT_MODEL_CHARACTERS: usize = 512;
pub const MAX_KNOWLEDGE_ENRICHMENT_ERROR_CHARACTERS: usize = 2000;
pub const MAX_KNOWLEDGE_MEDIA_METADATA_CHARACTERS: usize = 100000;
pub const MAX_KNOWLEDGE_ASSET_METADATA_CHARACTERS: usize = 20000;
pub const MAX_KNOWLEDGE_JSON_ARRAY_CHARACTERS: usize = 200000;
pub const MAX_KNOWLEDGE_TERM_CHARACTERS: usize = 128;
pub const MAX_KNOWLEDGE_TERMS_PER_CHUNK: usize = 4096;
pub const MAX_KNOWLEDGE_SEARCH_TOKENS: usize = 32;
pub const MAX_KNOWLEDGE_PAGE_ROWS: usize = 200;
pub const MAX_KNOWLEDGE_CATALOG_PAGE_SIZE: usize = 100;
pub const MAX_KNOWLEDGE_CATALOG_QUERY_CHARACTERS: usize = 200;
pub const MAX_KNOWLEDGE_CHUNKS_PER_DOCUMENT: usize = 65536;
pub const MAX_KNOWLEDGE_ASSETS_PER_DOCUMENT: usize = 65536;
pub const MAX_KNOWLEDGE_OWNER_ASSET_ROWS: usize = 262144;
pub const MAX_KNOWLEDGE_ENRICHMENT_OWNER_ROWS: usize = 512;
pub const MAX_KNOWLEDGE_DOCUMENT_BYTES: usize = 1048576;
pub const MAX_KNOWLEDGE_CHUNK_DOCUMENT_BYTES: usize = 33554432;
pub const MAX_KNOWLEDGE_ASSET_DOCUMENT_BYTES: usize = 16777216;
pub const MAX_KNOWLEDGE_SEARCH_POSTINGS_SCAN: usize = 262144;
pub const MAX_KNOWLEDGE_CATALOG_SCAN_DOCUMENTS: usize = 65536;
pub const MAX_KNOWLEDGE_CLAIM_SCAN_ROWS: usize = 4096;
pub const PAPER_REPORT_CORE_NAMESPACE: &str = "paper_report_core_documents";
pub const PAPER_REPORT_META_NAMESPACE: &str = "paper_report_meta_documents";
pub const PAPER_REPORT_LATEST_INDEX_NAMESPACE: &str = "paper_reports_by_hash_created_desc";
pub const PAPER_REPORT_PRESENCE_NAMESPACE: &str = "paper_report_presence";
pub const PAPER_REPORT_COUNT_NAMESPACE: &str = "paper_report_counts";
pub const MAX_PAPER_REPORT_ROWS_PER_OWNER: usize = 4096;
pub const MAX_PAPER_REPORT_DOCUMENT_BYTES: usize = 67108864;
pub const MAX_PAPER_REPORT_META_BYTES: usize = 8388608;
pub const MAX_PAPER_REPORT_RESPONSE_BYTES: usize = 67108864;
pub const MAX_PAPER_REPORT_REOPEN_SIBLINGS: usize = 8;
pub const MAX_PAPER_REPORT_EXCERPT_HASHES: usize = 40;
pub const MAX_PAPER_REPORT_EXCERPT_TEXT_CHARACTERS: usize = 6000;
pub const PAPER_TRANSLATION_DOCUMENT_NAMESPACE: &str = "paper_translation_documents";
pub const PAPER_TRANSLATION_COUNT_NAMESPACE: &str = "paper_translation_counts";
pub const MAX_PAPER_TRANSLATION_ROWS_PER_OWNER: usize = 4096;
pub const MAX_PAPER_TRANSLATION_DOCUMENT_BYTES: usize = 16777216;
pub const MAX_PAPER_TRANSLATION_RESPONSE_BYTES: usize = 16777216;
pub const PAPER_PODCAST_CORE_NAMESPACE: &str = "paper_podcast_core_documents";
pub const PAPER_PODCAST_STATE_NAMESPACE: &str = "paper_podcast_state_documents";
pub const PAPER_PODCAST_COUNT_NAMESPACE: &str = "paper_podcast_counts";
pub const PAPER_PODCAST_ACTIVE_INDEX_NAMESPACE: &str = "paper_podcast_generating_by_tenant";
pub const PAPER_PODCAST_ACTIVE_COUNT_NAMESPACE: &str = "paper_podcast_generating_counts";
pub const MAX_PAPER_PODCAST_ROWS_PER_OWNER: usize = 4096;
pub const MAX_PAPER_PODCAST_ACTIVE_PER_TENANT: usize = 256;
pub const MAX_PAPER_PODCAST_SCRIPT_BYTES: usize = 8388608;
pub const MAX_PAPER_PODCAST_META_BYTES: usize = 4194304;
pub const MAX_PAPER_PODCAST_CORE_DOCUMENT_BYTES: usize = 16777216;
pub const MAX_PAPER_PODCAST_STATE_DOCUMENT_BYTES: usize = 65536;
pub const MAX_PAPER_PODCAST_RESPONSE_BYTES: usize = 16777216;
pub const RAW_ARCHIVE_DOCUMENT_NAMESPACE: &str = "raw_archive_documents";
pub const RAW_ARCHIVE_ID_CLAIM_NAMESPACE: &str = "raw_archive_id_claims";
pub const RAW_ARCHIVE_TENANT_USAGE_NAMESPACE: &str = "raw_archive_tenant_usage";
pub const RAW_ARCHIVE_ATTEMPT_USAGE_NAMESPACE: &str = "raw_archive_attempt_usage";
pub const RAW_ARCHIVE_OWNER_COUNT_NAMESPACE: &str = "raw_archive_owner_counts";
pub const RAW_ARCHIVE_TASK_INDEX_NAMESPACE: &str = "raw_archives_by_task_created";
pub const RAW_ARCHIVE_TASK_ROUND_INDEX_NAMESPACE: &str = "raw_archives_by_task_round_created";
pub const RAW_ARCHIVE_ATTEMPT_INDEX_NAMESPACE: &str = "raw_archives_by_attempt_created";
pub const RAW_ARCHIVE_CONVERSATION_INDEX_NAMESPACE: &str = "raw_archives_by_conversation_created";
pub const RAW_ARCHIVE_CONVERSATION_STATS_NAMESPACE: &str = "raw_archive_conversation_stats";
pub const MAX_RAW_ARCHIVE_STORED_BYTES: usize = 16777216;
pub const MAX_RAW_ARCHIVE_DOCUMENT_BYTES: usize = 25165824;
pub const MAX_RAW_ARCHIVE_DECODED_PART_BYTES: usize = 67108864;
pub const MAX_RAW_ARCHIVE_TENANT_BUDGET_BYTES: u64 = 4294967296;
pub const MAX_RAW_ARCHIVE_READ_CHUNK_BYTES: usize = 1048576;
pub const MAX_RAW_ARCHIVES_PER_OWNER: u64 = 65536;
pub const MAX_RAW_ARCHIVES_PER_CONVERSATION: usize = 512;
pub const MAX_RAW_ARCHIVE_SUMMARY_BYTES: usize = 65536;
pub const MAX_RAW_ARCHIVE_SUMMARY_KEYS: usize = 32;
pub const MAX_RAW_ARCHIVE_LIST_ROWS: usize = 64;
pub const RAW_ARCHIVE_FREE_SPACE_WIRE_MAX_BYTES: u64 = 1000000000000000;
pub const RESEARCH_ARTIFACT_DOCUMENT_NAMESPACE: &str = "research_artifact_documents";
pub const RESEARCH_ARTIFACT_STATE_NAMESPACE: &str = "research_artifact_state";
pub const RESEARCH_ARTIFACT_CREATED_INDEX_NAMESPACE: &str = "research_artifacts_by_created_desc";
pub const RESEARCH_ARTIFACT_COUNT_NAMESPACE: &str = "research_artifact_counts";
pub const MAX_RESEARCH_ARTIFACTS_PER_OWNER: usize = 4096;
pub const MAX_RESEARCH_DIRECTION_ROWS: usize = 1000;
pub const MAX_RESEARCH_DIRECTION_SCAN_ROWS: usize = 2000;
pub const MAX_RESEARCH_ARTIFACT_DOCUMENT_BYTES: usize = 67108864;
pub const MAX_RESEARCH_RESPONSE_BYTES: usize = 67108864;
pub const RESEARCH_WORKSPACE_DOCUMENT_NAMESPACE: &str = "research_workspace_documents";
pub const MAX_RESEARCH_WORKSPACE_BYTES: usize = 8388608;
pub const OPTIMIZER_PROPOSAL_DOCUMENT_NAMESPACE: &str = "optimizer_proposal_documents";
pub const OPTIMIZER_PROPOSAL_CREATED_INDEX_NAMESPACE: &str = "optimizer_proposals_by_created_desc";
pub const OPTIMIZER_PROPOSAL_STATUS_INDEX_NAMESPACE: &str =
    "optimizer_proposals_by_status_created_desc";
pub const OPTIMIZER_PROPOSAL_STATUS_NAMESPACE: &str = "optimizer_proposal_status";
pub const OPTIMIZER_PROPOSAL_COUNT_NAMESPACE: &str = "optimizer_proposal_counts";
pub const OPTIMIZER_ACTION_DOCUMENT_NAMESPACE: &str = "optimizer_action_documents";
pub const OPTIMIZER_ACTION_APPLIED_INDEX_NAMESPACE: &str = "optimizer_actions_by_applied_desc";
pub const OPTIMIZER_ACTION_ACTIVE_APPLIED_INDEX_NAMESPACE: &str =
    "optimizer_active_actions_by_applied_desc";
pub const OPTIMIZER_ACTION_PROPOSAL_INDEX_NAMESPACE: &str =
    "optimizer_actions_by_proposal_applied_desc";
pub const OPTIMIZER_ACTION_EXPIRY_INDEX_NAMESPACE: &str = "optimizer_actions_by_expiry";
pub const OPTIMIZER_ACTION_COUNT_NAMESPACE: &str = "optimizer_action_counts";
pub const MAX_OPTIMIZER_PROPOSALS_PER_OWNER: usize = 4096;
pub const MAX_OPTIMIZER_ACTIONS_PER_OWNER: usize = 2048;
pub const MAX_OPTIMIZER_LIST_ROWS: usize = 500;
pub const MAX_OPTIMIZER_DOCUMENT_BYTES: usize = 4194304;
pub const MAX_OPTIMIZER_RESPONSE_BYTES: usize = 8388608;
pub const MAX_PROVIDERS_PER_OWNER_TENANT_LABEL: usize = 32;
pub const MAX_PROVIDER_TENANT_LABEL_CHARACTERS: usize = 256;
pub const MODEL_ROUTING_AUTHORITY_NAMESPACE: &str = "model_routing_authorities";
pub const MODEL_ROUTING_AUTHORITY_METADATA_NAMESPACE: &str = "model_routing_authority_metadata";
pub const MODEL_ROUTING_BACKUP_NAMESPACE: &str = "model_routing_backups";
pub const MODEL_ROUTING_MIGRATION_RECEIPT_NAMESPACE: &str = "model_routing_migration_receipts";
pub const MODEL_ROUTING_SECRET_NAMESPACE: &str = "model_routing_secrets";
pub const MODEL_ROUTING_SECRET_COUNT_NAMESPACE: &str = "model_routing_secret_counts";
pub const MODEL_ROUTING_SECRET_REFERENCE_INDEX_NAMESPACE: &str =
    "model_routing_secrets_by_reference";
pub const MODEL_ROUTING_SECRET_UPDATED_INDEX_NAMESPACE: &str = "model_routing_secrets_by_updated";
pub const MAX_MODEL_ROUTING_DOCUMENT_BYTES: usize = 8388608;
pub const MAX_MODEL_ROUTING_SECRETS_PER_OWNER_BOUNDARY: usize = 1024;
pub const MAX_MODEL_ROUTING_SECRET_REFERENCE_CHARACTERS: usize = 256;
pub const MAX_MODEL_ROUTING_CIPHERTEXT_CHARACTERS: usize = 32768;
pub const MAX_MODEL_ROUTING_KEY_HINT_CHARACTERS: usize = 64;
pub const MAX_MODEL_ROUTING_PRUNED_PER_COMMAND: usize = 256;
pub const MAX_MODEL_ROUTING_TIMESTAMP_SECONDS: f64 = 32503680000.0;
pub const WORKER_JOB_DOCUMENT_NAMESPACE: &str = "worker_job_documents";
pub const WORKER_JOB_IDEMPOTENCY_NAMESPACE: &str = "worker_job_idempotency";
pub const WORKER_JOB_QUEUED_INDEX_NAMESPACE: &str = "worker_jobs_queued";
pub const WORKER_JOB_QUEUED_SUMMARY_NAMESPACE: &str = "worker_jobs_queued_summary";
pub const WORKER_JOB_LEASE_INDEX_NAMESPACE: &str = "worker_jobs_by_lease";
pub const MAX_WORKER_JOB_PAYLOAD_BYTES: usize = 1048576;
pub const MAX_WORKER_JOB_ERROR_BYTES: usize = 65536;
pub const MAX_WORKER_JOB_CLAIM_KINDS: usize = 32;
pub const MAX_WORKER_JOB_PRIORITY: usize = 1000;
pub const MAX_WORKER_JOB_CLOCK_MILLISECONDS: u64 = 9223372036854775000;
pub const MAX_WORKER_JOB_FUTURE_CLOCK_SKEW_MILLISECONDS: u64 = 86400000;
pub const COMPACTION_ARCHIVE_DOCUMENT_NAMESPACE: &str = "compaction_archive_metadata";
pub const COMPACTION_ARCHIVE_MESSAGES_NAMESPACE: &str = "compaction_archive_messages";
pub const COMPACTION_ARCHIVE_SUMMARY_NAMESPACE: &str = "compaction_archive_summaries";
pub const COMPACTION_ARCHIVE_RECEIPT_NAMESPACE: &str = "compaction_archive_receipts";
pub const COMPACTION_ARCHIVE_CONVERSATION_INDEX_NAMESPACE: &str =
    "compaction_archives_by_conversation";
pub const COMPACTION_ARCHIVE_COUNT_NAMESPACE: &str = "compaction_archive_counts";
pub const COMPACTION_ARCHIVE_ID_CLAIM_NAMESPACE: &str = "compaction_archive_id_claims";
pub const MAX_COMPACTION_ARCHIVES_PER_CONVERSATION: usize = 1000;
pub const CONVERSATION_DOCUMENT_NAMESPACE: &str = "conversation_headers";
pub const CONVERSATION_ID_CLAIM_NAMESPACE: &str = "conversation_id_claims";
pub const CONVERSATION_COUNT_NAMESPACE: &str = "conversation_owner_counts";
pub const CONVERSATION_SEARCH_DIRTY_NAMESPACE: &str = "conversation_search_dirty";
pub const CONVERSATION_UPDATED_INDEX_NAMESPACE: &str = "conversation_by_updated";
pub const CONVERSATION_ACTIVITY_CANDIDATE_INDEX_NAMESPACE: &str =
    "conversation_activity_candidates";
pub const CONVERSATION_ACTIVITY_CANDIDATE_STATE_NAMESPACE: &str =
    "conversation_activity_candidate_state";
pub const MAX_ACTIVITY_CANDIDATE_BACKFILL_ROWS_PER_TRANSACTION: usize = 256;
pub const MAX_ACTIVITY_CANDIDATE_BACKFILL_SOURCE_BYTES_PER_TRANSACTION: usize = 16777216;
pub const CONVERSATION_EXECUTION_EPOCH_NAMESPACE: &str = "conversation_execution_epochs";
pub const CONVERSATION_TRASH_METADATA_NAMESPACE: &str = "conversation_trash_metadata";
pub const CONVERSATION_TRASH_AGE_INDEX_NAMESPACE: &str = "conversation_trash_by_age";
pub const CONVERSATION_TRASH_SETTINGS_OVERLAY_NAMESPACE: &str =
    "conversation_trash_settings_overlays";
pub const MAX_PROJECT_RELINK_CONVERSATION_CANDIDATES: usize = 10000;
pub const TURN_DOCUMENT_NAMESPACE: &str = "conversation_turns";
pub const TURN_LANE_INDEX_NAMESPACE: &str = "turns_by_lane_ordinal";
pub const TURN_ACTIVITY_INDEX_NAMESPACE: &str = "turn_activity_timestamps";
pub const MAX_ACTIVITY_TURN_ROWS_PER_QUERY: usize = 100000;
pub const TURN_LANE_HEAD_NAMESPACE: &str = "turn_lane_heads";
pub const TURN_LANE_LIVE_ATTEMPT_NAMESPACE: &str = "turn_lane_live_attempts";
pub const TURN_LANE_COUNT_NAMESPACE: &str = "turn_lane_counts";
pub const TURN_SEARCH_DIRTY_NAMESPACE: &str = "turn_search_dirty";
pub const CONVERSATION_SYNC_HEAD_NAMESPACE: &str = "conversation_sync_heads";
pub const CONVERSATION_SYNC_EVENT_NAMESPACE: &str = "conversation_sync_events";
pub const CONVERSATION_SYNC_AGE_INDEX_NAMESPACE: &str = "conversation_sync_events_by_created";
pub const ATTEMPT_EVENT_SYNC_REFERENCE_NAMESPACE: &str = "attempt_event_sync_references";
pub const MAX_SYNC_PRUNE_ROWS_PER_TRANSACTION: usize = 1000;
pub const MAX_SYNC_PRUNE_MATERIALIZED_BYTES: usize = 67108864;
pub const GENERATION_ATTEMPT_NAMESPACE: &str = "generation_attempts";
pub const ATTEMPT_DISPATCHABLE_INDEX_NAMESPACE: &str = "generation_attempts_dispatchable";
pub const MAX_DISPATCHABLE_ATTEMPTS_PER_QUERY: usize = 32;
pub const TURN_LANE_COMPACTION_INDEX_NAMESPACE: &str = "turns_by_lane_compaction";
pub const MAX_TURN_COMPACTION_METADATA_ROWS: usize = 100000;
pub const MAX_TURN_COMPACTION_PROJECTION_UPDATES: usize = 512;
pub const MAX_TURN_COMPACTION_REPARENTED_TURNS: usize = 512;
pub const MAX_TURN_COMPACTION_PROJECTION_BYTES: usize = 8388608;
pub const MAX_TURN_COMPACTION_MATERIALIZED_BYTES: usize = 67108864;
pub const ATTEMPT_RECOVERY_INDEX_NAMESPACE: &str = "generation_attempts_live_by_created";
pub const MAX_RECOVERY_ROWS_PER_TRANSACTION: usize = 500;
pub const MAX_RECOVERY_INDEX_ROWS_PER_OWNER: usize = 10000;
pub const MAX_RECOVERY_PROJECTION_BYTES_PER_TRANSACTION: usize = 8388608;
pub const ATTEMPT_TIMING_TASK_INDEX_NAMESPACE: &str = "generation_attempts_by_timing_task";
pub const ATTEMPT_TIMING_CONVERSATION_INDEX_NAMESPACE: &str =
    "generation_attempts_by_conversation_created_desc";
pub const MAX_TIMING_TRACE_ROWS_PER_QUERY: usize = 100;
pub const MAX_TIMING_TRACE_TASK_CANDIDATES: usize = 100;
pub const MAX_TIMING_TRACE_CLIENT_OBSERVATIONS: usize = 64;
pub const MAX_TIMING_TRACE_PERSISTED_BYTES: usize = 98304;
pub const MAX_TIMING_TRACE_COUNTER: u64 = 2147483647;
pub const TURN_PROJECTION_HEAD_NAMESPACE: &str = "turn_projection_heads";
pub const MAX_TURN_PROJECTION_INLINE_LIVE_BYTES: usize = 65536;
pub const MAX_TURN_PROJECTION_HEAD_PATCHES: usize = 64;
pub const MAX_TURN_PROJECTION_PATCH_BYTES: usize = 1048576;
pub const MAX_TURN_PROJECTION_PATCH_DEPTH: usize = 128;
pub const MAX_TURN_PROJECTION_PATCH_OPERATIONS: usize = 65536;
pub const MAX_LEGACY_TURN_IMAGES: usize = 20;
pub const MAX_LEGACY_TURN_IMAGE_BYTES: usize = 8388608;
pub const ATTEMPT_COMMAND_NAMESPACE: &str = "generation_attempt_commands";
pub const ATTEMPT_TURN_COUNT_NAMESPACE: &str = "generation_attempt_turn_counts";
pub const ATTEMPT_TURN_DIRECTORY_NAMESPACE: &str = "generation_attempts_by_turn";
pub const MAX_ATTEMPTS_PER_TURN: usize = 64;
pub const MAX_ATTEMPT_TURN_DIRECTORY_BYTES: usize = 65536;
pub const MAX_ATTEMPT_TOMBSTONE_BYTES: usize = 16384;
pub const ATTEMPT_EVENT_HEAD_NAMESPACE: &str = "attempt_event_heads";
pub const ATTEMPT_EVENT_NAMESPACE: &str = "attempt_events";
pub const ATTEMPT_EVENT_RETENTION_INDEX_NAMESPACE: &str = "attempt_events_by_settled";
pub const MAX_ATTEMPT_EVENT_PRUNE_ATTEMPTS_PER_TRANSACTION: usize = 64;
pub const MAX_ATTEMPT_EVENT_PRUNE_ROWS_PER_TRANSACTION: usize = 200000;
pub const MAX_ATTEMPT_EVENT_PRUNE_MATERIALIZED_BYTES: usize = 67108864;
pub const TURN_ID_CLAIM_NAMESPACE: &str = "turn_id_claims";
pub const ATTEMPT_ID_CLAIM_NAMESPACE: &str = "attempt_id_claims";
pub const ATTEMPT_CLAIM_LOCATOR_VERSION: u32 = 1;
pub const TURN_UPDATED_INDEX_NAMESPACE: &str = "turns_by_updated";
pub const TURN_TOMBSTONE_NAMESPACE: &str = "turn_tombstones";
pub const TURN_TOMBSTONE_AGE_INDEX_NAMESPACE: &str = "turn_tombstones_by_age";
pub const MAX_DESKTOP_AGENT_ID_CHARACTERS: usize = 128;
pub static EXECUTABLE_STORAGE_OPERATIONS: &[&str] = &[
    "artifact.create",
    "artifact.delete",
    "artifact.get",
    "artifact.library",
    "artifact.list",
    "artifact.pin",
    "artifact.versions",
    "billing.ledger.append",
    "billing.ledger.find",
    "billing.ledger.list",
    "billing.ledger.recompute",
    "billing.payment.find",
    "billing.payment.list",
    "billing.payment.record",
    "billing.payment.settle",
    "billing.redeem_code.apply",
    "billing.redeem_codes.list",
    "billing.redeem_codes.mint",
    "billing.reserve.stale",
    "billing.wallet.apply",
    "billing.wallet.get",
    "billing.wallet.settle",
    "browser.site_observation.get",
    "browser.site_observation.record",
    "compaction_archive.create",
    "compaction_archive.delete_conversation",
    "compaction_archive.get",
    "compaction_archive.list",
    "compaction_archive.prune",
    "compaction_archive.update_summary",
    "conversation.activity_dates",
    "conversation.clone",
    "conversation.count",
    "conversation.create",
    "conversation.delete",
    "conversation.get",
    "conversation.list",
    "conversation.metadata.update",
    "conversation.purge",
    "conversation.restore",
    "conversation.search",
    "conversation.settings.update",
    "conversation.trash.prune",
    "credential.authenticate",
    "credential.create",
    "credential.create_if_owner_empty",
    "credential.exists",
    "credential.get",
    "credential.identify",
    "credential.list",
    "credential.revoke",
    "credential.touch",
    "credential.update",
    "credential.validate",
    "daily_cost.delete",
    "daily_cost.latest",
    "daily_cost.month",
    "daily_cost.persisted_dates",
    "daily_cost.upsert",
    "desktop.egress_agent.get",
    "desktop.egress_agent.initialize",
    "desktop.egress_agent.set",
    "event.append",
    "event.append_batch",
    "event.bounds",
    "event.inspector_summary",
    "event.latest",
    "event.list",
    "event.prune",
    "goal.run.get",
    "goal.run.latest",
    "goal.run.start",
    "goal.run.transition",
    "integration.event.record",
    "integration.status",
    "integration.workspace.claim_next",
    "integration.workspace.discard",
    "integration.workspace.get",
    "integration.workspace.get_integrating",
    "integration.workspace.mark_failed",
    "integration.workspace.mark_merged",
    "integration.workspace.peek_ready",
    "integration.workspace.quarantine",
    "integration.workspace.register",
    "integration.workspace.requeue",
    "integration.workspace.retry",
    "integration.workspace.save_checkpoint",
    "integration.workspace.set_meta",
    "integration.workspace.submit",
    "knowledge.asset.claim",
    "knowledge.asset.get",
    "knowledge.asset.update",
    "knowledge.assets.mark_no_vision",
    "knowledge.availability",
    "knowledge.catalog",
    "knowledge.document.assets",
    "knowledge.document.content",
    "knowledge.document.create",
    "knowledge.document.delete",
    "knowledge.document.find_digest",
    "knowledge.document.get",
    "knowledge.document.list",
    "knowledge.document.metadata",
    "knowledge.document.patch",
    "knowledge.document.replace",
    "knowledge.enrichment.activity",
    "knowledge.enrichment.owners",
    "knowledge.owner.clear",
    "knowledge.search.candidates",
    "knowledge.settings.get",
    "knowledge.settings.patch",
    "log_aggregate.flush",
    "log_aggregate.query",
    "model_routing.commit",
    "model_routing.get",
    "model_routing.migration_receipt",
    "model_routing.migration_receipt.put",
    "model_routing.secret.delete",
    "model_routing.secret.get",
    "model_routing.secret.list",
    "model_routing.secret.prune",
    "model_routing.secret.put",
    "optimizer.action.expired",
    "optimizer.action.for_proposal",
    "optimizer.action.list",
    "optimizer.action.outcome",
    "optimizer.action.record",
    "optimizer.action.revert",
    "optimizer.proposal.create",
    "optimizer.proposal.get",
    "optimizer.proposal.list",
    "optimizer.proposal.update",
    "orchestration.definition.create",
    "orchestration.definition.delete",
    "orchestration.definition.get",
    "orchestration.definition.list",
    "orchestration.definition.update",
    "orchestration.event.append",
    "orchestration.event.page",
    "orchestration.event.project",
    "orchestration.run.create",
    "orchestration.run.delete",
    "orchestration.run.get",
    "orchestration.run.list",
    "orchestration.run.retire_interrupted",
    "orchestration.run.retire_interrupted_all",
    "orchestration.run.update_status",
    "paper.library.delete",
    "paper.library.get",
    "paper.library.identity",
    "paper.library.inputs",
    "paper.library.list",
    "paper.library.put",
    "paper.library.reader",
    "paper.library.recent",
    "paper.library.summaries",
    "paper.library.title.backfill",
    "paper.note.create",
    "paper.note.delete",
    "paper.note.list",
    "paper.note.update",
    "paper.podcast.get",
    "paper.podcast.mark_interrupted",
    "paper.podcast.upsert",
    "paper.report.excerpts",
    "paper.report.get",
    "paper.report.latest",
    "paper.report.reopen",
    "paper.report.resolve",
    "paper.report.second_pass.accumulate",
    "paper.report.second_pass.merge",
    "paper.report.upsert",
    "paper.translation.get",
    "paper.translation.upsert",
    "plugin.manifest.get",
    "plugin.register",
    "project.recent.clear",
    "project.recent.list",
    "project.recent.touch",
    "project.recent.touch_many",
    "project.relink",
    "project_brain.active.list",
    "project_brain.checker.register",
    "project_brain.checker.result",
    "project_brain.cursor.confirm",
    "project_brain.cursor.prepare",
    "project_brain.cutover",
    "project_brain.cutover.status",
    "project_brain.decision.promote",
    "project_brain.get",
    "project_brain.narrative.add",
    "project_brain.rebuild",
    "project_brain.recovery.snapshot",
    "project_brain.watch.add",
    "project_brain.watch.delete",
    "project_brain.watch.update",
    "project_brain.work.change",
    "project_brain.work.finish",
    "project_brain.work.refine",
    "project_brain.work.start",
    "provider.create",
    "provider.delete",
    "provider.get",
    "provider.list",
    "provider.touch",
    "provider.update",
    "queue.autopilot.arm",
    "queue.autopilot.clear",
    "queue.autopilot.get",
    "queue.autopilot.list_all",
    "queue.clear",
    "queue.conversations.list_all",
    "queue.depth",
    "queue.dequeue",
    "queue.enqueue",
    "queue.finalize",
    "queue.kind.clear",
    "queue.lease.bind",
    "queue.lease.release",
    "queue.list",
    "queue.reap",
    "queue.remove",
    "rate_limit.record_and_check",
    "raw_archive.list",
    "raw_archive.put",
    "raw_archive.read",
    "record.delete",
    "record.get",
    "record.list",
    "record.put",
    "research.artifact.upsert",
    "research.artifacts.get",
    "research.directions.list",
    "research.workspace.get",
    "research.workspace.put",
    "scheduler.poll.append",
    "scheduler.poll.log",
    "scheduler.task.claim_due",
    "scheduler.task.create",
    "scheduler.task.delete",
    "scheduler.task.ensure",
    "scheduler.task.get",
    "scheduler.task.list",
    "scheduler.task.list_all",
    "scheduler.task.record_result",
    "scheduler.task.update",
    "swarm.agent.save",
    "swarm.agents.mark_delivered",
    "swarm.resumable.list",
    "swarm.session.delete",
    "swarm.session.get",
    "swarm.session.quarantine_ownerless",
    "swarm.session.save",
    "swarm.session.terminate",
    "system.reclaim",
    "system.schema_version",
    "task_results.abort",
    "task_results.abort_requested",
    "task_results.checkpoint",
    "task_results.cost_experiment_scan",
    "task_results.recover_running",
    "task_results.replay_get",
    "task_results.summary_list",
    "tenant.user.authentication",
    "tenant.user.create",
    "tenant.user.get",
    "tenant.user.list",
    "tenant.user.record_login",
    "tenant.user.set_role",
    "tenant.user.set_status",
    "timer.active.count",
    "timer.active.list_all",
    "timer.cancel",
    "timer.create",
    "timer.get",
    "timer.history",
    "timer.list",
    "timer.poll.append",
    "timer.poll.commit",
    "timer.poll.log",
    "timer.progress",
    "timer.update",
    "tool_result_artifact.prune",
    "tool_result_artifact.put",
    "tool_result_artifact.read",
    "tool_result_artifact.search",
    "turn.append_settled",
    "turn.attempt.bind",
    "turn.attempt.claim",
    "turn.attempt.create",
    "turn.attempt.dispatch_worker",
    "turn.attempt.dispatchable.list",
    "turn.attempt.get",
    "turn.attempt.start",
    "turn.branch.create",
    "turn.branch.delete",
    "turn.compact",
    "turn.create_pair",
    "turn.delete",
    "turn.event.record",
    "turn.events.list",
    "turn.events.prune",
    "turn.exists",
    "turn.get",
    "turn.image.get",
    "turn.list",
    "turn.list_delta",
    "turn.perception.record",
    "turn.projection.update",
    "turn.queue.activate",
    "turn.queue.cancel",
    "turn.recover",
    "turn.related.announce",
    "turn.revision",
    "turn.steer.commit",
    "turn.sync.changes",
    "turn.sync.page",
    "turn.sync.prune",
    "turn.sync.snapshot",
    "turn.timing_trace.get",
    "turn.timing_trace.list",
    "turn.visible.sync",
    "worker_job.claim_next",
    "worker_job.claim_state",
    "worker_job.complete",
    "worker_job.enqueue",
    "worker_job.get",
    "worker_job.heartbeat",
    "worker_job.request_cancel",
];
