// Generated by scripts/gen_api_v4_contract.py; DO NOT EDIT.
// Canonical API v4 bootstrap contract for the iOS client (TofuClientCore).

public enum ApiV4Contract {
    public static let apiMajor = 4
    public static let minDesktopBuild = "0.16.0"
    public static let minAndroidBuild = 17
    public static let metaPath = "/api/v4/meta"
}

public struct ApiMeta: Equatable, Sendable {
    public let apiMajor: Int
    public let schemaVersion: Int
    public let serverBuild: String
    public let minDesktopBuild: String
    public let minAndroidBuild: Int
}

public struct ResponseMeta: Equatable, Sendable {
    public let requestId: String
    public let serverTimeMs: Int64
}

public struct ApiMetaResponse: Equatable, Sendable {
    public let data: ApiMeta
    public let meta: ResponseMeta
}

public func desktopBuildIsCompatible(
    _ currentBuild: String,
    minimumBuild: String = ApiV4Contract.minDesktopBuild
) -> Bool {
    let current = _numericBuild(currentBuild)
    let minimum = _numericBuild(minimumBuild)
    let length = max(current.count, minimum.count)
    for index in 0..<length {
        let difference = (index < current.count ? current[index] : 0)
            - (index < minimum.count ? minimum[index] : 0)
        if difference != 0 { return difference > 0 }
    }
    return true
}

public func androidBuildIsCompatible(
    _ currentVersionCode: Int,
    minimumVersionCode: Int = ApiV4Contract.minAndroidBuild
) -> Bool {
    currentVersionCode >= minimumVersionCode
}

private func _numericBuild(_ build: String) -> [Int] {
    let components = build.split(separator: ".", omittingEmptySubsequences: false)
    precondition(
        !components.isEmpty && components.allSatisfy { component in
            !component.isEmpty && component.allSatisfy(\.isNumber)
        },
        "build must contain only dotted numeric components"
    )
    return components.map { Int($0)! }
}
